### ISSUE TITLE
Histogramm of residuals of a PI does not look informative

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#100]
![pi histogram of residulas for osp](https://user-images.githubusercontent.com/25585248/33177645-a83bf0f4-d063-11e7-97f9-9116868be73f.PNG)
This was quite a simple PI with 4 Simulation and to paraemetrs to optimize. other results look quite well and a solution could be found However the Histogramm of residuals looks a bit strange. Is it a known bug? Thanks for you answer.

**Comment by tobiasK2001** [comment]
![predicted vs observed for 4 doses](https://user-images.githubusercontent.com/25585248/33177761-1c31563e-d064-11e7-9435-ffb4c0f5b903.PNG)
e.g the predicted vs observed looks quite OK  for me

**Comment by Yuri05** [comment]
same issue as https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/477 
will be fixed in 7.2

**Comment by tobiasK2001** [comment]
OK Thanks!
