### ISSUE TITLE
Vorinostat PBPK / PD model

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#102]
Dear community,

I wanted to share a recently developed PBPK/PD model of the chemotherapeutic agent vorinostat. May be someone wants to develop the model further or wants to develop other kinds of PBPK/PD models. In these cases the model might be a starting point

Short description:
Vorinostat is a histone deacetylase (HDAC) inhibitor. Implemented PD biomarkers were (i) HDAC activity in peripheral blood mononuclear cells and (ii) thrombocytopenia. The full PBPK/PD model was used to specify potentially more effective dosing regimens in comparison to the standard dosing regimen.

Format: MoBi .pkml (zipped)

Related publication: 
A physiologically based pharmacokinetic and pharmacodynamic (PBPK/PD) model of the histone deacetylase (HDAC) inhibitor vorinostat for pediatric and adult patients and its application for dose specification. Moj D, Britz H, Burhenne J, Stewart CF, Egerer G, Haefeli WE, Lehr T. Cancer Chemother Pharmacol. 2017 Nov;80(5):1013-1026. doi: 10.1007/s00280-017-3447-x.

Download: [Vorinostat_PBPK_PD.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1518396/Vorinostat_PBPK_PD.zip)

Best regards,
Daniel

**Comment by tobiasK2001** [comment]
Dear Daniel, thanks a lot for this. It is great to see that this forum becomes a repository for interesting PBPK/PD models. 
B.t.w. I am looking for Ketoconazole model which I might use for a quick check. So it does not has to be the latest super sophisticated version...mayb I will start a new discussion for this...

Keep up the good work!
Best Tobias

**Comment by msevestre** [comment]
Thanks @DanielMoj.
