### ISSUE TITLE
Is it possible to enter the bioavailability of oral drugs in PK-sim?

### ISSUE THREAD

**Issue by hong77777** [Open-Systems-Pharmacology/Forum#1022]
Hi guys, I am working on a drug where the bioavailability of the inactive prodrug is only 7% for oral administration and it is the active form that really works. I would like to know if bioavailability can be addressed in this software.

**Comment by prvmalik** [comment]
Yes, you can add a metabolic enzyme into the gut lumen, the gut mucosa, or the liver to describe conversion to the active form and optimize to 7% prodrug using an observer that tracks the amount of prodrug in the body as a percentage of dose administered

**Comment by hong77777** [comment]
> 
> 
> 是的，您可以将代谢酶添加到肠腔、肠粘膜或肝脏中，以描述转化为活性形式的过程，并使用观察者跟踪体内前药量占剂量百分比的情况优化为 7% 前药管理

Sorry，I don't understand the meaning of "optimize to 7% prodrug using an observer that tracks the amount of prodrug in the body as a percentage of dose administered".
