### ISSUE TITLE
Does anybody has PK-Sim Ketoconazole model to share?

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#103]
Dear all,
I am looking for Ketoconazole and / or Erythromycin model which I might use for a quick check. So it does not has to be the latest super sophisticated version. Pleas let me know if you have something you might want to share.

Thanks in advance! Tobias

**Comment by krinaj** [comment]
Hi Tobias,

I recently developed this attached Ketoconazole PK-Sim model. Please note different clearance rates are included for two doses (200 mg vs. 400 mg) as mentioned in Pathak et al 2017. 
[Ketoconazole.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1799618/Ketoconazole.zip)

thanks,
Krina

**Comment by tobiasK2001** [comment]
Dear Krina,

thanks for this interesting model. Just wondering, did you developed with IV data and than exprapolated the iv model to po? Or did you start with po data only? Having a closer look at it seems to me that not only the CL rates are different for the doses, but also some distribution Parameters like P (plasma ->blood cells). 
Did you do some evaluation step already or are you planning to do one with e.g. multiple dose data, or DDI data? 

kind regrads, Tobias

**Comment by krinaj** [comment]
Hi Tobias,

Yes, I forgot to mention that I am still working on evaluation of the model
with DDI data. I am almost done with it and can share it in few days.

I could not find IV keto PK data easily in literature and prior PBPK model
has been developed (pathak et al paper) with other software, so I just took
parameters from there, and optimized some of the parameters. One thing I
noticed while doing evaluation is that fixing fu to literature value is
better than optimizing. I will share updated model with evaluation soon.

Kind regards,
Krina

**Comment by tobiasK2001** [comment]
Dear Krina, 

yes it is a good idea to fix fu values to literature. You may also have a look at this Ketomodel described here (if not already known) as it seems to by somewhat better describing the DDI data than the model which Phatak et al are using:
https://www.ncbi.nlm.nih.gov/pubmed/23584886

Hope you might find this usefull.

Best Tobias

**Comment by krinaj** [comment]
Hello,

Here is the ketoconazole model that I ended up with. It has been evaluated across a couple of DDI studies (1 for oral Midazolam, 1 for IV Midazolam), and across different dosing regimen. I am attaching a simple sim with ketoconazole model that I saved in my user templates.

Hope this helps.
Krina
[Ketoconazole.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1813690/Ketoconazole.zip)

**Comment by tobiasK2001** [comment]
Dear Krina,

thanks a lot for this! That is a good starting point for further investigations. How dose the evalaution looks like?  
Are you planning to evaluate it further with more studies from the Paper I send you? 
Perhaps this could be another Publication featuring the first whole body full PBPK model with a freeware software providing improved performance over the SimCYP model. What do you think of it?.

Best, Tobias

**Comment by krinaj** [comment]
Hello Tobias,

> How  dose the evalaution looks like?

The evaluations look good and acceptable. Please note that model changed quite a bit from what I had shared last week. It has now very few parameters optimized vs. prior model.

> Are you planning to evaluate it further with more studies from the Paper I send you?

I had already referred to Han et al paper that you shared before. I referred to two original DDI studies (Tsunada 1999 and Zhao 2009) mentioned in that paper. I do not plan to evaluate it further at this point.

> Perhaps this could be another Publication featuring the first whole body full PBPK model with a freeware software providing improved performance over the SimCYP model. What do you think of it?.

I think it is a good idea, but I have not evaluated performance over SimCYP model. If you would like to do further evaluation and co-author a publication, I will be happy to work together.  :)

thanks,
Krina

**Comment by StephanSchaller** [comment]
Nice example of the OSP community collaborating:

Idea: if you actually will prepare a manuscript maybe it would be really helpful for the OSP community if you "add" the "OSP Community" in the Author list followed by you two as authors. Like e.g. the "EFPIA MI3D Workgroup" on [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4809625/) paper.

**Comment by msevestre** [comment]
Thanks @krinaj for sharing

**Comment by teutonicod** [comment]
Hi @krinaj @tobiasK2001,
Do you have by any chance an updated or finalized version of this model?
Thanks,
Donato

**Comment by krinaj** [comment]
I haven't worked on this model any further. I believe Saarland University
group was working on updating the ketoconazole model.

**Comment by tobiasK2001** [comment]
Dear Donato,

yes same here. I shared some thoughts with Jan-Georg Wojtyniak from the Saarland Uni. Maybe He got a bit further with the model.

Best, Tobias
