### ISSUE TITLE
OSPS 7.2.0 installation fails

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Forum#107]
Error 0x80070666 - another version already installed (though the 7.1 suite was uninstalled).

Log attached.
[Open_Systems_Pharmacology_Suite_7.2.0_20171208101534.log](https://github.com/Open-Systems-Pharmacology/Forum/files/1542126/Open_Systems_Pharmacology_Suite_7.2.0_20171208101534.log)

**Comment by msevestre** [comment]
This sounds a lot like https://github.com/Open-Systems-Pharmacology/Forum/issues/90.

Can you perform the steps described there and see if that helps?

**Comment by PavelBal** [comment]
Yes - wasn't sure, which vcredist it wants... Is there a possibility to create a "FAQ"-Thread (issue) and pin it to the top of the forum?

**Comment by msevestre** [comment]
@PavelBal Not aware of that. We are going to update the version of vcrredist for 7.3 so hopefully this won't be an issue again

**Comment by moulirc** [comment]
I had similar issue when I was trying to upgrade from 7.1 to 7.2.

You could try the following 

1. uninstall the old version (7.1) and reinstall (7.2)
2. Right click and run as an administrator - sometimes I have seen this happening in other application.

mouli
