### ISSUE TITLE
Installation error on windows

### ISSUE THREAD

**Issue by TingjieGuo** [Open-Systems-Pharmacology/Forum#108]
Every time when installation was almost completed, it said installation failed because another version was installed on the computer. I am sure I've never installed any version on the computer, can you help me out? Thanks in advanced.

**Comment by msevestre** [comment]
The issue was closed. Did you solve your problem?
Maybe that could help
https://github.com/Open-Systems-Pharmacology/Forum/issues/107

**Comment by TingjieGuo** [comment]
@msevestre I found #107 right after having this issue posted...so I closed it immediately. Thanks anyway!

**Comment by raej3158** [comment]
The version of the windows might be corrupted as of you have to change the windows version and change the OS. so that the issue can be resolved and restart the computer then. I have had the same issue, however, www.facebook.com has helped me to find out the solution about the same issue.
