### ISSUE TITLE
Simulation

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#109]
Hi,

I am  trying to run a simulation of an IV drug when administered as a oral dosage form. 
1. I wanted to block efflux transporter
2. I wanted to deliver the drug into the intestine (dissolution data based on nano-particle targeting intestine).

I am not sure do I need it raise it as a two issue.
kind regards
mouli

**Comment by StephanSchaller** [comment]
Can you give a few more details on what exactly you want to do?

The drug is originally marketed as IV but now you want to administer it orally?
Have you already modeled the IV PK?

Best,
Stephan

**Comment by moulirc** [comment]
Hi Stephan,

 Yes I have managed to model the IV PK. Please find attached the image.
I don't have much experiences in using Mobi, and I am looking for a mentor to guide me on Mobi

![image](https://user-images.githubusercontent.com/27323536/33968456-b1f9d84e-e0b3-11e7-82f9-9a2a94218af1.png)

**Comment by StephanSchaller** [comment]
Still need a mentor in MoBi?

**Comment by moulirc** [comment]
Yes, would love to learn PKSim in detail.

Thanks
Mouli
