### ISSUE TITLE
Clinical uses of OSP

### ISSUE THREAD

**Issue by jgonlop3** [Open-Systems-Pharmacology/Forum#11]
I´m new in OSP and I try to apply this software to real cases. I think that to have a verified models for the usual drugs we use in clinical behaviours will be of interest for many people. I´m thinking in aminoglycosides, vancomycin, phenobarbital, tacrolimus, CsA, infliximab, adalimumab, vedolizumab, metotrexate...etc. We can use data for real patients to probe different prediction models.

**Comment by TheiBa** [comment]
Sounds good. In fact, there is quite a bit in preparation and I am pretty sure 
that quite a few PBPK substance models will be released into the community 
this year. We will inform soon and support organizing to ideally prevent 
parallel/duplicate efforts.

**Comment by jgonlop3** [comment]
In addition to the ideas discussed above, could lines be included in the charts to indicate the therapeutic ranges of each drug?

**Comment by msevestre** [comment]
Could you create another entry for that? We'll be able to discuss this idea
there as well

**Comment by jgonlop3** [comment]
Yes, but I wrote here the idea due its relation with clinical use. No problem, I will create another entry.

**Comment by msevestre** [comment]
@jgonlop3 Did you create the issue regarding thee therapeutic range of drugs? I can't seem to find it. Thanks

**Comment by msevestre** [comment]
closing for now
