### ISSUE TITLE
P450 levels for cynomolgus

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#112]
Just found this in literature: may be of interest to the community:

[Comparison of P450 Enzymes Between Cynomolgus Monkeys and Humans: P450 Identities, Protein Contents, Kinetic Parameters, and Potential for Inhibitory Profiles](http://www.eurekaselect.com/106295/article)

**Comment by msevestre** [comment]
@StephanSchaller Thanks
