### ISSUE TITLE
Adding Parameter in MoBi 

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#114]
![image](https://user-images.githubusercontent.com/27323536/34101616-f91036e8-e431-11e7-9cea-779b0a0c30ff.png)

I added a parameter "Pgtest" (attached pic). 
I wanted to edit this parameter- I am not sure where to look for this parameter.
Project attached.

[PKsim_Mobi_18122017.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1567634/PKsim_Mobi_18122017.zip)

**Comment by Yuri05** [comment]
Well, according to your history seems to be in Organism|Liver , which is in the spatial structure Building Block.
In general you can use the Search function of Mobile (refer to the OSP Suite User Manual) for details

**Comment by msevestre** [comment]
@moulirc Closing. Let us know if you need more help. Cheers
