### ISSUE TITLE
How to fix scale value of Intracellular : plasma partition coefficient 

### ISSUE THREAD

**Issue by wanneekanta** [Open-Systems-Pharmacology/Forum#115]
I would like to simulate 1-compartment model by reducing distribution from plasma to intracellular.
1. For individual simulation
After run the simulation, in parameters tab: Distribution -> Partition coefficient -> Intracellular : Plasma. I set the value in scale to 0.5, the model with the setting scale well fitted to observed data.
How can I fix this scale value as default for another run. I have tried to clone that simulation to get the same scale setting. It worked well. Are there any ways to fix the scale values such as fix the values in building block before run. 
2. For population simulation
I would like to use this scale for population simulation. I manually set the value in user defined variability tab after run: Distribution -> Partition coefficient -> Intracellular : Plasma;Distribution drop down -> constant. Are there any ways to fix the scale values.
Best,
Wannee

**Comment by Aedginto** [comment]
Hi Wannee,
My suggestion is that you modify the lipophilicity term as opposed to modifying partition coefficients using the scale factor. Lipophilicity is a very important determinant of tissue: plasma partition coefficients. It is likely that a small change in lipophilicity (a usually uncertain number) will greatly affect the distribution profile of your compound. Further, try you can also optimize  your lipophilicity and the partition coefficient used to calculate the tissue: plasma partition coefficients in Parameter Identification. Use data following IV administration for this. Reasonably modifying lipophilicity allows you to use the building blocks without modification in your simulations. Then you don't have to worry about manually changing tissue: plasma partitioning. 
Take care!
Andrea
PS. manually try the Rodgers and Rowland algorithm first....that's my go-to algorithm.

**Comment by msevestre** [comment]
@wanneekanta Please let us know if you have any other questions. Thanks
