### ISSUE TITLE
How does Pk-Sim adjust administered dose to account for serum protein binding? 

### ISSUE THREAD

**Issue by hualiwu2017** [Open-Systems-Pharmacology/Forum#117]
If you have 30% bound, will the administered dose be used as input as 100% or reduced by 30%? I cannot see the differential equations in each organ compartment to help me understand that. Thank you very much for any information!!

**Comment by Aedginto** [comment]
The dose is 100% and not reduced by fraction unbound, as that would be incorrect. The dose would only be reduced if there was a dissolution function that did not reach 100% dissolved; I can’t think of any other way to have <100%.
Take care!
A.

**Comment by hualiwu2017** [comment]
Hi Andrea,

Thank you so much for your reply! This is very helpful. I got the question
from a very experienced PBPK modeler for chemical industry. I guess the
dose is not reduced by fraction unbound in PK-Sim and felt more confident
after you confirm that.

Again thanks and hope you have a wonderful 2018!

Warm regards,

Huali
