### ISSUE TITLE
Expression databases

### ISSUE THREAD

**Issue by BillFrez** [Open-Systems-Pharmacology/Forum#118]
Forgive my ignorance as I'm a new PK-SIM open source user.   I see there is an expression DB for humans but am looking for rat DB.   Does one exist?   If not, can the human db be modified for a rat model?    If mod is possible, what is the password for the human db?

**Comment by msevestre** [comment]
@BillFrez 
I am not sure what you mean with "can the human db be modified for a rat model" 

But you can definitely use the HUMAN DB for a rat. (technically doable but hard to say if this is a valid method). Check #8 and simply select the same database for the species rat

**Comment by msevestre** [comment]
@BillFrez Let us know if you need more help.
