### ISSUE TITLE
New event for MoBi in 2018

### ISSUE THREAD

**Issue by HiroQSP** [Open-Systems-Pharmacology/Forum#119]
Hello,
I am interested in a workshop for QSP/MoBi.
Do you have any plan to hold a workshop for MoBi in 2018?
Thank you in advance.
Hiro

**Comment by Yuri05** [comment]
s. [here](https://github.com/Open-Systems-Pharmacology/Forum/issues/136#issuecomment-364497406)

**Comment by HiroQSP** [comment]
Thank you very much for your reply.
