### ISSUE TITLE
Request example of monoclonal antibody .pksim project

### ISSUE THREAD

**Issue by drfreedman** [Open-Systems-Pharmacology/Forum#12]
Dear Sir,

Please consider providing a .pksim  project for an exemplary  monoclonal antibody with appropriate parameters.

Regards,

Immanuel Freedman, PhD SMIEEE
AAPS Pharmaco-Imaging Focus Group Past Chair

**Comment by TheiBa** [comment]
We will upload examples soon including an exercise on building an Ab model.

**Comment by TheiBa** [comment]
@drfreedman you may be interested in #16

**Comment by TheiBa** [comment]
Please see #19 - the material includes and Ab example. More to come, but I guess the start answers the question
