### ISSUE TITLE
allometric scaling in pksim

### ISSUE THREAD

**Issue by elmokadem** [Open-Systems-Pharmacology/Forum#120]
Hi,

I was curious about how the scaling of a typical individual physiologic parameters is done in pksim. I traced back the literature to an excellent paper by Willmann et al in 2007 that states that allometric scaling is being adopted. For example, scaling of organ weights (OW) follows:

OW_target = (Height_target/Height_mean)^0.75 * OW_mean

From what I understood, the Height_mean and OW_mean belong to a mean adult individual. So for example, the liver weight for a 5 year old with a height of ~109 cm would be:
OW_target = (109/176)^0.75 * 2.35
with 176 and 2.35 being the adult mean height and liver weight, respectively.

The thing is that when I apply this equation, the organ weights I get are way off the values mentioned in the measured ICRP database. Also, the results I get from the equation are very different than the results I get from the generated individuals in pksim. Furthermore, the generated results from pksim agree well with the ICRP data for some parameters but differ greatly for others.

So, I guess the short version of my question is: how is the scaling done in pksim?

Thanks and regards,
Ahmed.

**Comment by StephanSchaller** [comment]
@JanSchlender

**Comment by JanSchlender** [comment]
Hi Ahmed,

Well observed. You may also read Edginton et al 2006 (https://www.ncbi.nlm.nih.gov/pubmed/16984214). The ICRP population database is well explained in this publication.
Best regards,

Jan

**Comment by msevestre** [comment]
@elmokadem 

You can also check the wiki page [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Create-Individual-Algorithm) describing how the Create Individual Algorithm is implemented in details. This should compliment the above mentioned publication nicely

Cheers,

**Comment by elmokadem** [comment]
Thanks Stephan, Jan and Michael for your replies. The Edginton paper was very helpful in explaining some of the discrepancies between organ volumes/weights reported in ICRP and those calculated by PKSim. Nevertheless, it still doesn't explain why a scaling method based on weight or BSA wasn't adopted instead of a clearly erroneous height scaling method.
The wiki page was also very useful as it confirmed that the scaling with height is indeed the method used to calculate the mean organ volumes and this is where I am having a problem.
Take liver weight as an example. If we use the formula mentioned in my initial comment (and in the wiki page) to calculate the liver weights for a range of individuals ranging in heights from 51 to 176 cm, the equation will be:
Li_wt = 1.8*(HT/176)^0.75
This will result in liver weights that are so different from the ICRP reported weights as shown in the figure below. This means that when we use these scaled liver weights as means to sample random weights that are normally distributed, they will spread around the line shown in the plot and will not reflect a distribution close to the ICRP datapoints. On the other hand, if we simply use linear scaling with weight, the results now agree very well with the ICRP data. 
![](/Users/ahmede/Pictures/li_scaling.png)

**Comment by elmokadem** [comment]
Thanks a lot Michael for the clarification. I guess my last question here is: because ICRP lacks the organ specific data (volumes and flows) for every possible age, what kind of extrapolation do you do for covering these gaps? In the Edgington paper mentioned in Jan's comment, it is mentioned that cubic splines were used for some parameters as blood volume and heights, so is the same extrapolation used for organ volumes?

**Comment by msevestre** [comment]
@elmokadem PK-Sim does not use cubic splines interpolation anymore. 
At the moment, a simple linear interpolation is used between available ages and for all parameters

**Comment by elmokadem** [comment]
Thanks a lot Michael.. That was really helpful.

**Comment by elmokadem** [comment]
Looking forward to it :)
