### ISSUE TITLE
PK-Sim Error message

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/Forum#121]
I am a new user in PK-Sim. I have tried to open some projects in PK-Sim and I got the error attached. I would really appreciate if you could guide me how to solve this issue.

![pksimerror](https://user-images.githubusercontent.com/35151285/34739562-a7aca956-f54a-11e7-95b3-75fa25cd593e.JPG)

Thank you
Farzan

**Comment by msevestre** [comment]
@farzanehmaleki 
I am a little bit confused here. You are mentioning PK-Sim but the message is displayed in MoBi. 
What version of the OSPSuite are you using?

At any rate, this message indicates that you are trying to open a project that was created with a newer version of the tool (so your version is TOO OLD).

Please update to latest version and try again

**Comment by farzanehmaleki** [comment]
Sorry for the confusion. I have two projects in PK-Sim and MoBi. When I open MoBi file I get the error which I shared above. If I open PK-Sim file I will end up with an empty PK-Sim window. I have version 7.2.1 installed.

**Comment by msevestre** [comment]
@farzanehmaleki 

Is it possible for you to attach your MoBi project here? (zip and upload the file). Beware the forum is a public forum so this file will be available for everyone to see

Also what do you mean with "Empty PKSim window?". Can you try to follow the steps described [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/518)?

**Comment by msevestre** [comment]
Also please open MoBi and take a screenshot of the entire screen and update the screenshot

**Comment by farzanehmaleki** [comment]
Unfortunately I cannot upload the project because I did developed it. I found out that my MoBi is 7.0 while PK-Sim is 7.2.1. Do they need to be upgraded individually? As I said, I am very new to this software. Is there any tutorial to learn how to use this PK-Sim?

**Comment by msevestre** [comment]
@farzanehmaleki How did you install PK-Sim? Did you use the portable version?

In your case, you need to install the full setup that will uninstall the old 7.0 version and install the new PKSim.

https://github.com/Open-Systems-Pharmacology/Suite/releases/download/v7.2.1/OSPSuite-Full.7.2.1.exe

**Comment by farzanehmaleki** [comment]
It seems that it was the installation issue. I installed a full set up and now both PKSim and MoBi are working. Thank you for your help ;).

**Comment by msevestre** [comment]
great.
