### ISSUE TITLE
Enterohepatic recirculation

### ISSUE THREAD

**Issue by aargikar** [Open-Systems-Pharmacology/Forum#122]
Hi,
I was wondering enterohepatic recirculation could be added in PK-Sim. I have already added Bile clearance but it doesn't seem to cause the recirculation as it happens in vivo. Hence, AUC is severely underpredicted. Please let me know if this could be achieved. Thank you.

**Comment by msevestre** [comment]
Hi @aargikar 
Yes this is available in PK-Sim. Please refer to manual, chapter Chapter 18. PK-Sim® - Events for a detailed explanation on how to proceed.

Hope that helps

**Comment by aargikar** [comment]
Hi @msevestre,
I added the event + gall bladder emptying as Yes. I also manipulated the gall bladder ejection fraction and EHC continuous fraction. But none of these parameters improved the simulation. Is there a PK-Sim example file which I could work with /view? Please let me know. Thank you.

**Comment by msevestre** [comment]
@aargikar I would suggest to follow the common best practices for PBPK model development. EHC might not be the problem there

Check the following [link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5080648/pdf/PSP4-5-516.pdf). The article describes a step by step approach to building PBPK models with e.g. PK-Sim.

Hope that helps

**Comment by aargikar** [comment]
Thank you.
