### ISSUE TITLE
Possible Bug: Cloning a simulation 

### ISSUE THREAD

**Issue by vbalbas** [Open-Systems-Pharmacology/Forum#124]
Hello, 

I think I have found a little bug: 
When I clone a simulation (ID13) and I change the ID and the administration protocol (to ID14), the generated plot leaves in the simulated concentration legend, the name of the original Individual (from the cloned simulation), but the plasma concentration or fraction excreted to urine in the simulation are updated: 

**CLONED SIMULATION (ID 13) UPDATED TO ID 14**
![image](https://user-images.githubusercontent.com/16211975/34978778-a6bc95a6-fa9f-11e7-93e3-3b73b254b6bd.png)

Thanks you

Violeta

**Comment by msevestre** [comment]
@vbalbas Looks like a potential issue with PK-Sim so I moved your entry in the PK-Sim repo [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/534)
