### ISSUE TITLE
First and zero order formulation can be created but not used in PK-Sim 7.2.1

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#127]
I wanted to create an oral formulation with a first or zero orde dissolution profile. I could create the formulation building blocks, but is not possible to load the in the administartion protocol. What can I do with them now? Did I miss something?
Project attached
[first and zero order Formulations for GitHub.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1652097/first.and.zero.order.Formulations.for.GitHub.zip)
Kind regards, Tobias

**Comment by msevestre** [comment]
Hi @tobiasK2001,
 
FirstOrder and ZeroOrder Formulation are at the moment only supported for UserDefined application .

Do not hesitate to submit a feature request in the PK-Sim issue tracker if you feel that this is feature could be useful

Cheers

**Comment by teutonicod** [comment]
Dear @tobiasK2001, dear @msevestre,

Was there any feature request about this topic? Already in several occasion I wanted to test these formulations in a simulation and could not select them since I was not using the UserDefined application.

Thanks,

Donato

**Comment by msevestre** [comment]
Hi @teutonicod 
No feature request that I could find. Clearly, this was not so important for @tobiasK2001  at the time :)
The only way that a feature is considered for implementation is 
* there is a feature request 
* there is enough interest in it. 

You know what you have to do

**Comment by Yuri05** [comment]
@teutonicod @tobiasK2001 
As a workaround:
1. Open "Create formulation" dialog, select zero or first oder formulation and export it to Excel (you can Cancel after that, no need to create a formulation)
![grafik](https://user-images.githubusercontent.com/25061876/80460962-dac6fc80-8934-11ea-95db-5f5cb9b022a6.png)
2. Now create a table formulation and import the table from the exported 1st/0-order formulation
![grafik](https://user-images.githubusercontent.com/25061876/80461333-6ccf0500-8935-11ea-8c86-80bae6b1b429.png) ![grafik](https://user-images.githubusercontent.com/25061876/80461455-9425d200-8935-11ea-8dee-e70d327c1cb0.png)
3. Now you can use this table formulation with an oral application

**Comment by teutonicod** [comment]
@msevestre, @Yuri05,
Thank you very much! I was often stuck with this issue, and I also always forgot to submit a feature request! I will, since I think it is a pity that this options cannot be (easly) tested.

Donato

**Comment by tobiasK2001** [comment]
Thanks Donatoe for coming back to this and thanks Juri for providing this workaround. I was actually doing a workflow in MoBi to overcome this issue (which seems to be more complicated than Juris way :-0) when the need popped up in some previous project. Of course it would be much better to have it in PK-Sim integrated. Thanks for the initiative to make the request!
Best, 
Tobias
