### ISSUE TITLE
Enzyme polymorphism in PK Sim

### ISSUE THREAD

**Issue by aargikar** [Open-Systems-Pharmacology/Forum#128]
Hi,
I was wondering if poor (PM) and extensive (EM) metabolism of CYP2D6 substrates could be modeled in separate populations in PK Sim. Please let me know if there is a solution for this issue. Thank you.

**Comment by Aedginto** [comment]
The best way would be to reduce the reference concentration of CYP2D6 (assuming you are inputting this clearance pathway as an enzyme) by the factor of PM:EM. Make two populations (one with normal ref conc and one with reduced) and you can simulate them separately. 

Another option is to merge them into one population by exporting each to .csv and reimporting both the PM and EM populations in the same 'Import Population from File'. When you simulate, you can partition the graphs by 'Population Name' to see PM and EM separately or you can see the graphs merged. 

Take care!
Andrea

**Comment by aargikar** [comment]
Thanks Andrea. Would you recommend to decrease the CYP2D6 expression as per of the enzyme activity in PM? Thank you.

**Comment by Aedginto** [comment]
If you create the CYP2D6 enzyme in the PM individual, there will be an associated reference concentration of CYP2D6 in liver. Reduce this reference concentration as needed. This value is multiplied by the relative expression, the specific clearance and then a bunch of scalars thus reducing the associated clearance by the  reduced fraction of CYP2D6. 

Hope this answers what you're asking!
Andrea

**Comment by aargikar** [comment]
Yes. It does. Thank you so much.

**Comment by TheiBa** [comment]
For historic examples (mostly with older versions and workflow), please have look at 
https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/labels/CYP2D6
