### ISSUE TITLE
Renal Clearance

### ISSUE THREAD

**Issue by aargikar** [Open-Systems-Pharmacology/Forum#129]
Hi,
I am building a PBPK for an orally administered drug (no IV data available as yet). I have renal Clearance value from published literature. I noticed that PK Sim calculates specific clearance from plasma clearance and uses this value in the model. Is it possible for me to use a renal clearance value instead (ml/min/kg)? Please let me know. Thank you.

**Comment by msevestre** [comment]
@aargikar

I am not sure I understand your question. 

The value of renal plasma clearance in ml/min/kg is used to calculate the value of specific clearance using a predefined formula
![image](https://user-images.githubusercontent.com/1041237/35455125-d1323500-029e-11e8-9bd9-a6390d5a6877.png)

As long as you do not overwrite the formula, each change of renal plasma clearance will reflect in a change of a specific clearance. 

So renal plasma clearance is used in your model already.

**Comment by aargikar** [comment]
So, the row labelled as plasma clearance in the above image is really the renal plasma clearance and not the plasma clearance or systemic clearance. Is that accurate?

**Comment by msevestre** [comment]
@aargikar Correct:
You are defining a Renal clearance process and as such the parameter *plasma clearance* is the renal plasma clearance.

**Comment by aargikar** [comment]
Got it. Thank you so much.
