### ISSUE TITLE
Intestinal Metabolism

### ISSUE THREAD

**Issue by vaimun** [Open-Systems-Pharmacology/Forum#13]
Hello everyone,

I am working on a molecule which undergoes extensive intestinal metabolism and I am not sure how that can be included using PK Sim,  I would appreciate if you can share your experience/literature/suggestions to handle intestinal metabolism.   Thanks in advance for all the comments and help.

**Comment by JanSchlender** [comment]
Hi vainum,

Here are two examples for your case and how to handle them in the OSP
https://www.ncbi.nlm.nih.gov/pubmed/23696038
https://www.ncbi.nlm.nih.gov/pubmed/22125236

I hope this helps and explains already the procedure.

**Comment by rungineer932** [comment]
Along the lines of gut metabolism...

I see it is possible to modify transit times for gastric emptying, small intestine, and large intestine... is it possible to modify the transit times of segments that make up both small and large intestine?

Also, is it possible to access the dimensions of the intestinal compartments/segments?

Thanks for any info!

**Comment by Yuri05** [comment]
Set parameter view mode to "Advanced" as shown below; after that you will find parameters of interest 
under **_Anatomy/GIT-Dimensions_** and **_Physiology/GIT-Physiology/GIT-Transit time_**
<img src="https://user-images.githubusercontent.com/25061876/27076330-32adc68e-502d-11e7-91fa-a449b1e8e526.jpg" width="300">    <img src="https://user-images.githubusercontent.com/25061876/27076498-a2ad2268-502d-11e7-8c49-fabf385c2b8c.jpg" width="300">

<img src="https://user-images.githubusercontent.com/25061876/27076536-c7867968-502d-11e7-8462-9d78cd911590.jpg" width="600">

**Comment by rungineer932** [comment]
Thank you, Yuri05, that was very helpful.  Is there a way to track/simulate the concentration in the intestinal mucosa? It seems that a mucosal compartment exists for duodenum, jejunum, ileum, etc.  I assume it would be under simulation settings: curve selection, but I am not seeing an option for mucosa.   
Thank you!

**Comment by Yuri05** [comment]
You can find intestinal mucosa segments on the top level in the curves selection dialog
![clipboard01](https://user-images.githubusercontent.com/25061876/27120480-06c37412-50e4-11e7-9b3f-8c558dbca4ad.jpg)

**Comment by rungineer932** [comment]
Thanks again! Can the fraction unbound within enterocytes be incorporated/modified? I'm only finding fu, plasma.

**Comment by sfrechen** [comment]
No, within PK-Sim you do not have direct access to the fraction unbound in the compartments. The fu for intracellular compartment is calculated based on the fu,plasma and the partition coefficients under the assumption that at steady state all unbound concentrations are equal (in the absence of any active processes). If you have good reason to change the default behavior in enterocytes, I would recommend to assess these fractions unbound in MoBi (called here 'Partition coefficient (water/container)'). You find them e.g. for the Duodenum for your MOLECULE of interest in:
Organism|SmallIntestine|Mucosa|Duodenum|Intracellular|MOLECULE|Partition coefficient (water/container)

In general for all segments of the intestinal tract:
Organism|*|Mucosa|*|Intracellular|MOLECULE|Partition coefficient (water/container)

**Comment by rungineer932** [comment]
Thank you, sfrenchen... that is very helpful.  
Is it possible to plot the **total** drug concentration profiles within the intestinal lumen compartments? It seems as though the default lumen concentration for each segment is actually the **dissolved** drug concentration.

**Comment by sfrechen** [comment]
Yes, correct, plotting luminal concentrations shows you the dissolved part. If you are interested in the total amount in each lumen, please go to MoBi. There you have access to all amounts in every compartment (and you can also define your own observers).
