### ISSUE TITLE
Import Population from File error

### ISSUE THREAD

**Issue by watt0005** [Open-Systems-Pharmacology/Forum#130]
I have created several pediatric populations (e.g., neonate, infant, etc) that were exported to csv for modification then re-imported. All of the re-imports worked without issue except the neonate population where I received the error message in the screenshot below. Thanks for your assistance.
![population error 20180129](https://user-images.githubusercontent.com/31321213/35516157-08ded76a-04d9-11e8-9134-c50f0ca851ed.jpg)

**Comment by msevestre** [comment]
Hey @watt0005 . Looks like a bug indeed (or at least a better error message should be displayed.). 
Would you mind moving the issue to the [PK-Sim issue](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues) list and we'll go from there?
