### ISSUE TITLE
Intra muscular administration

### ISSUE THREAD

**Issue by nmens** [Open-Systems-Pharmacology/Forum#134]
Dear PK-Sim community
Any idea how to implement IM administration?
Thanks in advance

**Comment by JanSchlender** [comment]
Change the "Administration type" to "User Defined" and select the desired target organ/compartment

![grafik](https://user-images.githubusercontent.com/26056951/35879423-7767da26-0b7b-11e8-9df0-a28f28c3c595.png)

**Comment by PavelBal** [comment]
This is a simple (and working) solution. But you have to keep in mind that the administered compound will be "distributed" over the whole muscle tissue instantaneously.

If you think that this simplification may negatively affect simulation results, you can export the model to MoBi and implement a more comprehensive administration. You could separate a part of the muscle from the total muslce compartment (e.g., representig a special muscle typical for administration).

**Comment by tobiasK2001** [comment]
Additional to the above you might want to have a simpler solution (possible in PK-Sim) reflecting a time delayed release from your IM compartment. In that case you may couple the intracellular application with a formulation using zero or first order release into that compartment and adjust the t1/2 to your needs. Hope that might help you.

**Comment by msevestre** [comment]
@nmens Please do not hesitate to reopen if you have more questions. Thanks
