### ISSUE TITLE
bloof flow scaling

### ISSUE THREAD

**Issue by elmokadem** [Open-Systems-Pharmacology/Forum#135]
Hi,
Given the pseudo code on the "create individual" wiki page, it seems that PKSim doesn't add a "rest of the body" compartment but rather scales up the adipose volume to account for the weight difference between the target and mean weights. But not having that extra compartment that accounts for other tissues not explicitly described will cause an imbalance in blood flows and a lower estimate of cardiac output since all tissue flows should add up to the cardiac output. The way you might get around this is either scale down the cardiac output or scale up the tissue blood flows. So, is this what PKSim is doing or is it handling this differently?

**Comment by StephanSchaller** [comment]
It's the former. Although I would not call it "scaling".

AFAIK cardiac output is the sum of all organ blood flows.
Organ blood flows are defined by their volume multiplied by the specific blood flow for each organ type.

Sth. like:
F_Blood_Organ = V_Organ * F_Blood_spec_Organ

**Comment by StephanSchaller** [comment]
Hi @elmokadem , if you want to have a more detailed insight into how everything is connected, send your model to MoBi (right click on the SImulation in PKSim and -> send to MoBi).

There you can see all the formulas and click through all the relations...

Have fun!

**Comment by elmokadem** [comment]
Thanks Stephan. I will.
