### ISSUE TITLE
PKSim Workshop

### ISSUE THREAD

**Issue by BillFrez** [Open-Systems-Pharmacology/Forum#136]
Are there plans for a 2018 PKSIM workshop?

**Comment by StephanSchaller** [comment]
esqLABS will give a 1-day workshop on PKSim, MoBi & Working with R on Monday 28th May in Montreux, Switzerland just before the PAGE Meeting. We'll open the registration as soon as we have the confirmation from the venue. I'll post it here.

@JanSchlender  may have more info on additional workshops later this year.

**Comment by BillFrez** [comment]
Any in US would be of interest too.

**Comment by valdiman** [comment]
Webinar?

**Comment by BillFrez** [comment]
Yes.  Webinar would be helpful

**Comment by StephanSchaller** [comment]
> Any in US would be of interest too.

Yes, I am pretty sure, there will be a workshop just before ASCPT in Orlando in early October.

> Webinar?

esqLABS is also contemplating webinars, but we have yet to put sth. together.

Now, we'll be in the US from time to time (March, June and October). We'll be happy to put a workshop together. Were are you based?

**Comment by BillFrez** [comment]
In Cleveland OH w The Lubrizol Corp

**Comment by StephanSchaller** [comment]
I guess we would get sth. together with enough participants in New Jersey or Boston Area.

**Comment by BillFrez** [comment]
That might work nicely.   We're particularly interested in incorporating metab of industrial chemicals.  I'll stay tuned.   Thx Bill

**Comment by StephanSchaller** [comment]
Registration now open for the 1-Day workshop on PKSim & MoBi. 
To register, please send me an eMail or use workshop@esqlabs.com.

More information can be found [here](https://github.com/Open-Systems-Pharmacology/PAGE-2018-Workshop)

**Comment by HiroQSP** [comment]
Thank you for your good news. I am planning to participate in your OSP workshop as well as ACoP9.
You said it would be held in Orland. Is that Frolida?
I would also like to know how much time you will address MoBi. My interest is QSP.

**Comment by krinaj** [comment]
I am greatly interested in workshop in US as well; can't make it to PAGE. I am specially interested in advance training with PK-Sim and especially Mobi.

**Comment by BillFrez** [comment]
I wonder if a webinar-like workshop might be possiblefor pk sim and mobi?

**Comment by StephanSchaller** [comment]
@BillFrez any reason why you closed this issue?
A Webinar might be possible. We'll have to check options. Ideas on format welcome.

@HiroQSP, the workshops esqlabs will provide have a focus on QSP (working with MoBi and R) but also give you a good overview on PBPK model building in PKSim.

Hi @krinaj, we have planned a workshop for ACOP in October. Maybe we'll squeeze in another one in June somewhere in the Boston or NY area.

**Comment by BillFrez** [comment]
Mistakenly closed.  Still very much interested.

**Comment by BillFrez** [comment]
How to do that?

**Comment by StephanSchaller** [comment]
For the **US** (if you have not seen it already here on the forum) we will have a workshop just before ACoP on October 6th in San Diego. More Info [here](https://github.com/Open-Systems-Pharmacology/ACoP-2018-Workshop
