### ISSUE TITLE
is there a way to add variability on dose in Population simulations

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#137]
Dear all,

do you knw how I can add variability for the dose administered in Population simulations. There is a bunch of paramters visible in the "user defined variability" tab. But administerd dose is missing. How can I acces this parameter?

Best, Tobias

**Comment by StephanSchaller** [comment]
By intentions some parameters in PKSim are not available for user-defined variability, because it does not make sense.
You can export as xml, change canbevaried = 0 to 1 and then simulate the population in Matlab (and add your distribution there).

Good luck!
Stephan

**Comment by tobiasK2001** [comment]
Thanks Stephan for this workaround! 
@msevestre: However, I think the dose should be avalable for user defined varibility as it makes perfect sense adding varibility there.  The labelled dose is never the actual dose in e.g. a tablet. USP allows content of a drug to vary between 85 per cent and 115 per cent of the average content. For other applications this applies as well even more or less. So we might miss this variability in performing population simulation be default. Where was the place to put this on a wish list?

Kind regards, Tobias

**Comment by Yuri05** [comment]
>Where was the place to put this on a wish list?

https://github.com/Open-Systems-Pharmacology/PK-Sim/issues

**Comment by tobiasK2001** [comment]
;-)

**Comment by msevestre** [comment]
Feature request was added [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/567)
