### ISSUE TITLE
GENEDB password protected!!

### ISSUE THREAD

**Issue by elmokadem** [Open-Systems-Pharmacology/Forum#140]
Hi,
I just downloaded the GENEDB_human database from here:
https://github.com/Open-Systems-Pharmacology/Suite/releases
but it seems to be password protected. Could you please help me open it.

Thanks.

**Comment by msevestre** [comment]
Hi @elmokadem,

We are aware of that [see issue here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/519). The password protection will be removed in the next release of the database.

Thanks,
Michael

**Comment by elmokadem** [comment]
Great. Thanks a lot Michael.

**Comment by jasaiwaldk** [comment]
Dear Sir, please give me password. I am M.Pharmacy Pharmacology student. I shall be thankful to you for this help. Please provide me password of database or provide link of new database

**Comment by msevestre** [comment]
@jasaiwaldk As mentioned above, the password protection will be removed in the next release
Why do you need to access the raw data in the database? 
Maybe you simply need to use the query tool implemented in PK-Sim?
My suggestion would be to read the manual on how to use the GeneDB or to follow instructions from this [post](https://github.com/Open-Systems-Pharmacology/Forum/issues/8)

Also I will kindly ask you to not comment on closed issue in the future as this makes issue tracking quite difficult for us. Thanks for your understanding
