### ISSUE TITLE
How can I assigne the contribution enzyme

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#142]
The drug is metabolized by multiple enzymes. How I can assign enzymes for a drug metabolism. 

60% CYP2D6, 10% CYP1A2, 5%  CYP2C9, 5%  CYP2E1, and 20% UGT
Please advise

mouli

**Comment by prvmalik** [comment]
Here's one way I did it.

Step 1:  Determine total hepatic clearance (CLh) (mL/min)
- Use Compound > ADME > Metabolism > Total Hepatic Clearance > Plasma Clearance
- Optimize as appropriate

Step 2:  Model CLh with intrinsic clearance (CLint) through 1 enzyme
- Calculate a composite of the total intrinsic clearance (CLcomp) (umol*mL/min)
- CLcomp =  RefConc(1) * CLint(1); where RefConc(1) is the reference concentration of that enzyme

Step 3:  Portion the composite number according to relative contribution and determine the intrinsic clearance for each enzyme.
- Calculate intrinsic clearance for each enzyme (i) by : CLint(i) = CLcomp / RefConc(i)

**Comment by prvmalik** [comment]
Model total hepatic clearance (mL/min) using 1 metabolizing enzyme.

Calculate a composite for total hepatic intrinsic clearance (umol*mL/min) by:
Comp = refC(1) x CLint(1)
Where CLint(1) is the intrinsic clearance value required to match total hepatic clearance on the PK profile and where refC(1) is the reference concentration of the 1 enzyme used

Attribute the total hepatic intrinsic clearance according to relative contribution (%)

Calculate intrinsic clearance for each enzyme (i) by:
CLint(i) = Comp x RelCon(i) / RefC(i)
Where RelCon(i) is the relative contribution (%) of that enzyme to hepatic clearance.

**Comment by moulirc** [comment]
Hi Malik,

thanks for your guidance.

kind regards
mouli

**Comment by DanielMoj** [comment]
moulirc,

in case you do not want to use the total hepatic clearance but e.g. michaelis menten kinetics and tissue-specific distribution of the enzymes using the gene expression database you could also do the following:
1. Implement the above mentioned enzymes with literature vmax and km values. 
2. Go to MoBi and build an observer that sums up all intracellular amounts for each metabolite formed by one of the enyzmes. (As long as you do not try to model the metabolites with logP values etc., the formed metabolites will stay in the intracellular compartments.) Divide the sumed up amounts by the administered dose and you get the actual % contribution of each enzyme.
4. To assign % contributions you can then import the above mentioned % values. Link the generated observers to the imported % values and fit e.g. the Vmax values or reference concentrations of the enzymes to match the simulated with the observed % values. 

Best Daniel
