### ISSUE TITLE
PBPK for pregnant women 

### ISSUE THREAD

**Issue by AbilashReddybathini** [Open-Systems-Pharmacology/Forum#1423]
I am unable to run a pregnant model in MOBI, I am unable to run the simulation, and 
I am getting an issue saying "Unable to resolve path start value for entity cyp3a4".

I also request to kindly provide a "video tutorial on how to build a pregnant pbpk model using Mobi this can be very useful"

Thank you 
![pregnant PBPK](https://user-images.githubusercontent.com/121849202/210308956-b3c2156b-88fe-43f3-9681-c5aaf3f262ee.jpg)

**Comment by StephanSchaller** [comment]
Dear @AbilashReddybathini , you can find a course on use of the pregnancy model here: https://learn-esqlabs.talentlms.com/
