### ISSUE TITLE
How to express metabolizing enzymes in PK-SIM for Vmax, Km data by HLM

### ISSUE THREAD

**Issue by Cheruvh** [Open-Systems-Pharmacology/Forum#1432]
Hi,

I have to include saturation kinetics in my model rather than linear kinetics. So I got Vmax, and Km data by Human Liver Microsomes in vitro and do not have recombinant CYP-based data. Now, how should I express the HLM enzymes under 'Metabolizing enzymes' for metabolism? 

Does mentioning HLM in the metabolizing enzyme work I tried but no enzymes were expressed in the individual and cannot see anything for the metabolism process during the simulation.
![image](https://user-images.githubusercontent.com/103236850/211692597-12e7721b-50db-43fe-b373-e1b46a34b4ce.png)

I know it is easier to express them if we have individual recombinant CYP data but no idea related to HLM. Moreover, how to express all CYP enzymes in the individual? Please explain how to do this. Thanks in advance

**Comment by tobiasK2001** [comment]
Hi,
you have to add the metabolizing enzymes to your individual first. Than you can connect them to the metabolizing processes of the compound. Please check the documentation and here could be a good start: https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-profile#the-workflow.
Best, Tobias
