### ISSUE TITLE
Error message when using the GENEDB file

### ISSUE THREAD

**Issue by ErikssonJ** [Open-Systems-Pharmacology/Forum#148]
I get an error message when I try to create an individual with enzyme or protein from the database GENEDB. What could be the problem, and how to solve it? I downloaded the file and have not opened or changed it in any way.
![capture](https://user-images.githubusercontent.com/37363640/37390494-310a215a-2760-11e8-985a-0a7ef011a52d.PNG)

**Comment by msevestre** [comment]
Hi @ErikssonJ,

How did you install PK-Sim? Using the setup or the portable version?
Also which version of PK-Sim are you using? (you can find the version at the bottom right).

Lastly, can you try to download the file again? It could be that it was corrupted during the download for some reasons.  Also can you try moving the file to another drive and see if this solves the problem?

Thanks,
Michael

**Comment by msevestre** [comment]
@ErikssonJ I am assuming that you managed to solve your problem. If not, please do not hesitate to open an issue in the [PK-Sim Issue Tracker](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues).
Cheers
