### ISSUE TITLE
Minipig model in PKSim

### ISSUE THREAD

**Issue by AnVermeulenUGhent** [Open-Systems-Pharmacology/Forum#149]
I am looking for information and/or references (literature) that clarify the source of the physiological parameters used to define the minipig species in PKSim. I couldn't find anything in the help or the reference material thus far, maybe I overlooked it? We might consider to expand the minipig model to younger age groups, and would also like to better understand what parameters we would need to get data on/generate data for to allow such extrapolation. Any insights that you can provide are more than welcome!

**Comment by StephanSchaller** [comment]
That's great news!!

I have started a discussion [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/377).
Recently, I have also had questions about the references, I'll try to dig up the answer.

If you need support, maybe we (esqLABS GmbH) can help! Let us know.

Stephan

**Comment by Yuri05** [comment]
You will find the sources [here](https://github.com/Open-Systems-Pharmacology/Forum/issues/40#issuecomment-320976350)
