### ISSUE TITLE
pk-sim tutorial series

### ISSUE THREAD

**Issue by vjd** [Open-Systems-Pharmacology/Forum#15]
Hi -

I am writing on behalf of the ISoP education committee where we conduct what are called as [pharmacometric study groups](https://isop-phmx.github.io/studyGroup/). Our goal is to provide online education via webinars that include tutorials and hands-on sessions as you can see [here](https://isop-phmx.github.io/studyGroupHandbook/event-types.html). 

Would anyone from the Pk-sim community be open to coordinate and setup a series of tutorials on PK-sim right from installation to the going through simple examples to complex case-studies? This would be extremely valuable to the community especially considering that pk-sim is now open-source and free. We consider these webinars via youtube and is easy to setup. 

Please let me know if you have an interest in setting up a summer webinar series with us and we will be happy to host and figure out the logistics for you. All you have to do to begin is open an issue [here](https://github.com/isop-phmx/studyGroup/issues)

Best regards,
Vijay

**Comment by msevestre** [comment]
@vjd I think this is a great idea and this would be indeed very valuable.
>We consider these webinars via youtube and is easy to setup.

Are you talking here about tutorials that will be recorded and posted online? Or are you referring to the [work-along](https://isop-phmx.github.io/studyGroupHandbook/event-types.html#workalong) series?

**Comment by vjd** [comment]
@msevestre I meant to write we "conduct" these sessions, can be any kind via youtube. Take a look at some of the sessions already conducted here - http://discuss.go-isop.org/c/studygroup

you guys have rocked this field by open sourcing pk-sim which is brilliant, we just now need good/free/open tutorials to go with it. The advantage is that you don't have to wait for a conference to host such a session, just do it anytime and an entire audience will be there for you, not limited by the seating at the hotel :) and github issues or discussion forums to ask questions

**Comment by TheiBa** [comment]
@vjd thanks for supporting the rock ;-) first ISoP session including some tutorial part is in fact already planned! see #15; maybe you can announce it in isop-phmx? hope we will find more volunteers for additional tutorials here ;-)

**Comment by vjd** [comment]
@TheiBa the announcement has been done. I can provide some ideas on how to encourage people if I see you guys at PAGE next week. Exciting times ahead for #opensource software in pharma!

**Comment by TheiBa** [comment]
Thanks @vjd . After the first seminar is completed (see #19), I guess we can close this, keeping in mind to all aim for and work towards more tutorials to come.  Enjoy PAGE - and yes, several of us will be there.
