### ISSUE TITLE
Followup on Solubility gain per charge.

### ISSUE THREAD

**Issue by JoseDavidGomez** [Open-Systems-Pharmacology/Forum#152]
Hi everybody,
According to the Pk-Sim manual the gain in solubility by diferences in pH is described by the Henderson-Hasselbalch equation.
I assume it refers to:

LogS = LogSo + Log (1 + 10^(pKb-pH))   For a monoprotic base
So : Solubility of unionized form
pKb: Basic pKa

my two questions are:

Which part of this equation is affected by the solubility gain per charge parameter?
Is it assumed in Pk-Sim that the ionized form has the same permeability as the unionized form?

I am aware that the Solubility gain per charge was discussed before but issue is still open (https://github.com/Open-Systems-Pharmacology/Forum/issues/38)...

Thank you very much !

José David

**Comment by Aedginto** [comment]
Hi Jose David, 
So I can't answer this for you but, when I am doing a PBPK model, there is usually solubility data available at different pH levels, and I make sure to match the profile (which you can see if you click on the little symbol beside this parameter) with the data. If pH makes a difference to solubility, the data is going to be available for sure. Further, a sensitivity analysis will give you an indication of the importance of solubility to your outcome of interest.
Take care,
Andrea

**Comment by msevestre** [comment]
@JoseDavidGomez 
Upcoming version 7.3 will include a way to load a pH vs Solubility Table. This will be very easy to override the default behavior if required or ensure that the available solubility data at different pH is used. 

>Which part of this equation is affected by the solubility gain per charge parameter?

In order to see where a parameter is used, the easiest approach is to export the model structure to file and look for the parameter of interest, in your case `Solubility gain per charge`

![image](https://user-images.githubusercontent.com/1041237/38435599-1a14d47a-39a0-11e8-9e8f-ee7206e441bc.png)

For example exporting a default simulation reveals

```
Parameter: S|Organism|Lumen|Duodenum|C1|Solubility
	IsFixed: False
	Value: 2.45137295941161E-05 [kg/l]
	Formula: Solubility * Solubility_pKa_REFpH_Factor / Solubility_pKa_pH_Factor
		Solubility_pKa_pH_Factor: S|Organism|Lumen|Duodenum|C1|Solubility_pKa_pH_Factor(0.342660523661014)
		Solubility: S|C1|Solubility at reference pH(1.2E-05 [kg/l])
		Solubility_pKa_REFpH_Factor: S|C1|Solubility_pKa_pH_Factor(0.69999061830036)

Parameter: S|Organism|Lumen|Duodenum|C1|Solubility_pKa_pH_Factor
	IsFixed: False
	Value: 0.342660523661014
	Formula: K1+K2/base^(CT0^2)+K3/base^(CT1^2)+K4/base^(CT2^2)+K5/base^max(CT0+CT1;-CT0-CT1)+K6/base^max(CT0+CT2;-CT0-CT2)+K7/base^max(CT1+CT2;-CT1-CT2)+K8/base^max(CT0+CT1+CT2;-CT0-CT1-CT2)
		K1: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K1(0.0163226591603296)
		K2: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K2(0.649816765422792)
		K3: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K3(0.00818070839000644)
		K4: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K4(0)
		K5: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K5(0.325679867026872)
		K6: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K6(0)
		K7: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K7(0)
		K8: S|Organism|Lumen|Duodenum|C1|pKa_pH_WS_lum_K8(0)
		CT0: S|C1|Compound type 0(1)
		CT1: S|C1|Compound type 1(-1)
		CT2: S|C1|Compound type 2(0)
		base: S|C1|Solubility gain per charge(1000)
```
which shows HOW the `solubility` is calculated in `Lumen, Duodenum`

Hope that helps
