### ISSUE TITLE
Tissue to plasma partition coefficient. Experiment vs. Calculated 

### ISSUE THREAD

**Issue by gwchoi** [Open-Systems-Pharmacology/Forum#154]
Hello,

I have used other software to develop the PBPK model. I am new to PKsim, but I am sure it is a powerful tool for developing PBPK model. First of all, thanks to the scientists who developed this tool.

And I have some questions using PKsim.

1. As mentioned in the heading, I have found a difference in the tissue to plasma partition coefficient value obtained from the experiments and calculated from PKsim based on lipophilicity. When using calculated values to simulate, the observed plasma concentration data and predicted line was perfectly fitted. However, our experimental data showed that it was 100 times smaller than the calculated value. I would ask for advice on understanding this phenomenon.

2. Should I have to use the MoBi to add other organ compartments? For example, a virtual compartment to which Michaelis-Menten equation is applied to take into account the reabsorption of the kidney.

3. Can I report the PBPK models developed using PKsim to the journal without any restriction?

Thanks to all.
G.W. Choi

**Comment by Aedginto** [comment]
Hi G.W. 
I will try to answer all your questions. 

1. Assuming that you have the clearance correct and its IV administration, if the curve matches the observed data, especially in the first part of the profile, distribution volume is correct. Distribution volume is the summation of the tissue:plasma partition coefficients (PC) times their respective tissue volumes. Experimental data for PCs can be difficult to interpret. Ensure that steady state was reached prior to sampling or the observed PC will be lower than the simulated as a PC is a steady state value. For a highly lipophilic compound, it can take a very long time to reach steady state. 

2. you don't need Mobi unless you are doing something beyond what is typical in a PBPK model. All the usual organs are already included in PK-Sim. To model reabsorption as an active process, you would add a transporter in kidney from the lumen side into kidney cells. This does not require Mobi.

3. It is an open-source software. Just cite: PK-Sim (Open Systems Pharmacology Suite; open-systems-pharmacology.org). No restrictions. 

Take care!
Andrea

**Comment by sfrechen** [comment]
Hi G.W. and Andrea,

thank you, Andrea, for giving already answers. 
For the 2nd point regarding reabsorption from primary urine, I would like to clarify that this reabsorbtion is not ready to implement in PK-Sim as there is no lumen of tubules or collecting ducts. Urine is just implemented as a collecting compartment. Indeed, currently you need MoBi to manually extend your model. You may refer to this publication for examples: Niederalt, Development of a physiologically based computational kidney model to describe the renal excretion of hydrophilic agents in rats, Front Physiol. 2013 (https://www.ncbi.nlm.nih.gov/pubmed/23355822).

An easier work-around would be to implement GFR filtration as an excretion process and set the GFR fraction to a value < 1.

Hope that helps.

Best
Sebastian

**Comment by gwchoi** [comment]
Andrea and Sebastian,
Really helpful for my research! Thanks a lot.

Best regards.
G.W. Choi
