### ISSUE TITLE
New tutorial published: How to Extend an Open Systems Pharmacology Model to the Special Population of Pregnant Women.

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Forum#156]
Applied Concepts in PBPK Modeling: How to Extend an Open Systems Pharmacology Model to the Special Population of Pregnant Women.

https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues/156

**Comment by jzq90** [comment]
Thanks for the tutorial.
