### ISSUE TITLE
What is "Parameter m for correlation of intestinal permeability (transcellular)"?

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#158]
Dear all,

after doing a sensitivity analaysis in Mobi one parameter (not one of the ususal suspects like Lipophilicity and fu) popped out to have some impact on AUC, Cthrough and Half-Life. It is "Parameter m for correlation of intestinal permeability (transcellular)". It seems to be a simulation paparmeter for the compound. The value is set to 1 (dimensionless). However no description is given and I couldn't find anything in the manual about it. 
Please let me know: What is that for a parameter? Why was it introduced? What does it make?

Thanks and best regrads, Tobias

**Comment by tobiasK2001** [comment]
B.t.w this Paremeter is next to "Parameter b for correlation of intestinal permeability (transcellular)", which is set to 0. ...

**Comment by Yuri05** [comment]
Those parameters are used for calibration of `specific intestinal permeability (transcellular)` from _Caco-2-cell_/_PAMPA_ permeability assays.
In case "no calibration" they are set to the default values 1 and 0. 

Those parameters should be never changed by user (in PK-Sim they are hidden) and should be ignored in sensitivity calculations (changing them will have great impact on the intestinal absorption - but it just doesn't make any sense).
Please remove them from your sensitivity calculations.

**Comment by tobiasK2001** [comment]
OK, thanks! Will do so.

Best, tObias
