### ISSUE TITLE
gene expression

### ISSUE THREAD

**Issue by Mutaz94** [Open-Systems-Pharmacology/Forum#159]
how i can find password for access file, mdb "GENEDB'

**Comment by msevestre** [comment]
@Mutaz94 
Why do you need to access the raw data in the database?
Maybe you simply need to use the query tool implemented in PK-Sim?
My suggestion would be to read the manual on how to use the GeneDB and/or to follow instructions from this [post](https://github.com/Open-Systems-Pharmacology/Forum/issues/8)

**Comment by msevestre** [comment]
@Mutaz94 Closing. Let us know if you need more help
