### ISSUE TITLE
OSP seminar @ ISoP QSP Series, 2017, June 2 (and on YouTube afterwards)

### ISSUE THREAD

**Issue by TheiBa** [Open-Systems-Pharmacology/Forum#16]
http://discuss.go-isop.org/t/isop-qsp-series-session-4-pk-sim-mobi-open-systems-pharmacology-suite/1005

**Comment by vjd** [comment]
I should have known better before posting #15, however, I highly encourage the pk-sim team to develop a tutorial series of how many ever videos it takes and provide these youtube sessions which will greatly benefit the community.

**Comment by krinaj** [comment]
This was a great brief tutorial. PK-Sim is quite intuitive. I will appreciate more tutorials on Mobi later on. :)

Can you please share the project that Jan went over for the ADC?

thanks,
Krina

**Comment by Yuri05** [comment]
Dear Krina,

projects and slides will be available for download soon.

**Comment by TheiBa** [comment]
Video and example files available at #19
