### ISSUE TITLE
Problems with incorporating transporter kinetics into PBPK-model

### ISSUE THREAD

**Issue by ClausPatzer** [Open-Systems-Pharmacology/Forum#160]
Hey

Thank you for providing a great programme. 
I am doing my thesis, working with atorvastatin, which is a substrate for the P-glycoprotein-transporter.
The data I am working with (see link below) expresses the Michaelis-menten kinetics of this transporter in flux-values and not as a reaction velocity values. Is there any way of incorporating these data into my models?

The data I am working with, are derived from the Caco-2 monolayer model which, I know, is mainly for prediction of intestinal permeability, however even incorporation of just that, would be a huge help for my project. 

The manual for PK-sim mentions the option of using data from Caco-2 cell permeability assays for calculation of intestinal permeability, however I have not been able to find this option in my programme.

https://link.springer.com/article/10.1023/A:1007525616017

BR
Claus Patzer

**Comment by krinaj** [comment]
Hello Claus,

It is not very clear from just reading the abstract that whether or not Caco-2 cells were transfected with the transporters of interest and whether or not expression levels for the transporters in assay are known or not.

I suggest that try following the methods used in following papers for calculation of transporter kinetics to use in the model:
https://www.ncbi.nlm.nih.gov/pubmed/15322236
https://www.ncbi.nlm.nih.gov/pubmed/11748225

Good luck,
Krina

**Comment by ClausPatzer** [comment]
Thank you for your response!
