### ISSUE TITLE
Transporter protein - kcat

### ISSUE THREAD

**Issue by kitcheu** [Open-Systems-Pharmacology/Forum#162]
Hello,

I am a bit confused with the kcat value that was calculated using vitro Vmax: 
I understand that when creating a transport protein in "compound" using "in vitro active transport (vesicular assay)", the kcat is calculated based on the "in vitro Vmax/transporter" that I put in. May I know whether this kcat is the "kcat*" that was described in the tutorial PMID 27653238 (ie, catalytic efficiency x overall concentration)? If not, would I need to adjust this value by multiplying the overall concentration? 

In addition, do I need to apply a scalar to this calculation since I am extrapolating from in vitro experiment to in vivo? 

The reason why I am asking was because: 
- In my study, I have the absolute abundance of my transport protein of interest and it is located predominantly in one organ. I entered these two data in the transporter profile that I created in the building block "individual".  
- I found the Km and Vmax from a published in vitro uptake study. Nonetheless, when I input the Vmax (in the unit of pmol/min/pmol), the corresponding kcat calculated was much smaller than I anticipated. The concentration-time profile generated did not predict my observe data well. 
- I then try multiplying this kcat value by my abundance value and the profile improved and actually matched the observed data...I am uncertain whether this is what I am supposed to do and I would really appreciate your help! 

Thank you very much!

**Comment by sfrechen** [comment]
Hi,

your approach sounds reasonable. The kcat value in the compound sheet represents the "turnover" number, i.e. number of molecules transported per time by one transporter molecule.
In your simulation, this kcat value is multiplied by the transporter abundance in each organ where the transporter is expressed (resulting in the theoretical in vivo Vmax value: CLtranp = kcat*[T]_invivo*[S]/(Km+[S]) = Vmax_invivo*[S]/(Km+[S] with [T]_invivo being your transporter abundance in vivo.

Indeed, the mismatch from your simulation compared to your observation might result from a missing in vitro/in vivo scaling factor (currently you assume a 1), as in many cases in vitro results do not directly translate to the in vivo situation. You may identify this using "Parameter Identification" and then select the kcat value to be optimised.
