### ISSUE TITLE
A problem with Mobi simulation in "Simulation Settings" module

### ISSUE THREAD

**Issue by cet6574** [Open-Systems-Pharmacology/Forum#164]
Dear all,

I am now running a Mobi simulation to perform a PD prediction of warfarin alone without PK-Sim.I built the PD model and ran the simulation, but an error with a popup window occurred saying "Error solving ODE at time t=15: Either convergence test failures occurred too many times during one initial step or with /h/=hmin(CV_CONV_FAILURE)".  After following the manual, I located the problem to  "26.4. Output Intervals" and "26.5. ODE Solver Properties" in the "Simulation Settings" module, but the problem reoccurred when I changed the parameters like resolutions, MxStep or Hmax several times.

I would deeply appreciate if someone in this community could provide me some advice fix this problem.

Thank you in advance
Cet

![image](https://user-images.githubusercontent.com/30318820/38850022-16154148-4242-11e8-9817-5674622cc23a.png)

**Comment by PavelBal** [comment]
-Reduce the AbsTol value to, let's say, 1e-15
-Check your equations that everything makes sense...
-Try to reduce the rate constants of your PD - it seems like processes happen "too fast"
-Can you simulate t<15 min? If yes, try to find out what time interval you actually can simulate and look at the results. This could help to understand what the problem is.
-Check your equations again (no div. by 0?)

**Comment by Yuri05** [comment]
Changing MxStep or Hmax will unlikely solve the problem. 
Please follow the advices given by @PavelBal .

When trying this:
>-Can you simulate t<15 min? If yes, try to find out what time interval you actually can simulate and look at the results. This could help to understand what the problem is.

set simulation end time = 15 [min] and resolution 20000 [pts/h]
<img width="447" alt="aufnahme28" src="https://user-images.githubusercontent.com/25061876/38855002-cb83fed8-4211-11e8-914a-43a1972384b0.png">

If you obtain the same error as before with the output time` 1/20000*60=0.003[min]`: it's highly likely that already initial conditions of your system are invalid (e.g. division by zero in transport/reaction kinetics etc.). 
If you obtain the error for some output time bigger than 0.003[min]: set simulation end time to the error time minus small delta and check simulation results.

**Comment by cet6574** [comment]
@PavelBal @Yuri05 
Thank you very much for your responses.
After following your advice, the problem seems to come from my initial model and I will check that again.

**Comment by msevestre** [comment]
@cet6574 Please let us know if you need more help.
