### ISSUE TITLE
Install issue version 7.2.1

### ISSUE THREAD

**Issue by ncpunt** [Open-Systems-Pharmacology/Forum#165]
I tried to install PK-Sim 7.2.1 on my windows 10 machine but get the following error.

0x80070666: Another version of this product is already installed. Installation ....
[Open_Systems_Pharmacology_Suite_7.2.1_20180418083447.log](https://github.com/Open-Systems-Pharmacology/Forum/files/1922716/Open_Systems_Pharmacology_Suite_7.2.1_20180418083447.log)

That is very odd because I never installed PK-Sim before. 
Please find the log attached.

Best,
Nieko Punt,
Medimatics

**Comment by PavelBal** [comment]
Probably this issue: https://github.com/Open-Systems-Pharmacology/Forum/issues/90
Try to install Visual C++ redist manually.
