### ISSUE TITLE
R Toolbox for the 64bit R

### ISSUE THREAD

**Issue by kfc3** [Open-Systems-Pharmacology/Forum#166]
Hi,

When will the R Toolbox for the 64 bit R be available? I am getting an error message when installing the R Toolbox in R. I have a 64 bit system.

Thanks!

**Comment by msevestre** [comment]
The R tool box works for a 64 bit system. However you need to use the 32bit version of R. Please check the installation instructions for details and explain what error you are getting if this does not work

**Comment by StephanSchaller** [comment]
If you are using RStudio (recommended) then just switch to 32bit via "Tools" --> "Global Options".
In "General" click "change" right at the top and select the 32bit Version. --> Restart RStudio
![image](https://user-images.githubusercontent.com/25477643/39100224-1f34ac16-4687-11e8-86a9-0d55d9d40d8b.png)

**Comment by msevestre** [comment]
@kfc3 If the problem still persists, please open an issue in the [R ToolBox issue tracker](https://github.com/Open-Systems-Pharmacology/R-Toolbox/issues)
