### ISSUE TITLE
CFR 21 part 11 compliance

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#167]
Dear OSP users,

We are getting ready with the validation of the Open System Pharmacology Suite. Do you know if the software is compliant with the CFR 21 part 11 regulation of the FDA?

Thanks a lot in advance,

Donato

**Comment by StephanSchaller** [comment]
FYI: Latest issue of [part 11](https://www.fda.gov/downloads/RegulatoryInformation/Guidances/ucm125125.pdf)

**Comment by msevestre** [comment]
@teutonicod Why do you think that part 11 is relevant for OSPSuite? As far as I can tell (and this is my personal opinion here, I would strongly advise you to check with your legal team), it deals with electronic records and electronic signatures, neither of which is currently used in PKSim.
