### ISSUE TITLE
Active user groups and their area of expertise

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#168]
We were asked by a user if we knew any active OSPS user groups in the UK or Europe. What do you think of a Wiki entry, where we list (only user who want to be listed) all known groups in academia or individuals where users can enter their area of expertise and leave contact details?

**Comment by msevestre** [comment]
Yes it needs to be done. We should work on it at ACOP :)

**Comment by StephanSchaller** [comment]
I missed your reply before ACoP… should we still discuss?
