### ISSUE TITLE
No calculation methods in parameter identification

### ISSUE THREAD

**Issue by nmidde** [Open-Systems-Pharmacology/Forum#170]
I updated PK-Sim to 7.2.2 Build 3 but I couldn't Calculation methods under Configuration tab in Parameter Identification (Please see attached figure). Please let me know if this is an issue or my error.
Thanks for your help!
Narasimha
![image](https://user-images.githubusercontent.com/29755212/39498282-3ebb2ed0-4d75-11e8-9575-5e17fc5f661e.png)

**Comment by msevestre** [comment]
@nmidde
It looks to me as if there is not enough screen space to display the info. Could you try collapsing the section 'General' by clicking on the arrow on the left and see if the calculation methods are visible?

**Comment by nmidde** [comment]
Yes, that was it. Thanks a lot!
