### ISSUE TITLE
Examples for impact of disease effect (e.g. hepatic impairment)

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#172]
Dear all,

does anybody has ready examples how to model disease effect e.g hepatic impairment, which can be used as tutorial?

Thanks and best regards,

Tobias

**Comment by fredsevmartins** [comment]
Hi @tobiasK2001 ,
I built RI to 5 drugs and the publication is coming soon.  
In the meantime (if your needs are urgent) you can incorporate a new population with disease population (what I did) in Pksim. In this way if you need disease progression you need add one new population for stage or export it to MOBI or Simbiology. 
Certara has good publication with population meta analysis (www.certara.com)

**Comment by tobiasK2001** [comment]
Hi Fred,
thanks for your comment. I am looking forward to read your publication. Please let me know when it is available. I noticed that on the coming PAGE there is also an interesting Poster to this topic.
https://www.page-meeting.org/default.asp?abstract=9042
Probably the group will also create a publication from that and hopefully provide some material for the OSP here ;-).

Best, Tobias
