### ISSUE TITLE
PK-Sim vs MoBi: Passive diffusion clearance and pediatric trial simulation

### ISSUE THREAD

**Issue by kitcheu** [Open-Systems-Pharmacology/Forum#175]
Hi,

I am exploring what PK-Sim can and cannot do and when I would need MoBi. Specifically, I have two questions: 

- Passive diffusion clearance (CLpd) in kidney: I realized from an in vitro uptake study that a small amount of my drug can enter the cell via passive diffusion. Should I use "passive transports" in Mobi to incorporate this into the simulation? Is there any way where I can use PK-Sim to take this into account? 

- Pediatric simulation: In this paper by Zisowsky et al, Pediatr Drugs (2017) 19:121-130 (PMID 28078552), I read, in the methods section, that "simulations for different age groups were performed using MoBi". May I know whether it is necessary to use MoBi to simulate pediatric trials? Did the authors use MoBi because they need to consider "age-dependent protein binding"? 

Thanks in advance for your help!

**Comment by StephanSchaller** [comment]
Hi,

1. depending on the size of the molecule (and its lipophilicity) there may already be passive diffusion happening. To check, plot the intracellular concentrations once you have created your simulation:
![image](https://user-images.githubusercontent.com/25477643/39921453-377ea78e-551b-11e8-869d-67a5150339a6.png)

2. No, you do not have to use MoBi. PK-Sim is the tool to do it. Yes, "age-dependent protein binding" is most likely the reason they had to do it in MoBi to define a user-defined function for fraction unbound.

Hope this helps,
Stephan

**Comment by msevestre** [comment]
@kitcheu Closing. Let us know if you need more help
