### ISSUE TITLE
Make the user manual a Wiki?!

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#178]
Couldn't we put the OSPS user manual up on GitHub to make it an editable Wiki so that people can improve on the descriptions there?

If it is a living document it could also be used to more easily describe workflows e.g. like IVIVE (#101)...

@All : What do you think?

**Comment by msevestre** [comment]
The user manual will actually become a full blown website that will support search, indexing etc... 
Our goal is indeed to implement a workflow that will allow the community to make suggestions and improvements to the documentation.

The source will be available in the https://github.com/Open-Systems-Pharmacology/docs repo.

**Comment by tobiasK2001** [comment]
Great Idea!
