### ISSUE TITLE
Update Maximum Time for Simulations in PK-Sim

### ISSUE THREAD

**Issue by krinaj** [Open-Systems-Pharmacology/Forum#18]
Hello,

I am trying to lay simulations over observed data for a PK profile in PK-Sim. I have data upto time 120 hrs even though last few data points have very low concentrations. The PK-Sim is only performing sims upto 25 hrs (I am assuming it is stopping once concentrations reach certain limit). I tried updating axis settings and added max value to be 120. But, sims are still stopping at 25 hrs.

 Is there a way to manually update max sims time even though low concentrations?

Many thanks for making PK-Sim and Mobi open source. :)
Krina

**Comment by msevestre** [comment]
@krinaj 
Yes. You can increase the simulation time in the settings of a simulation
![image](https://cloud.githubusercontent.com/assets/1041237/26833785/6bc3bdde-4aa1-11e7-834e-5eb0c57642aa.png)

Open the simulation, go in the highlighted node `settings` and enter the desired end time

**Comment by krinaj** [comment]
Many thanks
