### ISSUE TITLE
Fasting Condition in Events

### ISSUE THREAD

**Issue by dineshbcp** [Open-Systems-Pharmacology/Forum#182]
Dear Sir, 
For Simulation of Fasting Condition, Which events to be selected or we can modify in existing Events.
Thanks and Regards,
Dinesh Bramhane

**Comment by msevestre** [comment]
@dineshbcp Fasting condition is the default state of your individual. That means that you do not need to define anything to simulate fasting condition. Hope that helps

**Comment by msevestre** [comment]
@dineshbcp Closing. Please reopen if you have more questions
