### ISSUE TITLE
Program Won't Install

### ISSUE THREAD

**Issue by lwollenberg** [Open-Systems-Pharmacology/Forum#183]
I received a new laptop from my employer and I have tried to install this package and an error message is thrown stating "Another version of this product is already installed", however the laptop is brand new and I do not see any instances of the program on the computer. Thoughts?

**Comment by Yuri05** [comment]
Might be the same issue as in #90 
Please try a workaround as described [here](https://github.com/Open-Systems-Pharmacology/Forum/issues/90#issuecomment-341939246)
This issue will be fixed in the upcoming 7.3 release

**Comment by msevestre** [comment]
@lwollenberg Agreed with @Yuri05 
This is certainly the same issue and following the proposed workaround should solve the issue.

**Comment by lwollenberg** [comment]
Thanks!

**Comment by msevestre** [comment]
@lwollenberg Assuming the workaround worked. Closing. Please reopen if you still have issues
