### ISSUE TITLE
Facing error

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/Forum#184]
Hi,

I am getting this error when I try to open one of my PKSim files.

<img width="1280" alt="pksimerror" src="https://user-images.githubusercontent.com/35151285/40337494-f6b991de-5d3d-11e8-8a88-e1c7c2a56dcb.png">

It started to happen when I restarted my computer while the program was trying to save.
your help is appreciated!

**Comment by msevestre** [comment]
This file is most likely corrupted and there is nothing we can do here.

Restarting the computer **WHILE** the file is saving is something I would strongly advise you not to do.

**Comment by farzanehmaleki** [comment]
The program could not save for half an hour and there was nothing I could do. Is there any way to find out if it can be restored? This is one of my main files :(

**Comment by msevestre** [comment]
Saving for 30 min is unusual no matter what.
The file is a SQLite database file. That means that there may be tools available to recover the file.
My suggestion would be to search for the message that PKSim sent "database image is malformed" along with SQLite and see if there are some ways to recover the file.

Also let say you file was named **project.pksim5**. Is there a file called something like **project.pksim.journal**? At the same location? This could be helpful to recover the information

I can give it a try tomorrow if you can send me both files at michael@design2code.ca

**Comment by msevestre** [comment]
Closing as per discussion
