### ISSUE TITLE
PKSim Error

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/Forum#185]
I am trying to do parameter optimization using PK-Sim and recently I get this error. Any thought?

<img width="644" alt="pksimerror" src="https://user-images.githubusercontent.com/35151285/40437614-ca58fb92-5e83-11e8-8669-b67d172a095d.png">

Thank you,
Farzan

**Comment by msevestre** [comment]
@farzanehmaleki This looks like a bug in the application.
Can you please open an issue in the [PK-Sim Issue tracker](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues) and if possible attach a project so that we can reproduce the issue. 

Thanks in advance,
