### ISSUE TITLE
Search blood expression levels in database

### ISSUE THREAD

**Issue by krinaj** [Open-Systems-Pharmacology/Forum#189]
Hello,

I am hoping to find brain and blood expression levels for some cytokines (IL-6, IL-8, TGF-B, etc) in newborn human. I have blood serum levels from a paper; however, of course, brain levels are not available in literature. I am wondering if I can find relative brain and blood levels from microarray or other experiments, I can approximate brain levels.

In PK-Sim, I created a 0.02 day human and am searching in expression database. I see microarray results for various tissues, but not for blood or plasma compartment. Any suggestions on how to get microarray  expression results in blood and brain from PK-Sim database?

What are the relative expression values relative to?

thanks,
Krina

**Comment by krinaj** [comment]
Nevermind, found it. Plasma compartment shows up in if I query in protein binding partners.

**Comment by sfrechen** [comment]
Please be aware that the expression database works independently of your created individual. Thus, your age is not considered, only in case an ontogeny/variability function is provided.
