### ISSUE TITLE
ISoP webinar material

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/Forum#19]
The recent ISoP webinar on the Open Systems Pharmacology platform is now available on [Youtube](https://www.youtube.com/watch?v=E1wqbIN4MHM). The tutorial files and supporting information can be accessed here on the [github platform](https://github.com/Open-Systems-Pharmacology/ISOP-webinar---PK-Sim-MoBi-introduction)

Please check out the Hands-on material and feel free to comment in the corresponding repository.

**Comment by john-harrold** [comment]
When I follow the Youtube link, it says the video was taken down. Is it available elsewhere?

**Comment by veilance** [comment]
@TheiBa @JanSchlender sorry to bother, was wondering if the youtube link could be uploaded to model a monoclonal antibody or equivalent resources? thanks!

**Comment by JanSchlender** [comment]
The YouTube channel has been discontinued due to administrative issues. Slides and Files are still available under the respective link

**Comment by StephanSchaller** [comment]
> @TheiBa @JanSchlender sorry to bother, was wondering if the youtube link could be uploaded to model a monoclonal antibody or equivalent resources? thanks!

In case you are looking for training resources, please check out our online training portal for OSP (PK-Sim and MoBi):
For Academia (**free**): https://learn-esqlabs.talentlms.com/
For Industry: https://esqlabs.shop/collections/online-courses
