### ISSUE TITLE
Portable Open System Pharmacology version 

### ISSUE THREAD

**Issue by jgonlop3** [Open-Systems-Pharmacology/Forum#191]
Hello,
First of all, I would like to thank the OSP team for the speed with which a few months ago they considered my suggestion to make a portable version.

However, I have been trying to work with this portable version of OSP for some time and I do not get it. I have tried on 5 different computers and it does not start. When it opens, it displays an error message related to OSPSuite.Funcparser.dll and then quits. I would like to know if it is planned to improve the portable version. It would be very useful to have a version that does not need to be installed.

![image](https://user-images.githubusercontent.com/4466601/41227371-c754c3e0-6d74-11e8-889c-26396e1d6ee1.png)

**Comment by Yuri05** [comment]
Portable versions have some prerequisites (standard libraries). If those are not installed on the target system, you have to install them manually before using a portable version.

For OSP Suite 7.2.x:
* [Microsoft .NET Framework 4.5.2](http://go.microsoft.com/fwlink/?LinkId=397708)
* [Microsoft Visual C++ 2015 redistributable (x86)](http://go.microsoft.com/fwlink/?LinkID=615459&clcid=0x409)
* [Miktex](https://systems-biology.com/fileadmin/sb_ftp/OSP_Updates/MikTex.2.9.3.msi) (optional, required only for generation of pdf reports)

**Comment by msevestre** [comment]
@jgonlop3 I should add that these dependencies (.NET framework and C++ redistributable) are changing very rarely so that this extra required instalaltion steps only need to be done on rare occacions. For example, dependencies on .NET framework 4.5.2 have not changed for almost 3 years.

**Comment by jgonlop3** [comment]
Don´t close this issue yet. I´m testing some solutions to this problem. I´ll write you as soon as I can. Thanks for the previous comments.

**Comment by msevestre** [comment]
@jgonlop3 

FYI: The new version that was released yesterday depends on a newer version of the .NET Framework (4.6.2) as well as newer C++ redistributable.

**Comment by Yuri05** [comment]
>newer C++ redistributable.

VC2017 x86

**Comment by jgonlop3** [comment]
Sorry, I can´t do anything with this problem. Without administrator rights it´s impossible to bypass the .NET Framework absence. Thanks for the comments.

**Comment by msevestre** [comment]
@jgonlop3 Thanks for trying. I just installed a new Win10 machine with office and .NET frameword, as well as VC2017 were already preinstalled. So I am fairly confident that this will be a non issue in most cases

**Comment by jgonlop3** [comment]
Yes, I know these situation with Windows 10. But in my hospital Windows 7 Proffesional is already installed. Thanks @msevestre

**Comment by jgonlop3** [comment]
Hi, I am using portable version 7.2. I would like to know if any portable update is planned. Version 8 is not portable and I wish I could use it. Thank you very much.

**Comment by msevestre** [comment]
Did you check the release page?

https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/tag/v8.0

Also please open a new thread if possible in the future

**Comment by jgonlop3** [comment]
Thank you very much! I had not seen it! I suggest you put it in the download area (https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/v8.0). I searched for it and I wouldn't have found it without your help.

**Comment by msevestre** [comment]
can you please create an issue with your suggestion here
https://github.com/Open-Systems-Pharmacology/Suite/issues

Thanks :)
