### ISSUE TITLE
P-gp and specific binding query

### ISSUE THREAD

**Issue by meensrinivasan** [Open-Systems-Pharmacology/Forum#192]
Hello,

I'm trying to replicate a prior PBPK model of Digoxin. 
The publication mentions ATP1A2 Koff and Kd values and P-gp Km and Kcat.

In the compounds- distribution- specific binding- protein binding partners tab, I entered the values for ATP1A2 Koff and Kd

In the transport and excretion- transport proteins tab, I selected "specific active transport" and entered values for p-gp Km and Kcat. 
How do we decide whether to use 
-Intrinsic active transport - MM
- Specific active transport - MM
- In-vitro active transport - MM?

Then, in the individual (expression) tab, I added transport protein for p-gp and expressed it 100% in the kidney. The transporter showed up as "Efflux" by default and then I changed it to P-gp type.
Also added ATP1A2 as the protein binding partner with reference conc and expressed it 100% in brain. 

Added the administration protocol and ran a simulation.

In the create simulation tab, there was a warning near specific binding. But its showing up as transporter in individual. Anything that I'm missing here?

![doubt 1](https://user-images.githubusercontent.com/37451822/41248096-8a580b4a-6d75-11e8-923a-033b6c4b5efc.jpg)

Also the reaction diagram doesn't mention P-gp. 

![doubt 2](https://user-images.githubusercontent.com/37451822/41248207-ea29434a-6d75-11e8-8745-f61cc2877e19.jpg)

Also, how can one increase the duration of simulation from the default 24 hrs to say, 100 hrs??

Have I made a mistake somewhere while entering the values for P-gp?

Any help will be greatly appreciated!!
Thank you!

**Comment by PavelBal** [comment]
Hi,

the "Specific binding" window just lists all the proteins in your individual that can act as binding partners. As you did not define any binding to P-gp (which is correct), no **binding** process is assigned to it. P-gp is correctly linked in the "Transport"-section.

Active transports (which P-gp mediated transport is) are not listed in the "Reaction Diagram", so the simulation seems to be set up correctly.

To change the simulation time, open your simulation by double-clicking on it and select "Parameters"-tab -> "Settings": 
![image](https://user-images.githubusercontent.com/25903040/41277764-7070448c-6e28-11e8-83dd-05c4ddfeee68.png)

**Comment by ms-12345** [comment]
Hi Dr Balazki @PavelBal ,

Thank you for your help in this regard!
I had few more doubts. 

1.) When we add Specific protein binding partners and transport proteins in the model by specifying Koff, KD, Km and Kcat values in the compound tab, we are supposed to express this in the individual tab (using the database developed by Bayer). 
I found the reference concentration in the publication (that I entered) and  the relative expression is shown in the expression tab. 
My first question is - transporter concentration = the relative fraction * the reference concentration (in organ with highest expression). Is this correct?

Secondly, where can I see the formula representing the transport protein (p-gp) mediated efflux that PKSIM is using?

Thirdly, if the compound undergoes GFR+TS (mediated by P-gp) in the renal clearances tab (where I can add GFR with fraction 1), do I need to add TS (Michealis Menten) as well? or will the P-gp expression in kidney naturally account for the clearance through P-gp?

Also, pls can you provide some resources regarding model qualification and sensitivity analysis using PK-SIM?

Thank you very much!

**Comment by ms-12345** [comment]
Hello @PavelBal please could you help answer the above query? :)

**Comment by PavelBal** [comment]
> My first question is - transporter concentration = the relative fraction * the reference concentration (in organ with highest expression). Is this correct?

Yes.

> Secondly, where can I see the formula representing the transport protein (p-gp) mediated efflux that PKSIM is using?

You can do it in MoBi.. Right-click on your model in PK-Sim and select "Send to MoBi". In MoBi, open the Molecules-Building Block, where you will find all molecules and their transport processes. You will find the equation in the "Kinetic"-Tab (see screenshot).

![image](https://user-images.githubusercontent.com/25903040/42931456-0ae8f5c0-8b40-11e8-90a9-a724818fddb1.png)

> Thirdly, if the compound undergoes GFR+TS (mediated by P-gp) in the renal clearances tab (where I can add GFR with fraction 1), do I need to add TS (Michealis Menten) as well? or will the P-gp expression in kidney naturally account for the clearance through P-gp?

P-gp will mechanistically account for TS. 

Hope it helps!

**Comment by ms-12345** [comment]
Thank you very much!!
