### ISSUE TITLE
Program installation

### ISSUE THREAD

**Issue by faisalhhu** [Open-Systems-Pharmacology/Forum#194]
Dear sir

I want to install pksim for pbpk modelling. Kindly guide me about that.

**Comment by msevestre** [comment]
@faisalhhu Download and install the setup file OSPSuite-Full.7.3.0 for the suite that contains PK-Sim and MoBi.
Setup can be found at http://setup.open-systems-pharmacology.org

**Comment by faisalhhu** [comment]
Thank you. I thought the academic license shall require documentation etc.

**Comment by msevestre** [comment]
@faisalhhu The tool is free and open source. Please check out the [license] (https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/LICENSE)
