### ISSUE TITLE
Incompleted absorbtion

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/Forum#195]
Hi,
I am using PK-Sim built-in template for Rifampin. I get this error message for oral dose. Any thought?
I have ABCB1 (Efflux) OATP1B1 (Influx) as transporters

<img width="1019" alt="rif2" src="https://user-images.githubusercontent.com/35151285/41503999-d9cf9cb8-71af-11e8-849c-46b9e4d4c2a7.png">

Thank you,
Farzan

**Comment by JanSchlender** [comment]
Which error message do you mean? Are you looking for an explanation for the "warning"? Have you plotted the the fraction absorbed? Due to the EHC, the absorption may still be incomplete. What is the predefined simulation time?

**Comment by msevestre** [comment]
@JanSchlender Fraction absorbed of 3.10... Can you explain how we can get to that?

**Comment by farzanehmaleki** [comment]
My model has two issues, fraction absorbed (Fa) and half life (HL). I got Fa~3 with modified PK-Sim template of Rifampin (same processes, different parameters). With the original template however, Fa~1.05 with the same warning mentioned above. Playing with the simulation time did not change the Fa. 
Reducing the simulation time to 12 hours improves the HL from ~10 to 4-5 hours which is what has been reported in the literature. But I have 24 hours oral data of 600 mg and cannot reduce the simulation time. For that simulation the HL remains 10 hours. The prediction looks good even with such high HL.

![image](https://user-images.githubusercontent.com/35151285/41750410-b572222c-7589-11e8-846f-a0e164a7023b.png)

 How can I take care of EHC?

Best,
Farzan

**Comment by sfrechen** [comment]
Hi Farzan,

the magnitude of EHC in the RIF template was informed from fraction excreted to bile data (https://rd.springer.com/article/10.1007/BF00561755). Fa of 3 suggests overprediction of EHC.

Regarding half-life: PK-Sim calculates half-life rom your terminal part of your curve. If you simulate for quite a long time (longer than observed data exist), additional distrivution/clearance phases may become obvious (at this point, I do not want to judge if they are true or just a PBPK model artefact) with very long half-life. Obviously, those values should not be compared to reported half lives  (as they are derive from observed PK curves). 

Of note, I do not see a good reason to compare half-lives in case full concentration time profiles are available. For derived PK parameters, I would suggest to compare tmax, Cmax and AUC (e.g. AUCtend).

Best
Sebastian

**Comment by msevestre** [comment]
@farzanehmaleki Let us know if you have more question. Closing for now
