### ISSUE TITLE
question about adding multiple metabolites through the same metabolizing enzyme

### ISSUE THREAD

**Issue by PKSimUser** [Open-Systems-Pharmacology/Forum#196]
I have a question about the best way to incorporate kinetic data for multiple metabolites through the same metabolizing enzyme. I have incorporated Michaelis-Menten kinetic parameters for two different metabolites mediated through CYP3A4. However, during configuration, I can only select one enzymatic process per enzyme in an individual. I tried to work around this by adding CYP3A4 twice in the individual, but I am concerned that this will create issues when I try to model CYP3A4 mediated drug-drug interactions since there is now twice as much CYP3A4. Does anyone have any ideas or experience with this? Thank you.

**Comment by msevestre** [comment]
@PKSimUser Just so that I get it right.

You are saying that the metabolization of your DRUG by CYP3A4 produces two different metabolites? Is this correct?

**Comment by PKSimUser** [comment]
Yes

**Comment by JanSchlender** [comment]
This is unfortunate but if you stay in PKSim, you need to create the same enzyme again in order to match another reaction kinetic to this process (see example). 
![grafik](https://user-images.githubusercontent.com/26056951/41714870-faecde9c-7551-11e8-9e2c-6a6723f9086c.png)

**Comment by msevestre** [comment]
> I am concerned that this will create issues when I try to model CYP3A4 mediated drug-drug interactions since there is now twice as much CYP3A4

@JanSchlender Can you address this question?

**Comment by sfrechen** [comment]
I hereby confirm that the current work-around would be to have two CYP3A4 enzymes. As long as you do not model the explicit binding/release of the substrates/products to CYP3A4 (and that is the common case), you have nothing to worry about. You can also use this model for CYP3A4-mediated DDIs; however, please note that you would also need to double the interaction parameters/processes in your perpetrator model (e.g. add two inhibition constants and add both in your simulation), e.g.
![unbenannt](https://user-images.githubusercontent.com/26569320/41730080-67e4f5c6-756a-11e8-8f23-415c2b44a8e8.png)


I would strongly support the idea to update PK-Sim facilitating the use of multiple metabolites arising from a single enzyme.

**Comment by msevestre** [comment]
A feature request was created in PK-Sim. We can close this issue for now
