### ISSUE TITLE
Run OSP on Linux Servers

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#197]
Dear all,

we would like to run the OSP on Linux Cluster. Is that possible? Is it also possible to run the R-toolbox there?

Please suggest a way how to do this?

Thanks, Tobias

**Comment by msevestre** [comment]
@tobiasK2001 Let me know if you have any more questions. Closing for now as I did not hear more from you. Cheers

**Comment by IngridMichon** [comment]
Is it possible to have a Linux release of the core engine?

**Comment by msevestre** [comment]
@IngridMichon Yes we are actually working on that now. It will even be possible to load full blown pkml from R on Windows and Linux. This is our main focus at the moment

**Comment by Yuri05** [comment]
@IngridMichon 

If you extract attached [**MoBi Toolbox for Matlab 8.0.zip**](https://github.com/Open-Systems-Pharmacology/Forum/files/3436446/MoBi.Toolbox.for.Matlab.8.0.zip) and after that extract the contents of [**OSP73CalcEngineLinux.zip**](https://github.com/Open-Systems-Pharmacology/Forum/files/3436425/OSP73CalcEngineLinux.zip) into the **lib**-subfolder (should look like below), then you should be able to run Matlab-Toolbox under Linux.

![grafik](https://user-images.githubusercontent.com/25061876/61964134-7bb31080-afcd-11e9-9fd7-4a703c70ffcf.png)

**Comment by IngridMichon** [comment]
Thanks! Will have a look at this
