### ISSUE TITLE
Kinetic order description

### ISSUE THREAD

**Issue by HiroQSP** [Open-Systems-Pharmacology/Forum#199]
Hello,
I am now building QSP model using MoBi.
How is dN/dt described on a Reaction building block for the followed equation?
dX/dt = k*(X^f)
where k is rate constant, X is amount of drug or endogenous molecule,
and f is one or more kinetic orders described as  #power.
Thanks.
Hiro

**Comment by msevestre** [comment]
Hi @HiroQSP 

Please look at the chapter 23.5. Enter a Reaction in the MoBi First step section of the documentation where all steps are described in details.

I have also created a small example project using the kinetic described above. 
![image](https://user-images.githubusercontent.com/1041237/43033734-dec8a716-8c9c-11e8-9eac-43fcacc129de.png)

Let me know if you have any questions,

Cheers,
Michael
[199-simple-kinetic.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/2215996/199-simple-kinetic.zip)
