### ISSUE TITLE
Characterization of a Monoclonal Antibody in PKSim

### ISSUE THREAD

**Issue by drfreedman** [Open-Systems-Pharmacology/Forum#2]
How should I enter the characteristics of a monoclonal antibody into PKSim v. 7.0?  

The Compound screen requires information on log P, pKa and solubility - what is appropriate to enter for a mAb?

How do I further characterize the expression level of its target in tissues?

Regards,

Immanuel Freedman, Ph.D SMIEEE
AAPS Pharmaco-Imaging Focus Group Past Chair

**Comment by Christoph27** [comment]
PK-Sim v. 7.0 has a common, general input window to define compound properties for both small molecules and biologics.
For a biologic, de-select the checkbox “Is small molecule” in the compound window. Relevant basic physicochemical properties for an antibody/biologic are the molecular weight and the fraction unbound (usually 1). Further relevant parameters for the biologics model can be found at the “Advanced Parameters” tab. Especially the  “Kd(FcRn) in endosomal space” is usually changed (definitely needed for antibodies, the default is just a high value indicating no binding).  Please see section 15.1.4 of the manual for further details.
While log P, pKa and solubility influence the oral absorption and distribution of small molecules, they do not influence a model for biologics (in a standard case). If the checkbox “Is small molecule”  is de-selected, the permeability for passive diffusion into the intracellular space of the organs and into blood cells and as well as the intestinal permeability are set to zero, i.e. there will be no distribution into cells or oral absorption (if no active transport is added by the user). Thus the values of log P, pKa and solubility will have no effect. I usually just set for antibodies logP to -5 (arbitrary value consistent with the action of the checkbox), define the drug as neutral, thus specifying no pKa value and set the solubility to 99999 mg/ml (indicating it is an arbitrary value). 
Regarding target binding:  At the compound it is only defined that the compounds binds to a certain target together with the respective binging parameters (at the ADME tab of the compound definition window).  The target expression is defined while creating an individual/organism. The relative expression in different organs can be specified using the expression database of PK-Sim or manually. The absolute target level is specified by the “Reference concentration”. 
Please see Chapter 14 of the Manual for the concepts and a detailed description where to enter it (the target would be a “protein binding partner”). The concept is also described in M. Meyer et al. "Using expression data for quantification of active processes in physiologically-based pharmacokinetic modeling." Drug Metabolism and Disposition (2012): dmd-111.

**Comment by drfreedman** [comment]
Dear Sir,

Please consider providing a .pksim project for an exemplary monoclonal antibody with appropriate parameters.

Regards,

Immanuel Freedman, PhD SMIEEE
AAPS Pharmaco-Imaging Focus Group Past Chair

**Comment by JanSchlender** [comment]
Dear Sir,

I added a tutorial example on 'how to model antibody drug conjugates', which might be of interest to you. Please have a look at the recent announcement.

#19
