### ISSUE TITLE
Adding additional compartments

### ISSUE THREAD

**Issue by miluez** [Open-Systems-Pharmacology/Forum#20]
Hello,

I have reviewed the PK-Sim manual and have two questions:

1) I am interested in modeling the accumulation of drugs in specific blood components, not just venous vs arterial blood. Is this possible in PK-Sim, or is it possible to add an extra, hypothetical compartment to my own specifications?

2) I have found the ontogeny functions for the CYP enzymes in the expression tabs when creating a population. The manual states that there are ontogeny functions in PK-Sim for albumin and alpha-glycoprotein, however I cannot seem to find the options within PK-Sim to confirm that my pediatric population (created from the included white American NHANES data) has the appropriate levels. How can I change this value manually, or how can I incorporate an ontogeny function for these serum proteins?

Thank you!

M.

**Comment by Yuri05** [comment]
>Is this possible in PK-Sim, or is it possible to add an extra, hypothetical compartment to my own specifications?

In PK-Sim you can simulate and visualize time concentration profiles not only in venous/arterial blood pools, but also in plasma/blood cells of different organs (you have to select them in "Define settings and Run..." dialog.

<img src="https://user-images.githubusercontent.com/25061876/26918480-822e33aa-4c32-11e7-81ce-fa035c290ab8.jpg" alt="Define settings" width="200"/><img src="https://user-images.githubusercontent.com/25061876/26918523-b1aa7526-4c32-11e7-86d2-a8e9c23a47f4.jpg" alt="Define settings" width="450"/>
<img src="https://user-images.githubusercontent.com/25061876/26918485-88f3be76-4c32-11e7-89d5-c812e143efbb.jpg" alt="Simulation output" width="500"/>

If this is not what you want and you need additional compartments, which are not part of a "standard" PK-Sim model, you can export PK-Sim simulation to MoBi. 
In MoBi you can e.g add additional model compartments, define new simulation outputs (e.g. total amount of drug in the whole blood pool ) etc.

>I have found the ontogeny functions for the CYP enzymes in the expression tabs when creating a population. The manual states that there are ontogeny functions in PK-Sim for albumin and alpha-glycoprotein, however I cannot seem to find the options within PK-Sim to confirm that my pediatric population (created from the included white American NHANES data) has the appropriate levels. How can I change this value manually, or how can I incorporate an ontogeny function for these serum proteins?

You have to define the major binding protein of a compound in the corresponding  compound building block of PK-Sim. If you select albumin or alpha-glycoprotein, the corresponding ontogeny will be automatically used in a population simulation
![clipboard04](https://user-images.githubusercontent.com/25061876/26919239-4d8f5fa4-4c35-11e7-8ccf-6a5fbaf2d81b.jpg)

**Comment by miluez** [comment]
Hi Yuri,

Thank you, this is very helpful. Regarding the albumin and alpha-glycoprotein, I have selected the appropriate protein for my compound of interest and I understand the ontogeny of these proteins are in the simulations.

 I would like to know whether I can view them or change them within PK-Sim (e.g., to account for changes due to disease state).

Thank you!

M.

**Comment by Yuri05** [comment]
It's an open issue: [Possibility to scale Albumin levels...](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/6)

A workaround for this: you can scale the albumin/alpha-glycoprotein level via **_Plasma Protein Scale Factor_** parameter of an individual
<img width="488" alt="aufnahme1" src="https://user-images.githubusercontent.com/25061876/26940574-77b99a60-4c7b-11e7-8a36-553f0da2c77b.png">

**Comment by TheiBa** [comment]
For the work-around I recommend checking the formulas in MoBi to see the 
implementation and maybe reading e.g. this also helps: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2751289/

**Comment by msevestre** [comment]
You can use the plasma protein scale factor as mentioned by @Yuri05 
Attach is a screenshot with also the tooltip explaining what the parameter does. 

![image](https://user-images.githubusercontent.com/1041237/26941946-51a039ce-4c4e-11e7-856f-ae569a39907b.png)

**Comment by Aedginto** [comment]
In addition to the above ideas....
To add a very specific ontogeny than is different from default for protein binding, you can export your population to a csv or excel file. There you will find the parameter values that are used for each individual in your population. You will find here the protein child/adult ratios. If you want to change them (based on a covariate such as age and accounting for disease) you can add an equation to do so. Remember to save as a .csv and reimport into PK-Sim.
Take care,
Andrea
