### ISSUE TITLE
PK-Sim training in UK

### ISSUE THREAD

**Issue by Hector5101** [Open-Systems-Pharmacology/Forum#202]
Hi there, are there any forthcoming PK Sim training events in the UK (or elsewhere in Europe)? Cheers, Hec

**Comment by tobiasK2001** [comment]
Dear Hector,
actually we are planning a 2 days Workshop in Berlin to beheld in November this year
Planned Titel: “Introduction to PBPK modelling using the free and open source Software PK-sim and MoBi”.
Beside an introduction for beginners a focus will be laid on DDI prediction.

Does that sound interesting to you?
please provide me you Email (see my contact details below) than I will set you on the notification list

Cheers, Tobias

Tobias Kanacher, PhD
Agriculture, Food and Life
Consultant Modelling & Simulation
Life Sciences – Modelling & Simulation
SGS Exprimo NV
E-mail: tobias.kanacher@sgs.com

**Comment by Saeed1-byte** [comment]
Hi there, are there any forthcoming PK Sim training events in Asia (or  Europe)? Thanks, Saaed

**Comment by StephanSchaller** [comment]
Hi Saeed, likely again at the PAGE meeting in Ljubljana in June next year, but nothing is currently planned before then.

**Comment by Saeed1-byte** [comment]
Thanks StephanSchaller, please inform me when its fixed.
