### ISSUE TITLE
Changed values of table parameters are not saved to new xml by saveSimulationToXML in matlab

### ISSUE THREAD

**Issue by VanessaBa** [Open-Systems-Pharmacology/Forum#203]
A changed table parameter is not saved to xml by saveSimulationToXML

Reproduction Steps:

    1)initialise a model containing at least one table parameter in matlab with initSimulation(XML,'allNonFormula')
    2)change any value of the table parameter
	3)call saveSimulationToXML(newxml,i)
	4)initialise newxml
	5)check table parameter
 

Expected behavior:

new value in table

Observed behavior:

old value in table

**Comment by Yuri05** [comment]
Closed in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/56
