### ISSUE TITLE
Visual Predictive Check in PKSim

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/Forum#205]
Hi,

I have two questions with regard to parameter identification in PKSim:
1. There is an option to have data and/or parameters in log scale with which the optimized parameters will differ from linear scale. How should I know which one to pick (log or linear)? For example I have parameters lipophilicity, Vmax and Km which I wish to optimize.

2. When I try to plot VPC, I get this message: 

VPC was not calculated. Ensure that the option "Calculate Sensitivity" is selected. 

Where should I select that?

Thank you,
Farzan

**Comment by tobiasK2001** [comment]
Dear Farzan,
regarding when to use the log scale: 
I use log scale generally if I ahve no clear idea about the magnitude of the parameter and thus have a wide spread between the min and max limit. For lipophilicity I use log scale if I have a LogP value as starting point.
regarding the VPC:
![grafik](https://user-images.githubusercontent.com/25585248/43630192-e183e64c-96ff-11e8-9600-4ba1bdb63c9b.png)
ensure to activate the checkbox on the Configuration tab.

Hope this might help you

Best, Tobias
