### ISSUE TITLE
2-Day OSP WORKSHOP: October 3/4 2018 BOSTON, MA, UNITED STATES

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Forum#206]
We are pleased to announce an upcoming TWO-day OSP workshop on integrating PBPK with QSP. The workshop will take place on October 3rd and 4th, 2018.

For more Information, please check out the Workshop info page [here](https://github.com/Open-Systems-Pharmacology/2-Day-BOSTON-Workshop-2018)

**Comment by wajab** [comment]
Hello, i m interested in a workshop or PK SIM training in germany. 
 Is there sommething in the near future?
regards
wajab

**Comment by tobiasK2001** [comment]
Dear wajab,
actually we are planning a 2 days Workshop in Berlin to beheld in November this year
Planned Titel: “Introduction to PBPK modelling using the free and open source Software PK-sim and MoBi”.
Beside an introduction for beginners a focus will be laid on DDI prediction.

Does that sound interesting to you?
please provide me you Email (see my contact details below) than I will set you on the notification list

Cheers, Tobias

Tobias Kanacher, PhD
Agriculture, Food and Life
Consultant Modelling & Simulation
Life Sciences – Modelling & Simulation
SGS Exprimo NV
E-mail: tobias.kanacher@sgs.com

**Comment by wajab** [comment]
Dear Tobias,
thanks. 
I sent you a mail 
Wajab
