### ISSUE TITLE
Fraction is not in the list 

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#21]
[Errorfile.docx](https://github.com/Open-Systems-Pharmacology/Forum/files/1059907/Errorfile.docx)
I am trying to add the observed data (Fraction dissolved) and getting the error.
Could you please advise me on this.

kind regards
Mouli

**Comment by Yuri05** [comment]
Currently **population** time profile plots does not allow displaying simulation outputs/observed data in different unit dimensions (e.g. _Concentration_ and _Fraction_) on the same plot.
Please create a second time profile plot for Fraction (e.g. via selecting _Fraction dissolved_ as one of selected outputs). After that you will be able to add fraction data to this plot
<img width="550" alt="time profile" src="https://user-images.githubusercontent.com/25061876/26920288-d4bc6488-4c38-11e7-8342-e979250e131d.png">

**Comment by moulirc** [comment]
Thanks for your comments and it helped
