### ISSUE TITLE
Unable to access or the add metabolizing enzyme (database not available)

### ISSUE THREAD

**Issue by REVATHICHAPA** [Open-Systems-Pharmacology/Forum#211]
![image](https://user-images.githubusercontent.com/33914315/44109355-ac7f6b50-9fb1-11e8-87b5-63f734c9c255.png)

Hi Team,

How do I integrate metabolizing enzymes or transporters data into PK SIM?

**Comment by Yuri05** [comment]
1. Download Gene Expression Database Human (**GENEDB_human.mdb**) from 
http://setup.open-systems-pharmacology.org
2. Set the database in your application settings. This can be set under _Utilities->Options->Application_
<img src="https://cloud.githubusercontent.com/assets/1041237/26009930/ef518ae2-3718-11e7-9c5e-a53347d818d7.png"></img>

**Comment by REVATHICHAPA** [comment]
Thank you so much Yuri! Appreciate it!
