### ISSUE TITLE
Identifying the dissolution Shape

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#213]
We did a dissolution study on 15 generic brands of a drug and build an IVIVE model. For this we tried using the raw dissolution data, the issue we had was very high Cmax and AUC compared to the published data. 
Hence we decided to determine the shape of the curve using Weibull method (  F = 100*{1 - Exp[ -(((t-ti)/Td)^β)]})  and we were able to match the published data on Cmax  and AUC. I would like to know is there any publication that I could use as a reference to justify my method.
 
Thanks for your help in advance.

**Comment by StephanSchaller** [comment]
You found sth.?
