### ISSUE TITLE
Help with continuous infusion dose on OSP/PK-Sim

### ISSUE THREAD

**Issue by samitganguly** [Open-Systems-Pharmacology/Forum#215]
I am trying to set up an administration protocol with continuous infusion and a bolus iv dose. 100 mg iv dose given for 5 mins, followed by 125 mg/hr infusion given over 12 hrs, i.e., 1500 mg dose given over 12 hrs. 
I am not being able to get it right! clearly from the attached image you can see that the entire infusion dose was administered within 0.2 hrs, end time for the protocol is selected as 0.08 hrs. 
Can you please advise?

![continuous infusion administration protocol](https://user-images.githubusercontent.com/42443624/44216349-b1574480-a142-11e8-81e4-36328a74f3e4.PNG)

**Comment by Yuri05** [comment]
It's just a problem in the **graphical representation** of the administration protocol (infusion time is not taken into the account)

Your administration protocol is correct and infusion time used for simulations will be 12h as expected.

**Comment by samitganguly** [comment]
Hi Yuri, Thank you for your response. 
But, as you can see from the simulation below, it clearly does a good job for the infusion once Css is achieved. But, it doesn't fit well with the observed iv bolus data! 
Can you please advise?
Regards
Samit

![simulation-oberved overlay](https://user-images.githubusercontent.com/42443624/44218302-6b50af80-a147-11e8-9e20-663dcbab58e6.PNG)

**Comment by StephanSchaller** [comment]
Without looking too close at what you are doing: Maybe you are just not "catching" the Cmax due to "sampong times". I.e. in your simulation settings, change the "Resulution" to > 60/hr?

![image](https://user-images.githubusercontent.com/25477643/44221479-f3ec4180-a181-11e8-9840-53c9725e6ef3.png)

**Comment by samitganguly** [comment]
Here is the simulation with 60pts/h for first 2 hrs. Clearly Cmax is not captured well. 
![simulation-oberved overlay 60ptsh](https://user-images.githubusercontent.com/42443624/44222773-a35def80-a153-11e8-8110-4c2bd553dfa9.PNG)

**Comment by StephanSchaller** [comment]
Alright, next steps for me would be 

1. to check if a simple IV bolus administration (leaving out the infusion for now) produces the same results (during the first half hour). But I am pretty sure it does.
2. to reconsider my distribution model, meaning: the lipophilicity of Meropenem seems rather low (depending on the source) and the assumption of "fast" tissue penetration could be not suitable, i.e. you probably used a 4-compartment model for small molecules, and permeability (P endothelial) for plasma <-> interstitial is set to 100 cm/min by default. This implicitly increases your volume of distribution. Try scaling it down to around 1e-4 and have a look at the results.


Hope this helps,
Stephan

**Comment by samitganguly** [comment]
Hi Stephan, 

Thank you so much for your advise. 
I checked with a iv dataset. As I suspected before, the model is not being able to find the Vmax so well. 

I am absolutely new to PKSim, thus may be I am missing the Permeability change you suggested. I suspect, it should be part of compound characteristics. I found that the permeability is set to a very low value there (attached) than what you suggested. 
Any advise?

<img width="541" alt="simulation-observed overlay" src="https://user-images.githubusercontent.com/42443624/44277762-aae7cc00-a219-11e8-8003-2e81bc475ddf.PNG">

<img width="586" alt="compund property" src="https://user-images.githubusercontent.com/42443624/44277522-f8b00480-a218-11e8-9739-3f5b77c4787c.PNG">

**Comment by StephanSchaller** [comment]
Hi Samit,

the value you found is the permeability calculated based on compound properties (Lipophilicity and Molecular Weight). This is applied for cellular permeation (interstitial to cell compartment) and the blood brain barrier. However, for plasma to intertitium permeation, the truth lies somewhere in between this calculated value for very tight vasculature and a very high permeability value (i.e. approaching the default 100 cm/min) for porous vasculature (spleen or liver-like).

You can change permeability (endothelial) here:

![image](https://user-images.githubusercontent.com/25477643/44279081-6cb9cf00-a250-11e8-8439-ba1675ca9618.png)

**Comment by samitganguly** [comment]
Hi Stephan, 

Thank you so much for your advise and help. It seems to fit much better now. 
I was also curious about your mention of 4-compartment model. Is there a way to select compartments when modeling in PKSim?

Regards
Samit

**Comment by StephanSchaller** [comment]
Hi Samit,

yes, you can choose between 4-compartment (for small molecules) and 2-pore (for proteins / biologics) model formalism right at the first view when you click "create simulation":
![image](https://user-images.githubusercontent.com/25477643/44290368-a43c7180-a278-11e8-835f-85669daadb2e.png)

**Comment by samitganguly** [comment]
Hi Stephan, 

Can you please explain this 4 compartment? 
The options you showed are the default options when we perform any simulation. Does that mean we always assume 4 compartment for small molecules?
What are these 4 compartments? Does it mean very high permeability to all organs, and whole body is now separated into 4 compartments? Or its just 4 compartment in each individual organ/tissue?

I ask because, if I am not changing the permeability, I find similar to plasma concentration-time profile in all tissues (skin/ muscle etc). My compound has very low lipophilicity, high solubility and a pKa which will keep it in ionized form at physiological pH. As you pointed out before, I do not expect to see very high concentration in all tissues, and it was not observed as well (published data on tissue concentration).

**Comment by msevestre** [comment]
@samitganguly 

>What are these 4 compartments? 

Please check the documentation here. This might hopefully answer your question

https://docs.open-systems-pharmacology.org/working-with-pk-sim-r/pk-sim-r-documentation/pk-sim-simulations#model-settings

Cheers,
Michael

**Comment by StephanSchaller** [comment]
@samitganguly 

> Does that mean we always assume 4 compartment for small molecules?

Yes, each organ is subdivided into: plasma, blood cells, interstitial, and cellular space.
By default, diffusion between plasma and interstitial space is set to very high values so you have them well mixed. This may not be suitable for your low lipophilic drug and you should reduce this permeability (you have to switch to advanced view, see bottom left in screenshot).
![image](https://user-images.githubusercontent.com/25477643/46575126-a1741800-c9af-11e8-8ca5-f923e5f10742.png)

Also, with an ionized drug, you may want to change to the Rodgers and Rowland distribution model.
(when you create a simulation):
![image](https://user-images.githubusercontent.com/25477643/46575113-86090d00-c9af-11e8-8d27-97d3c687aca0.png)


Hope this helps

**Comment by samitganguly** [comment]
Hi Stephan, 

Yes, this was definitely helpful. Few concerns that I have in altering the permeability are:
1. Will the altered permeability value be scaled with age? i.e, If I create a new permeability for adult populations, will that be scaled to geriatric or pediatric population?

2. Is it a convincing argument for publication purposes? Is there a publication that we can cite?
I found observed concentration data for only one tissue, and permeability is an important parameter that helps simulating the tissue concentration. Thus, I know alteration in the permeability is required. 
But, not sure if I can change the value for each population? 

3. Permeability could be different in all tissues. Specially the less vascular tissues. Now if I change permeability for only one tissue (because I have observed data), is that okay?

Thank you in advance for your help! 

Regards
Samit

**Comment by StephanSchaller** [comment]
Hi Samit,

1. No, permeability is never scaled. So it doesn't matter if you change that.
2. If you want a first estimate of tissue specific permeability, I would suggest to use the protein model. There you will have pores (organ specific) also contributing to permeation. if this is not enough I would then also scale diffusion permeability for all organs.
3. No, I would scale ALL Organs. And I would scale it with the factor that you get for the one organ, for which you have a measurement.

If this is not enough, you should do some parameter estimation!

Best,
Stephan
