### ISSUE TITLE
Diprotic base in PKSim

### ISSUE THREAD

**Issue by karthikl6** [Open-Systems-Pharmacology/Forum#216]
Hi,

I'm working on a compound that is diprotic base and when I use both the pka's (6.51 & 2.94) as a base the concentrations (Cmax) is very low almost 5 times lower than observed concentrations from literature. But If I change one of the pka (changes 2.94 to acid) to acid then the concentrations are close enough to observed data. I'm not sure what is going wrong since it is diprotic base I guess I must make both pka as base right? Please correct if I'm wrong.

**Comment by tobiasK2001** [comment]
Dear karthikl6,
indeed you should keep bost pKas as base if they are measured like that and you might think about other reasons for mismatch. Are your measured Cmax concentrations after iv or po dosing?
In the latter case you might think of influence of solubility and intestinal permeability as well. What about intestinal metabolsim and transprorter effects? Hard to give more conctrete advice without knowing more details of you compound.

Best, Tobias

**Comment by karthikl6** [comment]
Dear Tobias,

My apologies, I've missed compound name in the previous post. It is Ketoconazole, that I'm working on after po dosing. I'm using the physicochemical parameters from this paper [https://pubs.acs.org/doi/10.1021/acs.molpharmaceut.7b00406](url) and using total hepatic clearance for 200mg tablet. Observed Cmax is ~3.5 ug/mL and PKSim predicted is around ~0.5 ug/mL.

**Comment by karthikl6** [comment]
Yes, I did look into that model and found that it has one of the Pka as acid. I kept in my version as base for both Pka's and tried to fit solubility. But it looks like concentrations are not sensitive to solubility. Other parameters that I tried are specific clearance, permeability (in MoBi) and intestinal permeability. Concentrations with these fitted values are a bit close to observations but fitted parameters changed a lot (7-8 fold) from original values. Also, I'm not sure how to add that hepatic uptake value from Pattak et al 2017 into PKSim. Can we also get the amount (instead of concentrations) of compound dissolved, absorbed with time from PKSim like we get in GastroPlus?

**Comment by tobiasK2001** [comment]
I think the hepatik uptake value from Pattak cannot be directly translated to PK-sim. It seems to be somewhat SimCyp specific. However if you want to check how invreased liver intracellular levels behave you can simply increase the Partition coefficient Intracellular : Plasma. by Scale (e.e 2.07) and reste all organs except Liver pericentral:
![grafik](https://user-images.githubusercontent.com/25585248/44387047-ae829800-a524-11e8-8191-1e6847e00cf0.png)
However, for me it influenced the Cmax in the wrong direction in our case.

I would not be so worried about  7-8 fold change in parameters like intestinal permeability as it is often hard to measure and to translate e.g. from Caco to human intestine. However this is hard to judge without having a look at the other sanity checks in the PI like Correlation matrix and Covariance matrix. Changing Parameters like solubility and intestinal permeability is less substantial than ignoring that Ketoconazole is a diprotic base in my eyes. I wounder why Krinaj did it? @krinaj: Did you had a special reason for this?
regarding amount of compound dissolved / absorbed: yon can export the the Fraction of compound dissolved / absorbed to excel and multiply it by the dose. That should give the amount.

However, this might be a good feature to compare results in PK-sim or at least in MoBi to other programms. @msevestre: can we add it to a feature wish list?

**Comment by Yuri05** [comment]
>However, this might be a good feature to compare results in PK-sim or at least in MoBi to other programms. @msevestre: can we add it to a feature wish list?

@tobiasK2001 You can add anything to the feature wish list :smile: (just open separate issues for this please)

**Comment by Yuri05** [comment]
>Can we also get the amount (instead of concentrations) of compound dissolved, absorbed with time from PKSim?

_Amounts_ can be currently only shown MoBi. 

E.g. to show amount of drug absorbed into mucosa from a lumen segment:
1. Export simulation to MoBi
2. Open the simulation and navigate to the **Paramaters** view
3. Navigate to `Organism/Lumen/<Segment>/<Drug>` (e.g. `Organism/Lumen/Caecum/Theophylline)`
4. Locate the parameter **_Oral mass absorbed segment_** and activate the checkbox **_Plot Parameter_**
<img width="500" alt="aufnahme52" src="https://user-images.githubusercontent.com/25061876/44403463-0a104e00-a544-11e8-93b0-0b7097b175f4.png">

5. Recalculate the simulation (select the **_Oral mass absorbed segment_** curve in the chart browser if it's not shown automatically)

Total amount of drug absorbed into mucosa can be shown in the same way.
It's located under `Neighborhoods/Lumen_sto_Lumen_duo/<Drug>/Oral mass absorbed`
<img width="500" alt="aufnahme53" src="https://user-images.githubusercontent.com/25061876/44404009-5f992a80-a545-11e8-93b0-ad8556d971c4.png">

Drug amounts (of dissolved drug) can be selected in MoBi in **_Define Settings and Run_** dialog of a simulation:
<img width="600" alt="aufnahme54" src="https://user-images.githubusercontent.com/25061876/44404215-f2d26000-a545-11e8-9892-d9bd7a95d12c.png">

**Comment by krinaj** [comment]
@tobiasK2001 @karthikl6 
there was no particular reason for selection of acid vs. base; I guess it was an error since I had populated this quick model for some checks only. I have not worked on/developed/tested this model any further. Good luck.

**Comment by tobiasK2001** [comment]
Ah, Ok. Thanks a lot for the Info!

**Comment by karthikl6** [comment]
@Yuri05 , Thank you very much. This helps a lot.
@tobiasK2001 , I want to know more about the "scale" parameter for intracellular: plasma partition coefficients in Distribution section. In Pathak et al paper mentioned in my previous comments, they developed full PBPK model for Ketoconazole in SimCYP. But they used KPScalar value of 0.015 that scales the intracellular partition coefficients using Rodgers and Rowland method. When I did the same in PKSim (Scale = 0.015 in intracellular: plasma partition coefficients), the predictions were close to observations. Why do I need to scale down the original values to 1% of them? is it because of some missing information or LogP and pKa's were incorrect?

**Comment by tobiasK2001** [comment]
That would be an excellent question to ask Pathak et al. I am not sure why they used this scalar and I don't know how they implemented it in SimcCYP. Was it appliyed for all organs? Furthermor I am not sure if, applying this scalar in PK-sim and SimCYP influeneces the model in the same way. I assume that the didn't want to change LogP and PKA from measured values, as they are easily measurable and the needed this paramamteres for their Bio-dissolution story. However they needed to addapt the distribution behavior of the Keto. So they introduced the scalar as kind of fudge factor as it is hard to contradict with experimental values. At least you can now reason that you used a similar "scalar" than known from Literatur and cite Pathak et al. :-)
