### ISSUE TITLE
expression of CYP2D6

### ISSUE THREAD

**Issue by aargikar** [Open-Systems-Pharmacology/Forum#217]
Hi,
I was wondering if the RT-PCR expression of CYP2D6 in the PK-Sim software is based on average expression of CYP2D6 (somewhere equivalent to intermediate metabolizer level). Please let me know. Thank you.

**Comment by AndreDlm** [comment]
Dear @aargikar,

that is indeed an interesting question. You may find the publication on the [PK-Sim database](https://doi.org/10.1124/dmd.111.043174) helpful.
In this publication the source for all incorporated expression values is given, e.g. for [RT-PCR](https://doi.org/10.1248/yakushi.123.369). 
The original publication in which the RT-PCR method is described in some detail can be found [here](https://doi.org/10.1248/yakushi.122.339). From the description given there, it seems that the primers and probe used to detect and quantify gene expression are not specific to different CYP2D6 genotypes.
(Genotype-specific primers/probe sequences are described for example [here](https://doi.org/10.1016/j.clinbiochem.2009.04.009) and [here](https://doi.org/10.1002/humu.10280)).

For the other methods, EST and Array, you may found further information in the respective original sources given in the publication on the PK-Sim database.

Hope this helps!
André
