### ISSUE TITLE
Dissolution Profiles

### ISSUE THREAD

**Issue by AlejandraSchiavo** [Open-Systems-Pharmacology/Forum#218]
Dear all,

I've got a few questions about integrating in vitro dissolution data into PK-Sim. First, I know that for an oral administration of a tablet, the model simulates two separated transit rates through the GIT for the dissolved drug and the solid tablet. Is it possible to define these rates independently? 

When using data from USP-Appartus IV. What setting would you recommend in order to coordinate the dissolution profile (more than one dissolution media) with GIT transit time? 

Can I add variability in dissolution profiles when I make a solid oral formulation?

Thanks in advance for your help,
Best regards. 
Alejaandra

**Comment by StephanSchaller** [comment]
Sorry that there have been no responses so far.

> Is it possible to define these rates independently?
Not in PK-Sim, but in MoBi everything is possible (but challenging)

> What setting would you recommend in order to coordinate the dissolution profile (more than one dissolution media) with GIT transit time?
Not sure I understand your question, but in general, when incorporating dissolution data, you use the "table" from the available formulations and just enter your time-dissolution pairs.

> Can I add variability in dissolution profiles when I make a solid oral formulation?
Not directly, but you can e.g. set "solubility" in a population simulation as "user defined variability". But then you are also always including the variabilities in physiology from the population.
To run simulations with variabilities in your formulation properties specifically (and only), you would have to switch to the Matlab or R toolbox.

Hope this helps

**Comment by AlejandraSchiavo** [comment]
Thank you very much for your help!
