### ISSUE TITLE
Matlab generateMatlabCodeForXML: SimulationIndex 1 is not valid

### ISSUE THREAD

**Issue by nealpatel96** [Open-Systems-Pharmacology/Forum#22]
Hello,

I have been trying to create a Matlab script from my MoBi simulation using the generateMatlabCodeForXML.m file, however I am running into an error within the GUI stating: "Error while setting the Trees! SimulationIndex 1 is not valid.  There is none simulation initialized." I similarly received the same error when trying to use the PopSim.xml and PKSim_Input_04_MultiApp.xml example models within the MoBi Toolbox for Matlab 7.1.

Thank you!

**Comment by msevestre** [comment]
@KatrinCoboeken. Any idea what might be going wrong here?

**Comment by TheiBa** [comment]
@KatrinCoboeken is ooo, so here judgement will take a little. @nealpatel96 : can you provide further specifications, e.g. does the problem also occur, if you just export a very simple PK-Sim model to MoBi and run the GUI? Probably, if it also happens with the included examples. What Matlab version do you have installed? At which step do you get the error and can you paste the Matlab error message?

**Comment by nealpatel96** [comment]
I have attached a screenshot of the GUI with the error.  There is no error in the command window in Matlab. I am using Matlab R2013a.  The error comes up as soon as I select the simulation file prior to the loading of any input and output selections.
![generatematlabcodeforxmlerror](https://user-images.githubusercontent.com/19978792/27039084-e22567a8-4f5a-11e7-86ab-6cd8e79cd06e.PNG)

**Comment by PavelBal** [comment]
Which Matlab version are you using - 32 or 64 bit? MoBi-Toolbox only supports 32-bit versions of Matlab.

**Comment by nealpatel96** [comment]
I am using the 64 bit version so that may be it, thank you all!

**Comment by msevestre** [comment]
@TheiBa @PavelBal That would be great if the user could see a clearer error message when using the wrong Matlab version.

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox/issues/29

**Comment by TheiBa** [comment]
Dear Patricia,

This https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox/issues/30

might explain and present a work-around/solution for your issue?

**Comment by patriciamartinsconde** [comment]
Just to let you know that I have downloaded the "https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox" folder and the generateMatlabCodeForXML. function was not working.
No I am using the folder (MoBi Toolbox for Matlab 7.1) included in the setup of the Suite and it works.
Best,
Patricia

**Comment by msevestre** [comment]
It may have worked downloading the "https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox/tree/develop/src" folder instead. But at any rate, the setup is making sure that all the per-requesits are installed as expected. 

if a portable setup of all components is implemented (see https://github.com/Open-Systems-Pharmacology/Forum/issues/9), you will be able to simply download a zip archive file and unzip it.
