### ISSUE TITLE
Biliary concentration in PKSim

### ISSUE THREAD

**Issue by samitganguly** [Open-Systems-Pharmacology/Forum#220]
I have biliary concentration data across multiple time points. How can I create a simulation for biliary concentration in PKSim?

**Comment by tobiasK2001** [comment]
Dear samitganguly,

you can define with PK-sim in your compound a bilary excretion process e.g. like this:
![grafik](https://user-images.githubusercontent.com/25585248/44769684-bfa35880-ab65-11e8-9a5b-829552eab49b.png)
After running your Simulation you can check in "gallbladder" the observer for fraction excreted to bil like this:
![grafik](https://user-images.githubusercontent.com/25585248/44769767-f7120500-ab65-11e8-8dfd-bed2c297d0a5.png)
now PK-sim should show you the fraction excreted to bile, which you can compare with your data 
![grafik](https://user-images.githubusercontent.com/25585248/44769825-245eb300-ab66-11e8-944e-a2ae3bf2cb94.png)
Hope this might help you!
Best Tobias

**Comment by samitganguly** [comment]
Hi Tobias, 

Thank you for the detailed information. I have few more questions:

1. When I am trying to add observed drug concentration in bile, there is no such option in Organ or Compartment. Should I just add the concentration as "undefined"?

2. Since reported values are only drug concentration in bile and plasma, do you have any suggestion on the conversion of biliary concentration to fraction excreted in bile?

Regards
Samit

**Comment by tobiasK2001** [comment]
Dear Samit,

you have to recalculate your Concentration in bile to fraction of dose excreted to bile by dividing the concentration by dose. Than in PK-sim right mouse click on "observed Data" and chose "add fraction data". Be sure to set the units right .

Best, Tobias

**Comment by samitganguly** [comment]
Hi Tobias, 

Thank you for all the explanation. I could finally get the profile correct. 
But I have one more question: Concentration in bile may not be achieved immediately. It is possible to have a lag for the drug to appear in bile. How can you capture a lag in PK Sim?

Regards
Samit

**Comment by tobiasK2001** [comment]
Dear Samit,

I don't think a delay for bilary clearnce can be build in in PK-Sim. It seems to be somewhat unusual that you see the delayed appearance in bile. I would expect the compound to be ecreted as soon as it reaches the liver. What could be the physiological reason for this delay? 
Best regards, Tobias

**Comment by samitganguly** [comment]
Hi Tobias, 

Thank you for your response. 
I agree with you. It was a published observed data. It is possible that it takes some time for sufficient concentration to build up in bile for detection. The rate of appearance (efflux or other mechanism) in bile might be different than rate of infusion (which is very much likely) and thus the observed concentration appeared as a delay.

Regards
Samit

**Comment by lisach56** [comment]
I would like to simulate excreted fraction to bile too, but i can't find the galdbladder compartment in simulation setting..
thank you for your help
lisa
![capturenogaldbladder](https://user-images.githubusercontent.com/46817121/54034725-ecd95f00-41b7-11e9-9f1d-200fb6187474.PNG)

**Comment by samitganguly** [comment]
@lisach56 

The Gallbladder is definitely on the list. 
![image](https://user-images.githubusercontent.com/42443624/54050043-3f148300-41ac-11e9-9282-790e373647c1.png)

Not sure. I would probably complete the compound block with hepatic / biliary clearance, so that system knows that something is/might come out in bile.

**Comment by lisach56** [comment]
thank you for your answer but I just found out that rat lacks a gallbladder!! 
i have data of fraction excreted to bile for my compounds in rats implanted with bile duct catheter. do you know how to run this type of simulation?
thank you

**Comment by samitganguly** [comment]
@lisach56 
The short answer would be, I have never done this myself, not yet.
Yes, there is no gallbladder in the rats. Gallbladder is used for storage and timely release of bile. Not sure how the release is timed though. Anyway, so my understanding is that bile would be constantly released for the rats. Is there any bile synthesis/ flow related component in rat liver? I would start from there probably.

**Comment by StephanSchaller** [comment]
@lisach56 
Please open a new issue for each questions, even f it is related to an existing issue (you can then link existing issues if required).

In short: In rats, bile flows continously. There is no timing of bile flow. Biliary clearance will be what you define as biliary clearance in the compound:

![image](https://user-images.githubusercontent.com/25477643/54244994-5f876900-452f-11e9-82e4-cf3afb21b378.png)
