### ISSUE TITLE
How to deal with CYP Expression in GIT - Non-mucosal tissue?

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#221]
Dear OSP community,

Using the RT-PCR expression database in PK-sim predicts considerable expression of CYPs in non-mucosal intestinal tissue. This results in considerable fraction metabolized in this tissue. E.g. 11.7 % für CYP2C19 or 3-4 % for CYP3A4 or CYP2D6 after iv application of respective CYP-substrates. After oral dosing fraction metabolised in non-mucosal tissue is 2-3 % and the fraction metabilized in mucosa is higher. Without CYP Expression in non mucosal tissue AUC appears to be 2-5 % higher. Should relative expression of CYPs in non-mucosal intestine be set to 0? As it is believed the intestinal metabolism takes exclusive place in the mucosa only. Or should it be kept as is to vaid for consistence reasons with older models?

Please let me know what you think.

**Comment by Yuri05** [comment]
Closing. @tobiasK2001 Please reopen if you have any further questions on it.
