### ISSUE TITLE
Advice on Fitting My Rifampin Model Better?

### ISSUE THREAD

**Issue by yishuanwu** [Open-Systems-Pharmacology/Forum#222]
[PBPK-Rifampin.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/2365122/PBPK-Rifampin.zip)
Hi, I am working on building a Rifampin IV model. I am still working on fitting the adult model and have not started on the induction/inhibition processes. Ultimately, I would like to use it for neonatal DDI predictions. 

I know there is a rifampin model in the template but I hope to improve on that model, and also I did not understand how it derived some of the parameters. I found a range of values in the literature for some parameters (e.g. LogP from 2.7 to 3.13, and fu from 0.125 to 0.175) and I was missing rifampin transport kinetic data. I arbitrarily set the Km of the P-gp to 1 just so I can use parameter identification to get a Vmax. I kept trying to play with each of the parameters but my model is still overestimating Cmax. 

Please see the attached. RIF0 is the PK-Sim template, RIF3 is the model that I am working on. In the below images, my model is showed using dashed lines. 
Adult Data
<a href="https://imgur.com/BbIooYP"><img src="https://i.imgur.com/BbIooYP.png" title="source: imgur.com" /></a>

Neonate Data
<a href="https://imgur.com/X7HrHR7"><img src="https://i.imgur.com/X7HrHR7.png" title="source: imgur.com" /></a>

**Comment by sfrechen** [comment]
You may get some additional insights here:
https://github.com/Open-Systems-Pharmacology/Rifampicin-Model
and in our respective publication: https://doi.org/10.1002/psp4.12343

If that does not answer all your questions we are happy to give further support.

**Comment by yishuanwu** [comment]
Hi Dr. Frechen, 
Thank you for your reply. I did look at your model before but I will look at it again. 
Shirley
