### ISSUE TITLE
Are there parameters for Latin American populations?

### ISSUE THREAD

**Issue by Vanderson88** [Open-Systems-Pharmacology/Forum#223]
I want to work drug-drug interactions with populations in South America. Would it be equivalent to work with the Mexican population that shows Pk-SIM?

**Comment by msevestre** [comment]
@Vanderson88 There are no parameters defined for latin american populations.
You could look in litterature to see if these populations are similar (e.g. comparable body weight, height, etc...) and if yes, the mexican population would be a good surrogate.

Hope that helps,
Michael

**Comment by msevestre** [comment]
Closing for now. Let us know if you need more help.
