### ISSUE TITLE
Community OSP (Database) extensions

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#224]
Not sure where to post this:

I'd like to propose a "Space" on the OSP community, where we can "park" (publications on) new (physiological) data that could be used to extend the OSP Database.

This could be publications on new (or not yet integrated) Enzyme Ontogeny profiles, Expression levels (in special pops or animals), New Populations.

Likewise we could have a "space" where we can discuss new methods or workflows (e.g. IVIVE).

**Comment by tobiasK2001** [comment]
Great Idea! I would happy to contribute a some publications I came accross while looking for other stuff...

**Comment by msevestre** [comment]
I think this is a good idea. This could be  one repository with dedicated labels. All those entries would be issues that would only be close, when implemented in the OSP database or when deemed irrelevant.

How should we name such repository?

**Comment by sfrechen** [comment]
Great idea to gather our different efforts in establishing a "curated" database as a sort of meta-analysis.
We have to distinguish between absolute and relative abundances.

name suggestion: "(enzyme and transporter) abundance database" ?

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/Protein-Abundance-Database
