### ISSUE TITLE
Reliable protein expression data

### ISSUE THREAD

**Issue by utopianwy** [Open-Systems-Pharmacology/Forum#225]
I found the most challenging and tricky part of building a PBPK model is to find the reliable protein expression data. Most of the expression data from databases are RNAseq or microarray data. In rear cases, there is RT-PCR data available. However, even the mRNA levels are quite different from the protein levels. It is also very difficult to find data other than mouse and human. It makes building a model with animal data very challenging, since you do not have reliable protein expression data for that specific species. And you cannot really predict the human exposure with animal data since you do not know the differences between animals and humans.,, I wonder how other people handle this issue...

**Comment by PavelBal** [comment]
Protein expressioin data is indeed a challenging part of model building. We are currently gathering data on protein abundance determined with LC-MS/MS method, which allows quantification of enzymes and transporters. I thintkit would be great to establish a community curated protein database.

**Comment by utopianwy** [comment]
@PavelBal Thanks for replying! I wanted to repeat your dapagliflozin model published here (https://www.page-meeting.org/pdf_assets/5943-PAGE_2017_Balazki_DapagliflozinPBPKPD_v04.pdf), and cannot repeat the model. Could you tell me what specific parameter you have changed?

**Comment by PavelBal** [comment]
@utopianwy I have to ask you to be patient just a little bit more - a full publication, including the dapagliflozin model, is currently in revisioin and, when accepted, the whole model (including model files) will be uploaded here.

**Comment by PavelBal** [comment]
@utopianwy FYI https://github.com/Open-Systems-Pharmacology/SGLT2i-hyperfiltration-model

**Comment by utopianwy** [comment]
thank you :)

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Pavel Balazki <notifications@github.com>
发送时间: 星期五, 十月 26, 2018 2:53 下午
收件人: Open-Systems-Pharmacology/Forum
抄送: utopianwy; Mention
主题: Re: [Open-Systems-Pharmacology/Forum] Reliable protein expression data (#225)


@utopianwy<https://github.com/utopianwy> FYI https://github.com/Open-Systems-Pharmacology/SGLT2i-hyperfiltration-model

―
