### ISSUE TITLE
transporter kinetic parameters

### ISSUE THREAD

**Issue by aargikar** [Open-Systems-Pharmacology/Forum#227]
Hi,
I have literature values of multiple transporter kinetic parameters and I have an issue with the units for velocity. All the velocity parameters in literature reports seem to be in pmol/min/mg of total protein units while the only option in PKSim is pmol/min/pmol of transporter protein. In case I dont know the concentration of transporter per mg of protein, is there a way to resolve this issue? Please let me know.

**Comment by SCarter79** [comment]
What i've done so far (which may be incorrect) is this:
1) Data is per mg transporter protein (at least for vesicles and cell lines).
2) Find the MW of the transporter (eg BCRP = 72KDa)
3) moles = mass(g)/rfm = 1e-3/72000, convert to pmoles (*1e9)
4) multiply your Vmax by this number to normalise to pmol/min/pmol of protein

**Comment by samitganguly** [comment]
Wouldn't the mole to pmole conversion factor be 1e12 ? Or is there some other reason for which 1e9 is being used?

Thank you in advance for clarifying.

**Comment by SCarter79** [comment]
That is correct sorry - i've updated my comment accordingly!
