### ISSUE TITLE
Synthesis of endogenous protein in arterial/vernous compartment??

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#231]
Dear all,

I want to introduce an endogenous protein into a PBPK model. I have observations of this protein in venous plasma. 
Is there a way of implementing (i) a turnover model of a protein in the blood compartments or (ii) to set the protein concentration in venous plasma without applying a turnover model?
The turnover model would give me the chance to introduce variability to the half-life of the protein and the baseline concentration. Possibility (ii) would not help me to set the variability of the half-life but I could at least set the variability for the baseline concentration.

Any solutions or ideas??

Thank in advance,
Daniel

**Comment by Christoph27** [comment]
Dear Daniel,

you can introduce a formation process generating the endogenous protein in a (or all) plasma compartment(s) within MoBi. Then - together with the generic endosomal CL and any additional CL process you define - a turnover of the endogenous protein would result. 
(I hope I got your question right. You do not want to modify FcRn competition with the endogenous protein, right?)

All the best,
Christoph

**Comment by DanielMoj** [comment]
Dear Christoph,

you got the question right!  Thanks for your response... I am going to test to introduce the formation process within MoBi in the coming days and weeks.

... I guess I ask in more detail then :)

Best,
Daniel

**Comment by DanielMoj** [comment]
Dear Christoph,

I have a file attached with an IgM administration to a human individual (as a protein example). What I want to do here exemplarily is to set up an IgM formation process to obtain a certain baseline IgM concentration in plasma. So that IgM is administered "on top" of this IgM baseline.
In the end I want to do population simulations with baseline IgM (varied in population) and an IgM administration.

How do I do that? Where do I have to define the Synthesis (reactions building block?)? How do I have to choose the parameter paths? How do I have to define the synthesis rate If the IgM clearance is only determined by the endosomal uptake rate?

I guess these are a lot of questions... but I am quite lost at the moment....

Instead of using this mechanistic approach I thought of simply adding a baseline IgM concentration to the plasma observer. But I do not like that idea - or what do you think about that?

[IgM_synthesis.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/2447327/IgM_synthesis.zip)

Many thanks in advance
Daniel

**Comment by StephanSchaller** [comment]
Hi Daniel,

we did sth. very similar for an explicit Albumin Model we developed.

- You create (yes, in the reactions building block) a reaction somewhere, where IgM is produced (Bone(marrow)?)(check literature for synthesis rate). 
- Set Kd FcRn for IgM and run the simulation to steady-state. 
- Asses the base concentration of IgM: if the baseline is too low/high, you can either adjust synthesis rate, FcRn binding or introduce additional proteolysis (another reaction for degradation). But make sure you also et the right half-life (half-life is around 3 weeks? ). You can asses half-life visually, when turning of synthesis and simulate an IgM bolus.

**Comment by DanielMoj** [comment]
Hi Stephan,

thank you for your response!

on this point:
> 
 You create (yes, in the reactions building block) a reaction somewhere, where IgM is produced (Bone(marrow)?)(check literature for synthesis rate).
> 

How can I confine a reaction to Bone plasma?
Using the relative expression in PK-Sim with 100% to plasma for my "is_plasma" helper protein will get me the reaction in all plasma compartments.
In order to get the reaction just to Bone Plasma, can one use the Parameter start values building in MoBi? If, yes... which Path Elements do I have to take care of?? 

Thanks in advance,
Daniel

**Comment by DanielMoj** [comment]
Hi Stephan,

yes, that helps absolutely!! :)
My be you or Christoph could help me with one more thing...

What I aim at is a IgM forming reaction, for which I can define a Baseline IgM concentration (with standard deviation) in a population simulation. The Synthesis rate should be calculated for each individual's baseline in the population. Something in the form of ksyn = baseline * kdeg. Do you have some suggestion on how to write down the reaction in MoBI?

One of my first attempts looks like this:
![grafik](https://user-images.githubusercontent.com/30256131/46542531-eb310580-c8be-11e8-83cb-f5ff158426f0.png)

My baseline amount of 0.02 µmol results in a peripheral venous blood conc. of IgM of 0.47 µmol/L (dashed line):

![grafik](https://user-images.githubusercontent.com/30256131/46542693-54187d80-c8bf-11e8-858b-ec9ee543b441.png)

@StephanSchaller  "Asses the base concentration of IgM: if the baseline is too low/high, you can either adjust synthesis rate, FcRn binding or introduce additional proteolysis (another reaction for degradation). But make sure you also et the right half-life (half-life is around 3 weeks? ). You can asses half-life visually, when turning of synthesis and simulate an IgM bolus."
--> with this approach one has a synthesis rate for a single individual, right? How would you proceed with population simulations in which you want to have a pre-specified distribution of IgM concentrations?

Many thanks in advance!!

Daniel

**Comment by DanielMoj** [comment]
@StephanSchaller 
I think I solved all issues... for the population simulations I simply use the "can be varied in population" option for the synthesis rate. 

Thanks!
