### ISSUE TITLE
SLCO1B1 Gene Names (Protein Espression/Protein Selection)

### ISSUE THREAD

**Issue by SCarter79** [Open-Systems-Pharmacology/Forum#232]
Hi,
Theres an error on your "Transport Proteins", you have 3 different subtypes all labelled as SLCO1B1. The gene ID's are correct however. Can you please update the "Gene Name" field to reflect this?

Many thanks

Simon

**Comment by msevestre** [comment]
@SCarter79 Thanks for reporting. These. Because it looks potentially like a bug in PKSim, I am going to move the issue to the PKSim -issue tracker. 
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/966
