### ISSUE TITLE
Scaling partition coefficients in Population simulation

### ISSUE THREAD

**Issue by karthikl6** [Open-Systems-Pharmacology/Forum#234]
Hi,

I have PK sim model, in which I had to scale partition coefficients (Interstitial : plasma & Intracellular : plasma) during model development. Now, If I want an individual PK simulation, then I'm scaling partition coefficients in Parameters --> Distribution --> Partition Coefficients. But, if I'm doing population PK simulation, I couldn't find a way to scale partition coefficients under the same path. Is there any other way that I could scale partition  coefficients for population simulations?

**Comment by msevestre** [comment]
@karthikl6 You would typically **NOT** scaled partition coefficients. Instead, you could optimize lipophilicity for your individual PK simulation. The partition coefficients values are highly dependent on lipophilicity. 

The optimized lipophilicity would by construction be used in your population simulation as well so you would not have to worry about that anymore.

Does it make sense? 
Cheers,
Michael

**Comment by karthikl6** [comment]
@msevestre I'm working on Ketoconazole and its log P reported in literature is in the range of 3.85 - 4.40. But if I optimize this it is going below 2 and I thought it might be hard to justify. Instead I found couple of full of PBPK models of ketoconazole developed in Simcyp ([Pathak et al 2017](https://pubs.acs.org/doi/10.1021/acs.molpharmaceut.7b00406) and [Rodrigo et al 2016](https://www.sciencedirect.com/science/article/pii/S0022354915001483)) where they have scaled partition coefficients tp 2% of what Rodgers-rowland menthod predicts. So, I've done the same in PKSim which gave better fits. What do you suggest in this case?

**Comment by Aedginto** [comment]
By reducing the coefficients to 2 percent of the R&R values, they are assuming that the reduction in coefficients is irrespective of tissue composition. I personally would optimize lipophilicity instead which maintains the relative effect of tissue composition. There is probably no right answer here though.

**Comment by msevestre** [comment]
@karthikl6 As far as **HOW** To scale partition coefficients in population  is concerned, which was your original question,  you have two choices:

1/ Partition coefficient are defined as "Variable in population". Which means that you can add a distribution for those parameters (or even set a fixed value)
![image](https://user-images.githubusercontent.com/1041237/46952402-b4928200-d058-11e8-8e0c-00929643d9b9.png)

The downsize of that approach is that all distributions will be independent (unless you use a constant distribution)


2/ The other approach is to **CLONE** the individual simulation with the scaled partition coefficients and swap out the individual for the population. After cloning, the partition coefficient will have the value of the original simulation. You can verify that by adding a variability as described in 1/ and see that the default value is the one from the individual simulation
![image](https://user-images.githubusercontent.com/1041237/46952507-076c3980-d059-11e8-832f-ec77d2109828.png)


Hope that makes sense,

Cheers,
Michael

**Comment by karthikl6** [comment]
Dear Michael,
Thank you, I hope this helps. @msevestre Also is there any way in PKSim, where I can use liver microsomal data  (Vmax and Km) not specific to any enzyme but overall clearance in the liver, if there are multiple enzymes involved in metabolism?
@Aedginto : Dear Andrea,
Thank you for your inputs. The other reason for not optimizing lipophilicity, in this case, is because I found in the literature that ketoconazole has concentration-dependent protein binding in plasma. Percent unbound in plasma is 1% [@1 ug/mL], 3% [@ 10 ug/mL]. So, I thought this also might be affecting the KP's to be completely off as there is almost 100% increase in fraction unbound at different concentrations. Please correct if I'm wrong.

**Comment by Yuri05** [comment]
Closing the issue. @karthikl6 Please reopen if you have any further questions on this topic.
