### ISSUE TITLE
OSP on Windows Server 2016?

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#238]
Dear community,

does somebody know if our OSP suite in running on a windows server 2016??

Thanks
Daniel

**Comment by DanielMoj** [comment]
In case there are others who have this question: I got some info, that the OSP suite is working perfectly well on windows server 2016!

Best
Daniel

**Comment by msevestre** [comment]
@DanielMoj Thanks Daniel.

**Comment by Yuri05** [comment]
s. [OSP Suite System Requirements](https://github.com/Open-Systems-Pharmacology/Suite#system-requirements)
Windows Server 2016 is in the list of "officially" supported OS.
