### ISSUE TITLE
Protein abundance database - new repository?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Forum#239]
I propose to create a new repository for working on a new database of protein abundances. PK-Sim would greatly benefit from such a database, enabling IVIVE and inter-species extrapolation.

Additionally to gathering data, there are several scientific and technical aspects that need to be addressed. Having a separate repository, we could discuss the questions in separate issues, without flooding the forum.

What do you think @msevestre @Yuri05 @sfrechen @StephanSchaller ?

**Comment by msevestre** [comment]
@msevestre Sure. Do you have a name in mind for this repo? I can create it right now :)

**Comment by PavelBal** [comment]
How about "Protein abundance database"? :D

**Comment by PavelBal** [comment]
Great, thank you. I will compose a short description in the next days and start a discussion on what needs to be done.

**Comment by msevestre** [comment]
Done. Although having the name database in the name could be misleading because there is no database, we can rename if need me
