### ISSUE TITLE
Multiple population

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#24]
Hi,

How can I add multiple ethnic populations in the simulation? Is there an option for it?

kind regards
mouli

**Comment by msevestre** [comment]
@moulirc 
You cannot mix and match ethnicity within a given simulation. That being said, you can accomplish the desire behavior using a so called `Population Simulation Comparison`, which allows you to compare many population simulations with one another. 

In your case, my suggestion would be to create one `Population` for each ethnicity of interest. Then create a `Population Simulation` for each. That can be done by either `creating` a brand new simulation from scratch or `cloning` one simulation and swapping out the `Population` building block. Last you can start a `Population Simulation Comparison` and compare the simulations.

![image](https://user-images.githubusercontent.com/1041237/27083365-4ebe99be-5016-11e7-929d-c46ab526e940.png)

**Comment by msevestre** [comment]
[PopulationSimulationComparison.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1071439/PopulationSimulationComparison.zip)

**Comment by moulirc** [comment]
Thanks for your help.
kind regards
mouli

**Comment by msevestre** [comment]
For the sake of completion, it is also possible to create a population based on other populations.
The workflow is as follow
1. Create one population for each ethnicity
1. Export each population to CSV (right click on the population, `Export to CSV`)
1. Create a new population by using the `Import Population From File` (right click on the Populations Folder)
1. Select all files exported previously

This will create one population only with individuals from all exported populations. That way, you only have to create one simulation.
