### ISSUE TITLE
Buccal administration

### ISSUE THREAD

**Issue by nmens** [Open-Systems-Pharmacology/Forum#240]
Dear all
Does anyone has experienced to model (on MOBI) buccal administration of a drug? 
PK-Sim does not have Buccal administration as an option in the administration protocol, so I need to go for MOBI. The idea is to surpass GI absorption, i.e. the drug is pretended to be completely absorbed into the bloodstream directly from buccal mucosa, avoiding first pass effect.

Many thanks in advance

**Comment by msevestre** [comment]
@nmens Can't use a user defined application in PK-Sim for that? (you can specify target organ and compartment as well as a zero order or first order rate)

**Comment by nmens** [comment]
@msevestre thanks for your fast reply!
I tried to follow your suggestion in a common project I have, selecting a User Defined in Administration Protocol, target organ as Venous Blood and Plasma Compartment. I suppose your suggestion for zero order or first order rate is to be selected from Formulation tab. OK. 
However, how do I input a buccal permeability parameter? Just using the first order rate (as ka) from the formulation?

**Comment by msevestre** [comment]
>However, how do I input a buccal permeability parameter? Just using the first order rate (as ka) from the formulation?

This is not available. You have to define your rate to `mimic` a permeation process. If this does not work, or if you need more control over the process, going to MoBi is the only other alternative

**Comment by nmens** [comment]
Your initial approach seems simple and nice, avoiding the complexity of MOBI and changes in the spacial structure. Nevertheless, in the case of using only PK-Sim, is it possible to model a partial absorption in the buccal mucosa and the rest thought GI absorption, which may be a possibility in a real world administration by the swallow of the saliva solution.
How would I model this situation? Including two administrations (oral + user defined) at the same time (dose would be fractionated)?

**Comment by nmens** [comment]
@msevestre Thank you very much for your input. So it is possible to use a first order formulation with an IV administration?

**Comment by msevestre** [comment]
No it's not (at least not in PKSim out of the box)

In advanced protocol, you can combine IV and Oral as much as you want but you **cannot** use user defined application.

In simple protocol, you can use user defined application (with first order formulation). However you cannot combine it with another application type such as oral

**Comment by nmens** [comment]
OK. Once again, I wish to thanks for these precious inputs. I'll follow your advice.

**Comment by msevestre** [comment]
Ok no problem. Let us know if you need any help
