### ISSUE TITLE
hand-on drug drug interaction issue 

### ISSUE THREAD

**Issue by wuxuemei300** [Open-Systems-Pharmacology/Forum#244]
Hi, everyone,

I am learning to do DDI with PK-sim following the tutorial. Following the hand on exercise DDI with Rifampicin, I opened Ex_DDI_RIF_1, load the compound "Rifampicin" and the "standard european male for DDI", after that, I ran the simulation, the max was about 10 time lower than what it showed  in hand on book. 
![1](https://user-images.githubusercontent.com/44305281/47747781-853a6280-dc5f-11e8-8fff-654b99f8a9cf.GIF)
Do anyone get the same result with me?

Thank you

**Comment by wuxuemei300** [comment]
sorry, the figure above is not right, see below is what I get:
![image](https://user-images.githubusercontent.com/44305281/47748914-49ed6300-dc62-11e8-9574-6ae59c23c5b6.png)

**Comment by StephanSchaller** [comment]
Yes, I have identified a small bug in the template. please see: Issue [981](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/981).


Hope this helps!

**Comment by msevestre** [comment]
Thanks @stephanschaller

**Comment by wuxuemei300** [comment]
@StephanSchaller @msevestre Thank you, the problem solved, just like StephanSchaller said.

**Comment by wuxuemei300** [comment]
@msevestre In the DDI Rifampicin.PDF, objective 1, after simulation:
![image](https://user-images.githubusercontent.com/44305281/47794009-f2003c00-dcf5-11e8-93ac-5d401c9ff4fa.png)
What does the last sentence mean?

an other issue: DDI Rifampicin.PDF give two objective, then ended as below:
![image](https://user-images.githubusercontent.com/44305281/47801435-96897a80-dd04-11e8-9b2b-5ae954dd6423.png)
what is the objective of Ex_DDI_RIF_3? where can I find the PDF file for that?
There is ISSX_DDI Rifampicin.PDF, but I can't open it.

Thank you

**Comment by StephanSchaller** [comment]
> What does the last sentence mean?

P-gp reduces bioavailability. So you should get lower Cmax values (as you can see in the PLots in the PDF). Trough levels are likely also decreased.

> what is the objective of Ex_DDI_RIF_3?

There is no objective (The two Objectives were listed at the beginning of the PDF). This is the standard sentence they use to tell you at what point there are backup files you can load to continue from a certain point in the exercise. 
While it implies that the exercise continues here, it does not. No other objective. But if you want to look at the end result you open **Ex_DDI_RIF_3.pksim5**
