### ISSUE TITLE
Open Systems Pharmacology Suite Documentation is now live!!

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Forum#246]
Dear community,

Today we are beginning a new chapter in the **Open Systems Pharmacology Documentation**! It is with great pleasure that I am announcing the official launch of our live documentation available at http://docs.open-systems-pharmacology.org

# Open Source

As with the rest of the suite, the documentation is naturally open source and available on GitHub. The [docs](https://github.com/Open-Systems-Pharmacology/docs) repository (https://github.com/Open-Systems-Pharmacology/docs),  will be the centralized place where any change to the documentation will from now on take place.

# Responsive Design

Whether you are reading on your phone, tablet or desktop, the http://docs.open-systems.pharmacology.org website scales to ensure that the content is clear and easy to read.

# How to Contribute?

Each page cont contains an **Edit on GitHub** link so that the community can contribute fixes and updates.

Please refer to the [contribution guidelines](https://docs.open-systems-pharmacology.org/how-to-contribute) for a detailed description of the contribution workflow and the peer review process.  
 
# Your Help is Needed

There is already a growing list of [changes](https://github.com/Open-Systems-Pharmacology/docs/issues) that we have identified. If you always wanted to contribute to the suite but did not know how, wonder no more! Updating the documentation would be a fantastic place to start.

If you happen to find an issue with the current documentation and do not know how to change it, simply [open an issue](https://github.com/Open-Systems-Pharmacology/docs/issues) in the docs repository.

We are looking forward for your feedback,

Happy reading,

Michael

**Comment by StephanSchaller** [comment]
GREAT!

Should we also announce this on the NEWs section on OSP.org?
And pin it on the GitHub main page?

**Comment by Erik-Sjogren** [comment]
Very nice!
Thank you for all efforts.
