### ISSUE TITLE
How do I incorporate dissolution data of fasting and fed state in PK SIM model?

### ISSUE THREAD

**Issue by REVATHICHAPA** [Open-Systems-Pharmacology/Forum#249]

**Comment by StephanSchaller** [comment]
No replies, yet?

When you implement an oral administration, you have to also define a formulation.
There you can select type "table" and put in your dissolution data as input.

Hope this helps

**Comment by Prajwala1921** [comment]
For this, you need to clone the formulation and rename as fasted and fed, add the respective dissolution profile and also select the prandial state as fed by selecting the respective meal in the events block for fed state simulation. (both Fed state and fasted state simulations should be created).
