### ISSUE TITLE
What pH does PK-Sim calculate specific intestinal permeability for?

### ISSUE THREAD

**Issue by TatianaAlieva** [Open-Systems-Pharmacology/Forum#25]
Excuse me, I have not found this info in the manual.
Thank you in advance!

**Comment by Yuri05** [comment]
You will find detailed description of (specific) intestinal permeability calculation in
<a href="https://www.ncbi.nlm.nih.gov/pubmed/21993815" target="_blank">Evolution of a detailed physiological model to simulate the gastrointestinal transit and absorption process in humans, part 1: oral solutions.</a>

**Comment by TatianaAlieva** [comment]
Excuse me, I am asking, because I was unable to find the explicit value of pH neither in the manual nor in the paper you mentioned.

**Comment by KatrinCoboeken** [comment]
Per default for the permeability calculation, charge and pH value are not considered.
But it is possible to introduce a charge and pKa dependent penalty factor. 
To do this, go to the parameters of a simulation, search under "permeability" the parameter: "Use pH and pKa dependent penalty factor for charged molecule fraction" and set it to "Yes".
Then an additional factor is multiplied to the intestinal permeability.

The factor is calculated as described in:
A physiological model for the estimation of the fraction dose absorbed in humans.
Willmann S, Schmitt W, Keldenich J, Lippert J, Dressman JB.
J Med Chem. 2004 Jul 29;47(16):4022-31.

**Comment by TatianaAlieva** [comment]
Dear Katrin,
Excuse me for keeping silence so long. 
Thank you for your answer!
I'm not sure that all users are aware of pH-partition hypothesis. Why does PK-Sim  not account for dissociation in the default mode? It strongly improves the predictive power.
Tatiana

**Comment by msevestre** [comment]
Closing in favor of PKSim issue #607
