### ISSUE TITLE
Unable to capture high Cmax after IV bolus dose, all the parameters used were similar between simcyp and PK SIM, but couldnt capture high Cmax in PK SIM?

### ISSUE THREAD

**Issue by REVATHICHAPA** [Open-Systems-Pharmacology/Forum#250]

**Comment by PavelBal** [comment]
I am afraid we need more information on what you are trying to model. I do not think you should expect identical results when using the different models of PK-Sim and SimCyp.

**Comment by REVATHICHAPA** [comment]
The model is not different in any way. I am unable to get the high Cmax for IV Bolus dose. The Cmax prediction was very low. How do I improvise my prediction of Cmax?

**Comment by Aedginto** [comment]
Not hitting the Cmax of an IV bolus or infusion is very likely a distribution volume issue. If your predicted is lower than observed, the V is predicted to be too high. V is a function of tissue volumes (unlikely to be the problem), fraction unbound in plasma and tissue: plasma partition coefficients. How was V determined in the SimCyp model. Was V an input in SimCyp or was did you use a Kp algorithm (without adjustment) to predict tissue: plasma partition coefficients? If a Kp algorithm was used, are you using the same one in PK-Sim?

**Comment by REVATHICHAPA** [comment]
I used method II/Rodgers method in both the models.

**Comment by REVATHICHAPA** [comment]
I havent had any scalar in Simcyp, it looks like i need to adjust scalar in PKSIM to get the Cmax. Why is that so?

**Comment by Aedginto** [comment]
What is the fraction unbound in plasma? Is it low?

**Comment by tobiasK2001** [comment]
and what plasma concentration are you comparing to SimCyp: "Venous blood plasma" or "Peripheral venous blood plasma"?

**Comment by fredsevmartins** [comment]
If everything is similar the problem could be with the number of points that your pk curve has (  conc vs time). By defaunt Simcyp plot all grafics with 2000 blood sampling that should  be enough to 24hr simulation. So if you have 3 days simulation  maybe you will miss some points. Try to increase  this number in PKSim if possible.Like @Tobiask2001 suggested  it could be the problem.

**Comment by REVATHICHAPA** [comment]
yes it is 0.05

**Comment by REVATHICHAPA** [comment]
I am comparing peripheral venous blood  concentrations?

**Comment by fredsevmartins** [comment]
Depends, you can do both. Please check what option you set.

**Comment by StephanSchaller** [comment]
Best compare venous blood first.

Depending on the permeability measures, once in peripheral VB, the drug may already be mixed with interstitial and thus exposed to a higher volume of distribution.
Thus you should also compare permeability measures for plasma <-> interstitial (endothelial permeability)

**Comment by Yuri05** [comment]
Closing the issue. @REVATHICHAPA Please reopen if you have any further questions on this topic
