### ISSUE TITLE
Is there an OSP Version available for MacOS

### ISSUE THREAD

**Issue by Mutaz94** [Open-Systems-Pharmacology/Forum#251]
Is there any OpenPharmacologySuite version available for MAC? @msevestre

**Comment by StephanSchaller** [comment]
No, sorry to say, there is not.


Maybe in the future as we have heard this question posed quite often, now.

**Comment by msevestre** [comment]
There are many ways you can run the suite in your Mac. One of which is by using [parralels for Mac] (https://www.parallels.com). 
Another is by enabling a dual boot to windows. 

As for a native port of the UI to Mac, this will probably not happen. We are thinking about migrating the PKSim CLI to be compatible with Mac OS, but this will be the extent of the migration.

**Comment by PavelBal** [comment]
>As for a native port of the UI to Mac, this will probably never happen.

Unless some motivated member (team) of the community does not do it voluntarily ;)

**Comment by msevestre** [comment]
@Mutaz94 I have renamed the question so that people can find it in the future
