### ISSUE TITLE
PBPK Videos using PK-Sim for Beginners

### ISSUE THREAD

**Issue by krinaj** [Open-Systems-Pharmacology/Forum#253]
Hi,

I have recorded and added few videos on PBPK using PK-Sim targeting beginners. Feel free to take a look at my youtube page.

https://www.youtube.com/channel/UCaJKjD5K99RuibWd-iadd1g?view_as=subscriber

Thanks,
Krina

**Comment by msevestre** [comment]
@krinaj Very nice! Thanks for sharing

**Comment by Aedginto** [comment]
Fantastic! Well done!

**Comment by JanSchlender** [comment]
Great work! Highly appreciated and valueable for the community

**Comment by dineshbcp** [comment]
Thank You so Much for Tutorial Video. Very helpful to understand to run PK-Sim

**Comment by mmarikar** [comment]
Can someone please send me a link to download pk-sim for windows10
Thanks,
momaricks@gmail.com

**Comment by msevestre** [comment]
[Video Tutorials](https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/labels/Video)

**Comment by mmarikar** [comment]
Thanks !!

**Comment by xiaofeiwa** [comment]
Very nice! Thanks for sharing
