### ISSUE TITLE
Cynomolgus monkey model

### ISSUE THREAD

**Issue by aargikar** [Open-Systems-Pharmacology/Forum#254]
Dear all,
I am trying to develop a model in cynomolgus monkeys. I was wondering if someone could provide me with the reference paper for all the anatomical and physiological parameter values for monkeys in PK-Sim (ex. organ volumes, flow rates, GIT physiology).

**Comment by Aedginto** [comment]
The gut parameters can be found in:
https://www.ncbi.nlm.nih.gov/pubmed/17373575

**Comment by aargikar** [comment]
Thank you!

**Comment by aargikar** [comment]
Hi,
I was also wondering if organ (ex. liver, kidney, heart, etc) volumes, weights and blood flows for monkey model in PK-Sim were obtained from a specific paper. Please let me know.
