### ISSUE TITLE
Using Ki for Protein Binding in TMDD model

### ISSUE THREAD

**Issue by LudwigvomHofe** [Open-Systems-Pharmacology/Forum#255]
Dear all,
I am currently working on a PBPK model for a substance with a target mediated drug disposition (TMDD) effect. 
I would like to implement this effect in my PK-Sim model by adding a Protein Binding Partner in the Specific Binding section. For that, I need Kd and koff values to describe the binding, but I only found Ki-values. 
It is my understanding, that the Ki-Value is essentially identical to the Kd-value, as it is also defined as the ratio of the rate constants koff/kon. Is it possible to use Ki as Kd in PK-Sim or do I have to convert the value somehow? Also, is there some way I can get koff from Ki without knowing kon?

Thank you in advance,
Ludwig

**Comment by PavelBal** [comment]
@UlrichSi Can you perhaps comment on that?

**Comment by UlrichSi** [comment]
PK-Sim has a static implementation of enzyme inhibition. Only Ki values are considered, no dynamics of different kon or koff values. Protein binding, on the other hand, does indeed use koff and Kd. To see the equations in detail, I would recommend to export the project simulation to MoBi and look into the kinetics within the reaction building block. Using the "List" view may be the way to go.

If you have a Ki value for a binding partner, and if the reaction mechanism is purely competitive, Kd should be equal to Ki. In a more complex mechanism, however, this may vary. In that case one cannot use the simple binding mechanism PK-Sim provides but instead needs to add the necessary reactions via MoBi.

My recommendation would be to try out Ki and see if the result in in line. The koff value, if not measured, may have to be identified by parameter identification. As a first estimate: diffusion-limited binding has a kon value of around 1E8 L/mol/s for small molecules; values between 1E7 and 1E6 L/mol/s are estimates for protein-protein interactions. For these estimates and Ki, koff can be calculated by kon/Ki.

I hope this helps a little. 

Ulrich

**Comment by LudwigvomHofe** [comment]
Hi Ulrich, 
thank you very much for your in-depth answer! I will gladly test your suggestions.

Best regards
Ludwig
