### ISSUE TITLE
Issue with fat partition coefficient parameter

### ISSUE THREAD

**Issue by calixto16** [Open-Systems-Pharmacology/Forum#256]
Hi,

I'm having an issue with editing a parameter on the individual building block. For my simulation I made a Parameter identification and as a result I ended up changing the partition coefficient (neutral phospolipids/intracellular water) and commiting it to the building block.

However, when I create a population based on that individual who has that parameter changed, it doesn't seem to stick to it, the population hasn't got that parameter anymore. Even if I create a new simulation for that same individual the parameter doesn't mantain changed, and I have to run the identificacion parameter all over again and change it from there.

Is there any way I can edit this parameter manually in the individual without going through the parameter identification, and how can I create a population based on this one?

Thank you,

Pilar

**Comment by msevestre** [comment]
Hi @calixto16 

Thanks for reaching out

> I ended up changing the partition coefficient (neutral phospolipids/intracellular water) and commiting it to the building block.

The parameter `Partition coefficient (neutral phospholipids/intracellular water)` is a simulation parameter and is not defined in a building block. More specifically, it is not defined in the `Individual` building block

That means that updating the Individual building block will have no effect whatsoever on other simulations. Note that the parameter `Partition coefficient (neutral phospholipids/intracellular water)` is also only used in the calculation method `Cellular partition coefficient method - Schmitt`. If you are using another partition coefficient method, changing the value of the parameter will have no effect.

>Is there any way I can edit this parameter manually in the individual without going through the parameter identification, and how can I create a population based on this one?

See answer above. This parameter is a simulation parameter and is not defined in the individual (or in the population) .Therefore, you will have to change it in all simulations.

Out of curiosity, are you **sure** that you need to change this parameter?

**Comment by calixto16** [comment]
Hello @msevestre, thank you for your quick response.

I am currently trying to simulate a Warfarin single oral dose. Started with previously reported parameters from a Simcyp model, but I'm having trouble with the profile PK-sim is simulating because it doesn't match with observed data. I am using the Schmitt partition coefficient model. While evaluating the model, I found that reducing the partition coefficient to fat greatly improved the fit. In the document I attach both profiles.

[Doc1.docx](https://github.com/Open-Systems-Pharmacology/Forum/files/2640782/Doc1.docx)

How would you proceed to adjust a specific blood:tissue partition coefficient inside the model?

**Comment by StephanSchaller** [comment]
Have you tried slightly changing lipophilicity or fu or using another partition coefficient method to improve the fit?

**Comment by calixto16** [comment]
Yes @StephanSchaller , I've tried changing almost every parameter from the molecule building block and nothing works. 

Also I checked with other partition coefficient methods and Schmitt is far superior than the others.

**Comment by StephanSchaller** [comment]
I actually now looked at your attached Doc1.docx.
I believe it is a permeability issue. Please note, that the small molecule model in PKSim by default (well-stirred) assumes fast permeation into tissue (interstitial space) and endothelial permeability is set to a default (high) value.

In your Simulation, go to the "Parameters" Tab and there to  "Permeability" --> "P endothelial". See what happens if you scale these values down a notch (use the scale tool in top right corner of the Tab (scale e.g. from 100 to 0.1)).

**Comment by calixto16** [comment]
I tried scaling up and down the values, nonetheless there was no appreciable change. However, the scaling of this parameter can only be done in an individual simulation and my primary concern is regarding a population. How can I repeat this approach for a population?

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
