### ISSUE TITLE
PBPK modeling for chiral drugs

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/Forum#257]
Can PBPK modeling be conducted for chiral drugs using PKSim and Mobi and how?

**Comment by PavelBal** [comment]
Well, you can simply model the enantiomeres as distinct molecules. Would this be sufficient?

**Comment by regulus92** [comment]
thanks, I'm gonna try.

**Comment by sfrechen** [comment]
In case you need an output for "total concentration" of the two (or even more) enantiomers, you need to export to MoBi your model. There you can define new observers, e.g. the sum over the enantiomers.

**Comment by msevestre** [comment]
See [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/984) also for a proposal to create dynamic observers in PK-Sim. If we get enough interest, it might be implemented
