### ISSUE TITLE
Incorporate changes in MoBi to PKSim

### ISSUE THREAD

**Issue by samitganguly** [Open-Systems-Pharmacology/Forum#258]
Hi, 

I need some help with MoBi.
I created my simulations in PKSim. Then I exported one of my adult individual simulations to MoBi and then made some changes in MoBi which helped successfully predicting the plasma concentration. 
1. Now, can I export the MoBi simulation with the changes back to PKSim? 
2. How can I apply the changes I made in MoBi to other simulations I have on PKSim? 
3. Later I want to create a population simulation as well. How can I make sure that my population simulation is incorporating the changes I made in MoBi?

Thank you for all the help that we get here in this forum! 

Regards
Samit

**Comment by StephanSchaller** [comment]
Hi Samit.

this wont be that easy.

1. & 3. Once you have changed a simulation in MoBi, you can only re-load it back to PK-Sim for population simulation (within the same species). But you can't edit the simulation beyond that in PK-Sim any more. There is an entry in the context menu for that if you right-click on the simulation in MoBi:
![image](https://user-images.githubusercontent.com/25477643/49674134-2394c180-fa71-11e8-97bd-20c80aede262.png)

2. You cannot transfer the changes to other models in PK-Sim.


An alternative way to do what you want is to go to the R/Matlab Toolbox after you made the changes in MoBi and simulate everything there. But again, getting the nice plots from the popsim in PK-Sim will be your own handiwork in the Toolbox. There are no "plot templates", yet.

**Comment by samitganguly** [comment]
Hi Stephan, 

Thank you for the information. 

It is technically not other models. I have one PKSim file with many simulations, but they are following the same model. May be the age group or ethnicity are different. 
Do you think I can modify these factors in the population simulation? 

Regards
Samit

**Comment by StephanSchaller** [comment]
Yes, this is possible. Like in any other population simulation.

**Comment by samitganguly** [comment]
In continuation with the above issue:
I wanted tubular secretion to mature similar to GFR. 
As I noted that Tubular secretion equation is lacking the Fpma part of the maturation equation, I added it to in the following format in MoBi:
Passive transports building block>"my simulation"> renal clearances-tubular secretion> kinetic
dN/dt = fu * TSspec * V_kid * C_kid_pls * Renal_aging_scaling_factor*(PMA^Hill/(TM50^Hill+PMA^Hill))

With this, I can see changes in my individual simulation as I would expect. 
But, when I send the MoBi simulation to PKSim to perform a population simulation, I am not getting the result. Population simulation not incorporating the changes I made in MoBi. 
Can you please help me sort out this?

![image](https://user-images.githubusercontent.com/42443624/49722459-cf393f80-fc32-11e8-831f-afe8295800c8.png)


Regards
Samit

**Comment by msevestre** [comment]
@samitganguly Did you manage to solve your issue?

**Comment by samitganguly** [comment]
Hi, 

Yes I was able to resolve this particular issue. But then was suggested to take an alternate route anyway. 

I would want to make a request, not sure if it would be a reasonable one though! 

For transporters we do not have a lot of ontogeny information. For transporters that are involved in renal secretion, we use the Hayton equation, which does not include Gestational age, so probably not incorporating maturation during GA. 
Would it be possible to have a function in PKSim, to incorporate the GFR like maturation for these renal transporters? I found it was helpful for my situation, when I considered renal secretion maturation similar to GFR. 
This can be among the list of Ontogeny options to select from. This way, we would also be able to incorporate some variability information similar to GFR. Which may not be true. But the variability information for these transporters in protein expression database are all over the place anyway!
Do you think it is a reasonable idea and request?

Regards
Samit

**Comment by Aedginto** [comment]
Hi Samit,
Tubular secretion occurs via transporters. There are various transporters that contribute to tubular secretion and sometimes you will know which one is important for your compound and sometimes you won't. In order to incorporate a kidney transporter, you would do this is in the same way as you would add a hepatic transporter in the Individual building block. If you know which transporter is important, you can add the relative expressions in organs via the protein expression database attached to PK-Sim.  In order to include ontogeny to the transporter, you can add it as a table; there will be linear interpolation between your data points. This is all done in the Individual building block. To capture variability, when creating the population, add variability to the reference concentration of the transporter. Variability measures come from literature of interindividual protein concentrations. 
take care,
Andrea
