### ISSUE TITLE
Empty PK-Sim/MoBi user interface

### ISSUE THREAD

**Issue by JGWojtyniak** [Open-Systems-Pharmacology/Forum#259]
Dear all, 

I have the following issue: While working with MoBi I had an unexpected crash (the file has simply closed itself without a warning). Since then, every MoBi file I open has an empty user interface. However, if I open the file on another computer everything is right at its place. A co-worker of me has the same issue with PK-Sim. 

I darkly remember that I've had the same problem one or two years ago and it's somehow related to the Microsoft Visual C++ 2015 redistributable. However, neither a fresh installation of the redistributable nor of the osps solve it. Does anybody has an idea how to deal with this issue.

Thank you in advance and with best regards,
Jan-Georg Wojtyniak

**Comment by msevestre** [comment]
@JGWojtyniak : Presuming that 'Empty user interface' means that the app is starting, you see the frame with the ribbons, but no views inside correct?

In that case, this looks like a corrupted layout problem. It happens unfortunately very rarely and we never managed to reproduce it (probably a mix of docking station usage and multiple screen, flavors of windows etc..)

The good news is that it's easy to fix:

1/For PK-Sim, check the answer [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/518)

2/ For MoBi, check the answer [here](https://github.com/Open-Systems-Pharmacology/MoBi/issues/322)

**Comment by JGWojtyniak** [comment]
@msevestre : Sorry for the a little bit vague error description.  However, you guessed right. And your solution works - thank you very much! You safed my day! :)

Best,
Jan

**Comment by msevestre** [comment]
great news. Cheers
