### ISSUE TITLE
Metabolic Enzymes - Values for relative expression 

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#26]
Values for relative expression - I have downloaded and was able to import the enzyme list,  I am not able to see the values for relative expression.
[relative.docx](https://github.com/Open-Systems-Pharmacology/Forum/files/1071199/relative.docx)

**Comment by msevestre** [comment]
@moulirc What do you mean with `see` the value for the relative expression?
I can see on your screenshot a value of `0.17` for `Kidney` and of `1` for `Liver`.
Please explain the problem you are facing as well as the expected outcome.

Thanks

**Comment by moulirc** [comment]
I have copied those values from the template provided. I have attached the picture when I am trying to create individual population.

Hope i have explained ...
thanks

![image](https://user-images.githubusercontent.com/27323536/27083696-ba0e0116-508c-11e7-9e70-36d21cd884ce.png)

**Comment by msevestre** [comment]
@moulirc How do you create the enzyme? Are you using the gene expression database?
![image](https://user-images.githubusercontent.com/1041237/27084554-519dac3e-501a-11e7-8b89-7f8aa2f004b0.png)
If it is disable, you need to select the download the database (see setup.open-systems-pharmacology.org) and update the path to the gene expression DB in your options

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/Forum/issues/8

**Comment by moulirc** [comment]
Thanks for your comments and it worked.
kind regards
mouli
