### ISSUE TITLE
How to use the InstallationValidator

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#261]
Dear all,

I would like to validate the local installation of PK-Sim on my computer. I have seen that there is the InstallationValidator tool, which from my understanding accomplishes exactly that. Could you point me in the direction of some instruction which could be used to set up the tool? I did not find anything on the forum.

Thank you very much in advance for your help!

Donato

**Comment by teutonicod** [comment]
I found it, I just include the answer in case somebody else will look for this in the future.

The validation software is already installed, and it is available in the installation folder where PK-Sim is installed, for instance C:\Program Files\Open Systems Pharmacology.

**Comment by Yuri05** [comment]
Also available via the _Open Systems Pharmacology_ group in Windows start menu ;)

**Comment by teutonicod** [comment]
Yes, sorry, I did not see it there! Thanks
