### ISSUE TITLE
How to add salivary gland compartment to mouse species

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/Forum#263]
Hello,

I am trying to build a mouse PBPK model and would like to predict saliva concentrations of the drug in the mouse. Could any please advise me on how to add salivary gland/saliva component in mouse species for PK-Sim. I noticed that humans already have salivary gland/saliva in built.

Thanks,
Kash

**Comment by AndreDlm** [comment]
Dear Kash,

adding an additional compartment to a species is possible in MoBi, but not in PK-Sim.
You would have to export your simulation to MoBi and add the compartment in the spatial structure; thereafter you can reimport the model pkml file in PK-Sim via the Import/Export ribbon tab.

The supplementary information of the following tutorial article provides a detailed guide on how to add a compartment to a compartmental model: [Applied Concepts in PBPK Modeling: How to Extend an Open Systems Pharmacology Model to the Special Population of Pregnant Women](https://ascpt.onlinelibrary.wiley.com/doi/full/10.1002/psp4.12300)
Although the added compartment there is a human tissue compartment, many points will be similar for a salivary gland compartment in rodents and the guide should be of help. 
Be aware that the guide is only useful if you want to simulate small molecule drugs (no large molecules, e.g. proteins).

Good luck!

Best regards
André

**Comment by yvkashyap** [comment]
Hi Andre,

Thanks for your detailed reply. I will work and it and will get back to you
if there are any questions.

Regards,
Kash
