### ISSUE TITLE
over prediction of AUC

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#27]
Hi,

Using my dissolution data I am trying to predict the saliva concentration of the drug.  On comparison with the observed data, the model was over-predicting AUC. 
To overcome this I added the following parameter under "Identification Parameters" Vmax and Km. The predictions were better and how can I go about explaining this. 

Also how I can run a simulation including the estimated parameters and get the final model.

Also please let me know where I can download the user manual.

Thanks and kind regards

Before adding parameters

![image](https://user-images.githubusercontent.com/27323536/27131708-350f6194-514f-11e7-8c0c-38f6157475af.png)

After adding parameters
![image](https://user-images.githubusercontent.com/27323536/27131736-4db5794a-514f-11e7-8591-563ae52ab74a.png)

**Comment by TheiBa** [comment]
@moulirc: you may need to explain what Km and Vmax are in your model - do they belong to a metabolic enzyme or transporter? And what was your administration route, IV admin and sampling well described? 

User manual PDF is in the installation folder but also accessible within the software by menu or F1 button.

**Comment by moulirc** [comment]
Hi,
Thanks for your message and the manual was useful.
In regards to the Vmax and Km - they belong to a metabolic enzyme (think I am right - please correct if I am wrong - picture attached).

Also one final question - when I am exporting the con - time profile to Excel, the values are expressed in [µmol/l], in spite of changing the values.
Thanks in advace 
![image](https://user-images.githubusercontent.com/27323536/27280777-89772574-552c-11e7-8e1b-aba911212490.png)

**Comment by msevestre** [comment]
@moulirc Please create one thread per question so that other people can search and use the answer. Thanks for your understanding

**Comment by TheiBa** [comment]
Yes, it looks like your/the model contains a CYP clearance. Fitting clearance should improve AUC - if that is mechanistic explanation you will have to evaluate: do you describe data after IV and PO admin with the same clearance parameters? If not, think about extra clearance or release effects.
