### ISSUE TITLE
How to convert metabolic parameters from literature?

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/Forum#271]
Hello, I'm a beginner to PBPK and I have a question. In PKSim, some drug metabolic and transport processes under Michaelis-Menten type use units of volume such as μmol/l/min for Vmax, however, I found that mg-1 protein are more frequently used in references. For example, Vmax value of metformin transport by hOCT2-expressing HEK293 cells was 11.9 ± 1.5 nmol mg protein−1 min−1 (Naoko Kimura 2005). So how should I convert such value for PKSim modelling?

**Comment by StephanSchaller** [comment]
Just select one of the lower entries:

![image](https://user-images.githubusercontent.com/25477643/51300131-25b44d80-1a2b-11e9-9792-2b861c2df00d.png)

**Comment by regulus92** [comment]
MW of hOCT2 is 62.59 kDa, 1 mg protein = 10e-3/62590*10e9=15.98 pmol protein, so Vmax 11.9 noml/min/mg = 0.745 nmol/min/pmol. Is this right ?
