### ISSUE TITLE
FcRn Kd variability in population simulation

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#272]
Dear all,

I am doing a population simulation in PK-Sim and I would like to include in the simulation the uncertainty on the Kd to FcRn in the endosomal space. Is there a way to do it in the population simulation in PK-Sim without using R or Matlab?

Thanks a lot in advance for your help.

Donato

**Comment by msevestre** [comment]
Hi @teutonicod ,

1. if the parameter can be defined as user defined variability, then you can simply update it here.
1. If not, you can export the simulation to Mobi, set the parameter to Can Be Varied In Population to true, import back to PKSim and add a user defined variability there.

@Yuri05 Maybe this parameter should be variable in a population by default? 

Hope that helps,
Michael

**Comment by teutonicod** [comment]
Hi Michael,

Thanks a lot for this work around! Indeed this parameter is not available in the user defined variability, but I think that it makes sense to have it there, since it is a paramater which is often estimated, and in this case one could incude the uncertanty in the simulation.

Donato

**Comment by StephanSchaller** [comment]
@teutonicod @msevestre @Yuri05 

We had this discussion before. We had proposed the following update for 7.5 : https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1041

**Comment by Yuri05** [comment]
Clsoing. @teutonicod Please reopen if you have any further questions on this topic.
