### ISSUE TITLE
Differential Equations check

### ISSUE THREAD

**Issue by Mutaz94** [Open-Systems-Pharmacology/Forum#274]
hello. 
How can I check the differential equations implemented in my model (see them)? @msevestre

**Comment by msevestre** [comment]
@Mutaz94 

PK-Sim and MoBi support an export of the Model Structure of a simulation to a file
Please see the documentation [here](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/importing-exporting-project-data-models#exporting-simulation-structures-to-file)

Alternatively, you can open MoBi and navigate through the structure dynamically

Last, you can export the ODE system to Matlab. The menu entry is called `Export Simulation as Matlab® Differential Equations` See the section in the documentation [here](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/importing-exporting-project-data-models#exporting-simulation-structures-to-file)

**Comment by msevestre** [comment]
@Mutaz94 Let us know if you need more help.

**Comment by Mutaz94** [comment]
Thank you so much @msevestre

**Comment by Radwa100** [comment]
Hi msevestre, 
I try to find the ODE through "Export Simulation as Matlab® Differential Equations". I can not find this in the dropdown menu. 
Can you please help with that or is there any other way to find the ODEs?
Thank you, 
Radwa
