### ISSUE TITLE
population template database for PK-Sim version 7.4

### ISSUE THREAD

**Issue by rhishi24niper** [Open-Systems-Pharmacology/Forum#277]
Hi,

I am studing DDI with PK-Sim using 7.4 version, how do I download population template database?

Thank you

**Comment by msevestre** [comment]
Hi there,

What database are you talking about?

**Comment by rhishi24niper** [comment]
When I right click on "Population" building blocks and select "Load from Template" it gives "No template population availabe in the template database" see attached screenshot 
[Pop template database.docx](https://github.com/Open-Systems-Pharmacology/Forum/files/2799620/Pop.template.database.docx)

**Comment by msevestre** [comment]
I don't think that there are any predefined population template with the setup.

If you save your own however, you will be able to load them later on.

Does it make sense?

**Comment by rhishi24niper** [comment]
That make sense. Thanks
