### ISSUE TITLE
DDI, although no interaction parameters are configured. 

### ISSUE THREAD

**Issue by NinaHanke** [Open-Systems-Pharmacology/Forum#278]
Dear all, 
I have a problem with one of my DDI simulations. 
It is a DDI between my new compound and rifampicin, and there should be no interaction. However, the plasma and urine concentration-time curves change, if I add rifampicin to my simulation: 
 
![grafik](https://user-images.githubusercontent.com/36850897/51823889-f7632780-22e0-11e9-82d4-3f68fde638dd.png)

The PK mechanisms are totally different for both compounds, except they both have a GFR fraction of 1 and intestinal permeability. It is a single dose administration of rifampicin, and both drugs are given together at the same time. 
The interaction parameters of rifampicin do not affect the metabolic enzymes and transporters of my compound. Even if I remove the interactions in the configuration of the simulation, the problem stays the same. Only if I take out the rifampicin administration protocol, the profile looks as my control again. 

Why? How can I fix this? 
Competition for glomerular filtration (does not make too much sense, as fe to urine goes down, but plasma concentrations go down as well)? Competition for intestinal absorption?  

If anyone has an idea, please help. 
Thank you, 
Nina

**Comment by StephanSchaller** [comment]
If you have not explicitly defined any interaction, there is no interaction.
But then why do you call it DDI if there is no interaction. Just simulating two compounds within one simulation will not cause interactions to happen if not specified.

Have you not specified any DDI, or did you specify sth. and deactivated it?
Have you used template individuals and compounds?

Otherwise try to export your simulation with Rif to MoBi and change the solver settings to a higher accuracy and check if the curves change.

Hope this helps,
Stephan

**Comment by Yuri05** [comment]
As far as I understand both compounds are applied orally?
Then applying `drug2 `(Rifampicin in your case?) might change absorption of `drug1`.
E.g. you usually add some amount of water to an oral application, which changes intestinal volumes and thus also intestinal concentrations of `drug1`.

You could temporarily set amount of water for `drug2 `to zero and check if you still observe differences in plasma concentration of `drug1`.

**Comment by NinaHanke** [comment]
Thank you very much! 

"Set amount of water for drug2 to zero and check if you still observe differences in plasma concentration of drug1." --> Perfekt! This really was the problem. Thx! 

"Just simulating two compounds within one simulation will not cause interactions to happen if not specified." --> Yes it does. Just two compound, no interactions configured.

**Comment by StephanSchaller** [comment]
Great catch, Juri. But technically it is not the drugs interacting ;-)
