### ISSUE TITLE
New OSP tutorial video series released!

### ISSUE THREAD

**Issue by JGWojtyniak** [Open-Systems-Pharmacology/Forum#279]
Dear OSP-Community,

on behalf of the PBPK Tutorial Team at Saarland University we are happy to announce the first part of our OSP-Online tutorial series “Getting started with PK-Sim”. The series was developed by the Clinical Pharmacy group at Saarland University and currently consists of 8 videos. The different videos take less than 10 minutes to watch and cover the PK-Sim basics from “How to install PK-Sim?”, over the generation of the different PK-Sim building blocks, up to “How to set up a simulation in PK-Sim?”. Further videos will follow soon, covering PBPK model development and drug-drug interaction modeling. 
To keep up-to-date check out our Youtube Channel: 
[https://www.youtube.com/channel/UCrjhCoM0g5C5wtQQ4JQYpJg](https://www.youtube.com/channel/UCrjhCoM0g5C5wtQQ4JQYpJg)
Or visit us on our University Webpage:
[www.tutorials.clinicalpharmacy.me](https://www.uni-saarland.de/lehrstuhl/pharm-lehr/tutorials/gettingstartedpksim.html)

Many thanks and with best regards,
Jan-Georg Wojtyniak and the PBPK Tutorial Team:
@HannahBri
@Fatima-Marok
@LMFuhr
@NinaHanke
@LudwigvomHofe
@DeniTue
@thorstenlehr

**Comment by AndreDlm** [comment]
Wonderful :)

**Comment by msevestre** [comment]
@JGWojtyniak and team. Very cool! Well done.

**Comment by jzq90** [comment]
Thanks very much
