### ISSUE TITLE
Pre-clinical species gene expression data base

### ISSUE THREAD

**Issue by drfreedman** [Open-Systems-Pharmacology/Forum#28]
The ADC tutorial shows mouse protein expression data loaded via data base query.  However, only the Human GENEDB.mdb database appears to be currently available.

Please point us to the requisite pre-clinical gene expression data base. 

Thank-you in advance,

Immanuel Freedman, Ph.D SMIEEE
AAPS Pharmaco-Imaging Focus Group Past Chair

**Comment by StephanSchaller** [comment]
AFAIK, the Mouse GENEDB.mdb is not open-source yet. Will be in due time.

**Comment by msevestre** [comment]
We will make announcement if and when the GeneDB is available

**Comment by DamoiseauxD** [comment]
> We will make announcement if and when the GeneDB is available

I wondered if the Mouse GeneDB is open-source yet? I couldn't find an announcement.

Thank you in advance
