### ISSUE TITLE
No Ionisable Center In Molecule

### ISSUE THREAD

**Issue by dineshbcp** [Open-Systems-Pharmacology/Forum#282]
If molecules don't have ionizable center and no pka. In this case which value to be entered in pk-sim, Or we have to put zero in acid , base and neutral table.

**Comment by msevestre** [comment]
If you don't enter anything, the molecule will be considered neutral by the system. Does it answer your question?

**Comment by dineshbcp** [comment]
Yes sir. Thank you!!
