### ISSUE TITLE
refering to a molecule start value

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/Forum#288]
Dear all,
I need a bit instruction how I refer to start values.  I would like to enter a formula in the reaction tab of Mobi, in which I would like to refer back to it's start value (at time zero), such as dN/dt =...*(N_0-N), or, when defining Kin in an indirect response model. E.g. I define 2 umol of a supermolecule in the intercellular compartment of the brain in the molecule start value tab. Where do I find this value if I want to refer to it in the reaction formula? Or would I need to define the start amount as formula with a set baseline parameter? If so where do I find it then? Do I have to redefine the formula in the formula tab of the reaction tab again?  Many thanks for a some hints.
Best regards,
Rudiger

**Comment by Yuri05** [comment]
>Where do I find this value if I want to refer to it in the reaction formula? 

You cannot. It's not stored in the model as standalone entity.

>Or would I need to define the start amount as formula with a set baseline parameter?

Yes, this is the way to go.

>If so where do I find it then?

Check the example attached. 
[Example_StartConcentration.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/2893799/Example_StartConcentration.zip)
* In the spatial structure there is a parameter `Start concentration of free FcRn (endosome)` (screen 1)
* In the molecule start values, start amount of **EndogenousIgg/Endosome/FcRN** is defined by a formula (screens 2 and 3)
Now you could access the parameter  `Start concentration of free FcRn (endosome)`  in any equation.
(if you need to define a start _amount_ and not start _concentration_ - same procedure)
![grafik](https://user-images.githubusercontent.com/25061876/53241214-4febd180-36a1-11e9-8442-ac9ac6a88d95.png)
![grafik](https://user-images.githubusercontent.com/25061876/53241251-701b9080-36a1-11e9-92a9-7f32709f2e59.png)
![grafik](https://user-images.githubusercontent.com/25061876/53241282-80cc0680-36a1-11e9-8cd5-0880fcd0c6c1.png)

**Comment by RKasp** [comment]
Thank you for the quick response, much appreciated!
