### ISSUE TITLE
Problems with Visual Studio

### ISSUE THREAD

**Issue by patriciamartinsconde** [Open-Systems-Pharmacology/Forum#29]
Dear all,
I am currently trying to compile the code for MoBi.
I started by following the instructions given in
https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/GETTING_STARTED.md.
Then I tried to compile MoBi, and I got 308 errors with files that are missing.
Then I checked for other new folders, and I tried to compile the InstallationValidator, and again I got one error that the type or namespace 'DevExpress' does not exist in the namespace 'OSPSuite.DataBinding'.
I then downloaded the folder OSPSuite.DataBinding.DevExpress and added it to the packages folder of the InstallationValidator and it still does not recognize it.
Could you help me please?
Best,
Patricia

**Comment by msevestre** [comment]
@patriciamartinsconde 

Which VS version are you using and which branch are you trying to compile?
Also what do you mean with
> downloaded the folder OSPSuite.DataBinding.DevExpress

All dependencies are resolved via nuget packages. So you need to restore all packages before attempting compilation. All packages are available from nuget.org so you should be able to compile the package without any problem. You should NEVER have to copy packages by hand :)

My suggestion is to try with a smaller project first until you get it right. For example, try compiling [OSPSuite.Core](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core). Use the master branch (corresponds to the 7.1 release) if you are using VS2015

**Comment by patriciamartinsconde** [comment]
Dear msevestre,
I finally managed to do it.
Thank you.
Best,
Patricia

**Comment by msevestre** [comment]
This is great. Would you mind maybe enhancing the getting started with what was missing for you to get to get to get going?
