### ISSUE TITLE
Saliva/Plasma Partition coefficient

### ISSUE THREAD

**Issue by AlejandraSchiavo** [Open-Systems-Pharmacology/Forum#290]
Dear all, 

I am trying to simulate salivary concentrations after an oral administration in PK-Sim for a drug with acid characteristics (pKa = 4.8).
PK-Sim references a presentation of Willi Cawello on original value of salivary parameters.
Taking this into account, R (saliva/plasma) depends on saliva and plasma pH, fu (plasma) and fu (saliva).
The base PK-Sim saliva pH is equal to plasma pH, and this drug is not bound to saliva proteins, therefore R=fu (plasma). However, when I change saliva pH, R remains equal to fu (plasma).
Is it possible to change R in PK-Sim so it can follow the equation proposed by Cawello? 

Thanks in advance for your reply, 
Best regards.

Alejandra

**Comment by msevestre** [comment]
Did you figure this out?

**Comment by AlejandraSchiavo** [comment]
Hi, 
No, I could not do this because I do not know how to do it. 
I have an IV model, that simulates correct plasma concentrations after an IV infusion. But simulated salivary concentrations result higher than in vivo salivary concentrations. I thought I could improve that by changes in salivary pH, but I did a Sensitivity analysis with salivary pH and the result showed PK do not change with changes in salivary pH did not change PK parameters.  My question is how to optimize salivary concentration in PK-Sim, if it is possible.
![image](https://user-images.githubusercontent.com/41156451/66911341-b46bf000-efe6-11e9-8d45-5ee9db990c8b.png)
Plasma Concentrations
![image](https://user-images.githubusercontent.com/41156451/66911672-62779a00-efe7-11e9-906a-5d2df76b09ce.png)
Salivary Concentrations 

Thanks, 

Alejandra

**Comment by HenrikCordes** [comment]
Dear @AlejandraSchiavo ,

 PK-Sim calculates the saliva concentration as follows:

Transport: PassiveDiffusionPlsToSaliva
	Source: vpa|Organism|Saliva|SalivaGland|VPA
	Target: vpa|Organism|Saliva|Saliva|VPA
	Formula: fu * (C_pls_art - C_slv / K_slv_pls) * Q_slv
		Q_slv: vpa|Organism|Saliva|Saliva flow rate(0.001 [l/min])
		C_pls_art: vpa|Organism|ArterialBlood|Plasma|VPA|Concentration(0 [µmol/l])
		C_slv: vpa|Organism|Saliva|Saliva|VPA|Concentration(0 [µmol/l])
		fu: vpa|VPA|Fraction unbound (plasma)(0.055)
		K_slv_pls: vpa|Neighborhoods|Saliva_slv_Saliva_slv|VPA|Partition coefficient (intracellular/plasma)(0.055)

Thus, the saliva concentration results from passive diffusion only. In your simulation you could try to improve the model fit modifying the saliva VPA Partition coefficient:

![image](https://user-images.githubusercontent.com/4817133/68533544-581c9780-032a-11ea-9e63-e641bab1fcb5.png)

Kind regards,
Henrik

**Comment by AlejandraSchiavo** [comment]
Hello Henrik,

Your way is easier than the use of Mo-Bi!
Thanks for your help

Regards, 
Alejandra
