### ISSUE TITLE
Fluvoxamine and theophylline PBPK models

### ISSUE THREAD

**Issue by HannahBri** [Open-Systems-Pharmacology/Forum#292]
Dear all,

We have been working on models for DDI prediction, building a small network of interacting CYP1A2 perpetrator and victim drugs. Two whole-body PBPK models of fluvoxamine and theophylline were carefully developed and then evaluated by prediction of clinical DDI studies.

The corresponding manuscript, including comprehensive documentation, has been published online in CPT: PSP and the models as well as PK-Sim projects presenting the predicted DDI studies have been uploaded as Open Systems Pharmacology repositories to GitHub.

Related publication:
Britz H, Hanke N, Volz AK, Spigset O, Schwab M, Eissing T, Wendl T, Frechen S, Lehr T. 
[PBPK models for CYP1A2 DDI prediction: a modelling network of fluvoxamine, theophylline, caffeine, rifampicin and midazolam.](https://ascpt.onlinelibrary.wiley.com/doi/abs/10.1002/psp4.12397) CPT Pharmacometrics Syst Pharmacol 2019.

All models can be found [here](https://github.com/Open-Systems-Pharmacology?utf8=%E2%9C%93&q=%22osp-model%22+%22ddi%22).

Best regards,
Hannah

**Comment by sfrechen** [comment]
Great work, Hannah! Thank you for sharing!

**Comment by regulus92** [comment]
Something learned. Thank you for sharing!
