### ISSUE TITLE
Total error calculation formula in parameter identification

### ISSUE THREAD

**Issue by mmalsmadi** [Open-Systems-Pharmacology/Forum#293]
Hello,

I need to know how is the "total error" is calculated with the parameter identification inside PK-Sim
what is the formula used for its calculation?

many thanks

**Comment by PavelBal** [comment]
Please see Section ["Mapping Simulation Outputs to Observed Data - Scaling"](https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification#mapping-simulation-outputs-to-observed-data). The total error is the sum of single residual errors (@msevestre correct me if I'm wrong).

**Comment by StephanSchaller** [comment]
It is the sum of squares.

@msevestre I still have to update the documentation ;-)

**Comment by StephanSchaller** [comment]
See discussion [here](https://github.com/Open-Systems-Pharmacology/docs/issues/74#issuecomment-465282811)

**Comment by msevestre** [comment]
@mmalsmadi This is incorrect. 

Total error = Square of ( Sum of all residual ^2 for all outputs)

Whether log is used or not depend on the output and the scaling selected. Also Weight is also part of the equation (global weight for the output and single weight for each data point). Those weights are one by default so if you did not change them, you can forget about them

**Comment by msevestre** [comment]
Closing for now. Let us know if you need more help.
