### ISSUE TITLE
referring to #260, individual dosing

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/Forum#297]
Dear Stephan, Michael and all,

this is referring to closed issue #260 , I wasn't sure if re opening works by dropping a comment.

I would have a few more questions to this topic. I actually do need to run a parameter identification on a data set of 35 different doses, each dose has about 5-10 DVs. Due to the model set up, I run these in MoBi generating a file of about 90 MB, which is very difficult/slow to work with. All doses are here computed as separate simulations.

Is there a smart way around it in MoBi, unless running a parameter identification in R, which I may check into next?

Many thanks for your feedback.

Best regards,

Rudiger

**Comment by msevestre** [comment]
I am closing this one and have reopened the other one
