### ISSUE TITLE
Ethnicity issue in the population simulation

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/Forum#299]
Hello, everyone. I have a question. 
Vonlunteers enrolled in many clinical PK studies represent not only one race, but a population is only created based on a single individual in PKSim. I think this may impact results, especially when multi racial subjects are included.

**Comment by msevestre** [comment]
@regulus92 Yes it's possible. You will need to create each simulation separately export them as csv and import them using the "Import Population From File"
![image](https://user-images.githubusercontent.com/1041237/55280802-dc249080-5300-11e9-9f9a-66202fcce135.png)


Alternatively, you can run multiple simulations independently and compare them using the Compare Population Simulation feature

![image](https://user-images.githubusercontent.com/1041237/55280813-070ee480-5301-11e9-9a58-caa7ca649536.png)

Hope that helps,

Michael

**Comment by msevestre** [comment]
@regulus92 Closing for now. Please let us know if you need more info
