### ISSUE TITLE
Dissolution data

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#3]
I would like to know if I can use dissolution data to establish a pbpk model.
Is there any references available.

thanks in advance
mouli

**Comment by TheiBa** [comment]
PK-Sim offers predefined options to model drug dissolution. You can either fit a "simple" function to your data including Weibull, Lint80, zero- and first order, table read-in the "raw" data, or semi-mechanistically model particle dissolution. The best choice depends on data you have and the task you are up to. Beyond the predefined options, you can, of course, implement alternative solutions in MoBi. The technical steps are described in the PK-Sim (or MoBi) manual. The most relevant references might be:
https://www.ncbi.nlm.nih.gov/pubmed/22686345
https://www.ncbi.nlm.nih.gov/pubmed/20554023

Cheers,
Thomas
