### ISSUE TITLE
Propose survey of timeline  for  PKSim/MoBi projects

### ISSUE THREAD

**Issue by drfreedman** [Open-Systems-Pharmacology/Forum#30]
Colleagues,

Since Bayer and its user group have completed many projects with PKSim & MoBi, for planning purposes it may help the entire OSP community to understand the timeline in OSP model development for small molecules and biologics, from gathering information to model development, model refinement and report writing.

If Bayer have ballpark numbers to hand, please post them. Alternatively, I suggest an anonymous survey. 

Regards,

Immanuel Freedman, Ph.D SMIEEE

**Comment by TheiBa** [comment]
I am not sure, if I fully understand the questions. But if it refers to efforts needed for "OSP model development", I believe there is not generic answer. Even if I restrict it to PBPK models, this highly depends on the complexity of the PK of the molecule as well as the mechanistic understanding thereof, as well as the application purpose. A first model is usually quickly done. Investigating origins for potential mismatches can take some time. Then you may want to apply it in a translational setting and beyond predictions, investigate the confidence in these. Report slides for discussion of exploratory results are also less work than reports meant for e.g. regulatory communication ...

**Comment by msevestre** [comment]
@drfreedman I am going to close this issue. Please feel free to reopen it if you want to add more details to the discussion.
