### ISSUE TITLE
What transformation does PK-Sim apply to the Residuals vs. Time in the Parameter Identification tool?

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/Forum#303]
Looking to export the Residuals vs. Time plot to excel and reverse the transformation to get the residuals back in (what I assume will be) uM concentration as default.

**Comment by msevestre** [comment]
@prvmalik What do you mean with `transformation`?

**Comment by msevestre** [comment]
Just in case: This is [how](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ResidualCalculator.cs#L70) the residuals are calculated

More specifically [this line](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ResidualCalculator.cs#L96)

The only transformation that I see is the LOG transformation if your scaling was set to log. Also depending on your LLOQ method of choice, some residuals may be set to 0 if the simulated or observed data values are < LLOQ

Let me know if this is what you need or if I missed the point completely:)

**Comment by prvmalik** [comment]
It looks like they are studentized or normalized as they are marked as dimensionless and have distribution typically between [-2 2]. There are a variety of ways of doing these transformations (especially when predictions across multiple datasets are evaluated) and I'm just wondering which one is used.

**Comment by msevestre** [comment]
>It looks like they are studentized or normalized as they are marked as dimensionless

We have not implemented any normalization whatsoever.
 
Dimensionless is probably because of the scaling that I was talking about. If your scaling is log, then your dimension would be in fact dimensionless. Also if you are optimizing fractions, the dimension won't be uM but dimensionless as well

So in short, what is exported to excel is the true value of the residuals as PKSim or MoBi calculate them.

**Comment by prvmalik** [comment]
Hi Michael, got it working by switching the scaling to linear as you suggested and re-running the evaluation. Thanks!
