### ISSUE TITLE
Create variability in Plasma Clearance

### ISSUE THREAD

**Issue by RobinPharma** [Open-Systems-Pharmacology/Forum#304]
Hello OSP Forum !

I am trying to create a population of mice. I don't have any metabolizing enzymes information on my drug so I can't create a variability in term of these. However I would need to create a variability of the Total Hepatic Clearance -> "Plasma clearance" 
I don't find that option in the population building block, since this clearance is usually set up in the compound block. 
Is there a way to configure such a variability or is it only possible to create variability on physio and anatomical sections ?

Thank you !

**Comment by HenrikCordes** [comment]
Dear @RobinPharma RobinPharma,

you could define an arbitrary enzyme only expressed in the liver in combination with a first order clearance process. (see picture)
![image](https://user-images.githubusercontent.com/4817133/55739806-1a6d2e80-5a2a-11e9-8694-c447fb4537d6.png)

Now in your population you can alter the expression level of the hepatic enzyme and create your clearance variability.

Does this help you?

Kind regards,
Henrik

**Comment by msevestre** [comment]
@RobinPharma I would add to the excellent answer from @HenrikCordes that you can use the value `Specific Clearance` value calculated by the Plasma clearance as an initial value

![image](https://user-images.githubusercontent.com/1041237/55740331-dada1e80-59f8-11e9-9eec-436fa7efe6d8.png)

**Comment by RobinPharma** [comment]
Thank you veeeery much for your quick answer @HenrikCordes and for the precision @msevestre 
I haven't thought of doing it that way ! Seems to work just fine.
