### ISSUE TITLE
Development of User Defined Administration Protocol Template using Excel

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/Forum#305]
Hello,
I am trying to perform simulations using 26 different dosing regimens and each regimen has multiple administrations with different doses at each time point. Could you please let me know if I can upload all regimens in an excel format to create an Administration Protocol template to avoid manually entering all 26 dosing regimen.
Thanks,
Kash

**Comment by teutonicod** [comment]
Hi @msevestre,  what are the implication of starting PK-Sim with the --dev flag? What does it change?

Thanks a lot!

Donato

**Comment by msevestre** [comment]
@teutonicod Starting with the `--dev` flag simply adds a bunch of extra features (that we use mostly to debug issues that we have, or generate template files etc..). It does not change the behaviour of the application. Instead, it adds a bunch of extra options, specifically on context menus (All suffixed with the (Developer Only) text)

**Comment by yvkashyap** [comment]
Hi Michael,

Thank you so much for answering my question within such a short time. I was able to convert my Admin Protocols in Excel to .json files and got them imported into PKSim and run simulations accordingly.

Sincerely,
Kash
