### ISSUE TITLE
Rat PBPK model

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#310]
Hello All,
Iam trying to build PBPK model in rats for a NCE administered by IV Infusion for 1hour. I have physicochemical parameters, invitro data and invivo data.
My questions are

1.  In the individual building block apart from providing the biometrics , do we also have to provide enzyme expression (CYP3A4 etc)

2. I have converted CLint measured in hepatocytes through IVIVE and provided the Clint values for CYP3A4 enzyme
3. I have also provided t1/2 from hepatocytes data
4. Compound has liability for renal clearance so accounted for that by giving Renal process

Inspite of that fitting looks something like the attached figure.
Any suggestions will be of great values as to what i have to keep in mind

Regards
Harish 

![fitting](https://user-images.githubusercontent.com/49284633/56281193-a289bd00-6129-11e9-9723-9e3948d2bff0.jpg)

**Comment by tobiasK2001** [comment]
Dear Harish,
her some thoughts in a rush to your questions. Hope I understood you correct.

1) you have to add the CYP3A4 enzyme to your individual BB. Easiest way would be to use the PK-Sim expression database. However there is only one for human available. Nevertheless you can yous this as a starting point for rats. It will give you the CYP3A4 abundance for humans. You can use rat values as well if you have. For details how to use it check out here: https://github.com/Open-Systems-Pharmacology/Forum/issues/279

2) You can input this Clint values in the compound BB, ADME properties Tab. You have to create a metabolic process for your desired enzymes. Again for details check the videos.

3) your t1/2 in hepatocytes can be inputted in the compound BB as total hepatic clearance. Select input from half live in hepatocytes. Be sure to provide the correct number of hepatocytes you used in your assay.
4) in the compound BB,  ADME properties Tab you can also input renal clearance e.g. as renal plasma clearance or active secretion process. Of course this can be fitted additional to a metabolic clearance as well.

B.tw.: your fit seems to describe the distribution of your compound very well. There seem to be some clearance process missing to catch the points after 2 hours. I think you are almost there.

Hope this might help you. Keep up the good work.

Best, Tobias

**Comment by harishkaushikbugworks** [comment]
Thanks Tobias,

[bw977 rat 30mpk PBPK_Clearance problem.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3165124/bw977.rat.30mpk.PBPK_Clearance.problem.zip)
Further if any of you can help it would of great help, i have attached the PK Sim project file

Any suggestion it will be great

Regards
Harish

**Comment by tobiasK2001** [comment]
Dear Harish,

thanks for providing the PK-sim file. I had a look into it and here are my thoughts:

The Individual "SD rats" has no CYP expression in liver or other organs. Relative Expression is 0 everywhere.
Thats why I corrected it by using RT-PCR expression from PK-sim expression data base. See "SD rat_corrected in the attached projectfile.
Than I was wondering why acharge dependent permeability used and if is RR distribution really optimal?
To investigate that, I did Parameter Identification (PI) 1a. Results show that PT , Berezh and RR distribution coefficients lead to similar results. That can be explained as the compound is amphoter, i.e. at physiological Ph the net charge is zero = molecule behaves as a neutral. For neutral compounds RR model is often similar to a Poulein Theil or Berezskovskiy distribution model. A charge dependent permeability seems not justified here.
Further the Correlation matrix shows: clearance is not identifiable as 95% CI is larger than optimized parameter. The measured start parameter for lipophilicity is in range of 95% CI. This is a hint that the limited in vivo Data allow no differentiation here.  We have only mean values. Individual data or data with SD range could help here. Tries  with PI1b and c suggests to keep the input from your measured data, but use a compound without charge dependent Permeability.

Than I investigated if renal clearance is necessary to describe the data in three scenarios: "S1 SD rat CYP3A4 and GFR_not charge dependend" : base  bodel with LAB Cyp3a4 metabolism in SD rats_corrected with BWC_not charge dependent.
![image](https://user-images.githubusercontent.com/25585248/57930515-71caae00-78b6-11e9-9250-a964f810d67e.png)
This looks pretty good already. please note the fraction metabolised in liver and kidney and fraction excreted to urine. If you have measured counterparts in vivo you can use these for model qualification.

S2 SD rat t1-2 hepatocytes and GFR_not charge dependend: base  bodel with total hepatic CL lab and GFR  in SD rats_corrected with BWC_not charge dependent.
![image](https://user-images.githubusercontent.com/25585248/57930618-b8200d00-78b6-11e9-9377-4270b9837a11.png)
This looks not so bad, but could be a bit more CL. Please note the higher simulated 
fraction renally excreted.

S3 SD rat t1-2 hepatocytes and optimized renal CL_not charge dependend: base  bodel with total hepatic CL lab and fitted TSspec  in SD rats_corrected with BWC_not charge dependent.
![image](https://user-images.githubusercontent.com/25585248/57930681-e69de800-78b6-11e9-9c55-70a23d0194db.png)

Plasma levels looks very similar to S1, but renal fraction excreted very high. The TSspec was estimated in Parameter Identification 2. Cave the Covariance matrix shows that TSspec is not identifiable.
![image](https://user-images.githubusercontent.com/25585248/57930720-fe756c00-78b6-11e9-9939-a6814c9f2f8b.png)
Metabolism is probably underestimated here. Therefor I would go with S1. Again, if you have measurements for fraction renally excreted in rats you can use this to finally decide between the two model variants
[bw977 rat 30mpk PBPK_Clearance problem_tk.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3191655/bw977.rat.30mpk.PBPK_Clearance.problem_tk.zip)

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
