### ISSUE TITLE
Visualizing infusion rate in a simulation

### ISSUE THREAD

**Issue by Fatima-Marok** [Open-Systems-Pharmacology/Forum#312]
Hello everyone,
is there a way to visualize the administration rate of a continous infusion in a simulation in MoBi?
I built in a time-dependant administration rate and if it's possible I would like to see it in my simulation. I tried building an observer for it, but sadly I can't use objects as references, that are implemented in the events building block.
Thank you!
Best regards,
Fatima

**Comment by Yuri05** [comment]
Try the following:
* Open Events building block, go to your application of interest and select the application transport
* Activate Create process rate parameter and Plot process rate parameter
![grafik](https://user-images.githubusercontent.com/25061876/56366879-63746e00-61f4-11e9-9b7e-1d6976b0f131.png)
* Update Events-Building Block in your simulation or create a new simulation
* In the simulation: click on Define Settings and Run: the process rate of the infusion should be preselected per default
![grafik](https://user-images.githubusercontent.com/25061876/56367699-25784980-61f6-11e9-8b2c-6c687b189262.png)
* Run the simulation. If you created a new simulation, infusion rate will be plotted automatically. If you updated an existing simulation, it might be additionally required to activate the Infusion process rate under the chart settings
![grafik](https://user-images.githubusercontent.com/25061876/56367873-8acc3a80-61f6-11e9-8466-4dd692b3d935.png)

P.S. This way you can also easily plot transport/reaction rate of any (passive) transport or reaction

**Comment by Fatima-Marok** [comment]
Nice! It worked perfectly! Thank you very much, you helped me a lot with this!

**Comment by Yuri05** [comment]
>I can't use objects as references, that are implemented in the events building block.

In fact, you can (it's "just" a user interface problem in MoBi).

As a workaround:
* When editing a formula, right click in the empty space of the References area and select `Create Reference`
![grafik](https://user-images.githubusercontent.com/25061876/56368935-b3edca80-61f8-11e9-96e6-d5901b2b115c.png)
* This will create an empty formula reference
![grafik](https://user-images.githubusercontent.com/25061876/56369513-c87e9280-61f9-11e9-9147-3a399d380ff9.png)
* now you can set the alias and the path manually
* E.g. if you would like to use Infusion time of an IV application in your formula, set the path to something like this: `Applications|Infusion|Application_1|ProtocolSchemaItem|Infusion time`. You can see all the path levels in the events building block, just separate them by pipe `|`
![grafik](https://user-images.githubusercontent.com/25061876/56369280-58700c80-61f9-11e9-882f-a40bf9387afc.png)
* Finally, select a proper dimension of the reference - and now you are using an event parameter in your formula
![grafik](https://user-images.githubusercontent.com/25061876/56369363-7f2e4300-61f9-11e9-8cb5-712d0c3f89ea.png)

**Comment by Fatima-Marok** [comment]
Again thank you very much, I will definitely make use of it in the future!
