### ISSUE TITLE
mean of total hepatic clearance

### ISSUE THREAD

**Issue by CHOCHANGKEUN** [Open-Systems-Pharmacology/Forum#313]
I wonder that mean of total hepatic clearance is whether other pathway except CYP metabolism or plasma to liver flow clearance.

please answer this question. thank you.

**Comment by StephanSchaller** [comment]
Please clarify your question.

What do you mean by 

> mean of total hepatic clearance

?
hepatic clearance may be caused by multiple mechanisms / enzymes which you need to specify.

**Comment by msevestre** [comment]
@CHOCHANGKEUN If you are asking what pathway corresponds to the default `total hepatic clearance` in PK-Sim: It is equivalent to one enzyme with relative expression 1 in Liver (e.g. only one process)
