### ISSUE TITLE
Missing simulations in parameter identification and sensitivity analysis 

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/Forum#316]
Hello Everyone,

I am trying to perform parameter identification and sensitivity analysis for my simulations. However, I couldn't find my simulations in both parameter identification and sensitivity analysis tabs when i am clicking on "create". I was able to find the simulations in PK Sim examples theophylline and Aciclovir without any problem. Can anyone please suggest me on what may be the problem. 

Sincerely,
Kash

**Comment by msevestre** [comment]
@yvkashyap Are your simulations population simulations? PI And SA is only available for Individual simulations

**Comment by yvkashyap** [comment]
Hi Michael,

Thanks for your quick reply. Yes, my simulations are population simulations. I will try performing PI and SA on individual simulations.

Sincerely,
Kash

**Comment by yvkashyap** [comment]
Hi Michael,

I am able to perform PI and SA on individual simulations.

Thanks,
Kash
