### ISSUE TITLE
MoBi export to population model with dimensionless variable

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/Forum#318]
Hello all,
I am having an issue when exporting a MoBi file into the population simulator.

I needed to introduce a dimensionless parameter state variable (fraction) but the export to the population simulator seem not to allow such step. Is there a solution to this problem or can I work around it?

The message: Could not load simulation from ...
Dimension dimensionless per time not available in DimensionFactory.

![Picture1](https://user-images.githubusercontent.com/33650076/57076633-69854700-6cea-11e9-825d-b24915d8363b.png)

Thank you.

Best regards,

Rudiger

**Comment by PavelBal** [comment]
Hi Rudiger,

did you solve the problem? If not, I have a solution how to overcome the error.
