### ISSUE TITLE
How to predict curve (AUC) by dissolution data in ivtro ？？？

### ISSUE THREAD

**Issue by LanceLiang1992** [Open-Systems-Pharmacology/Forum#321]
How to predict curve (AUC) by dissolution data in ivtro ？？？
please every expert !
thank you

**Comment by JanSchlender** [comment]
Hi Lance,
You can incorporate the dissolution kinetics in the formulation building block. There you have a variety of options to choose from. 
However, you need a couple of further Information to build a PBPK model such as some Prior knowledge about the compound. There is a good tutorial on that (https://ascpt.onlinelibrary.wiley.com/doi/pdf/10.1002/psp4.12134).
Best,
Jan

**Comment by LanceLiang1992** [comment]
Hi jan 
thanks for  your reply! i have got some prior knowledge about the compound, how should i build a model and use the dissolution data to predict AUC by steps? could you let me know a simple and clear  method about using pk-sim ? maybe you can do an example to give me by ppt or video!
thank you very much

**Comment by tobiasK2001** [comment]
Dear Lance,
perhaps you can start with checking out this videos:
https://www.youtube.com/channel/UCrjhCoM0g5C5wtQQ4JQYpJg
Best, Tobias
