### ISSUE TITLE
TMDD and repeated administration

### ISSUE THREAD

**Issue by NicolasATX** [Open-Systems-Pharmacology/Forum#324]
Hello,

I am building a model for predicting mAb PK following i.v. administration. To do so, I defined a Protein Binding Partners (TNF) in an Individual and defined a Compound as a mAb with affinity for FcRn and TNF. I had to estimate the Reference Concentration for TNF (see also my post #322 ). The model is ok and fit closely to observed data in human following single dose.
In order to confirm the predictability of the model, I used an additional set of observed data from another study where repeated administration was done (two i.v.). In that case the model worked fine following 1st administration, but failed to simulate TMDD following 2nd administration:
![image](https://user-images.githubusercontent.com/50614567/57916130-8301c380-7892-11e9-87e1-245e10081933.png)

It appears that TNF concentration is drastically decreasing following 1st administration and then slowly increase but not sufficiently to achieve enough concentration to insure TMDD following 2nd administration. I tried to play with half-lives (liver / intestine) of TNF but these did not change TNF "recovery". I did not succeed in identifying in Mobi where Binding Partner TNF is described as being synthesized / renewed: there is only a Start Amount which is defined in parameters.

Any suggestions that may help me with this issue? Just an additional comment of importance: the Binding Partner TNF localization is set to 'Extracellular Membrane' ,

Nicolas

**Comment by Christoph27** [comment]
Hello Nicolas,
Do you have also included TNF turnover and adjusted the turnover rate?

**Comment by NicolasATX** [comment]
Hello Christoph,

Thank you for answering.
No actually this is what I would like to fine-tune. I did not add a specific turnover - i just created a binding Partner, didn't see any turnover - but when I look to TNF simulation data I observe that its concentration is slowly increasing (too slowly actually). Could you give me some advice on how to include and adjust the turnover rate?
Best,

nicolas

**Comment by Christoph27** [comment]
Hello Nicolas,
you have to export your PK-Sim model to MoBi in order to add a turnover.
In the Reaction Building Block you can then add a zero order reaction producing your TNF and a first order reaction for the degradation. An example where this is done and described in more detail can be found at "https://github.com/Open-Systems-Pharmacology/ISOP-webinar---PK-Sim-MoBi-introduction".
You can have a look at "Ex_1_ADC_Tox_Modeling_10.mbp3" and the reactions "synthese" and "degradation" for the molecule "TMEFF2".

All the best,
Christoph

**Comment by NicolasATX** [comment]
Hello Christoph,

Thank you for you answer it definitively helped! I did manage to add a turnover on the target allowing TMDD to occur after the 2nd injection. I still have to improve parameters in order that simulation fit better with observed data.

Thank you again,
Nicolas
