### ISSUE TITLE
Relative expression of CYP3A4 in beagle dog

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#326]
Hello Members,
Can any one share the relative expression of CYP3A4 enzyme in beagle dog, iam trying to build PBPK model of a compound in beagle dog

Is there any link from where we can download the expression data base of different preclinical species. I could only see human expression data base for download

Regards
Harish

**Comment by HenrikCordes** [comment]
Dear @harishkaushikbugworks,

as far as I know there are currently no animal expression data bases available for PK-Sim.
However, we are working on them right now and will hopefully provide them soon.
 
In the mean time what you could do is:
1) using the human expression db as surrogate
2) or typing in the relative expression values manually

As resource for dog gene expression, you could use this side for example:
http://bigd.big.ac.cn/idog/gene/getGeneDetail.action?geneName=ENSCAFG00000014877

Hope this helps and kind regards,
Henrik

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
