### ISSUE TITLE
optimisation of protein binding in pbpk modelling

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#327]
When iam fitting pbpk model of my drug, i used experimental fup from PPB values (6%) but the distribution was impacted , however when i used parameter optimisation i found that plasma protein binding values fup was 17%, it drastically improved my fitting and distribution is just fine. is it possible to observe this kind of observation
Regards
Harish
![fitting issue](https://user-images.githubusercontent.com/49284633/58094050-685e8000-7bed-11e9-9b57-4e0f77b7906f.jpg)
![with optimised PPB fitting improved](https://user-images.githubusercontent.com/49284633/58094125-888e3f00-7bed-11e9-9426-807d353046e8.jpg)

**Comment by HenrikCordes** [comment]
Dear @harishkaushikbugworks,

I'm not sure what your question is. When the fraction unbound is altered you will for sure see an alteration in the plasma PK. 
Could you provide more information on your model, processes and used data?

Be aware that PK-Sim uses the fraction unbound, meaning a plasma protein binding (PPB) of 6 % has to be implemented as 95 % fu. 

Also, the logP has a profound impact on the PK and might be a better parameter to estimate than the fraction unbound, especially if you have experimental data for the fu. 

Kind regards,
Henrik

**Comment by harishkaushikbugworks** [comment]
Dear Henrik,
Thanks for reply
I will give some data
Rats PPB is 95%, dogs PPB is 94%
can you tell me what values fup to be entered in PK SIM compund block 
this would answer my question
Regards
Harish
![ppb](https://user-images.githubusercontent.com/49284633/58094914-64336200-7bef-11e9-9846-179ec6ccb926.jpg)

**Comment by tobiasK2001** [comment]
Dear Harish,
 in that case you have an fu of e.g. 6% for human (fu = 100 % - PPB). Additional to the comment of Henrik, which is totally right, your fu seems to be in a range which should be measurable with high precision. Therefore, I would not fit that and go for lipophilicity.

Best, Tobias

**Comment by harishkaushikbugworks** [comment]
Hello Tobias&Henrik
Thanks for your comments, 
I have attached data which iam using for fitting, if you can help it will be of great help.
I tried optimising the lipophillicity from the LogP value i have, if i increase the value to >3 then my distribution is fine but Clearance gets impacted 
if i use my experimental logp~ 1.14 then my distribution gets impacted with clearance seems almost ok

I am in fix what to do, your help is greatly needed here

Regards
Harish
[Data for my modelling.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/3205875/Data.for.my.modelling.xlsx)
[bw977 dog 3mpk PBPK_Distribution issue_trials.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3205889/bw977.dog.3mpk.PBPK_Distribution.issue_trials.zip)

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
