### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by fredsevmartins** [Open-Systems-Pharmacology/Forum#328]
Hi
Please could you help me with this message? my model was working before
![image](https://user-images.githubusercontent.com/45317633/58103788-e158da00-7be3-11e9-9d29-ca228407ca60.png)
 
Thanks
Fred

**Comment by HenrikCordes** [comment]
Dear @fredsevmartins,

you can try to decrease the solver tolerances of your simulations.

![image](https://user-images.githubusercontent.com/4817133/58104156-94c1ce80-7be4-11e9-8613-a9b2f31228c4.png)

If that does not do the trick, sometimes if you use estimated parameter with tailing precision rounding them can help ((for example 20.453454353543 --> 20.45)

You can find more information here: https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/setting-up-simulation#ode-solver-properties 

Hope this helps!

Kind regards,
Henrik

**Comment by fredsevmartins** [comment]
Dear @HenrikCordes 
I already did it before, but I still get same message.
I noticed that it started after I create my own compound file and save it as template.

**Comment by msevestre** [comment]
@fredsevmartins Can you look at the history and see if something has changed?

Are you saying that a simulation that used to run before suddenly does not run without changing ANYTHING in that simulation (no building block update etc..?)

**Comment by Yuri05** [comment]
@fredsevmartins I guess 3 min is your first output time point (you are calculating with 20 pts/h at the beginning)?
If the simulation fails at the very first output point - it might be wrongly setup.

To check this you can e.g. set simulation time to 1 second and resolution to 1000 points/second.
If you still get convergence issues - **_initial_** model is with very high probability wrong.

In this case, please try this: https://github.com/Open-Systems-Pharmacology/Forum/issues/210#issuecomment-412834236

**Comment by fredsevmartins** [comment]
Dear @Yuri05  and @msevestre 
Thank you very much . I tried your suggestions but still the same error message.  
If I run a simulation that was built before, everything goes smoothly . But If I clone my simulation or open any compound file from PKSIM library , the message pop up.

Any suggestion ? for now I don't have matlab 
Fred

**Comment by msevestre** [comment]
@fredsevmartins Can you attach the project for us to inspect.
Also please describe exactly what you mean with "Open a compound from the PKSim Lib". Are suggesting that the simulation is working, you load a compound in the project, and the simulation is not working anymore? Or is the simulation not working anymore when you swap the compound with the newly loaded compound?

In short, we need a step by step instructions on how to reproduce the issue.

Thanks :)

**Comment by msevestre** [comment]
@fredsevmartins No feedback in over 26 days. Closing the issue. Please do not hesitate to reopen with a project file so that we can reproduce and fix the issue
