### ISSUE TITLE
Middle Eastern Population

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#33]
Hi,

In my population group, I have few subjects from Iraq and from UAE. 
Can I classify them as a European? any suggestion.

Thanks 
mouli

**Comment by msevestre** [comment]
@moulirc Do you know if there is something similar to ICRP or NHANES for middle eastern population? If yes, this could be a good enhancement. 

As a reminder for everyone out there, PK-Sim currently supports the following populations:
* Asian (Tanaka, 1996)
* Black American (NHANES, 1997)
* European (ICRP, 2002)
* Japanese (2015)
* Mexican American - White (NHANES, 1997)
* White American (NHANES, 1997)

**Comment by moulirc** [comment]
[nhsr044(1).pdf](https://github.com/Open-Systems-Pharmacology/Forum/files/1117866/nhsr044.1.pdf)

BMC Public Health. 2009; 9: 272.
Published online 2009 Jul 30. doi:  10.1186/1471-2458-9-272
PMCID: PMC2728720
The health of Arab-Americans living in the United States: a systematic review of the literature
Abdulrahman M El-Sayedcorresponding author1,2 and Sandro Galea1,2,3,4

**************
 NHANES refers to  National Health and Nutrition Examination Surve?
ICRP refers to International Commission on Radiological Protectction ?
I have attached a pdf, could you please let me know what information is needed for this population group and I shall try and sort them out.

kind regards
mouli

**Comment by JanSchlender** [comment]
Dear Mouli,

The paper you refer to is a health survey and not adequate to inform a PBPK database. Please have a closer look at the ICRP Reference Man (http://www.sciencedirect.com/science/article/pii/S0146645303000022) or the Reference Asian Man (http://www-pub.iaea.org/MTCD/Publications/PDF/te_1005v2_prn.pdf). Once you have anatomical and physiological data at hand, you can inform a PBPK database like it was done for pediatrics and adults in Edginton 2006 (https://rd.springer.com/article/10.2165%2F00003088-200645100-00005) and for older adults in Schlender 2016 (https://rd.springer.com/article/10.1007/s40262-016-0422-3). 

Once you have defined the anatomy and physiology, you may need add differences in protein abundance and activity and/or GI tract conditions. In case you want to incorporate any disease stages, you need to consider additional deviations compared to your (so far) healthy population. 

Best,

Jan
