### ISSUE TITLE
Launch of MoBi skin permeation model

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/Forum#334]
Dear all,

@msevestre , @Aedginto and I are happy to launch a MoBi implementation of a skin permeation model, located at https://github.com/Open-Systems-Pharmacology/Skin-permeation-model

The implementation is based on the model reported in:

Y. Dancik, M.A. Miller, J. Jaworska, G.B. Kasting
Design and performance of a spreadsheet-based model for estimating bioavailability of chemicals from dermal exposure
Adv. Drug Del. Rev., 65 (2013), pp. 221-236

The model reflects the permeation of a dermally applied compound into skin.  The skin itself is regarded as a multilayered slab, where each layer corresponds to an anatomical skin layer.  The diffusion of the compound is governed by user-input parameters that describe the physical/chemical properties of the skin and the compound.  The user has the option of simulating both in vitro and in vivo skin permeation under a variety of conditions that include: the presence/absence of an excipient, evaporation of the compound due to wind, skin occlusion, partial/full skin hydration and metabolism of the compound in the viable skin layers.  

In addition to time-course simulations of the amounts of the applied compound present in different skin layers, Observers have been built to report the mass flux and the cumulative mass of the compound crossing the skin over time. 

The user guide contains a summary of the model's theoretical background as well as details on creating simulations and on connecting the model to a whole-body model generated in PK-Sim.

Please let us know of any bugs, suggestions or comments.

Have a won-dermal day!
Abdullah Hamadeh

**Comment by StephanSchaller** [comment]
> Have a won-dermal day!
Love it! You, too!

Thank you very much for this contribution!

**Comment by tobiasK2001** [comment]
That is great! Thanks for that;-)

**Comment by PriKalra** [comment]
Thank you for this contribution! Its very valuable for me 🥇
