### ISSUE TITLE
Mapping Observed data for PI, Value required, output mapping has inconsistent dimension

### ISSUE THREAD

**Issue by thanghodn** [Open-Systems-Pharmacology/Forum#336]
Hello,
 I have quick question about observed data mapping for PI? I import the observed data and mapped them to orgran/compartment/molecule of interested.
![image](https://user-images.githubusercontent.com/48608393/58304655-05661800-7daa-11e9-8561-0409f1cbb912.png)

But then when go to PI and try to map it to observation data. It doesn't look like it mapped correctly with the following error:

![image](https://user-images.githubusercontent.com/48608393/58304947-3abf3580-7dab-11e9-8c70-7fbffc83a310.png)
I wonder if I missed something as simple as the unit or something?

Thanks,
Thang

**Comment by StephanSchaller** [comment]
Hi Thang,

in the second column,where the red "x" appears you have to use the drop-down at the right to actually select the observed data.

For now, you have only the simulation output in the first column selected.

Best,
Stephan

**Comment by tobiasK2001** [comment]
Hi Thang,

I think I could reproduce the error and it seems to be a bug.
I transfered a PK-sim Simulation to Mobi. The Simulation had Data included in PK-sim already. Evrything fine there.
After opening in MoBi. Data show up in BB explorer there to. 
However the the drop down button with the red "x" is not accessible and no data can be selected.

Looks like a bug to me. could be related to this one:
https://github.com/Open-Systems-Pharmacology/MoBi/issues/378

Best, Tobias

**Comment by tobiasK2001** [comment]
However, the dimension was in my case set in PKsim and imported to MoBi...
probably there is something else going on, too. Can you opene another issue ther,e, Thang?
Thanks!

**Comment by thanghodn** [comment]
@StephanSchaller, The drop down menu on the right is not accessible when I clicked on it.  Nothing is available to be selected there.
@tobiasK2001, Let me try to see if I can import the data via PKsim and export to Mobi to see if it is a bug or something else going on.

**Comment by StephanSchaller** [comment]
@thanghodn have you managed to solve the issue.
Otherwise we should report this as a bug.

**Comment by msevestre** [comment]
@thanghodn One can see on the screenshot that no observed data is associated with the simulation. You need to have at least once used an observed data set (drag and drop onto the simulation chart) in order to PI. Starting directly with a PI without ever checking if the data fits the simulation beforehand is not recommended.

**Comment by thanghodn** [comment]
I was able to see that we do need to drop the data in the charts in order to for the software to recognize there are data. 
Thank you for all of your input.
