### ISSUE TITLE
need help in fitting the PBPK

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#337]
Hello all,
I have attached data which iam using for fitting, if you can help it will be of great help.
I tried optimising the lipophillicity from the LogP value i have, if i increase the value to >3 then my distribution is fine but Clearance gets impacted
if i use my experimental logp~ 1.14 then my distribution gets impacted with clearance seems almost ok

I am in fix what to do, your help is greatly needed here

Regards
Harish
[bw977 dog 3mpk PBPK_Distribution issue_trials.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3215745/bw977.dog.3mpk.PBPK_Distribution.issue_trials.zip)
[Data for my modelling.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/3215747/Data.for.my.modelling.xlsx)

**Comment by PavelBal** [comment]
Can you show here some figures of your fits?

Also, consider the different calculation methods for the partitione coefficients. In the Parameter Identificication tool, in the "Settings" tab you can select Calculation methods variation” from the “Options” drop-down menu located at the bottom of the configuration frame. Select “Partition coefficients” and then all five available calculation methods.

**Comment by harishkaushikbugworks** [comment]
Ima unable to locate parameter identification tool, iam searching in parameter identification
<img width="372" alt="fitting distribution issue" src="https://user-images.githubusercontent.com/49284633/58314224-b2817480-7e2c-11e9-99d7-08aa61bff7db.png">

**Comment by harishkaushikbugworks** [comment]
![2cmt model fitting](https://user-images.githubusercontent.com/49284633/58316954-6b967d80-7e32-11e9-987d-aec7f96cae7c.jpg)
i have got the location of changing calculation methods, 
when i fitted the data to 2 cmopartment model, i got the fitting as attached
![2cmt model fitting](https://user-images.githubusercontent.com/49284633/58316994-87018880-7e32-11e9-861f-b0c1e40e9dcb.jpg)

what iam missing in my pbpk fitting is the similar kind of fitting, i have issues with distribution

**Comment by tobiasK2001** [comment]
Dear Harish,
maybe there is some general misunderstanding what PBPK modelling is about. PBPK modeling is a powerful technique to fusion information from different sources and areas with the ultimate goal to bridge knowledge gaps and elucidate the mechanism driving the PK of the compound. 
Read more e.g. here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5080648/

The kind of fitting you are referring to looks like classical data driven and non-mechanistic compartmental fitting. This is not included in PK-sim. 
For you problem:
> I tried optimising the lipophillicity from the LogP value i have, if i increase the value to >3 then my distribution is fine but Clearance gets impacted<

PK-sim tells you that the extend of Clearance seems to be connected with your assumptions for distribution. So you might consider rephrasing your question to: does the measured compound data (e.g. lipophilicity) and my knowledge about Clearance and metabolism (hepatocyte 1/2, and renal CL) explain the found plasma concentration time profile in animals. 
E.g. in you Simulation the model suggests a quite high fraction of parent compound excreted renally (80%). Is that realistic? Is renal CL realy the major driver of Elimination here? Do you have data supporting that?
![image](https://user-images.githubusercontent.com/25585248/58412465-c5878500-8076-11e9-9adc-1de440cd5c48.png)
Before you try to bring you simulation closer to the data you might also consider possible variability in your measured data? You are simulating for a virtual mean dog. Some confidence interval for the measured means or single individual data would be helpful to see if the simulated mean individual is inside the expected possible range.
 Hope that might help you. 

Best, Tobias

**Comment by harishkaushikbugworks** [comment]
![improved fitting](https://user-images.githubusercontent.com/49284633/58456606-41023880-8142-11e9-9b40-f28c34fe9d3b.jpg)
Hello Tobias,
Thanks for your comments,
I have attached here the fitting which is improved after considering the CYP3A4 (80% compound metabolism from phenotyping assay), Renal (invivo dog pk study) and Biliary Cl (from rat invivo study) invitro here.
my questions are as follows

1. Is there any CL processes missing still?
2. If so how do i know which process is missing?
3. Is the fitting ok as iam simulating for virtual mean dog?
4. i know there is scope for improving the fit, then what should i do in addition?

your response will be really helpful, please help me

Regards
Harish

**Comment by tobiasK2001** [comment]
Dear Harish,

this looks better now, but only until 14 hours. The answers to your questions seem to be highly depending on your data point at 24 h. Before I can provide you answers, I think we have to take a closer look at your data and the scope of your project. Further we should consider, that your project might need broader support in a more confidential setting than in a forum.  If that is the case than you can of course reach out to me via tobias.kanacher@pharmetheus.com.

Best, Tobias
