### ISSUE TITLE
Gemfibrozil, repaglinide and pioglitazone PBPK models

### ISSUE THREAD

**Issue by DeniTue** [Open-Systems-Pharmacology/Forum#338]
Dear all,

We have been working on models for DDI prediction, building a network of interacting CYP2C8 and OATP1B1 perpetrator and victim drugs. Three whole-body PBPK models of gemfibrozil, repaglinide and pioglitazone were carefully developed and then evaluated by prediction of clinical DDI studies.

The corresponding manuscript, including comprehensive documentation, has been published online in Clinical Pharmacokinetics and the models as well as PK-Sim projects presenting the predicted DDI studies have been uploaded as Open Systems Pharmacology repositories to GitHub.

Related publication:
Türk D, Hanke N, Wolf S, Frechen S, Eissing T, Wendl T, Schwab M, Lehr T. [Physiologically Based Pharmacokinetic Models for Prediction of Complex CYP2C8 and OATP1B1 (SLCO1B1) Drug–Drug–Gene Interactions: A Modeling Network of Gemfibrozil, Repaglinide, Pioglitazone, Rifampicin, Clarithromycin and Itraconazole.](https://link.springer.com/article/10.1007%2Fs40262-019-00777-x) Clinical Pharmacokinetics 2019. 

All models can be found [here](https://github.com/Open-Systems-Pharmacology).

Best regards,
Denise

**Comment by tobiasK2001** [comment]
Great work! Thanks for that!
