### ISSUE TITLE
Enzyme in Plasma and Intracellular Space

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/Forum#339]
Hi all. 

Can the same enzymatic process occur in plasma and in the intracellular space of all organs in PK-Sim? Can I accomplish this by setting the "location" of a metabolizing enzyme to intracellular and inputting relative expression = 1 into all organs AND the plasma?

If not, I will go into Mobi and adjust the relative expression in all the plasma subcompartments with attention to venous blood, arterial blood and all organs.

Do you have a better way?

Thanks in advance.

**Comment by Yuri05** [comment]
>Can I accomplish this by setting the "location" of a metabolizing enzyme to intracellular and inputting relative expression = 1 into all organs AND the plasma?

Yes.

**Comment by prvmalik** [comment]
Thanks Yuri, saves me a lot of time!
