### ISSUE TITLE
Enzyme/Transporter Reference Concentrations

### ISSUE THREAD

**Issue by ncarter1** [Open-Systems-Pharmacology/Forum#34]
Hello,

Does anyone know how/where PK-Sim attains reference concentrations in umol/L for enzyme/transporter expression in tissues, i.e. in the 'Standard European Male for DDI' individual template? The original Rodrigues (1999) paper that PK-Sim cites gives Cyp enzyme abundance in units of pmol/mg HLM; PK-Sim appears to convert this concentration to umol/L tissue by dividing by 25, yet I am not sure where this conversion factor comes from and if it would also hold for other tissues or in other species. I also noticed that PK-Sim has reference concentrations given for some transporters that are not included in the Rodrigues paper (i.e. OATP1B1), and it would be useful to know the source for this data.

Thanks,
Nicole

**Comment by msevestre** [comment]
@TWendl Could you chime in please?

**Comment by ncarter1** [comment]
Hello - just wanted to follow up and see if anyone with knowledge in this area has gotten the chance to look at this (would be very helpful to my team and me). Thank you and have a good weekend!

**Comment by sfrechen** [comment]
Hi! You need to consider the mean protein content per gram liver (MPPGL) to come up with reference concentrations in µmol/L: pmol CYP/mg Prot * mg Prot/ g Liver / 1000 = µmol CYP / g Liver.
With an approximate density of 1 g/L this is µmol CYP / L Liver.

**Comment by ncarter1** [comment]
Hi! This is very helpful - thanks so much!

Nicole
