### ISSUE TITLE
Tissue distribution with protein model

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#340]
Dear all,

I am modelling an antibody with the protein model in MoBi. I am trying to describe the concentration in different tissues (organs). Since the concentrations are slightly under-predicted, I would need to increase the distribution of the drug in some of the tissues. Which parameter do you think it would be the more appropriate to modify? I don't need to modify the clearance of the drug, which is already OK in plasma and in the tissues, but only the distribution to some tissues. In my comparison I am considering the total concentration in the organ including the FcRn complex.

Thank you very much in advance for your help!

Donato

**Comment by Christoph27** [comment]
Hi Donato,

how were the tissue concentrations measured? Were iodine or metal labeled antibodies used?
In case of a metal label (e.g. In), the metal label remains in the tissue for a long time after the antibody has already been cleared and still contributes to the measured tissue concentration (discussed e.g. in https://doi.org/10.4161/mabs.28254 ). Another general thing which might to be considered is contribution from residual blood. The parameters which were adjusted to mice tissue concentrations during development of the model were lymph- and fluid recirculation flow rates.

All the best,
Christoph

**Comment by teutonicod** [comment]
Hi @Christoph27, 
Thanks a lot for your reply! Indeed in my case I have accumulation because of the degradation, but I am not sure if this is able to explain all the concentrations in the organs, so I was looking for also additional parameters that could be adjusted. But globally the model predict quite nicely the concentrations, there are just minor adjustment that are probably needed.

All the best,

Donato
