### ISSUE TITLE
Metronidazole PBPK model following Oral dosing

### ISSUE THREAD

**Issue by rkdevarakonda** [Open-Systems-Pharmacology/Forum#342]
I tried running simulations using PK-Sim 7.4 for metronidazole following 500mg IV as well as oral dosing. IV simulations were very close to the literature reported observed data whereas for oral route the simulations were grossly under predictive. 
The Cmax (observed) is about 13 ug/ml, simulated one is about 3.3 ug/ml

Fraction absorbed (observed) is about 0.9 where as the simulated one is 0.51. 
Clearance & t1/2 seem to be close to observed data. 
My guess is that the model is missing something related to accounting for complete intestinal absorption (or entero-hepatic recycling??).

Can you provide any help? 
Thanks in anticipation. 
Krishna

[plot_simulated.pdf](https://github.com/Open-Systems-Pharmacology/Forum/files/3266587/plot_simulated.pdf)

**Comment by prvmalik** [comment]
First check solubility, specific intestinal permeability (transcellular) and your dissolution profile against literature values where possible and optimize where appropriate.

One study in rats suggests that 25% of the metronidazole dose may undergo enterohepatic recirculation (doi: 10.1016/0006-2952(78)90084-9). 

A possibile mechanism is: Metronidazole undergoes glucuronidation in the liver and is excreted into feces via the bile. In the intestine the glucuronide conjugate can be metabolized back to metronidazole by B-glucuronidase and reabsorbed.

An example of a PK-Sim PBPK model where this mechanism has been implemented is available for Sorafenib (doi: 10.1007/s00280-016-3018-6).

If a drug undergoes EH-recycling, the rate and extent of oral absorption are often affected by food/high fat meals. After a quick search it seems that most studies report a negligible effect of food on metronidazole PK.

Whether you optimize intestinal absorption parameters or attempt to incorporate this mechanism will depend on the purpose of your PBPK model and the research questions that you are trying to answer with it.

**Comment by regulus92** [comment]
Maybe this reference can help you?
Applied Concepts in PBPK Modeling: How to Extend an Open Systems Pharmacology Model to the Special Population of Pregnant Women. CPT Pharmacometrics Syst. Pharmacol, 2018.
where metronidazole is taken as a demonstration compound.

**Comment by rkdevarakonda** [comment]
Thanks Paul and Liang for the helpful references and comments. As far as metabolic clearance goes the model developed seems good. The major issue is that the model predicts the fraction absorbed (F) to be 0.51 (Cmax 3.3 ug/ml compared to literature reported 13 ug/mL). For metronidazole the literature value of F is > 0.9%. Obviously this has something to do with absorption...I agree with Paul that there about 30 - 40% contribution by EH recycling as a result of conversion of glucuronide into metronidazole. I will be thankful if someone could suggest how I should include this in my model...

**Comment by regulus92** [comment]
Premising that you have defined biliary clearance, EH circulation-related parameters can be set here.
![B{~ 5}G0E@M55~@$EME0UEH](https://user-images.githubusercontent.com/45459593/59179135-b4209b80-8b93-11e9-9c38-fddb6dfef826.png)

**Comment by rkdevarakonda** [comment]
That's exactly what I am looking for...but how is that I don't see that option available here? AM I missing something...forgive my ignorance!
![image](https://user-images.githubusercontent.com/30701109/59233500-53eb2300-8bae-11e9-9804-4c28ff6a4e6c.png)

**Comment by tobiasK2001** [comment]
Please make sure you switched to Advanced view mode 
![image](https://user-images.githubusercontent.com/25585248/59248791-b9c5c200-8c23-11e9-869a-15252bcd4112.png) in the bottom left corner.

**Comment by AndreDlm** [comment]
Dear Krishna, 

if you were referring to total bioavailability (F = 90%), which is the typical parameter reported in clinical PK studies, and not the fraction absorbed, you could also have a closer look at the oxidation of metronidazole to 2-hydroxymetronidazole - in addition to the aspects already suggested above.

Approx. half of the dose is eliminated through this pathway, but the relative contribution of CYP3A4 (low affinity, high capacity enzyme) and CYP2A6 (high affinity, low capacity enzyme) to this reaction is unknown. In the model, roughly equal parts were assumed for both enzymes (~26% each), but since CYP2A6 is not expressed in the intestine, a higher contribution of this enzyme likely results in a higher Fg (fraction escaping gut wall metabolism) and hence in a higher bioavailability.

Best,
André

**Comment by rkdevarakonda** [comment]
Hi Andre,
Thanks for your helpful suggestions. Yes, I am aware of different metabolic pathways of MET mediated by CYP2A6, 3A4 as well as glucuronidase...and am trying to refine the model further!

Best,
Krishna

**Comment by rkdevarakonda** [comment]
Thank you so much Tobias!

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
