### ISSUE TITLE
SLC transporters input

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#343]
Hello,
I have 2 SLC transporters (OAT3 & MATE2-K) for which my drug is substrate from the Human HEK vesicles assay. Determined Vmax & Km from the assay, which process should i use under transporters module while building compounds. is there any need to IVIVE to calculate for whole liver

Thanks

**Comment by HenrikCordes** [comment]
Dear @harishkaushikbugworks,

could you specify what information you have in hand? Do you have information on the amount of transporter protein in the assay? 
PK-Sim offers different pre-implemented transport processes you could implement in the compound building block:
![image](https://user-images.githubusercontent.com/4817133/60079430-3382a300-972e-11e9-99f2-569a78e598a8.png)

If you can normalize you Vmax to the amount of transporter protein in the assay you could try the "in vitro acitve transport (vesicular assay). Otherwise the "specific active transport-Michaelis-Menten might be interesting for you. 

Hope this helps and kind regards,

**Comment by harishkaushikbugworks** [comment]
Hello Henrik

My drug is an substrate to renal transporters in our studies OAT3 & MATE2-K with Km & Vmax as follows for MATE2-K (Vmax=111.2775 pmol/mg/min & Km =468.7402 uM) and for OAT-3 (Vmax=76.1050 pmol/mg/min & Km =120.6556 uM).
If i use the transporter protein Vmax and Km values in Transporter module then at the time simulation, how would i use both transporters values. Can you help me
I dont have information on transporter protein used in the assay.

I have used these values under Tubular Secretion – Michaelis-Menten in Renal clearance process.
So in this case which one is right and whats the approach i should take

Regards
Harish

**Comment by HenrikCordes** [comment]
Dear @harishkaushikbugworks,

I guess the pmol/mg/min are related to mg of portein/tissue in your assay? You might have to translate the mg into molecular amount before using it in PK-Sim.

You have to add the transporter expression in the individual building block and the active process in the compound building block. 

It might be a good starting point for you to get familiar with the PK-Sim documentation of how to implement [active process](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-compounds-definition-and-work-flow) in general and how to use the [expression data base](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-data) to place an enzyme into a specific compartment. 



Kind regards,
Henrik

**Comment by prvmalik** [comment]
It boils down to knowing:

- The concentration of lysate protein per HEK293 cell volume (mg/uL)

- The molar concentration of the OCT transporter in HEK293 cells (nmol/uL)

I'm working on the same problem but so far these numbers have evaded me. Let me know if you come up with an answer.

**Comment by harishkaushikbugworks** [comment]
Hello Henrik,
How do we convert, can you give some details
"pmol/mg/min are related to mg of portein/tissue in your assay? You might have to translate the mg into molecular amount"

@prvmalik 
Did you get the values which we can use to do the above conversion and use these values

it would really help

Regards
Harish

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help

**Comment by prvmalik** [comment]
New data available this year on kidney transporter expression proteomics.

This data is available in units of pmol/g kidney. We should develop a method for converting this to a useful number. Success is within reach!

http://dmd.aspetjournals.org/content/early/2019/05/23/dmd.119.086579.abstract

**Comment by PavelBal** [comment]
This is great! We should look into it and integrate into PK-Sim.

**Comment by msevestre** [comment]
that's awesome. @prvmalik Would you mind creating an issue in the PKSim repo with this content so that we can start a discussion of what needs to be done?
