### ISSUE TITLE
how to simulate amount in feces in PK-sim?

### ISSUE THREAD

**Issue by wdzth** [Open-Systems-Pharmacology/Forum#344]

**Comment by wdzth** [comment]
I care about the drug biliary secretion, but I donot find the export result of the amount in feces. thanks a lot.

**Comment by StephanSchaller** [comment]
If you have set up your simulation and select "define settings and run" you can filter for "feces" (in "Organ" "Lumen")  plot either the "amount" in feces or "fraction excreted to feces":

![image](https://user-images.githubusercontent.com/25477643/59598095-b470e780-90fb-11e9-9e8d-842abbbc9e72.png)

Is this what you were referring to?

Best,
Stephan

**Comment by wdzth** [comment]
that is it, thanks so much.
