### ISSUE TITLE
How to map observed data

### ISSUE THREAD

**Issue by MichaelMKrug** [Open-Systems-Pharmacology/Forum#345]
Dear Mobi team,
being an absolute novice I could not succeed in mapping observed data to a simple reaction in Mobi :-(
I'm also wondering why for a decay reaction:  dC/dt = -k*A the formula has to be defined as k*A?

So what am I doing wrong?

Thanks for helping!

 (s. att. zipped .mbp3 file)
[A Stability_fit.zip]
(https://github.com/Open-Systems-Pharmacology/MoBi/files/3298155/A.Stability_fit.zip)

**Comment by StephanSchaller** [comment]
I didn't see the attached file before, but I have found the solution.

So, to map the simulation vs. observed in the PI, you have to select "Plot Parameter" for the Molecule Concentration:

![image](https://user-images.githubusercontent.com/25477643/59677225-a5586b00-91c9-11e9-9580-05b22876a608.png)

Mapping in the PI should work therafter:

![image](https://user-images.githubusercontent.com/25477643/59678244-2dd80b00-91cc-11e9-8841-f37fed828cc9.png)

and the result:

![image](https://user-images.githubusercontent.com/25477643/59678295-519b5100-91cc-11e9-9da7-5e7cbc6dec2e.png)

**Comment by MichaelMKrug** [comment]
Thanks @StephanSchaller !
Didn't have much time to look at it, now. But I'll do the next days!
... and keep you updated on success :-)

Best regards,
Michael

**Comment by MichaelMKrug** [comment]
@StephanSchaller 

Success! :+1: 
Thanks a lot for helping

Thanks also to @msevestre !

**Comment by StephanSchaller** [comment]
@MichaelMKrug my pleasure
