### ISSUE TITLE
enterocyte lysosomes  trapping  simulation

### ISSUE THREAD

**Issue by wdzth** [Open-Systems-Pharmacology/Forum#346]
need help! my drug, logp 3.8, pka 9.2 base, is considered to be trapping in enterocyte lysosomes when po adminstration, resulting tmax delayed to 4-8 h, how can i simulate this process in pk-sim?

**Comment by wdzth** [comment]
dear all, 
can anyone help me? 
best
zhang

**Comment by StephanSchaller** [comment]
Hi Zhang,

i guess it depends on how detaiuled you need this implemented.

A good workaround could be to introduce unspecific binding (to protein/phospholipids) in the GITract.
Either luminal or within mucosa.


For this you just have to define a Protein Binding Partner in the "Individual" building block and the corresponding binding mechanism in the "Compound" building block.


Anything more complex/detailed will require MoBi to implement.

Hope this helps,
Stephan

**Comment by wdzth** [comment]
Hi Stephen,
an excellent answer, thanks so much. I will try this method.
best
Zhang

**Comment by wdzth** [comment]
Hi Stephen,
 I have not found the place to set the unspecific binding in GI tract. As your advice, I try it by defining a protein in the  "individual"  building block (expression, protein binding partners, reference concentration, location, intestinal mucosa, duodenum, upper and lower jejunium). and correpondingly defining the parameters  koff kd, in the "compound" building block (ADME, distribution, specific binding, protein  binding parterners). however it does not work. I wonder if anything wrong or ignored in setting. 
could you please give some advices more detail? thank you.
best
Tianhong Zhang
![1](https://user-images.githubusercontent.com/51363547/60559882-7ffa5e00-9d80-11e9-8965-b7d080056a59.jpg)
![2](https://user-images.githubusercontent.com/51363547/60559925-a1f3e080-9d80-11e9-83b8-58956c3d24eb.jpg)

**Comment by tobiasK2001** [comment]
Dear Tianhong Zhang,

probably you found a better solution. However the apporach described by Stephan should work. However you should bring the sensitive parameters into a meaningfull range. E.g. the Reference concentration of the hypothetical binding partner should be in a similar range than your compound is dosed to have an effect. E.g. like this:
![image](https://user-images.githubusercontent.com/25585248/61218050-68708d00-a711-11e9-9655-a03ee64f6f31.png)

than you should see and effect like this 
![image](https://user-images.githubusercontent.com/25585248/61218250-e765c580-a711-11e9-8f06-5f0ae5d55eb1.png)
[enterocyte lysosomes trapping simulation #346.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3392395/enterocyte.lysosomes.trapping.simulation.346.zip)

Please find the project attached. The only reason to chose Midazolam as compound was, to have it quick from the template database. No clue if it does Lysosomal trapping.

Hope this might help you. 
Best Tobias

**Comment by StephanSchaller** [comment]
@wdzth sorry for not following-up. I missed your reply.

@tobiasK2001 thanks for picking up ;-)

**Comment by davidbturner** [comment]
Hi wdfth,
I can't help with code but I have a science question. What evidence do you have that lysosomal trapping is influencing the absorption of your drug? Furthermore, I have seen the paper on dextromethorphan by Bolger et al. In their PBPK model they simply adjusted enteroctye unbound fraction which is not lysosomal trapping which I would think has a kinetic component. Also to model this correctly one would need to know, amongst other things, the lysosome fractional volume of the enterocytes. This is not known to my knowledge. Any comments welcome! Regards

**Comment by wdzth** [comment]
Hi davidbturner,
Thank you for comments. Firstly, I have no direct evidence for my drug influenced by  lysosomal trapping, but the Tmax of conc.-time curve of rat plasma after PO administration is delayed (2-8h) and exhibits a high con. plateform from 2 to 8 hours. In addtion, the PKa of the drug agrees with lysosomal trapping theory.
secondly, I agree with your viewpoint that only adjust enteroctye unbound fraction can not fit the curve accurately, because of the ignorence of the  kinetic process. Furthemore, this adjustment also affects the eliminate phase of the curve which hardly be fitted well anymore.
lastly, the lysosome fractional volume of the enterocytes should be an important factor to consider.
So, I am trying to add an compartment as  lysosome between the lumen and the portal vein， inwhich the drug is bound by a first order kinetic rather than a zero oder. 
Regards.

**Comment by Yuri05** [comment]
@wdzth Closing. Please reopen if there are still any unanswered questions here
