### ISSUE TITLE
Regarding Renal tubular secretion process inputs

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#347]
Hello All,
Can anyone explain as to what this specifically means!!.
**You can also define a saturable tubular secretion process by specifying Km and TSmax values (either estimated or scaled from in vitro data). The specific tubular secretion rate is then calculated taking into account the kidney volume.**
I understand it is about transporters (OAT3/MAET2-K) involved in tubular secretion of the compound. For which we have Kmax and Vmax values for each transporter and using IVIVE we can estimate invivo CL specific to tubular secretion. Now my question is what are those values which should entered 
TSmax & Km here???

Any inputs will be of great help

Regards
Harish

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
