### ISSUE TITLE
OSP Suite Version 8 released

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Forum#349]
# Release Notes for the Open Systems Pharmacology Software Suite 8

## Important note – read BEFORE installation
[User Template Database migration from 7.3 (and below) to 7.4 and above](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Converting-User-Template-Database)

### (Re-)Qualification framework
A technical framework to assess the confidence of specific intended use of the OSP platform was developed (qualification runner and reporting engine). This framework allows for an automatic (re)-qualification workflow of the OSP suite, comprising the following steps:
-	PBPK model development and verification with observed data
-	Qualification plan generation
-	Qualification report generation

<p align="center">
<img src="https://user-images.githubusercontent.com/25061876/59437904-c1879100-8df2-11e9-92b9-54b407e29eee.png">
</p>

In a first step, the respective qualification scenario is saved in a special qualification repository on GitHub. This qualification scenario repository contains a detailed qualification plan that links and combines respective models and data to address the use case that shall be qualified. Therefore, the qualification plan consists of: 
-	PK-Sim project files (more precisely: PK-Sim project file [**snapshots**](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/importing-exporting-project-data-models#exporting-project-to-snapshot-loading-project-from-snapshot))
-	Description of potential cross-dependencies between PK-Sim project files (if adequate) (e.g. it is possible to inherit building blocks or simulation parameters)
-	Observed data sets (needed for model development and verification)
-	Qualification scenario description text modules
-	Detailed report settings to describe the generation of charts and qualification measures. 

PK-Sim projects, observed data sets, and qualification scenario text modules can, but not necessarily have to, be saved in their own/different repositories and then conveniently be referenced by the qualification plan.

<p align="center">
<img src="https://user-images.githubusercontent.com/25061876/59438295-833ea180-8df3-11e9-89c5-ac1f090e4305.png">
</p>

In the next step, the **Qualification Runner** (stand-alone tool) processes the qualification plan, i.e. all project parts are exported and prepared for the **Reporting Engine**. The Reporting Engine provides a validated environment (currently implemented in MATLAB®, a transfer to R is in development) for model execution and generates tables and figures for the final qualification report. This report contains the evaluation of the individual PBPK models with observed data (i.e. standard goodness of fit plots, visual predictive checks) and a comprehensive qualification of the specific use case assessing the predictive performance of the OSP suite by means of a predefined set of qualification measures and charts. 
The automated execution of the described workflow can be triggered to assess re-qualification in case new data, changes in model structure or parameterization, or new OSP suite releases arise.

### Supersaturation
**Supersaturation**, i.e. the concentration increase of a solution beyond its saturation, can now be simulated for the formulation type _particle dissolution_. The parameter can be found in the Advanced Parameters Tab of the Compound Building Block. If activated, the effective compound concentration in the intestinal lumen can exceed the solubility defined in the compound. The default value of this new parameter is false meaning that supersaturation is inactivated.
<p align="center">
<img src="https://user-images.githubusercontent.com/25061876/59669276-39223b00-91ba-11e9-9ecb-f7b6b6be3ee4.png">
</p>

### Observer in PK-Sim
Now it is possible to add custom observers in PK-Sim. Workflow for this:
1. [Create observer in MoBi](https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/model-building-components#observers) and export it to PKML
2. Add new Observer Building Block in PK-Sim
<p align="center">
<img width="400" src="https://user-images.githubusercontent.com/25061876/59692064-74d1fa80-91e4-11e9-8c29-c84f4ca91c98.png">
</p>
3. Import observer(s) previously exported as PKML in MoBi
<br><br><p align="center">
<img width="500" src="https://user-images.githubusercontent.com/25061876/59691305-1bb59700-91e3-11e9-84e3-b6b281d3dee7.png">
</p>
4. Add observers during simulation creation
<br><br><p align="center">
<img width="500" src="https://user-images.githubusercontent.com/25061876/59691857-05f4a180-91e4-11e9-8253-ea0f434833a5.png">
</p>
5. Select observers of interest as outputs
<br><br><p align="center">
<img width="500" src="https://user-images.githubusercontent.com/25061876/59692395-1d805a00-91e5-11e9-85e4-5bd28dbbd56d.png">
</p>

### Combination of user defined administrations with advanced protocols
<p align="center">
<img width="500" src="https://user-images.githubusercontent.com/25061876/59453196-a6774a00-8e0f-11e9-9229-b5e711edce91.png">
</p>

### Calculation of the **_Total_ fraction metabolized**
In the past fraction of metabolized dose could be plotted _per compartment_ only. 
Now it is also possible to show the **total** fraction metabolized (= sum of fraction metabolized over all compartments). It can be found under ```Organism/Total fraction of dose - <Compound name>```
<p align="center">
<img src="https://user-images.githubusercontent.com/25061876/59697680-97691100-91ee-11e9-856d-bbfe1f4d0c9e.png">
</p>

### PK-Sim and MoBi

* [Parameter Identification: allow multiple mapping of observed data sets](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/494)
* [Parameter Identification: dublicate names possible when cloning](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/477)
* [Fixed parameters flag is not included in the Parameter Identification export](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/485)

### PK-Sim

* [Figure in Formulation BB displaying Fraction dissolved has cropped x-axis title](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1263)
* [Cannot load population from CSV anymore](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1254)
* [Error recreating a popualtion simulation from snapshot](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1115)
* [Expression databse on share drive: sometimes, user can't open the file](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1073)
* [Transporter location disappears sometimea (Indiviudal Building Block)](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1149)
* [Names of parameters from Parameter Identification are exported to snapshot but not re-imported](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1183)
* [Parameter Identification: Error message for maximum value of meal energy content not clear](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/532)
* [Refresh problem: deleted curves remain in chart](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1019)
* [Error in comparison of compounds: e.g. differences of defaults are not displayed](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1027)
* [Working Journal name not displayed in the status line after project reloading](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1125)

### MoBi
* [(Re-)configuration of existing simulations](https://github.com/Open-Systems-Pharmacology/MoBi/issues/351)
* [Enable Sum Formula tag "within container"](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/534)
* [Improve sum formula](https://github.com/Open-Systems-Pharmacology/MoBi/issues/368)

### MoBi Toolbox for Matlab

* [Provide list of all effectively used parameters](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/59)
* [initSimulation with ExecutionTimeLimit appears not to work](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/67)

**Comment by StephanSchaller** [comment]
🎉 🍾
