### ISSUE TITLE
Blood to plasma concentration ratio

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/Forum#35]
As a follow-up to issue #232 in the PK Sim forum, when using Rodgers and Rowland, the manual states: "...additional input parameters are therefore necessary for the calculation of partition coefficients: the blood to plasma concentration ratios BPratio, as a measure for electrostatic interactions of drugs with acidic phospholipid..." and I'm just wondering where to input the BPratio when entering the compound's parameters?

**Comment by msevestre** [comment]
@mlcraig 
Probably the formulation is a bit misleading in the manual. 
There is another input parameter that is used indeed in the `Rodgers and Rowland` model called `Blood/plasma concentration ratio`

That bein said, unlike other parameter like `Mol Weight` or `Lipophilicity`, this parameter is estimated based on a model which is defined in the R&R paper (I may be wrong on that)

Take a look at that screenshot. You can access this parameter in the simulation and override the default calculated value if required

![image](https://user-images.githubusercontent.com/1041237/27772362-7adb971e-5f2e-11e7-8f36-3309454e201a.png)

**Comment by mlcraig** [comment]
@msevestre This is very helpful, thank you very much.

**Comment by msevestre** [comment]
@mlcraig any time :)
