### ISSUE TITLE
Use of Caco-2 permeability in PK-Sim

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#352]
Dear all,

Is there a way in PK-Sim to convert the Caco-2 permeability to intestinal permeability in PK-Sim? Basically something like what we have to predict permeability from MW and lipophilicity but using Caco-2 permeability. If this is not the case, I have seen in literature some correlation to get the effective permeability from the Caco-2 permeability. Since such relation has been obtained from patients directly, it is independent from the model and consequently it could be included in PK-Sim. 
This is the paper I am referring to:

https://rd.springer.com/article/10.1023%2FA%3A1020483911355

Do you any thought about that? I am very much open to your wisdom!

Cheers,

Donato

**Comment by regulus92** [comment]
Should intestinal transcellular permeability be optimized primarily through parameter identification when developing a p.o. model?

**Comment by AndreDlm** [comment]
Dear Donato,

I remember [this discussion](https://github.com/Open-Systems-Pharmacology/Forum/issues/23) which touched some of the questions you raised. It may help you.

Best wishes
André
