### ISSUE TITLE
Strange values for partition coefficient

### ISSUE THREAD

**Issue by MahmAbdelwahab** [Open-Systems-Pharmacology/Forum#353]
Hello,

I'm new to using Pk-sim, just practicing with a basic PBPK model for clofazimine, which his highly lipophilic drug that accumulate mainly in adipose and fatty tissues mainly metabolized by liver (Cl : 0.26 l/h/kg) 
given the published physicochemical characteristics of the drug,

Effective M.w: 429 (drug bank)
Fu : 0.01 (published study)
Logp : 7.66 (drug bank)
Water solubility : 0.233 mg/l (drug bank)
PKa is 8.6
When Pk-sim calculate  (B/P ratio and Pc's), it gives me strange values, for example the B/p value of > 1 (2615.2) which I know is not correct, but if I log10 the value I get reasonable values for B/p ratio and Pc's.

What I'm missing or doing wrong ?

Thanks 

Mahmoud

**Comment by StephanSchaller** [comment]
Some initial thoughts:

In our experience, DrugBank LogP is often too high by some margin. LogD (@pH 7.4) or LogMA is more likely to be the right input for PK-Sim.
Also an fu of 0.01 is probably measured with high uncertainty. Increasing fu should also lower B:P.

What Partitioning Calculation Method did you use? For a highly lipophilic drug, I would recommend Rodgers and Rowland.

If you have data for B:P try first setting R&R as the calculation method, then decrease lipophilicity (Calculated LogP of ~7 often compare to LogD ~5)  and maybe increase fu and see where you end up.


Hope this helps,
Stephan

**Comment by msevestre** [comment]
Please reopen if needed
