### ISSUE TITLE
Plasma albumin reference concentration in adults

### ISSUE THREAD

**Issue by eyun514** [Open-Systems-Pharmacology/Forum#354]
Hi folks,
I am looking for a plasma albumin reference concentration in a mean adult individual (30 yr, male). What I could find in the database was 1 umol/L. It is not in line with the literature value of 4.5 g/dL (Alcorn and McNamara (2002) AAPS Pharmsci 4, no. 1: 19-26). 
I'd appreciate your help if you could let me know the albumin reference concentration used in PK-Sim.

**Comment by msevestre** [comment]
Hi @eyun514 

>What I could find in the database was 1 umol/L.

Where did you find this value? More specifically, what actions did you perform in PK-Sim to see such a value for Albumin? 

Thanks,
Michael

**Comment by eyun514** [comment]
Hi Michael,
I created a mean adult individual. In the expression tab, I added albumin for 'protein binding partner'. 
![image](https://user-images.githubusercontent.com/4565717/60298071-a428eb80-98f7-11e9-9128-e23b47aa553c.png)

**Comment by prvmalik** [comment]
Binding to albumin is described by a constant fraction unbound in the compound building block. No explicit reference concentration is available in PK-Sim.

When you add a protein binding partner from the database where a reference concentration is not pre-populated (this applies for most if not all protein binding partners in the database), it will by default be set as 1 umol/L.

**Comment by msevestre** [comment]
@eyun514 

@prvmalik gave you `as always` the correct answer. This 1 is just the default value when there is no value available in the database

Note that binding to albumin is indeed defined in the compound building block and effectively affects fu as a function of age etc.. .Modelling explicitly binding to albumin in PKSim is not straightforward...at all

**Comment by eyun514** [comment]
Thanks for letting me know that 1umol/L is a default value not the albumin reference concentration in adults.

**Comment by StephanSchaller** [comment]
V. M. Rosenoer, M. Oratz, M. A. Rothschild, Albumin: Structure, Function and Uses.  (Elsevier, 2014).

on Pg. 232:

![image](https://user-images.githubusercontent.com/25477643/60399473-0c303980-9b65-11e9-8e85-c3a788283609.png)
