### ISSUE TITLE
Gestational age for a newborn

### ISSUE THREAD

**Issue by eyun514** [Open-Systems-Pharmacology/Forum#355]
Hi folks, 
Do anyone know a postmenstrual age (PMA) or gestational age (in weeks) for a full term neonate (post natal age of 1 day old) in PK-Sim? According to the PK-Sim manual, preterm infants' gestational age range is 24- 37 weeks. So if I create a newborn individual of 1-day-old, would the PMA be 37 weeks +1 day or 38 weeks +1 day? 

Thanks in advance!
E.

**Comment by prvmalik** [comment]
The mean gestational age at birth is 40 weeks, so this would be a safe bet.

**Comment by StephanSchaller** [comment]
And the preterm infants' gestational age range is 24- 37 weeks as birth after week 37 is considered birth on term (term-born neonate).

**Comment by eyun514** [comment]
Thanks for your help! I appreciate it.
