### ISSUE TITLE
Change Molecule in existing observed data block

### ISSUE THREAD

**Issue by wilbertdew** [Open-Systems-Pharmacology/Forum#361]
Hi all,

I would like to attach my previously imported data to a different molecule than the original molecule it was attached to, yet this seems to be the only thing that cannot be changed in the metadata in an observed data block in PK-Sim. Is there somehow a way to do this without re-importing the data?

Best,
Wilbert

**Comment by Incei** [comment]
**Not sure if it works**, but you could try change the original compound properties to the different molecule and rename it to the different molecule. (you would need to recreate/the the existing simulations though) 
The data-file needs the molecular weight to switch from molars to gram, if not hard-coded in the data-file, this may work..

**Comment by wilbertdew** [comment]
Thanks! That works in principle, but it does not solve my problem since I have multiple observed datasets of similar compounds all linked to one PK-Sim molecule. Now I want to give each dataset a separate PK-Sim molecule to allow for the small differences between compounds.

**Comment by Incei** [comment]
If the datasets belong to different molecules, it would be indeed cleaner then to reimport after all molecule building blocks have been created. This is unfortunately how it works currently (no possibility to import data without having the molecule building block first).

@sfrechen fyi

**Comment by wilbertdew** [comment]
Thanks, that's what I will do then :).
