### ISSUE TITLE
Correctly defining whole blood metabolism from half-life

### ISSUE THREAD

**Issue by Tpa3** [Open-Systems-Pharmacology/Forum#363]
Hi Everyone,

I was wondering if someone might be able to tell me if my methodology is correct for modeling metabolism of a compound in whole blood.

I currently have a half-life value for the stability of a compound in whole blood and would like to add it to my model as a metabolic process resulting in a metabolite. Unfortunately we do not know what the actual metabolic enzyme involved is.

This is my currently thought process:
To make things simple I am assuming all of the metabolism occurs in the plasma and is first order.
1. I can define a dummy enzyme in the plasma, and use the "In vitro clearance -First Order" as the metabolic process.

2. I can calculate the required specific clearance value using the half-life in the form _Specific Clearance_ = ln(2)/thalf * (body total plasma volume)/(volume of plasma in in-vitro incubation)

3. If I define the required Enzyme concentration parameter to be the same as the reference concentration  of the dummy enzyme(with 100% expression in plasma), it should not matter that I don't know the real concentration of the metabolizing enzyme, since I can assume that the concentration of metabolizing enzymes is the same in the in-vitro whole blood study and in the animal.

Would this be the correct methodology? I am somewhat confused about the definition of specific clearance used in the simulations. Using the method above it seems that I am vastly over predicting the metabolism of the compound (granted the PK data I have may be unreliable). 

Thanks!

**Comment by prvmalik** [comment]
I think you are on the right track. Just don't normalize the first order Kmet (specific clearance) by the volumes. Try:

1. Define dummy enzyme in plasma with reference concentration 1uM and use the in vitro clearance - first order as the metabolic process (as you have done).

2. Calculate specific clearance by using the half-life in the form:
CLspec = ln(2)/thalf

3. Double check that your half life and your CLspec are using the same unit of time measurement

4. Define the concentration of the dummy enzyme in the base individual = 1uM

And that should do it. Let me know!

**Comment by Tpa3** [comment]
Thanks for the quick reply @prvmalik !

I tried running the simulation without normalizing specific clearance to the volumes, and double checked the units. 

Unfortunately I now seem to have the opposite problem, the blood metabolism appears to have only a very small impact on the simulated profile. The compound in question has an extremely short half life <4min in whole blood so I am pretty confident that it should have a major impact on the model.

Perhaps I need to normalize my specific clearance value but simply normalizing by volume isn't enough? I know in the case of total hepatic clearance, when using the half-life versions of _in-vitro hepatocytes_ or _microsomes_ PKsim further normalizes specific clearance with fraction unbound and fraction intracellular, but in this case given that the blood used in the in-vitro study and the animal should be identical I don't feel it should matter.

**Comment by prvmalik** [comment]
OK, I could be wrong then and I will wait for another senior member to chime in.

In the meantime, other things to check are:
**Blood to plasma ratio in the simulations:** if the enzyme is only in plasma but the drug is in the blood cell portion, you will not have a strong metabolic rate.

**Distribution and LogP:** If the compound distributes extensively out of plasma, then that may explain why the metabolic enzyme in plasma may have a low impact on the overall PK-profile

**Comment by prvmalik** [comment]
I created a test compound:
MW 300g/mol, logP = 1, fu = 1, neutral, eliminated by plasma metabolism and GFR 1.0

I implemented the plasma metabolism with a CLspec of 0.17325 1/min

The test model is very sensitive to the plasma metabolism process. 

Turning the plasma metabolism off increases the half-life from 6.5 hours to 23.5 hours.

**Comment by Tpa3** [comment]
@prvmalik 
I feel that a half-life of 6.5 is very long for a compound with a plasma half-life of 4min, especially for a compound that has a fraction unbound of 1.

If we use your example and take this to the extreme, logP = -10, fu = 1 and set B:P ratio to 0, so that distribution into tissue is minimal and all of the compound is available for metabolism when in blood the terminal half life appears to be ~20min, which though much closer than before I feel is still somewhat high since I would expect it to be very similar to the plasma half-life. 

On a separate note I think I should be normalizing my specific clearance using the fu of the assay even though it is the same as fu in plasma, as you said in your post the metabolic process only takes into account the unbound compound. So I need to normalize/scale my specific clearance such that it appears without binding. So specific clearance should be something like CLspec = ln(2)/thalf *1/fu_assay_. However this does not seem to increase the rate enough to account for the difference I am seeing. 

I am still somewhat confused about what specific clearance is, it's described as "intrinsic clearance normalized to where the process occurs" when I hover over the parameter, but is it just the first order rate constant?

**Comment by prvmalik** [comment]
Hi @Tpa3 

I went into Mobi to bring out the formula for the reaction.

![CLspecformula](https://user-images.githubusercontent.com/29066045/61816182-d86dca00-ae19-11e9-838a-6db17986e678.JPG)

The CLspec ODE term in plasma is:
d/dt[Amount of Drug in Plasma] = EnzymeConc x DrugAmount x CLspec/EnzymeConc x K 

Where K is the Partition Coefficient (water/container). 

The K parameter can be found in Mobi with the path Organism|Organ|Plasma|CompoundName|PartitionCoefficient(water/container). 

Partition Coefficient (water/container) for the plasma in all organs is equal to fraction unbound. 

So yes, CLspec (1/min) appears to be a first order rate constant for the reaction that is multiplied by fraction unbound.

**Comment by prvmalik** [comment]
I believe I have identified the prevailing issue (in addition to the blood cell, logP and fu considerations above):

For small molecules, the interstitial spaces and plasma spaces are assumed to be rapidly mixed/equilibrated. Therefore you have drug in the interstitial spaces of all the organs that is not being metabolized. That is why in your test case with logP = -10 % fu = 1 the half-life is around 20min rather than 4min. 

Setting B/P ~0 and adding the enzyme into the interstitial spaces of all organs as well as into plasma results in the desired half-life of 4min. 

With that said, you will have to decide whether it is physiologically relevant to have the dummy enzyme present in both plasma and interstitial spaces (or blood cell spaces, for that matter).

Pleasure discussing this with you!

**Comment by Tpa3** [comment]
@prvmalik 
That definitely makes sense! I am definitely learning a lot. Thank you!

However I am curious how you were able to get a 4min half life, using the same model as before (logP = -10; fu = 1;B/P =0) with the dummy enzyme added to the organs tissues and matrices with the localisation set to interstitial I get a half life of ~1.6min. Definitely much closer to 4min, but it's proportionally less than half of expected half life. Theoretically in this case I would expect it to be impossible for the half life to be less that the 4min if the reference concentration and enzyme concentration parameter in the metabolic process are the same and no other clearance process is added.

**Comment by prvmalik** [comment]
There are two reasons for this:

First, the dummy enzyme concentration in the interstitial compartment of every organ is scaled by (f_cell/f_int) where f_cell is the cellular fraction and f_int is the interstitial fraction. You end up with higher enzyme concentrations in the interstitial space and thus faster metabolism.

Second, the K PartitionCoefficient(water/interstitial) is set to fu/K_int_pls where K_int_pls is the PartitionCoefficient(interstitial/plasma). In the example case, the K works out to 1.04, increasing the metabolism by 4%.

Setting both of these parameterizations to 1 gives a half-life of 3.97min.

**Comment by Tpa3** [comment]
@prvmalik 
Sorry for the late reply, but this was very helpful! I was able to get the same result.
Looks like I still have a lot to learn about how enzyme concentrations are defined in PKsim and MoBi

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
