### ISSUE TITLE
Impact of CYP & P-gp on bioavailability

### ISSUE THREAD

**Issue by RobinPharma** [Open-Systems-Pharmacology/Forum#364]
Hello OSP !

I am currently working on a project with compounds that are both P-gp substrate molecules and are metabolized by CYP3A4. Some of these compounds show very low bioavailability in vivo. I am interested in using the software to determine the impact of P-gp and CYP3A4 (isolated AND combined) on bioavailability and particularly on first pass gut effect. 

Has anyone tried to do this before? If so, could you share your conclusions and the information of how to explore it in PK-sim?

Many thanks in advance

Best regards,

Robin

**Comment by StephanSchaller** [comment]
Hi Robin,

I am not aware of any work that explicitly looks into estimating the impact of first-pass CYP3A4 metabolism and P-gp transport. 
Needless to say, the impact would be compound-specific depending on the actual intestinal metabolization and transport rates.

The closest to what you are looking for is a very recent publication on CYP3A4 and P-gp DDI in PK-Sim: https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues/191
All associated model files are available for download.


Within PK-Sim, there is no direct way to separately assess impact of the different routes (e.g. intestinal vs. hepatic) either with a sensitivity analysis or a population simulation, but you can do so after exporting the model to MoBi.

You could, of course, also do this via the Matlab or R interface with your own scripted sensitivity analysis.

Hope this helps as a start,
Stephan

**Comment by Aedginto** [comment]
Hi Robin
Yes, I have certainly done this a number of times (not published). Setting up your simulation appropriately with distinct CYP3A4 and Pgp processes is the first step with associated relative expression of each protein defined using the GeneDB included in PK-Sim or using other sources (Protein Atlas). How you define the relative importance of each process is of course dependent on the information that you have available to you (in vitro assay, in vivo PK in presence and absence of 3A4 and/or Pgp inhibitors) and I couldn't possibly tell you how to do this without knowing the data that you have. Once you have a model set up, turning on and off the intestinal component of Pgp and/or CYP3A4 can be done by modifying the relative expression of each protein and assessing the outcome of interest (F, AUC, Cmax). 
Take care,
Andrea

**Comment by StephanSchaller** [comment]
Yes, @Aedginto is certainly right. You can do it in this very convenient way by simply changing the expression values. Thanks for adding this. I was somewhat in the automated relative assessment mode.

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help

**Comment by NataliaRivaSJ** [comment]
Hi all, thank you for the discussion. @Aedginto Would you turn off (0%) in the relative expression of CYP3A4 at the expression profile block level in the organ (i.e., all intestinal mucosa), instead of 7% for human ? Correct?
Thank you in advance for your help
