### ISSUE TITLE
Integration of Reduction to active metabolites in PK-Sim

### ISSUE THREAD

**Issue by Ilyrub** [Open-Systems-Pharmacology/Forum#367]
Hello

For my model I want to integrate a reduction to active metabolites, which I also characterized as compounds. The integrated warfarine model in Pk-Sim, which also includes a reduction, was not helpful for me because the reduction was characterized by biliary clearance.

Is there a possibility to integrate a reductase like a cyp-enzyme, because my data is based on liver microsomes and in Pk-Sim, I can only use the content of cyp proteins in liver microsomes?

Thanks in advance

**Comment by tobiasK2001** [comment]
Dear llyrub,

I am not sure if I get your question and what do you mean with 

> The integrated warfarine model in Pk-Sim, which also includes a reduction, was not helpful for me because the reduction was characterized by biliary clearance. < 

 The intergrated warfarin models has 3 clearance processes: 
1.) via CYP2C)
2.) vio total liver Clearance (this seems to be deduced from "reduction to alcohols" 
and 3.) renal plasma Clearance.
![image](https://user-images.githubusercontent.com/25585248/62123602-94bb0a80-b2c8-11e9-9a29-317b5c4fd721.png)

Of course you can easily add further CYP enzyme. Just go to your Individual BB and add the e.g. from the PK-sim expressiondatabase. If you want to adjust your CYP-protein expression (apart from the CYP-content per mg microsomal protein) you can also there or adjust reletive expression per organ:
![image](https://user-images.githubusercontent.com/25585248/62123872-29256d00-b2c9-11e9-957e-62fcb17cb406.png)

check out also the video tutorial for details here
https://github.com/Open-Systems-Pharmacology/Forum/issues/279

Hope this might help you.

Best, Tobias
