### ISSUE TITLE
Location of examples projects for PK-Sim and MoBi

### ISSUE THREAD

**Issue by zt1947** [Open-Systems-Pharmacology/Forum#37]
how do I download the example files, e.g. those used in the manual to exercise Parameter Identification

**Comment by msevestre** [comment]
@zt1947 All example files can be found in the AppData of the application, typically `C:\ProgramData\Open Systems Pharmacology\MoBi\7.1` or `C:\ProgramData\Open Systems Pharmacology\PK-Sim\7.1`

You can also access these folders directly from the Windows Application Menu, under Open Systems Pharmacology. I think there are 2 menu entries for PK-Sim and MoBi examples respectively called `PK-Sim Examples` and `MoBi Examples`.

Hope that helps

**Comment by zt1947** [comment]
Dear Michael
Thanks!
It works OK
Sincerely
Zvi

**Comment by msevestre** [comment]
Do you mean that your installation issues are solved? (#36)

**Comment by zt1947** [comment]
Not yet. I"ll get to yhis only much later today.
I"ll obviously let you know how this issue develops.
I meant that I did locate the Example files.
Zvi

**Comment by dineshbcp** [comment]
Dear Michael,

How to input Digitilized IV Data and how it Calculate Pharmacokinetics Parameters.
Further How to Compare Observed and Predicted Plasma Profile

**Comment by StephanSchaller** [comment]
Hi Dinesh,

best open a new issue for every question you have. So we can keep track what questions are solved.

You can input observed data from e.g. excel sheets via data import by e.g. richt-click on the observed data import and:
![image](https://user-images.githubusercontent.com/25477643/40273110-880ff180-5bba-11e8-994a-33fcde972a97.png)

Once you have simulated your experiment you can then drag&drop the loaded data from there into your plot window to compare it against simulated data. Also, below your Plot, you will find a large "button" that reads "Show PK Data" where you find calculated PK parameters.

As a Beginner, I wpuld advise you to firs do a couple of Tutorials, see [here](http://www.open-systems-pharmacology.org/#tutorials)

Best,
Stephan

**Comment by dineshbcp** [comment]
Dear Sir,

Thank You for information, as advised will go through available tutorials.

Thanking you once again.
