### ISSUE TITLE
Standard Compartmental Models

### ISSUE THREAD

**Issue by delbenef** [Open-Systems-Pharmacology/Forum#374]
Hi All,

I was wondering whether it is possible to fit standard compartmental models within PK-Sim.

Many thanks for your feedback.

Kind regards,
Francesca

**Comment by PavelBal** [comment]
PK-Sim always creates a ful PBPK model. You can build compartmental models in MoBi and fit them there.

**Comment by delbenef** [comment]
Thank you so much for the information.
