### ISSUE TITLE
Exporting Graphs from PK-Sim including observed Data

### ISSUE THREAD

**Issue by BoomShooter** [Open-Systems-Pharmacology/Forum#377]
Hey guys, 
I was wondering whether its possible to include the graphs for observed Data when exporting it out of PK-Sim via the "Report". I know that the values are included when exporting it via Excel, but it seems like an unnecessary extra step, since I want to export the graphs the way they look in PK-Sim.
Best Regards
Yusuf

Edit: spelling

**Comment by msevestre** [comment]
What about copying the graph to clipboard instead?

**Comment by BoomShooter** [comment]
thanks for the fast answer @msevestre, 
I have to admit that I hadnt tried that yet and it really copies everything, but now the "Draft", which is across the picture bothers me. Is there a way to remove it?

**Comment by BoomShooter** [comment]
![Clipboard copy](https://user-images.githubusercontent.com/53944420/63935268-66faea00-ca5d-11e9-820e-4357bb295732.png)

**Comment by BoomShooter** [comment]
ok, I found it under the options menu, my mistake, didnt recognize it as a watermark.
thank you very much!

**Comment by msevestre** [comment]
No problem. If you go the chart settings, you will see a section called export settings or something like that. There, you can specify how the graph will look when exported to clipboard (e.g. change fonts, size etc..)

**Comment by BoomShooter** [comment]
ok nice :D
