### ISSUE TITLE
A problem on the clearance pattern of a drug when start work with MoBi 8

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#378]
I am a fresh user of OSP software, when I am learning MoBi 8 I encounter a problem.
In the expamle in the **Documentation -> MoBi Documentation -> First Steps** (https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/first-steps), molecule A and B had been created and A was to be converted to B with the PK profie like this:
![image](https://user-images.githubusercontent.com/54141158/63994696-21efba00-cb28-11e9-8715-28b6f156f0ce.png)
However, after I copy these settings and run it, the result is this:
![image](https://user-images.githubusercontent.com/54141158/63995201-4ba9e080-cb2a-11e9-984e-71a603d307b9.png)
Why is molecule A cleared  as a linear pattern when dN/dT has been defined as A*K1 and all the steps has been set the same with the guidance?

**Comment by wangwei1619** [comment]
Sorry, I make the scaling pattern of Y axis wrong!

**Comment by StephanSchaller** [comment]
Yes, your y-axis is in log scale ;-)
