### ISSUE TITLE
Default for Solubility gain per charge in the Compound block

### ISSUE THREAD

**Issue by TatianaAlieva** [Open-Systems-Pharmacology/Forum#38]
Hi to everybody,
Excuse me, what rational is behind the default value of 1000 for Solubility gain per charge?
Thank you in advance!!

**Comment by Yuri05** [comment]
The logP is typically reduced by 3-4 units. 
According to our observations, however, it is mostly near 3 (factor 1000). 
Since solubility is reciprocal to lipophilicity, a solubility increase of 1000 is assumed.

**Comment by TatianaAlieva** [comment]
Hi,
when I asked, I hoped to learn a new thing for myself, and not to make another argument here. However, this answer is in obvious contradiction with solubility and LogP octanol-water definitions. So, I clarify this, but I will not argue further. 

Aqueous solubility is not reciprocal to LogP.
Solution process is a transfer from pure liquid state of the solute to solution (aqueous in our case). Solution energy can be represented as
Gsolution=Gvaporization+Gsolvation_in_H20
(Solvation is the gas-to-solvent transfer according to IUPAC).
In contrast, octanol-water partitioning refers to transfer: solution in water ->solution in octanol
Go-w= Gsolvation_oct -Gsolvation_in_H20
A very good diagram illustrating the difference between solubility and partitioning is represented in Zhang and Gobas (1995), Fig 2.

The first terms in the eqs. above (Gvaporization and Gsolvation_oct) are not negligible, therefore LogS and LogP are not reciprocal.

Further,

>The logP is typically reduced by 3-4 units. 

I guess you mean here that LogP for the ionized species is typically 3-4 units lower than that one for the neutral one, correct? Therefore LogD never goes 3-4 units below logP at any pH.
As far as I understand, this property is related to solvation in octanol process (because the residual water in octanol ~2,5%; high dielectric constant, due to which octanol effectively stabilizes charged species, so on) .
Therefore the observed relation between LogP and LogD has nothing to do with solubility limitations for electrolytes.

**Comment by JLPangloss** [comment]
Dear Tatiana,

the implemented heuristic is a pragmatic approach to improve rough estimates for solubility in absence of experimental data we recommend to use. When solubility is of concern for project reasons we suggest to measure dissolution in FaSSIF / FeSSIF and to potentially characterize pH dependence of solubility also experimentally.  

More sophisticated prediction models were not implemented in PK-Sim since you could easily input predictions from dedicated in-silico tools into PK-Sim as a table - like we do with experimental data.

Best wishes
Jörg

**Comment by msevestre** [comment]
Upcoming version 7.3 will include a way to load a Table pH vs Solubility. This will be very easy to override the default behavior if required
