### ISSUE TITLE
How to construct a comparision between population simulations?

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#380]
Hi, all,

I have three simulations for three kinds of formations of the same molecule on one defined population, but I can't compare them or put them in one plot. Do I neglect something?

![image](https://user-images.githubusercontent.com/54141158/64609247-1db47e00-d3ff-11e9-9990-b38978a97b4f.png)
![image](https://user-images.githubusercontent.com/54141158/64609277-33c23e80-d3ff-11e9-8dd4-30ae920a6555.png)

**Comment by wangwei1619** [comment]
The version is PK-Sim 8.0

**Comment by msevestre** [comment]
@wangwei1619 What parameters did you select in  `Output` and `Population Parameters`? Can you show us a screenshot?

**Comment by msevestre** [comment]
Also please check the docs here for more info https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#comparison-chart-for-individual-or-population-simulations-in-one-plot

**Comment by wangwei1619** [comment]
I just select plasma concentration in 'Output' and no parameter in 'Population Parameters' like this
![image](https://user-images.githubusercontent.com/54141158/64661514-88090500-d477-11e9-91e6-94a17139a965.png)
![image](https://user-images.githubusercontent.com/54141158/64661518-8b9c8c00-d477-11e9-88f3-b8d16918daa2.png)
, because I just want to put concentration versus time profiles together, like this:
![image](https://user-images.githubusercontent.com/54141158/64661572-cdc5cd80-d477-11e9-80fd-d7005a4dc8bc.png)
(Manuel Ibarra, et al. 2018.)

**Comment by msevestre** [comment]
Is there a way you can attach the project so that I can check what's going on?

**Comment by wangwei1619** [comment]
Here is the link: https://github.com/wangwei1619/Learnin-PBPK-PK-Sim
I wish I make this link right~

**Comment by wangwei1619** [comment]
Hi, @msevestre .Thanks for your zealous concern on my question. Is there anything wrong in my work?
