### ISSUE TITLE
How to define the parameter 'Solubility gain per charge'

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#381]
Hi, all
Since I don't need to define any parameter related the ionization step of a molecule, what is this parameter **Solubility gain per charge** used for? Is it OK to always keep the default value of it?

**Comment by HenrikCordes** [comment]
Dare @wangwei1619,

the parameter "Solubility gain per charge" is only of relevance if you have a charged molecule. 
It basically scales the given solubility value with respect to the charge, depending on the pH. 

Kind regards,
Henrik

**Comment by wangwei1619** [comment]
Dear @HenrikCordes 

Thanks for your answer. May I judge your mean as this parameter is for some molecules whose active form is being charged? Could you please give me some example of this kind of drug, because I am not familiar with this field?

Best regards,
Wang Wei

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
