### ISSUE TITLE
How to correctly simulate an oral administraion with the formation as table?

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#382]
Hi, all
 
I am following a simulation in one paper (Manuel Ibarra, Cristian Valiante, Patricia Sopeña, et al. Integration of in vitro biorelevant dissolution and in silico PBPK model of carvedilol to predict bioequivalence of oral drug products. European Journal of Pharmaceutical Sciences, 2018,118: 176-182).
In this paper, author input the **Formulation** as a **Table** of an in vitro dissolution result which mimics the time and pH when drug goes through GI tract like this :

![image](https://user-images.githubusercontent.com/54141158/64752163-17361b80-d551-11e9-9ae3-3ebf73801358.png)
![image](https://user-images.githubusercontent.com/54141158/64752175-21f0b080-d551-11e9-86af-79acab19e98d.png)

I define the **Administration Protocol** as **User Defined** with **Target organ** as **stomach** , **Target compartment** as **plasma** and I also use the same dissolution tale in **formulation**. Finally I get a similar but moderately different result in plasma concentration profile like this:
![image](https://user-images.githubusercontent.com/54141158/64752687-0a1a2c00-d553-11e9-8063-a6867ba088f3.png)

I want to ask if there is any way more acceptable to simulate these data?

**Comment by wangwei1619** [comment]
Maybe I can share some development by myself after several days of trying.

In **Events** building block in **MoBi**, I changed the  value of **Use as Suspension** to 0, resulting in the parameter **Tablet_Location** increasing druing simulation. Each **Tablet_Location** value is responsible for just one GI segment where drug release takes place as if drug would be dissolved in different segments at different time.
^^^^
However, simulation result get worse even though I think this change is an improvement.
![image](https://user-images.githubusercontent.com/54141158/65245517-5a7b2600-db1f-11e9-954f-2e1d824b0cd8.png)

**Comment by wangwei1619** [comment]
Thanks for your helpful comment. And Is there any way to change the **Use as Suspension** value in PK-Sim?
I forgot to mention that I changed the **Administration** as Oral in the simulation result posted yesterday (2019/09/19), and result tended to be worse. Today, I try making **Administration** as **User defined** with the target as Lumen->Stomach, **Use as Suspension** activated or deactivated, and I get  similar results, still bad.
However, I find when I use this approach, there is no parameter related to drug release existing in **Applications**. What is the difference between this approach and normal oral setting?

**Comment by Yuri05** [comment]
> I try making Administration as User defined with the target as Lumen->Stomach

Don't. Creating a user defined administration into Stomach would be equivalent to:
* the tablet does not leave the stomach at all
* the tablet dissolves in stomach according to the selected formulation
* only the dissolved drug is moved along the lumen

Not really a realistic scenario. And **Use as suspension** parameter does not have any effect here.
Instead, use an **oral** administration in combination with a **table formulation**.

>Is there any way to change the Use as Suspension value in PK-Sim?

Yes, you will find it either in a formulation building block, or in a simulation under formulation properties.

![grafik](https://user-images.githubusercontent.com/25061876/65308203-d611bd00-db89-11e9-8aa3-14fffd613619.png)
![grafik](https://user-images.githubusercontent.com/25061876/65308361-34d73680-db8a-11e9-81a8-f80b1105e828.png)

**Comment by wangwei1619** [comment]
Thanks for your help!!

**Comment by wangwei1619** [comment]
Here I come again. When I read the paper _Willmann, S.; Schmitt, W.; Keldenich, J.; Dressman, J. B. A physiological model for simulating gastro-intestinal flow and drug absorption in rats. Pharm. Res. 2003, 20, 1766-1771._, I am wondering: does these formulas below apply to the condition that **Use as Suspension** is activated (set to 1),
![image](https://user-images.githubusercontent.com/54141158/66456612-a8d97000-eaa0-11e9-9062-ceed1cde0b25.png)
![image](https://user-images.githubusercontent.com/54141158/66456580-99f2bd80-eaa0-11e9-8463-798c90568b8e.png)
with the [1-fabs(z,t)] replaced by the dissolution process selected (Weibull / Table / …)?

**Comment by teutonicod** [comment]
Hi @wangwei1619,

The model described in the paper you mentioned is the old model implemented in PK-Sim. Please refer to the following paper for the current gastro intestinal model
- _Evolution of a Detailed Physiological Model to Simulate the Gastrointestinal Transit and Absorption Process in Humans, Part 1: Oral Solutions_  by Thelen et al.
- _Evolution of a Detailed Physiological Model to Simulate the Gastrointestinal Transit and Absorption Process in Humans, Part II: Extension to Describe Performance of Solid Dosage Forms_ by Thelen et al.

These papers describe the case when the "Use as suspension" is not activated. In this case the tablet is considered as a single dosage unit that transit trough the intestine releasing the drug. This means that there is a discrete transition between one segment and the other of the intestine. When on the other side the option "use as suspension" is activated, the solid dosage form is instantaneously desegregated and the single units transit trough the intestine. So in this case the transition from one segment and the other does not occur at the same time for all dosage units, providing more realistic release behavior. The description of the option "Use as suspension" was not described in any publication, as far as I am aware.
In both the situations, the release from the dosage form is defined by the formulation function (Weibull, table,...).
Hope that it helps!
Donato

**Comment by wangwei1619** [comment]
Dear Donato,
Thanks a lot for your help. I will read the papers you suggest.
On the other hand, is there any paper illustrating the formula when "use as suspension" is activated?
Best regards,
Wang Wei

**Comment by teutonicod** [comment]
Hi @wangwei1619,
As I mentioned, I am not aware of any publication describing the "Use as suspension".
Donato

**Comment by wangwei1619** [comment]
Hi, Donato,
Thank you a lot for your help again!!
Wang Wei

**Comment by wangwei1619** [comment]
Here I come again.
After I change the distribution model to PK-Sim standard model (different from the input of literature), the result tends to be much better!!
![image](https://user-images.githubusercontent.com/54141158/66913279-e4e37680-f046-11e9-974a-53245c8cfdd1.png)
The C_max is almost double of that from Poulin & Theil model, and the t_amx is much advanced.
I think the potential reason is the fu of carvedilol is 0.0054, very small, so that its concentration should be infunced by protein constituent. PK-Sim standard distribution model takes account the protein as a separate compart, so its simulation is more accurate in this case.
However, when I compare these two simulations in MoBi, I find the **Partition coefficient (blood cells/plasma)** defined in **molecule** in both simulations is equal with the same formula taking protein into the account. Besides, in **organism**, there are **Vf(water, plasma)** and **Vf(water, plasma)-P-T**, defining the fractional volume content of water in plasma used in PK-Sim standard and Poulin & Theil model respectively, but in somewhere, e.g. **partition coefficient (interstial/plasma)**, only **Vf(water, plasma)** is used in both models. So, where is the difference between these two models embodied actually in PK-Sim or MoBi?

**Comment by Yuri05** [comment]
@wangwei1619 Dear Wang Wei, it seems to me that the last question is not directly related to the current discussion thread. Then please open a new issue for this. Having 1 topic per issue makes discussions much easier to follow. Thank you.
