### ISSUE TITLE
Volume distribuition

### ISSUE THREAD

**Issue by AParisotto** [Open-Systems-Pharmacology/Forum#384]
Hello everyone, I would like to know how to add the volume distribution parameter, this parameter related to the compound.

**Comment by msevestre** [comment]
@AParisotto Vd is typically an output of your simulation in PBPK
You can check out the online documentation, especially the section about PK-Analyses

https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#pk-analysis-view

Hope that helps,

Michael

**Comment by AParisotto** [comment]
Thanks Michael for the answer, I am starting to learn PBPK modeling. taking advantage, another parameter that I doubt is the Delay Time or T lag. Related to the studied compound, is this value added before the model? and where would it be inserted?

**Comment by StephanSchaller** [comment]
Hi @AParisotto , ideally please open a new issue for each question (so others can also search for answers to specific topics).

Tlag could be a property of an absorption process, i.e. an oral formulation? In this case you can set a lag-time in some of the pre-define formulations (Weibull, lint80 or explicitly in a Table format)  from which you can select in PK-Sim:

https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-formulations#definition-of-new-formulations-in-pk-sim-r
