### ISSUE TITLE
Two questions on the drug transportation in lumen

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#385]
Hi, all
When I compare two neighborhoods in simulation:
![image](https://user-images.githubusercontent.com/54141158/65246291-cf9b2b00-db20-11e9-8919-7e08e35605a4.png)
![image](https://user-images.githubusercontent.com/54141158/65246339-ea6d9f80-db20-11e9-96ed-f65ecbeb775c.png)
Since both of them are related to GI tract, why does only this stomach-to-duodenum one keep parameter?

The second question is based on this:
![image](https://user-images.githubusercontent.com/54141158/65246983-281ef800-db22-11e9-85bc-a3a08ba5ff2b.png)
Where is the value of the parameter **M** in formula references defined? Is it equal to the  integration of  **TabletDrugReleaseXX** in **Applications**.

**Comment by Yuri05** [comment]
>Since both of them are related to GI tract, why does only this stomach-to-duodenum one keep parameter?

`Oral mass absorbed` represents the **total** mass absorbed for the given compound and thus is defined **only once per compound**. 
The decision to put it into the neighborhood `Lumen|Stomach` ◀️▶️ `Lumen|Duodenum` was more or less random. 

>Where is the value of the parameter M in formula references defined?

"_M is defined as .._" means: M is the molecule amount of the parent molecule.

**Comment by wangwei1619** [comment]
Thanks for your help. 
However, as I didn't find any parameter related to amount in parent molecule, can I judge the amount 
equal to sort of integration of **TableDrugReleaseXX** in **Application**?

**Comment by Yuri05** [comment]
>I didn't find any parameter related to amount in parent molecule

Molecule amount is not a parameter. It is the (time dependent) value of the molecule amount.
Which is the result of solving the underlying ODE system.

S. MoBi documentation for details.
https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/building-block-concepts#molecules
https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/model-building-components#molecules

**Comment by wangwei1619** [comment]
Thanks for your help!!
