### ISSUE TITLE
Unable to capture PK profile in IV admin

### ISSUE THREAD

**Issue by J-Herz** [Open-Systems-Pharmacology/Forum#386]
Hi,

I am working on a project where I have PK data from IV and PO administrations across 4 pre-clinical species (mouse, rat, beagle, monkey). However, I'm not able to capture the shape of the PK profile for the IV administration - I can achieve a fairly good fit for the mouse data but in rat, dog and monkey I either see an overprediction of the initial rate of clearance (2-8 hours), or an underprediction of the terminal phase of clearance (8-24 hours).

I've tried multiple sensitivity analyses which bring up the usual suspects - the model is sensitive to clearance parameters, lipophilicity and fraction unbound however multiple parameter identifications later my fit is not much improved. I also tried switching from a first order hepatic clearance process (based on liver microsome data) to a saturable process through the addition of an arbitrary enzyme using Michaelis-Menten kinetics expressed only in liver. Identification of Km and VMax simply removed the saturable element by increasing VMax to the maximum allowed value. I also added a first order GFR clearance (compound is known to be subject to significant renal clearance) in conjunction with saturable enzymatic clearance but once again parameter identification reverted to using only first order clearance processes by turning up renal clearance and reducing the rate of enzymatic clearance to minimum.

I've also tried varying calculation methods for partition coefficients; again, this leads to some improvement in fit but the overall shape of the PK profile is not captured. I've included an example picture below, unfortunately I'm not able to share the model itself or the input parameters. I am very new to PBPK modelling and PK Sim so would really appreciate some help on how to further improve the fit, my instinct is some sort of non-linear clearance is needed but I'm not sure how best to implement this in PK Sim.

Thanks in advance for your help

![Monkey IV best fit](https://user-images.githubusercontent.com/54309920/65414703-212b0a80-ddec-11e9-94fc-3bb145961b33.PNG)

![Monkey IV best fit linear](https://user-images.githubusercontent.com/54309920/65414916-8f6fcd00-ddec-11e9-8d0b-fd6037184ace.PNG)

NB: This is the best fit I have achieved to monkey PK data. In this case I did not include any renal clearance processes and the identification has actually used a saturable clearance process, but I can achieve a similar fit using first order clearance process.

**Comment by tobiasK2001** [comment]
Dear J-Herz,

on the first glance I would think this does not look to bad. If you receive similar fits with saturable and linear clearance processes, this means that you do not have enough data to inform a saturable clearance process. E.g. iv data over 3 different doses in on species would be good to have here.
In your case I would leave the linear process follow occams razor.
To give you more hints I would need more details like: is that mean data or single animals? fasted/feed? What time was feeding after dose. Exact application rout: bolus or infusion (which infusion time). Is the time of sampling exact time or nominal sampling time. The inital part of the simulation might differ if this is not accounted for.

Hope that might help you.

Best, Tobias

**Comment by J-Herz** [comment]
Hi Tobias,

Thanks for the quick response, I'll give a bit more information for your queries where I have it myself

- The observed data is mean data, I do have access to the individual animal data, inter-individual variability was very high and only 3 animals dosed for each study. Perhaps it would be worth modelling each animal individually to see if they high variability is resulting in the mean data not being representative of the shape of the individual PK profiles - I will try this and come back with results.
- The administration was IV bolus and sampling time is nominal not exact so as you suggest this could affect the first timepoints.
- Unfortunately I don't have information on the fed/fasted state of the animals.

In the rat only I have PK data for 2 IV doses (0.5 mg/kg and 1 mg/kg), all other species only a single dose

I agree the fit is not too bad, but I was hoping to use identified parameters to model oral PK and then translate to human to predict human PK after oral dosing. I am not confident in validity of this approach if I cannot capture PK profile well even for the IV administration. I did some PK modelling in R and achieved good fits in all species with a 2-compartment model so I will fall back on this option if I cannot get similar fits using the PBPK approach.

Thanks

**Comment by msevestre** [comment]
@J-Herz 
> I did some PK modelling in R and achieved good fits in all species with a 2-compartment model so I will fall back on this option if I cannot get similar fits using the PBPK approach.

PBPK describes mechanistically what's happening in the body. This is not a fit. If you just need to describe the data, you do not need PBPK. if you need to extrapolate between species, play with different what-if scenarios, then PBPK is your tool. I'd suggest checking the PBPK introduction in the online documentation https://docs.open-systems-pharmacology.org/mechanistic-modeling-of-pharmacokinetics-and-dynamics/modeling-concepts/modeling-concepts-pbpk-modeling-systems-biology

**Comment by msevestre** [comment]
@J-Herz Please reopen if you need more help
