### ISSUE TITLE
 Anatomical and physiological parameter values for humans in PK-Sim

### ISSUE THREAD

**Issue by delbenef** [Open-Systems-Pharmacology/Forum#389]
Dear All,

From PK-Sim settings, I see a liver blood flow of 0.43 L/min for a 30 years old European male, which surprise me respect to the 1.2-1.5 L/min for healthy men. Am I missing something here?
I was wondering if someone could provide me with the reference paper for all the anatomical and physiological parameter values for humans in PK-Sim.
Many thanks in advance.

**Comment by JanSchlender** [comment]
Hi delbenef,
Since the liver is perfused by the hepatic artery and the portal vein, you need to add the blood flow of the splanchnic organs to account for the entire hepatic perfusion. Details are descibed here: https://www.ncbi.nlm.nih.gov/pubmed/16984214 
Best, Jan
