### ISSUE TITLE
Why each compound has to have a unique administration protocol?

### ISSUE THREAD

**Issue by TatianaAlieva** [Open-Systems-Pharmacology/Forum#39]
Excuse me, why **create simulation** chart does not allow the same administration protocol for several compounds? Is there a reason for this limitation in the software?
In my case I needed to create artificially quasi-identical protocols in order to simulate (quasi) the same dose for several drugs. 
Thank you!

**Comment by msevestre** [comment]
@TatianaAlieva The administration protocol is independent from the molecule. You can definitely use the same protocol for different compounds. 

Now,  if you are modeling multiple compound at the same time within ONE simulation (for example for DDI or Parent Metabolite models), the same protocol cannot be used for multiple compounds. This is a technical limitation that is more a theoretical limitation really. In general, different compounds have different dosage so you would practically very rarely want to use the same protocol for two different compounds

**Comment by TatianaAlieva** [comment]
Thank you!
