### ISSUE TITLE
Protein binding partner in interstitium vs extracellular membrane

### ISSUE THREAD

**Issue by wilbertdew** [Open-Systems-Pharmacology/Forum#390]
Hi All,

I was wondering what makes up the difference in PK-Sim between expressing a protein binding partner in interstitium or in the extracellular membrane. I am using the large molecule model.
I guess one of the differences is that membrane proteins are stationary in PK-Sim while interstitial proteins are not. 
I noticed that the reference concentration that is given as parameter value is actually set as the concentration in the intracellular fraction of the organ, but is present in the interstitium at a different concentration when interstitial and intracellular fractions are not equal to each other. This does make sense to me, but after playing around with interstitial (and consequentially, intracellular) fractions I noticed that the intracellular "Volume of protein container" is equal to the organ volume and different from the "Volume", while for interstitial these volumes are equal to each other. Do I need to worry about this last observation? I am also asking this because I observe counter-intuitive results when changing interstitial fraction and protein reference concentrations: when I increase interstitial fraction (and therefore decrease intracellular fraction) I also increase the protein reference concentration to keep protein amount in the tissue constant. This is confirmed by plotting interstitial protein amount. Because of the increased interstitial volume, the protein concentration is now decreased, but I see an increased depletion of my drug from the systemic circulation.
Any thoughts on this are appreciated!

**Comment by wilbertdew** [comment]
The last part of my question about the counter-intuitive results is solved in the mean time :)

**Comment by StephanSchaller** [comment]
Hi @wilbertdew , 

in both cases, the proteins are stationary. Proteins are only floating, if you define them as a compound.

The difference in expressing a protein binding partner in Interstitium or in the extracellular membrane should be that you also define expression on vascular endothelium (in case expression there is not equal zero). Depending on how you set localization in vasc. endoth. values will be added to plasma or interstitial expression.
How the reference concentration (tissue) will be used to calculate compartment-specific concentrations is best checked when looking at the parameter "Relative expression out." in the "Parameter Start Values" Building Block.

Hope this helps.
Stephan

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
