### ISSUE TITLE
Changing lymph flow proportionality factor

### ISSUE THREAD

**Issue by wilbertdew** [Open-Systems-Pharmacology/Forum#393]
Hi All,

I want to increase the lymph flow proportionality factor in one of my organs in Mobi.
When I do this, I get a nice prediction, but I was wondering if this violates any mass/fluid/flow balances in the model?
Thanks!

Wilbert

**Comment by StephanSchaller** [comment]
Hi Wilbert,

no this is fine. The lymph fluid balances will still be in order as both in- (TwoPoresTransportLink) and outflow (MassTransferLymphOrgInt2BloodPool) depends on Q-lymph which is calculated with this proportionality factor.

Best,
Stephan

**Comment by wilbertdew** [comment]
Thanks Stephan!
