### ISSUE TITLE
Hepatic arterial infusion

### ISSUE THREAD

**Issue by Fatima-Marok** [Open-Systems-Pharmacology/Forum#394]
Hello everyone,

Is there a way to simulate a hepatic arterial infusion? I tried tagging the application transport with ArterialBlood and Liver (see picture). I also tried different combinations of tags, but somehow nothing is shown in plasma. The compound I'm simulating is metabolized by an enzyme, which is expressed in many tissues, not just liver. Since no metabolite is generated, I assume, that the implementation was unsuccessful. 
Thank you in advance!

Best regards,
Fatima

![Forum](https://user-images.githubusercontent.com/45940242/66206294-f2484a80-e6af-11e9-8fa9-48479f4061ed.JPG)

**Comment by Fatima-Marok** [comment]
@msevestre Thank you for your reply!
The patients in the study received an infsuion, which was administered into the liver artery via a catheter linked to a pump. I'd like to applicate the compound into the artery, which flows right into the liver, if this is possible.

**Comment by PavelBal** [comment]
The target is `LIVER` and `PLASMA` and `PERIPORTAL`

**Comment by Fatima-Marok** [comment]
@PavelBal Thank you very much! It worked.
