### ISSUE TITLE
Where can I find parameters in NEIGHBORHOOD|MOLECULE ?

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#395]
Hi, all 

Does anyone know how to find parameters like absorption rate in NEIGHBORHOOD|MOLECULE in 
MoBi?
![image](https://user-images.githubusercontent.com/54141158/66378464-107eb500-e9e6-11e9-8200-43b82aa3faa0.png)

**Comment by wangwei1619** [comment]
There is not a part named by drug name in **Neighbrhoods**

**Comment by msevestre** [comment]
@wangwei1619

`NEIGHBORHOOD` or `MOLECULE` are reserved keywords. 
These keywords will be replaced automatically in the simulation by real instances of a  `neighborhood` or a `molecule`. (e.g. everywhere, where your transport will take place and with the name of the molecule being transported)

## Example:
If your transporter takes place between `Muscle|int` and `Muscle|cell`, you would have a neighborhood defined in your spatial structure, called for example `Muscle_int_Muscle_cell`. 

When an instance of the transporter is created in the simulation, the keyword  `NEIGHBORHOOD ` will be replaced with `Muscle_int_Muscle_cell`. 
On their other hand, the keyword `MOLECULE` will be replaced by the name of the molecule being transported. Meaning that in the simulation, you have a full valid path

This technic allows you to define your transporter only once and apply them everywhere in a very generic way.


Now looking specifically at the DrugAbsorption_para passive transport, you can see that the transport will be from all compartments tagged with the tag `Lumen` to compartments tagged with the tag `Mucosa AND Plasma AND SmallIntestineSegment`

![image](https://user-images.githubusercontent.com/1041237/66614765-38157f00-eb98-11e9-9705-f87da33b5db1.png)


To see where instances of the transport are created, I usually advise to create  simulation report (right click on simulation and press `Create Simulation Report`
![image](https://user-images.githubusercontent.com/1041237/66614814-5ed3b580-eb98-11e9-94d4-7ad60be6bf12.png).

There you can search for `DrugAbsorption_para` and see where it has been created. 

In my example, it has been created 5 times
```
Transport: DrugAbsorption_para
	Source: S1|Organism|Lumen|UpperJejunum|Caffeine
	Target: S1|Organism|SmallIntestine|Mucosa|UpperJejunum|Plasma|Caffeine
	Formula: DrugAbsorptionLumenToMucosaRate
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_uje_UpperJejunum_pls|Caffeine|Drug absorption rate (lumen to mucosa)(0 [µmol/min])
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_uje_UpperJejunum_pls|Caffeine|Drug absorption rate (lumen to mucosa)
	Description: Drug absorption paracellular

Transport: DrugAbsorption_para
	Source: S1|Organism|Lumen|LowerJejunum|Caffeine
	Target: S1|Organism|SmallIntestine|Mucosa|LowerJejunum|Plasma|Caffeine
	Formula: DrugAbsorptionLumenToMucosaRate
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_lje_LowerJejunum_pls|Caffeine|Drug absorption rate (lumen to mucosa)(0 [µmol/min])
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_lje_LowerJejunum_pls|Caffeine|Drug absorption rate (lumen to mucosa)
	Description: Drug absorption paracellular

Transport: DrugAbsorption_para
	Source: S1|Organism|Lumen|UpperIleum|Caffeine
	Target: S1|Organism|SmallIntestine|Mucosa|UpperIleum|Plasma|Caffeine
	Formula: DrugAbsorptionLumenToMucosaRate
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_uil_UpperIleum_pls|Caffeine|Drug absorption rate (lumen to mucosa)(0 [µmol/min])
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_uil_UpperIleum_pls|Caffeine|Drug absorption rate (lumen to mucosa)
	Description: Drug absorption paracellular

Transport: DrugAbsorption_para
	Source: S1|Organism|Lumen|LowerIleum|Caffeine
	Target: S1|Organism|SmallIntestine|Mucosa|LowerIleum|Plasma|Caffeine
	Formula: DrugAbsorptionLumenToMucosaRate
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_lil_LowerIleum_pls|Caffeine|Drug absorption rate (lumen to mucosa)(0 [µmol/min])
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_lil_LowerIleum_pls|Caffeine|Drug absorption rate (lumen to mucosa)
	Description: Drug absorption paracellular

Transport: DrugAbsorption_para
	Source: S1|Organism|Lumen|Duodenum|Caffeine
	Target: S1|Organism|SmallIntestine|Mucosa|Duodenum|Plasma|Caffeine
	Formula: DrugAbsorptionLumenToMucosaRate
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_duo_Duodenum_pls|Caffeine|Drug absorption rate (lumen to mucosa)(0 [µmol/min])
		DrugAbsorptionLumenToMucosaRate: S1|Neighborhoods|Lumen_duo_Duodenum_pls|Caffeine|Drug absorption rate (lumen to mucosa)
	Description: Drug absorption paracellular

```

As you can see `NEIGHBORHOOD|MOLECULE|Drug absorption rate (lumen to mucosa)` has been replaced everytime wih a concreate instance of a neighborhood and molecule, for example 
`S1|Neighborhoods|Lumen_uje_UpperJejunum_pls|Caffeine|Drug absorption rate  (lumen to mucosa)`


Hope that helps,

Cheers, 
Michael

**Comment by wangwei1619** [comment]
@msevestre,
Thanks for your specific explanation. I find the parameter by following your illustration, thank you!
Best regards,
Wang Wei
