### ISSUE TITLE
Create population within R

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#397]
Dear All,

is there a way to generate a population from within R for further simulations in R?
If yes, can someone share a R code example?

Thanks in advance and 
best regards,
Daniel

**Comment by msevestre** [comment]
@DanielMoj 
We are currently implementing a full rewrite (open-source obviously) of the OSPSuite package for R
The code can be found [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R)

This is still a work in progress. The creation of a population is, unfortunately, one of the features that hasn't been implemented yet.  

A feature request is available and you can track its progress [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/40)

However, if you happen to have a population available (for example exported from PKSim, or created via Matlab and exported to csv), you can use it to simulate in R. This is already implemented in the rewrite

Hope that helps,

Michael

**Comment by HenrikCordes** [comment]
Dear @DanielMoj,

had the same issue for a population simulation within Matlab, but I guess it should be similar winthin R. 

My workflow was as follows: 
1. Genarate a population in PK-Sim 
2. Export the population to an excel/csv file
3. (From within Matlab/R) use the headers of that population file to set up the parameter paths for the "initStruct"
4. loda your .xml model file & initSimulation with the initStruct from 3.
5. Itterate over the population: by a) setParameter, b) processSimulation, c) save results 

I hope this helps. 
If you want I can dig up and share the Matlab code snippets. 

Kind regards,
Henrik

**Comment by DanielMoj** [comment]
Dear @msevestre and @HenrikCordes,

thanks for you quick reponses! Then let's wait for the version after next. Until then I am going with the method both of you mentioned (PKsim export etc.).

Best,
Daniel
