### ISSUE TITLE
How to calculate CLHint from CLh?

### ISSUE THREAD

**Issue by xixi-1995** [Open-Systems-Pharmacology/Forum#399]
Hi,all
I am new learner and I met difficulties when I calculate CLintH from CLh,  I am confused the selection of the formula.
as I see, 
![image](https://user-images.githubusercontent.com/54713645/66975760-19e8db00-f0d2-11e9-8d79-0ed30812a5e0.png)
but another formula I found is 
![image](https://user-images.githubusercontent.com/54713645/66975844-574d6880-f0d2-11e9-819e-f9956a3ee1f7.png)
which one should I use in PKsim ? or is there any other formula?
I really appreciate your help. Thank you very much.

**Comment by wangwei1619** [comment]
Hi, @xixi-1995 ,
I thouth about this problem before. And I guess the CLh and CLint in your second formula must be stated as blood clearance other than plasma clearance, and the . However, the PK-Sim uses hepatic clearance data as "Hepatic plasma clearance "
![image](https://user-images.githubusercontent.com/54141158/66981376-1b240300-f0e6-11e9-9c4b-01f68bbc7ce4.png)
and CL_blood*C_blood=CL_pls*C_pls=CL_pls*C_blood/BP, so CL_blood=CL_pls/BP.
Judging the CLh in your first formula is the kind of CL_pls, divid it by BP, and move the BP to the right side. Now the CLh in left is CL_blood, and you can get the term CLint/BP both in denominator and numerator at the right side. If you judge the term as CL_blood, you derive the second formula.
Hope this is helpful.

**Comment by wangwei1619** [comment]
By the way, PK-Sim uses the first formula
![image](https://user-images.githubusercontent.com/54141158/66982628-27f62600-f0e9-11e9-9ec8-76a279135be7.png)

**Comment by xixi-1995** [comment]
@wangwei1619 Thanks for your help~~
