### ISSUE TITLE
Publication for Minipig Model

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#40]
I was not able fo find a reference to the Minipig Model implemented in PKSim in the Manual.
Did you use the Model by Claudia [Suenderhauf & Neil Parrott](https://rd.springer.com/article/10.1007%2Fs11095-012-0911-5?LI=true) or collect your own data?

Pleas advise.

Best,
esqlabs Team

**Comment by Yuri05** [comment]
Minipig data in PK-Sim comes from:

1) [Ellegaard Göttinger Minipigs](http://www.minipigs.dk)

2) [Peter Glodek und Benno Oldigs: "Das Göttinger Miniaturschwein"](https://www.researchgate.net/publication/258065342_Peter_Glodek_und_Benno_Oldigs_Das_Gottinger_Miniaturschwein)

3) [Einführung in die Versuchstierkunde. Band IV: Das Miniaturschwein. Hrsg. von W. Leucht, G. Gregor und H. Stier.](http://onlinelibrary.wiley.com/doi/10.1002/pauz.19830120608/abstract)

S. [Ellegaard Newsletter 33: 15-16](http://minipigs.dk/fileadmin/filer/Newsletters/Newsletter_33.pdf) for more details.

**Comment by msevestre** [comment]
"Das Göttinger Miniaturschwein"

Sounds like a bed time story for kids ;-)
