### ISSUE TITLE
prediction interval and error analysis

### ISSUE THREAD

**Issue by KaixiangZhou** [Open-Systems-Pharmacology/Forum#400]
Hi, I built the PBPK model and input the observed data, but how to analysis the predictive accuracy?  For example, how to obtain the following figures? Thank you very much.
Dr. Zhou

![GEWFU7F97%U7NRM %`R0K)M](https://user-images.githubusercontent.com/56682328/67058606-1a43ad80-f188-11e9-8fa3-755ebc70f7b8.png)

![P{WGFA_D%(TV$)6` (T8GD6](https://user-images.githubusercontent.com/56682328/67058690-84f4e900-f188-11e9-9a77-d801225a4f66.png)

**Comment by regulus92** [comment]
You can use R or other statistical softwares with plotting function.

**Comment by KaixiangZhou** [comment]
Dear Zheng:
   Thank you so much. Can you speak chinese? I am a student of Huazhong agricultural university, Wuhan, Hubei. I am a newer in PBPK modeling. I need your help, this is my QQ number: 272652338. Thank you for your help.





------------------ 原始邮件 ------------------
发件人: "Liang Zheng"<notifications@github.com>; 
发送时间: 2019年10月18日(星期五) 上午10:22
收件人: "Open-Systems-Pharmacology/Forum"<Forum@noreply.github.com>; 
抄送: "周凯翔"<272652338@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Open-Systems-Pharmacology/Forum] prediction interval and erroranalysis (#400)




You can use R or other statistical softwares with plotting function.

**Comment by Yuri05** [comment]
@KaixiangZhou you might also take a look at the new **qualification framework** provided as an AddOn to the OSP Suite (s. [here](https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/v8.0) for details and download instructions). This framework allows creation of qualification reports (also **across projects**) with variety of plots (e.g. predicted vs. observed).

You need to write a so called "qualification plan" (s. [here](https://github.com/Open-Systems-Pharmacology/QualificationPlan/releases/tag/v2.0) for details) where you can define what kind of plots, tables and qualification measures you would like to see in your report.
This plan is processed then by the qualification tools to generate a report.
<details><summary>Qualification Plan (click to expand)</summary>
<img src="https://user-images.githubusercontent.com/25061876/67088802-57b73380-f1a6-11e9-9f78-1ea71fb4653d.png">
</details>

Here you can see some examples of qualification plans and corresponding reports:
* [Example 1](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_GFR_Ontogeny/tree/master/input)
  * [Plan](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_GFR_Ontogeny/blob/master/input/Qualification-Ontogeny-Distribution-GFR.json)
  * [Report](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_GFR_Ontogeny/releases/latest)
* [Example 2](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP3A4_Ontogeny)
  * [Plan](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP3A4_Ontogeny/blob/master/Input/Qualification-Ontogeny-CYP3A4.json)
  * [Report](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP3A4_Ontogeny/releases/latest)
* [Example 3](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP2C8_Ontogeny)
  * [Plan](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP2C8_Ontogeny/blob/master/Input/Qualification-Ontogeny-CYP2C8.json)
  * [Report](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP2C8_Ontogeny/releases/latest)

Best starting point is: take the template from https://github.com/Open-Systems-Pharmacology/Evaluation-plan-template and adjust it to your needs

@incei @sfrechen @TWendl FYI

**Comment by prvmalik** [comment]
There is a manual way to export the observed and simualted AUC, CL, Vd etc. from your simulations so that you can make the plots above.

Individual Simulations:  Click 'Show PK Analysis' and Click 'Export to Excel'
![IndividSim](https://user-images.githubusercontent.com/29066045/67116415-5a1d8b80-f1ae-11e9-8f36-8e156837c1b9.JPG)

Population Simulations: Click 'Export' in the top toolbar when your population simulation is open, then click 'PK-analyses-to-CSV'
![PopSim](https://user-images.githubusercontent.com/29066045/67116443-67d31100-f1ae-11e9-9f20-2bdac70d6722.JPG)

**Comment by Yuri05** [comment]
@KaixiangZhou Closing. Please reopen if there still any questions.
