### ISSUE TITLE
plasma clearance and specific clearance.

### ISSUE THREAD

**Issue by CK-CHO** [Open-Systems-Pharmacology/Forum#401]
Hello, i have a simple question. 
In my project, i have to put in renal clearance data. So, i investigated various clinical trial literature for getting in vivo renal clearance data. for example, i had 4 ml/min renal clearance data of carvedilol in Neugebauer G et al, 1987. Then, i add renal clearance category, and is this clearance value input in plasma clearance row or specific clearance row? any literature do not have renal "plasma" clearance specifically, only renal clearance. So, i was confused because of difference between these clearance

**Comment by tobiasK2001** [comment]
Dear prasugrel,

I am a bit confused, if this issue is open or not ;-) But you might checkout the issue discussed here
https://github.com/Open-Systems-Pharmacology/Forum/issues/129

Hope this might help.

Best, Tobias
