### ISSUE TITLE
Reference for in vitro hepatocytes T/2

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#402]
Dear all, 

I am trying to use the IVIVE option in PK-Sim which allows you to input the T/2 in hepatocytes and calculate the intrinsic clearance.  Is there a reference for the equation used (see screenshot below)?
In this equation there is the fraction unbound in the essay, which in this case would be Fu_Hep and I am having problems to understand why increasing the Fu_Hep for the same T/2 we see a decrease in the clearance. 
(Since from my point of view: higher Fu_Hep= more drug available in the essay, so for the same T/2 this would mean higher clearance...)
Any help is highly appreciated!
Thanks,
Donato

![image](https://user-images.githubusercontent.com/11489621/67076078-bcfe2b00-f18c-11e9-9021-7b602ef7be1e.png)

**Comment by tobiasK2001** [comment]
Dear Donato,

I am not sure if this is the direct reference, but some basic equations and concepts you will find here:
https://www.ncbi.nlm.nih.gov/pubmed/9336307
 e.g. Equation 11 might be usefull
![image](https://user-images.githubusercontent.com/25585248/67077952-9d690180-f190-11e9-811d-22d91f3c62bd.png)

From that it appears logical that increasing fu_Hep will result in a lower Clint, if t1/2 is kept constant as it is together with the t1/2 in the denominator.  

Hope this might help you.

Best, Tobias

**Comment by teutonicod** [comment]
Hi @tobiasK2001 ,
Thank you very much! It is exactly what I was looking for to better understand this point!
Donato

**Comment by teutonicod** [comment]
Hi @msevestre, would it be possible to add this reference to the software? Like in the value origin? Since also other users can have the question about the origin of this equation.

Donato

**Comment by msevestre** [comment]
@teutonicod Can you please create an issue in the PKSim repo?
