### ISSUE TITLE
PopPK for Rats

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#403]
Dear All, 

I would like to create a PopPK model for the Rats. How can I achieve this considering that there is no age dependent distribution information?  We have observed a considerably close variability in the PK of rats as that seen in humans. Therefore, we are interested to go in the direction of population modelling in Rats. 

Further to that, I would like to have a user defined variability in the CaCo values on this population model. I tried to work around this in PKSim but I am afraid, I am lost.

Any directional help would be much appreciated. 

Best, 
Pri

**Comment by Yuri05** [comment]
what you could do:
1. Calculate parameter values for those parameters where you have information about age dependency/variability in your tool of choice (Matlab, R, Excel, ...) for the required number of individuals
2. Create a Rat individual in PK-Sim
3. Create a Rats-Population with desired number of individuals based on Rat
4. [Export Rats-Population to CSV](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-creating-populations#exporting-populations-to-csv) This will export all anatomical/physiological parameters of the population. (now you can delete tha Rats-population in PK-Sim)
4. Replace exported values by those created in step 1
5. Save new population as CSV again.
6. Import adjusted population CSV in PK-Sim
![grafik](https://user-images.githubusercontent.com/25061876/67098712-ee8eea80-f1bc-11e9-8b21-4dcd005bd886.png)

From now on you can work with this population in the same way as with any other "standard" population.

**Comment by PriKalra** [comment]
Hi Yuri, 
Just to make it clear for myself: If I want to have a weight variability.And further to that, a variability on CaCo values (`specific intestinal permeability` ), in such a case, as an example, I create a file in step number 1. with what fields? Do I do that for the variability in CaCo value too? Or that is something I define in the `user defined variability`  section in PKSim in step 3? 

Is there an example somewhere for the 1. file? This is my first time doing population modelling itself, so please excuse my basic questions. 

Thank you for the clear and methodological explanation.

**Comment by Yuri05** [comment]
>If I want to have a weight variability...

Do you have a weight variability _only_ or do you have variabilities of organ volumes/organ weights as well?
And is your desired weight distribution _uniform_ or any other kind of distribution (normal, ...)?
* In case "weight only, uniform distribution": you can vary the weight immediately in PK-Sim just by selecting the [Min Max] Weight range during population creation
![grafik](https://user-images.githubusercontent.com/25061876/67101523-0f0d7380-f1c2-11e9-8071-df502cc482cf.png)
* In case "weight only, other distribution": create weights according to your weight distribution first. After that, just scale organ volumes proportionally (e.g. take any rat from the exported population; for each organ calculate the percentage of organ volume; every new rat created should have the same organ volume percentage). 
Thus you would create something like:

Rat No|Weight [kg]|Volume Liver [l]|Volume Kidney[l]|...
-|-|-|-|-
1|1|0.1|0.2|...
2|3|0.3|0.6|...
...|...|...|...|...

Then replace the columns Weight, Volume liver, Volume kidney, ... in the exported CSV with your generated values
* In case: weight AND organs weights distributions: more complicated.

**Comment by Yuri05** [comment]
>And further to that, a variability on CaCo values (specific intestinal permeability ), in such a case, as an example, I create a file in step number 1. with what fields? Do I do that for the variability in CaCo value too? Or that is something I define in the user defined variability section in PKSim in step 3?

You could just add variability to the `Intestinal permeability (transcellular)` in a population **simulation**:
![grafik](https://user-images.githubusercontent.com/25061876/67102990-a96eb680-f1c4-11e9-8a78-942ac6e83a6f.png)

**Comment by PriKalra** [comment]
Thanks a lot. until now, it sounds doable to me. If I encounter issues while constructing the model, I will reopen this topic!
Thank you!
