### ISSUE TITLE
Influence of solubility on absorption in PKSim 

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#404]
Dear All, 

I am having difficulty in understand the basics of the impact of solubility of the compound (Solubility at ref. pH) on the absorption in PKSim. Previously I have worked with solubility restricted and non solubility restricted models. However, the following is not clear to me: 
1) The influence of solubility on the absorption? 
2) Where to exactly locate this equation in PKSim?
 3) How do I have a non solubility restricted model in PKSim?

For example for ketoconazole, I have the solubility at ref pH as 0.089 mg/l and I changed this parameter to 50 mg/l , in that case, the fraction dissolved is the same for both scenarios: 1
However, the simulations show higher concentration in the venous blood with higher solubility. See below:

![image](https://user-images.githubusercontent.com/13007976/67097499-8808cd00-f1ba-11e9-92b7-c0de88006125.png)
Is this explained by the effective concentration formula in PKSim where the Solubility/MW is a part of the equation? Or I am looking into something wrong here?

![image](https://user-images.githubusercontent.com/13007976/67097531-95be5280-f1ba-11e9-8c71-dfc16d4791c1.png)

Thank you. 

Best, 
Pri

**Comment by Yuri05** [comment]
>Is this explained by the effective concentration formula in PKSim where the Solubility/MW is a part of the equation? Or I am looking into something wrong here?

You are looking at the right place. Solubility limitation - in the (default) case `No supersaturation` - is given by `min(Solubility/MW ; M/Liquid)`. And `Effective concentration in lumen` is what is used in all absorption processes.

> For example for ketoconazole, I have the solubility at ref pH as 0.089 mg/l and I changed this parameter to 50 mg/l , in that case, the fraction dissolved is the same for both scenarios: 1

I guess your formulation is NOT `Particle Dissolution`?
* For `Particle Dissolution` the transformations `Solid <=> Dissolved [<=> Precipitated]` are modeled and fraction dissolved shown is what you expect.

* For all other oral formulation types: only one way transformation 'Solid => Dissolved' is modeled (according to your formulation). The back transformation 'Solid <= Dissolved' (which takes place as soon as solubility goes below intestinal concentration) is not modeled. Instead, effective intestinal concentration is cut at the solubility level (as you can see in the formula above). This is less physiological then in case of `Particle Dissolution` but still an acceptable approximation.
Now when it comes to the fraction dissolved: what is shown is the total amount of dissolved drug according to the formulation. Thus de facto you will see here exactly the function of your oral formulation. E.g. if the formulation was `Dissolved `you will see `FDissolved = const = 1` disregarding your intestinal solubility. Which is.. well - probably not what your expect. What is important to know here: Fraction dissolved is just a derived output (_observer_) of a model. It is **not** used for any calculations.

**Comment by Yuri05** [comment]
>I am still confused a bit: as you stated that in the case of dissolved formulation, it is disregarding intestinal solubility, 

That was **not** the statement. In case of _dissolved_ formulation (same as for any other oral formulation) intestinal solubility is taken into account in the absorption processes within `Effective concentration in lumen` via `min(Solubility/MW ; M/Liquid)`.

**Comment by Yuri05** [comment]
Just to be clear: models are ALWAYS solubility limited (unless you activate supersaturation - which is NOT the default case and makes sense only in combination with `particles dissolution`)

**Comment by PriKalra** [comment]
Oh Sorry! Thank you! I understand now. :)
