### ISSUE TITLE
Prediction of Vss by different partition coefficient calcuation methods?

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#405]
Dear all, 
The longer way would be to build different simulations with different calculation methods to analyze the Vss.  Any smarter way to do it?
Thanks!!

**Comment by msevestre** [comment]
@PriKalra Not at the moment, unfortunately. (or at least, I don't see a way that would be faster than cloning the simulation so that they use the same set of building blocks)

**Comment by PriKalra** [comment]
Thank you

It would be nice to have something smarter. Quite a tool for IVIVE and Reverse Dosimetry projects.😊
