### ISSUE TITLE
unable to perform simulation

### ISSUE THREAD

**Issue by rajarathnam6** [Open-Systems-Pharmacology/Forum#41]
though giving all the required inputs in simulation interface, after administration protocol, simulation is not perfoming
kindly help 
thanks

**Comment by msevestre** [comment]
In order to help you, I will need some more details as to what is not working. 

Please attach a project and describe exactly what steps are required in order to reproduce the issue. 

Thanks for your feedback

**Comment by rajarathnam6** [comment]
Respected sir,
I am a research scholar, doing my PhD in M S Ramiah University, Bangalore, India.
I am working on a simulation model, to simulate the effect of Arecoline hydrobromide on oral tissue.

oral sub mucous fibrosis is more prevalent in India due to pan chewing habit, which is a pre cancerous condition 
So, in PkSim interface I had given all the required inputs for simulation. 
I had defined the individual, compound and administration protocol 
I started to simulate, but it's not happening 
Kindly help

As a student and research scholar should I need the administrator rights to install???
Kindly give your inputs and I request you to do the needful.

Thank you,
Regards,
Dr B N Rajarathnam 
Research Scholar
M S Ramiah University 
Bangalore

**Comment by Yuri05** [comment]
>I started to simulate, but it's not happening

Please attach you project (you have to zip it first) and describe the steps your take to start a simulation.

>should I need the administrator rights to install?

Yes

**Comment by rajarathnam6** [comment]
Respected Sir,
Thank you for your reply.
I will send you the details shortly..
Please, Can you assist me the procedures to get the administrator rights.
Thank u,
Regards,
Dr Rajarathnam

**Comment by Yuri05** [comment]
Regarding administrator rights please ask your local IT administrator

**Comment by rajarathnam6** [comment]
Sir,
I am located in Bangalore, India.
Can you please suggest me the local IT administrator. Their contact details. Please do the needful.

Thank you
Regards
Dr Rajarathnam

**Comment by msevestre** [comment]
@rajarathnam6 Since you have installed the `Open Systems Pharmacology Suite` successfully, you have admin rights on your machine so no further steps are required.

You will need to be more explicit as to what is the problem you are facing.
>I started to simulate, but it's not happening

is unclear. As @Yuri05 mentioned above, please attach a project file and describe **exactly** what you are doing. We will not be able to help otherwise

**Comment by rajarathnam6** [comment]
Respected Sir,

I wanted to *simulate the effect of arecoline in rats*

So i defined the individual as rat, compound as arecoline; metabolizing
enzyme-flavin mono oxygenase ; fed all the required data in that interface
for arecoline compound and adminstration protocol – user defined as
10mg/kg, target organ muscle, interstitial space,single dose

After defining,

Starting with simulation on right click

Model structure-standard model for small molecules

Compounds-arecoline

Biological process-enzyme flavin mono oxygenase is selected

Administration protocol for the compound is selected

After clicking that events tab opens up. Since it is an optional i have not
loaded.

The OK button is not functioning later

I am not able to create simulation further,,, I wanted to know what fault
am I doing.

Kindly help

**Comment by msevestre** [comment]
Did you also enter a name for the simulation? At the top of the window where the big white X on red background is located?

**Comment by rajarathnam6** [comment]
Sir,
Thank you for your assistance.
Can you please assist the steps in simulating the buccal tissue of oral cavity...
Thanks
Regards
Dr Rajarathnam

**Comment by msevestre** [comment]
@rajarathnam6 please only one entry per issue. would you please open another issue with your question? Thanks
