### ISSUE TITLE
IV and Oral doses for biliary processes- How to proceed with a good fit?

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#410]
Dear all,

I have a compound, which seems to show biliary excretion as we see a second peak in the data for oral dose (species:Rats). Elimination is predominantly seen via urine and to a small extent via feces. In such a case, I simulated the IV dose with and without biliary excretion and there, the inclusion of biliary clearance improves the fit, but does not replicate the second peak of the biliary clearance. See below:
![image](https://user-images.githubusercontent.com/13007976/67841369-37696c00-faf8-11e9-9547-8bc9500e90a3.png)

I do know from the data that the concentrations of the compound found in liver are  low (after oral dose). What other parameters I could analyse and have a better understanding to the biliary processes? 

When I proceed with this fit to simulate oral doses, the simulation fails to predict the plasma concentrations well. 

![image](https://user-images.githubusercontent.com/13007976/67841806-2a00b180-faf9-11e9-9812-fe65992b8092.png)

Any ideas to test the model and improve the model fit would be appriciated as I have limited knowledge at tackling EHC. 

Thanks 
Pri

**Comment by PavelBal** [comment]
It does not make any sense that the fraction excreted via urine decreases over time, and starts at almost 100%! There must be some misinterpretation of the data.

**Comment by PriKalra** [comment]
The data shows that the fraction excreted is 77% at 5 hours, and then over the coming hours it decreases.

I implemented the measurement the way it is because it was in percentage. What would be a misinterpretation here?

**Comment by tobiasK2001** [comment]
Ah, Ok (sorry for jumping in) in that case you should transform your fraction excreted data as cumulative data. As PK sim does. E.g. like after 5h 77%, after 12 h 77% +fraction excreted between 5 and 12 h. etc.
 However, I cannot see a reason for linking urinary excretion data to EHC. In my eyes you need an experiment in bile duct cannulated rats to get an experimental proof here.

Hope this might help you.

Best, Tobias

**Comment by PriKalra** [comment]
Thank you for the correction. I will do so. I was not linking it. It seemed strange to me that the graph looked similar to the data (which misinputted as pavel said).

Thank you.

**Comment by PriKalra** [comment]
I also wanted to have your suggestions to know how I can improve the fit for the plasma (first question) 😊

Thank you

**Comment by tobiasK2001** [comment]
hmm, I am not sure if it is wise to implement gallbladder emptying for the rat, when it does not have a gallbladder. Did you ruled out any possible other reasons for the second peak? 
PK-sim of course does not let you add a gallbladder emptying event for the rat given the reasons above. I am sure there are ways to add a gallbladder to a rat with MoBi. However, I would prefer to do a cheap trick first. Try creating a giant Mice with Bodyweight, organ volumes and liverbloodflow adapted to a rat. With that mice-rat chimera you might try to investigate the impact on gallbladder emptying further.

Hope that might help you.

Best, Tobias

**Comment by PriKalra** [comment]
I see, no I have not ruled out any other possible reason for the second peak. I am not sure what else can allow this peak.

**Comment by RobinM92** [comment]
Hello Priyata,

Enterohepatic recirculation seems indeed a bit difficult as rats don't 
have a galbladder. Another possibility might be enterogastric 
recirculation (is it a basic compound?), which is much less described 
but still can be relevant, especially for alkaline compounds (e.g. 
https://www.ncbi.nlm.nih.gov/pubmed/8237395 and more recent 
https://link.springer.com/article/10.1007%2Fs10928-014-9371-3).

Good luck!
Robin

Dr. ir. Robin Michelet
Post-doctoral researcher

Freie Universitaet Berlin
Institute of Pharmacy
Dept. of Clinical Pharmacy & Biochemistry
Kelchstr. 31
12169 Berlin
Germany
Phone:  + 49 30 838 50659
Fax:      + 49 30 838 4 50656
Email: robin.michelet@fu-berlin.de
www.clinical-pharmacy.eu

**Comment by PriKalra** [comment]
Hi Robin, 

Thank you so much for this comment. Does enterogastric recirculation occur for acidic compounds too? 

Best, 
Priyata

**Comment by Yuri05** [comment]
@PriKalra Closing. Please reopen if there are still any questions.
