### ISSUE TITLE
Amikacin PBPK Model

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#412]
Hello ,
I have noticed that Amikacin PBPK Model was provided in some repository but iam unable to find the project file.
can anyone please help me by sharing the PKSIM project file or input parameters, i found the publication by Bayer team but details are not much provided in it

Regards
HKK

**Comment by PriKalra** [comment]
https://github.com/Open-Systems-Pharmacology/Amikacin-Model

Is this what you are looking for?

**Comment by harishkaushikbugworks** [comment]
Yes, but I couldn't find PK Sim project or any information here just code is there

If you find anything, please share

Regards
Harish

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by harishkaushikbugworks** [comment]
https://github.com/Open-Systems-Pharmacology/Amikacin-Model/blob/a2ea07f0780527234983d5afec5d22b2f14d6d7b/Amikacin.pksim5

Is this what you are referring to

Regards
Harish

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by msevestre** [comment]
yes this is the PKsim project :) which is what you are looking for I
believe.
