### ISSUE TITLE
PBPK Valproic acid

### ISSUE THREAD

**Issue by vbalbas** [Open-Systems-Pharmacology/Forum#414]
Dear community,

A colleague would like to develop a PBPK model of Valproic Acid (VPA) in the paediatric population to characterize the VPA concentration in saliva.

We have found an article and a poster regarding PBPK and VPA:
- Conner TM, Nikolian VC, Georgoff PE, Pai MP, Alam HB, Sun D, et al. Pharmacokinetic modeling of disposition and pharmacological interactions of valproic acid and divalproex with physiological basis. Eur J Pharm Sci. January 2018; 111 (May 2017): 465–81.

- https://www.certara.com/wp-content/uploads/2019/09/Fisher_2019_EUToxRisk_biokinetic.pdf

But we were wondering if anyone knows if there is any PBPK model of VPA built in PKSim, before starting from scratch.

Thanks in advance.
Best,
Violeta

**Comment by HenrikCordes** [comment]
Dear Violeta,

During my PhD I build a human PBPK model for VPA and some of its metabolites. 
We did use simulation results of the model in a paper (https://www.ncbi.nlm.nih.gov/pubmed/28151932), but did not publish the model itself yet.

Lets further discuss this outside the forum.

Kind regards,
Henrik

**Comment by vbalbas** [comment]
Dear Henrik, 

Thank you very much for contacting me and for sharing your interesting publication. 

I am looking forward to hearing from you. 

Kind regards, 
Violeta

**Comment by nina-nauwelaerts** [comment]
Hi

I was wondering if you found any PK Sim models for valproic acid, as this will also be a compound I will work with. 

Kind regards
Nina
