### ISSUE TITLE
Disabling colonic absorption

### ISSUE THREAD

**Issue by Zons2015** [Open-Systems-Pharmacology/Forum#415]
Dear forum, 

During development of PBPK models in PKSim, I frequently observe that disabling colonic absorption leads to improved fit of peripheral venous blood-plasma concentration in the elimination phase for PO data. An example for fluconazole is shown below, where (red curve) with colonic absorption and (black curve) with colonic absorption disabled.

![image](https://user-images.githubusercontent.com/57356709/68140515-3be4b900-ff2c-11e9-9416-0f01d04e7365.png)

However, this approach might be problematic. For instance, in DDI modelling where one of the compounds might actually involve the colonic absorption part.  Has any user of this forum similar experiences or perhaps an explanation to this behaviour?

Kind regards,
Zons2015

**Comment by sfrechen** [comment]
Have you tested the sensitivity of solubility?

**Comment by TWendl** [comment]
It might be that the fraction cleared by gut wall metabolism is too small in your model. As a consequence, there is still substance left to be absorbed in the colon. If you increase gut wall metabolism in the model by e.g. increasing relative expression in the gut wall, fu in the gut wall or the permeabilities mucosa<->blood, this might solve the issue.
