### ISSUE TITLE
Can OSP run from a Network Share?

### ISSUE THREAD

**Issue by VitaminBrad** [Open-Systems-Pharmacology/Forum#417]
My IT Admin asked me this question.

Thanks!

**Comment by Yuri05** [comment]
Is the goal 
1. to install the OSP on a net share on computer A and later use it on computer A or
2. to install the OSP on a net share on computer A and later use it on computer B ?

Option 1. will work, option 2. will not.
OSP installs some components under ProgramData as well as some prereqs (C++ redist, .NET framework).  
If it's not feasible for some reason, portable versions of PK-Sim and MoBi can be used (C++ redist and .NET framework have to be installed here as well)
