### ISSUE TITLE
Share an oxycodone model and working on aripiprazole model

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/Forum#418]
Hi, everyone.
We recently developed a PBPK model for oxycodone, a widely used opioid in adults and children. The model had been provided as the supplementary file of our publication [1].  
Next we hope to build models for some psychotherapeutic drugs including aripiprazole. Apparently we are now faced with some really hard problems. In short, the current model can not give satisfactory performance for cross validation. So I'm wondering if I should post questions in the forum or anyone would like to work together with us. Thank you.

Best,
Liang Zheng
zhengliangscu@163.com

[1] Zheng L, Xu M, Tang SW, Song HX, Jiang XH, Wang L. Physiologically Based Pharmacokinetic Modeling of Oxycodone in Children to Support Pediatric Dosing Optimization. Pharm Res. 2019;36(12):171.

**Comment by Incei** [comment]
Hi Zheng, first of all congratulations with your excellent PBPK work and very nice paper!!

To support you, it would be great if you could upload and share your published model in the OSP community. This would allow the community to respond and provide you with new ideas and possible suggestions.

For this you need to create a repository in OSP, where the PBPK model, your paper can be uploaded, and discussions can be started. 

If you agree, please let us know, we can support you with creating this repository and next steps.

Best, Ibrahim

**Comment by Incei** [comment]
In case you do not want to publicly share the **unpublished** models yet, ofcourse you can let the community know which specific problems you have for those models, so we can provide input and support.

**Comment by regulus92** [comment]
@Incei Yes, I'm very happy to upload the published model file to the community.

**Comment by Yuri05** [comment]
@regulus92 An empty repository was created for your model upload: https://github.com/Open-Systems-Pharmacology/Oxycodone-Model Please upload your model file(s) following the guideline [here](https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/CREATING_MODEL_REPOSITORY.md) (start with step 4. :-) ) Thank you!

@Incei FYI

**Comment by regulus92** [comment]
@Yuri05 To let you know that I have completed the initial commit.

**Comment by regulus92** [comment]
@Yuri05 To let you know that I have uploaded the model file.

**Comment by Yuri05** [comment]
@regulus92 Oxycodone-Model is now online. Thank you for the contribution - well done!

**Comment by Incei** [comment]
Thanks to both!
