### ISSUE TITLE
Difficulties in installation of the most recent PK Sim version 

### ISSUE THREAD

**Issue by zt1947** [Open-Systems-Pharmacology/Forum#42]
I am now trying to install version 7.1.0 on my office table top and new problems pop up. 

Enclosed please find a file with error messages describing the problems that I and the network's administrator have encountered. 

The same eeror messages are received upon an attempt to unisntall older versions of PK-Sim.

We did check and all of Windows updates have been installed.

**Comment by Yuri05** [comment]
>Enclosed please find a file with error messages...

Seems there is no attachment here...

**Comment by zt1947** [comment]
Thanks!
Please close this issue.
I have opened a new issue (#43) and included the error messages there
