### ISSUE TITLE
Over prediction in mouse submandibular tissue

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/Forum#421]
Hello Everyone,

I developed a mouse PBPK model for my compound (acidic, with Log P 3.22, molecular weight 376.5 ) with submandibular gland added as an additional tissue using MoBi. I saved gonads as the primary container and re-imported back to MoBi and added it as a submandibular gland. I changed parameters such as tissue weight, tissue volume, and specific blood flow rate to reflect the values of submandibular gland reported in the literature. After completing the simulation the model is over predicting the concentrations when compared to observed data. Could you please provide some insights into what may be contributing to over prediction. Any help is much appreciated.   

![SMG_PBPK](https://user-images.githubusercontent.com/42623466/68611595-bdca6a00-0477-11ea-9df4-34feca9acb7f.jpg)

Sincerely,
Kash

**Comment by prvmalik** [comment]
Hi Kash, out of curiosity, how do the simulations for saliva in the unmodified model compare? 
![Kash](https://user-images.githubusercontent.com/29066045/68612014-85cc2280-0489-11ea-8bde-2c3c0a79b263.JPG)

**Comment by prvmalik** [comment]
While these types of simulations are wildly uncertain, it seems that you have an excellent estimate for distribution into the gland. Physiologically you may want to consider that there is an additional active process removing the drug from inside the cells of the submandibular gland. For example, saliva excretion into the mouth?

**Comment by yvkashyap** [comment]
Hi Paul,
Thanks for your suggestions. I now realized that I did not consider the secretion of my drug into saliva from the submandibular glands. I will modify my model structure accordingly and see if it helps.
Sincerely,
Kash

**Comment by yvkashyap** [comment]
Hi Paul,

I added an additional saliva compartment to my model and then created a neighborhood between the submandibular gland and saliva compartment. I obtained the saliva compartment from standard human simulation and loaded it to my model as a new container. I removed the salivary gland compartment inside the saliva compartment to avoid redundancy.  

However, now I am having trouble defining the transport from the submandibular gland to the saliva. From the literature, it is clear that the transport process from any salivary gland to saliva usually follows first-order process. I tried few default equations (fu/k_int_pls etc) and simulations failed to show any transport of drug from the submandibular gland to saliva.

Could you please suggest me the best way to add an equation to account for the transport of drug from the submandibular gland to saliva.

Thanks,
Kash

**Comment by prvmalik** [comment]
Hi Kash, you have to make a new passive transport formula. It would be something like this:
1. Open 'Passive Transport' building block
2. Click 'New'
3. Name it
4. In the 'Source' tag box, add tags that would denote the Submandibular gland (whatever you have tagged the gland as). If you are copying from the Gonads, you will likely have to add another tag that says "Intracellular"
5. In the 'Target' tag box, add tags that would denote the Saliva

![Kash1](https://user-images.githubusercontent.com/29066045/68708035-e5493180-0560-11ea-870c-67dc20b7475a.JPG)

6. Create a first order rate constant in the 'Parameters' tab of your new passive transport. Name it, select the units as 'Inverse time' and enter the value you would like to use.

![Kash3](https://user-images.githubusercontent.com/29066045/68708143-188bc080-0561-11ea-9d0d-729e94ccf2c6.JPG)

7. In the 'Kinetic' tab click 'Add formula'

8. In the 'References to Add' box, scroll down to the bottom. Drag and drop your new kinetic rate parameter into the 'Alias-Path-Dimension' box.

9. In the 'References to Add' box, open up your spatial building block > organism > navigate to the source of your submandibular gland. If you want to use the amount of drug in the formula (RECOMMENDED), open up your submandibular gland, open up the intracellular compartment then left click on the drug and drag it into the 'References to Add' box. I have done this with the Gonads compartment as an example.

![Kash5](https://user-images.githubusercontent.com/29066045/68708413-a7004200-0561-11ea-95fd-210372ecdafb.JPG)

10. Write the kinetic formula at the bottom using the exact names of the Alias' you have entered in the 'References to Add' box.

Click OK!

**Comment by yvkashyap** [comment]
Hi Paul,

Thank you so much for providing a detailed flow of instructions. I will follow them and get back to you if i run into any issues.

Sincerely,
Kash
