### ISSUE TITLE
Fit Elevated Tissue Drug Concentration

### ISSUE THREAD

**Issue by yishuanwu** [Open-Systems-Pharmacology/Forum#422]
Hi All, 
I have a hydrophilic small molecule (logP ~ -2, pKa (basic) = 7.5) that I am trying to fit in mice, with goal of extrapolating tissue concentrations to humans. The drug has negligible tissue binding (Fu = 1.0 across multiple species), and it is not a substrate of any of the major transporters in humans (P-gp, BCRP, OATP, OCT, MATE, OAT, SGLT, etc.). 

Here is the simulated curve for a single oral dose of 100 mg/kg in mice:
![Image](https://i.imgur.com/UlJLqKK.jpg)

Sorry for not showing the observed data. Based on the observed data, the concentration in kidney is 10x the concentration in plasma at all times. 
I could not get the tissue concentrations to be higher than the plasma concentration. I tried the following:

- Changing the logP (explored -10 to -0.1 as well as positive logP and optimizing)
- Trying different distribution calculation method - minimal change
- Adding a hypothetical renal reabsorption or secretory transporter
- Adding a hypothetical intracellular protein binding partner in kidney. (I tried different combinations of Kd and Koff, but it doesn't seem to change anything? Was my drug too hydrophilic to get into the cells?)
- Changing Permeability - P endothelial. However, that seems like it can only decrease the concentration in the tissue as the baseline is set to be very high. 
- I know I shouldn't, but changing the partition coefficient - Intracellular : plasma for the tissues of interest seem to be the only thing that will help me achieve a much higher concentration in the kidney than in plasma. 

Thank you very much for your help!
Shirley

**Comment by prvmalik** [comment]
Are you certain that you are measuring unchanged drug in the kidney? Quite often the glucuronide conjugates and other metabolites are excellent substrates for urinary transporters and accumulate in the kidneys prior to excretion (e.g. morphine). Could your assay be picking these up? Based on your physchem properties I imagine that it is a wonky small molecule, perhaps inorganic even.

**Comment by yishuanwu** [comment]
Hi @prvmalik , thank you for the fast response! 

The drug is a sugar analogue, so it is organic. It does get glucuronidated as a minor elimination pathway. The assay is LC-MS/MS, which I assumed would be very specific; I will look into this some more. I did not perform the experiments, so I will have to ask about the drug transport data. I will find out these information and post back tomorrow.

**Comment by prvmalik** [comment]
If it is a sugar analogue, it would be important to check affinity for the GLUT family of influx transporters

**Comment by yishuanwu** [comment]
I believe we did not test for the GLUT transporters in vitro, as it was not an FDA requirement for DDI testing. I will try to incorporate GLUT transporters in my model and see what it does.

**Comment by yishuanwu** [comment]
The assay analyst confirmed that they have confidence in the assay methodology.
Adding hypothetical transporters or changing permeability did not help much. 
Is it ever acceptable to increase the partition coefficient to some really high number?

**Comment by prvmalik** [comment]
You've got something in this model removing the drug from the system quite quickly, which is why the model may not be sensitive to the changes you are applying. It's possible that instead of being eliminated, the sugar analogue is being 'sequestered' in the kidneys by a transporter. You would expect some similar pattern in the liver, if this was the case. 

Changing the partition coefficient for the kidney manually would compromise the utility of your model for extrapolation to humans.

**Comment by yishuanwu** [comment]
Thank you Paul, You are right... I put in an exaggerated clearance that is higher than what I would have expected to fit the initial steep decline, but I think I am getting the Vss wrong. From the structure, the GLUT transporters likely do play a role, 

I will not change the partition coefficient then because that would defeat the purpose of the model. I am pondering some more on this data. I am going to try some more and see.

**Comment by yishuanwu** [comment]
I may have tried to optimize a bit too many things at once. A hypothetical transporter in the kidney does help to raise the tissue concentration, but the effect tends to be greater later on instead of immediately (5 minutes). 
Also, if I have no in vitro support for the hypothetical transporter (at this point I am changing the tissue expression of the transporter as the GLUT/SGLT1 transporter expression profile does not suit my need enough), what is the implication for extrapolating to human, and how is it different from fudging with the partition coefficient for both mice and human?

**Comment by prvmalik** [comment]
Any evidence that extracellular clearance is happening?

1. Remove extracellular clearance or fix it at the in vitro value (if you need to achieve a desired in vitro half-life in plasma/interstitial space, let me know)
2. Add a first order clearance enzyme in the cellular spaces of the organs where elimination happens
3. Add first order GLUT influx transporter in Kidney and Liver manually
4. Optimize intrinsic rate of transport and intracellular clearance using the observable states (Plasma PK, Kidney PK, Liver PK). The parameters will be uniquely identifiable. Make sure that logP and fu are fixed.

Extrapolate to humans and factor any changes in GLUT expression. Predictions would be plausible, depending on how well your intracellular CL extrapolates.

**Comment by yishuanwu** [comment]
Thank you very much again for helping. I need to find you in future ASCPT meetings and thank you in person.

1. There is no extracellular clearance. Actually, I am not quite sure if I understand extracellular clearance in PK-Sim. Would that be incorporating an enzyme in the extracellular space to metabolize the drug?
2. I forget to mention that this drug is mostly eliminated renally unchanged, with only a small fraction being metabolized. What might be an advantage in adding the clearance enzyme?
3. The GLUT transporters do seem to be helping with the relative tissue distribution. I used the human GLUT2 transporter mRNA expression profile as a start because it seems to be less specific for glucose. You said to factor in any changes in GLUT expression, but is it acceptable to use the expression profile fitted to mice data for humans, seeing that mRNA expression pattern is not very good for protein expression a lot of times? 
4. I have experimentally determined logD (from which I calculated logP) and Fu, but I thought that logP is a very uncertain parameter. I will optimize the clearance processes once I get the relative tissue Cmax in the range.

**Comment by prvmalik** [comment]
Happy to discuss. I'll be at ASCPT again this year, I would look forward to meeting you.

1. Yes. To add extracellular clearance, an enzyme would be added to the interstitial and plasma spaces,

2. That's great news. If it is less than 5% metabolized, forget about adding a metabolizing enzyme. Ensure that the GFR fraction in the model is 1.0.  If tubular secretion is involved (e.g., when renal clearance is greater than fu x GFR), add an apical transporter in the kidney. Set Km high if it is a dose-independent process and the Vmax can be identified using data for Fe_urine, even in the context of concurrent optimizations for distribution. 

3. the mRNA expression for GLUT2 might be misleading for two reasons. A - we are not 100% sure it is actually GLUT2 that is responsible for the transport and B - the protein expression data does not well-align with the GLUT2 mRNA data; see URL https://www.proteinatlas.org/ENSG00000163581-SLC2A2/tissue. Does any species-specific expression data exist for GLUT2? Without doing a comprehensive literature search, you might be safest by doing liver rel exp 1.0, kidney rel exp 0.5 and intestines rel exp 0.5, or even optimizing the relative expression with the kidney as a reference (using Mobi) if organ-specific PK data is available.

4. You're right, logP is uncertain. However, when dealing with transporters that govern distribution, either logP or the transporter Vmax has to be fixed to maintain parameter identifiability. With the experimental logP, I would hope *fingers crossed* that your predicted profile lies above your observed Cmax. This difference in Cmax can be used to optimize the GLUT2 influx transporter Vmax.

**Comment by yishuanwu** [comment]
Also, maybe for future people, I was previously making the mistake of setting the GLUT transporters to efflux transporter because that is what the human expression database defaulted to (It was bidirectional but my drug needs to get in before it can get out, so the transporter was not having an effect).

2. The relative clearance process appears to be different between mice and human. In humans it was mostly GFR, but in mice the CL was several times the mice GFR. I am hoping that I do not have to figure out the contributions, as I am only interested in tissue concentrations.

4. Good news is I do have IV human and mice data... Bad news is that the predicted Cmax was at and not above the observed Cmax. I wonder how much I can deviate from the observed or SAR predicted logP.  Trying some more today as I have a lot of unknowns.

**Comment by yishuanwu** [comment]
I tried to normalize the observed dataset so I would not have to worry about Km or variability. I fitted exponential model/steady state exponential model to the single dose and steady dose tissue data, and did a quick PopPK modeling to fit the plasma data. I initially used MoBi to parameter identified the GLUT tissue expression, but I can only send one simulation to MoBi and I have tissue expression for two dose levels. So, I tried creating a GLUT transporter for each tissue I have data for and optimize in PK-Sim. The brain was not clearing the drug at all, so I added GLUT efflux on top for each tissue. The parameter identification looks really bad (I know that I am optimizing too many at once with two transporter processes per tissue) so I have been doing the fitting manually. For some tissue it seems like I can fit more easily if I change the endothelial permeability (someone told me I am allowed to reduce it) to some very small number. I am a bit worried that I am making too many assumptions. In addition, the transporter/permeability tend to have more effect for the terminal phase than for the initial phase, which seems more affected by logP, but I don't know how far I am allowed to deviate from the experimental and structure-relationship predicted logP?

**Comment by prvmalik** [comment]
There's a lot here, but this may be of assistance: you can actually send multiple simulations to the same Mobi file by importing them in .pkml format. In PKSim, right click the simulation and save as .pkml and then 'load' into the desired Mobi file.

**Comment by StephanSchaller** [comment]
> I am a bit worried that I am making too many assumptions.

Yes, fitting multiple transporters and permeability is likely bordering on "overfitting" a model (depending on the underlying observed data). It is hard to troubleshoot the actual model building (and not just technical issues) without the model file, compound info and associated data.

If you have a SAR calculated LogP, it likely is uncertain. I would allow variations on a couple of orders of magnitude (log-scale). So e.g. if you have a calculated LogP of 7, a value of 4 or 5 is still feasible.

**Comment by yishuanwu** [comment]
Sorry for the late reply, I was out sick for a few days. 
I realized that GLUT transporters are passive transporters, while all the transport processes in PK-Sim are for active transports. For now, I will remove the transport processes. 
My observed tissue data all have flatter and mostly parallel terminal phase than the plasma concentrations, so it seem like there is a slow uptake after the initial rapid partition. I will first try varying the logP to account for the initial rapid partitioning.

**Comment by StephanSchaller** [comment]
Hi @yishuanwu, GLUTs are actually facilitating transporters requiring a concentration gradient, which is similar to passive transport, yes.
The transport processes in PK-Sim are for whatever you want them to be, if you are willing to switch to MoBi.
But I have to agree with your new approach.
Good Luck,
Stephan

**Comment by yishuanwu** [comment]
I had been wondering why my tissue clearance was slower than plasma binding. It appears that lysosomal binding could be an explanation for the phenomenon.

**Comment by leeking-55** [comment]
> Hi All,
> I have a hydrophilic small molecule (logP ~ -2, pKa (basic) = 7.5) that I am trying to fit in mice, with goal of extrapolating tissue concentrations to humans. The drug has negligible tissue binding (Fu = 1.0 across multiple species), and it is not a substrate of any of the major transporters in humans (P-gp, BCRP, OATP, OCT, MATE, OAT, SGLT, etc.).
> 
> Here is the simulated curve for a single oral dose of 100 mg/kg in mice:
> ![Image](https://camo.githubusercontent.com/5eb2a23ea54487006c9faab283e005419f23455a/68747470733a2f2f692e696d6775722e636f6d2f556c4a4c714b4b2e6a7067)
> 
> Sorry for not showing the observed data. Based on the observed data, the concentration in kidney is 10x the concentration in plasma at all times.
> I could not get the tissue concentrations to be higher than the plasma concentration. I tried the following:
> 
> * Changing the logP (explored -10 to -0.1 as well as positive logP and optimizing)
> * Trying different distribution calculation method - minimal change
> * Adding a hypothetical renal reabsorption or secretory transporter
> * Adding a hypothetical intracellular protein binding partner in kidney. (I tried different combinations of Kd and Koff, but it doesn't seem to change anything? Was my drug too hydrophilic to get into the cells?)
> * Changing Permeability - P endothelial. However, that seems like it can only decrease the concentration in the tissue as the baseline is set to be very high.
> * I know I shouldn't, but changing the partition coefficient - Intracellular : plasma for the tissues of interest seem to be the only thing that will help me achieve a much higher concentration in the kidney than in plasma.
> 
> Thank you very much for your help!
> Shirley

你好，很高兴看到了相同的问题。最近我的课题遇到了相同的问题。药物性质和您描述的差不多。请问我可以发邮件想您请教一下么？
祝好
leeking

**Comment by yishuanwu** [comment]
@leeking-55 
你好，我也是初學者，不知道能幫上什麼忙。
最後我的模型做的很簡單，我有很多實際的數據，我們試了所有方案後決定相信數據的partition coefficient而不是計算推導出來的partition coefficient，而且小白鼠跟人類算出來的partition coefficient差不多，所以我們覺得可以直接沿用從小白鼠實驗推導出來的partition coefficient。器官排掉得比較慢的則是用tissue binding來解釋。注意一點就是，跟目標綁在一起的不算在free drug的濃度裡面，所以要分別模擬，事後你再用別的軟件加在一起。

你是否英文不太擅長?  這邊都是英文，我翻譯一下我們都說了什麼，對別人可能比較禮貌點。

=====Summary of Our Discussion Below=========
leeking said s/he had a similar problem for a drug with similar characteristics and would like to ask for my help through email. 

I responded that I am an amateur and might not be of much help.

I told him/her that I ended up with a very simple model, in which we used the actual observed data in mice for partition coefficient instead of the calculated values. We think that this is acceptable given that the calculated partition coefficient for the same set of physicochemical properties were similar between mice and humans. 

The slow elimination from tissue was explained by tissue binding. I fell for the pit fall of not realizing that free and protein-bound drug are not simulated together, so I emphasized that the two concentrations must be separately simulated then added using separate software.

**Comment by leeking-55** [comment]
Thank you for your help, and thank you for your patience in explaining our discussion in the forum. Indeed, I lacked consideration.
have a good day,
Sincerely，
leeking.







在 2020-05-25 23:38:03，"yishuanwu" <notifications@github.com> 写道：

@leeking-55
你好，我也是初學者，不知道能幫上什麼忙。
最後我的模型做的很簡單，我有很多實際的數據，我們試了所有方案後決定相信數據的partition coefficient而不是計算推導出來的partition coefficient，而且小白鼠跟人類算出來的partition coefficient差不多，所以我們覺得可以直接沿用從小白鼠實驗推導出來的partition coefficient。器官排掉得比較慢的則是用tissue binding來解釋。注意一點就是，跟目標綁在一起的不算在free drug的濃度裡面，所以要分別模擬，事後你再用別的軟件加在一起。

你是否英文不太擅長? 這邊都是英文，我翻譯一下我們都說了什麼，對別人可能比較禮貌點。

=====Summary of Our Discussion Below=========
leeking said s/he had a similar problem for a drug with similar characteristics and would like to ask for my help through email.

I responded that I am an amateur and might not be of much help.

I told him/her that I ended up with a very simple model, in which we used the actual observed data in mice for partition coefficient instead of the calculated values. We think that this is acceptable given that the calculated partition coefficient for the same set of physicochemical properties were similar between mice and humans.

The slow elimination from tissue was explained by tissue binding. I fell for the pit fall of not realizing that free and protein-bound drug are not simulated together, so I emphasized that the two concentrations must be separately simulated then added using separate software.
