### ISSUE TITLE
MoBi not showing any simulations

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/Forum#423]
Hello Everyone,

When I am opening my MoBi files I am unable to see any of the old simulations that i ran. I even tried to open the example MoBi file "PK_Manual_Dicolfenac" and couldn't find anything. I am not sure if it is something wring on my side or there is some problem with MoBi. I was working with it this morning and everything was okay. Please help!

![PK_Manual_Diclofenac](https://user-images.githubusercontent.com/42623466/68621537-430c4980-048d-11ea-96b3-d23447cd1e85.jpg)

Sincerely,
Kash

**Comment by prvmalik** [comment]
Try clicking on 'views' and then these two buttons 


![kash2](https://user-images.githubusercontent.com/29066045/68621908-dbf79080-049e-11ea-95bb-10eebdfa9fc3.JPG)

**Comment by yvkashyap** [comment]
Hi Paul,

Thanks for your quick reply. I tried and it is not showing anything.

Sincerely,
Kash

**Comment by prvmalik** [comment]
Another trouble shooting option: Click 'parameter identification', click 'create new' and then click 'add simulations.'  if the simulation appears there then it still exists in the file. if it is not there then it probably doesn't exist in the project file anymore. 

![Kash3](https://user-images.githubusercontent.com/29066045/68622346-ee25fe80-049f-11ea-86f5-0222626a828d.JPG)

**Comment by prvmalik** [comment]
Also try 'Modeling' and 'create Simulation' to see if your prepopulated building blocks are still in the project file as shown here

![kash4](https://user-images.githubusercontent.com/29066045/68622472-36ddb780-04a0-11ea-9680-ea53929794a1.JPG)

**Comment by yvkashyap** [comment]
Hi Paul,

I can see all my simulations when I tried the parameter validation. Also, I can see my prepopulated building blocks when I am trying to create a new simulation.

Sincerely,
Kash

**Comment by prvmalik** [comment]
The problem then is not being able to view your building blocks and simulations windows. Should be an easy fix for some of our technical people...

**Comment by msevestre** [comment]
@yvkashyap Can you actually see the Simulation explorer?

If not, please go to your settings (Utilties => Options). 
Click on Reset Layout
![image](https://user-images.githubusercontent.com/1041237/68625194-858e5000-04a6-11ea-9c79-60902db11a18.png)

Restart PKSim
Try again

That should fix the corrupted layout

**Comment by StephanSchaller** [comment]
Hi Kash, Paul,

if you are missing the BB and Sim Browser Windows, an easy fix is to reset your user settings:
https://github.com/Open-Systems-Pharmacology/MoBi/issues/322

**Comment by StephanSchaller** [comment]
Or what Michael wrote ;-)

**Comment by yvkashyap** [comment]
Thanks, Paul, Michael, and Stephan for quickly addressing my issue. I removed the settings.xml file from my AppData and now able to access my simulations in MoBi.

Sincerely,
Kash
