### ISSUE TITLE
Unestimate the concentration of vemurafenib

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#424]
Hi, all

I am doing a vemurafenib (Log P 5.1, pka 7.1, MW 500, fu <0.01)simualtion, but I can't reach the Cmax like the observed data.
![image](https://user-images.githubusercontent.com/54141158/68741261-1e000e00-0628-11ea-896b-a3821016efd9.png)

The hepatic clearance rate is according to publication value, and the fu is fitted to be 2.70E-4 to get consistent with blood plasma ratio of 0.72. The distribution model is Poulin & Theil. It's an oral formulation, however, choosing dissolved formulation can only make littele difference
I have condiser transporters like ABCG2, ABCB1, OATP1B3 and also the EHC. After parameters identification, the parameters for transporters have been set to make the distribution in brain be of small fraction, which is agreement with publication, and biliary clearance get very small so that EHC might get insignificant.

Is there any else factor to better the fitting? Moreover, published data says vemurafenib is mainly excreted unchanged by biliary pathway, especially within first 48 h, and I think it suggest the EHC for vemurafenib is important. Can EHC influence the Cmax?

Any comment is appreciated.

**Comment by prvmalik** [comment]
Try optimizing intestinal permeability (transcellular) in the parameter identification tool.

With pKa 7.1 a notable portion of your molecule will be charged at physiologic pH. Try switching the cell permeability calculation algorithm to charge-dependent schmitt. Of course this will change your blood:plasma ratio.

On opinion alone, I find that using a dummy enzyme inside hepatic intracellular space works better than using the total hepatic plasma clearance function, especially in the case when permeability may be limiting to elimination.

**Comment by wangwei1619** [comment]
Dear @prvmalik 
Thanks for your help. I tried to find Km, Vmax for transporters on vemurafenib but failed. What I know is the fraction of unchanged vemurafenib excreted to feces should be 0.38 at 48h and 0.55 at 96h, but these data is for 960 mg vemurafenib mutiple dose after 14 days of treatment (on day 15 , 960 mg vemurafenib labled with isotope was given and fraction was then calculated )not for 160mg which I am simulating. The observed data is far above my result (with the difference of 7 magnitude). It seems I can never reach that degree.

**Comment by wangwei1619** [comment]
Besides the problem above, I also find something very weird.
Basing on the parameters for transporters, the plasma concentration curve would be like this even if the specific clearance is set to be 0:
![image](https://user-images.githubusercontent.com/54141158/68830978-1ef87480-06e8-11ea-8a0a-a541197703e5.png)
I want to see where the drug accumulates  in and I find concentration curve for every tissue is showing decreasing shape. But for small intestine and the intracellular space of duodenum, jejunum and ileum, the Cmax are especially high.
![image](https://user-images.githubusercontent.com/54141158/68831646-db9f0580-06e9-11ea-98d4-04df098dd8bb.png)
![image](https://user-images.githubusercontent.com/54141158/68831654-e0fc5000-06e9-11ea-85bb-696b42faf7c8.png)
How can drug concentration in every tissue decrease when the clearance is 0? 
And, I know there is a mechanism of scaling the permeability between intracellular and interstial space in mucosa to avoid drug accumulation in enterocytes, does the figure mean an accumulation in my simulation (I use the specific intestinal permeability and organ permeability calculated automatically )?

**Comment by tobiasK2001** [comment]
Hi, It is indeed very hard to explain your results without having a chance to look at the model. Do you think you can upload it?
Some general things. Your compound is very lipophil and a week base. Why do you use Poulin Theil distribution? Have you tried fitting Lipophilicity in a range of 4-6 with variation of distribution model calculation as a fist step?

Best, Tobias

**Comment by wangwei1619** [comment]
Hi, @tobiasK2001 
Thanks for your help. Here is my PK-Sim file, the simulation named "Shan" is what I am focusing on now, and only the individual "Shan" is loaded with transporters expression. I forgeted to mention that I changed the distribution model to Rodgers & Rowland. However, with fu is fitted to blood plasma ratio, results form two model seem to be similar. I have tried less Log P, and the result was truly better, but I don't know if there is another way to make it. 
[Vemurafenib randoomly.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3845501/Vemurafenib.randoomly.zip)

**Comment by StephanSchaller** [comment]
Hi @wangwei1619 ,

> Besides the problem above, I also find something very weird.
Basing on the parameters for transporters, the plasma concentration curve would be like this even if the specific clearance is set to be 0

If I switch off all your clearance processess in the "Shan" simulation, I get this:

**Comment by StephanSchaller** [comment]
To continue:

>  for every tissue is showing decreasing shape. But for small intestine and the intracellular space of duodenum, jejunum and ileum, the Cmax are especially high.

Yes, this is expected, as the drug gets firs absorbed in small intestine mucosal tissue. The concentrations (technically) always follow a gradient that decreases from source (i.e. the gut) to sink (i.e. the plasma in case of plasma clearance). Partitioning coefficients may offset this gradient, but not to go into details here.

> How can drug concentration in every tissue decrease when the clearance is 0?
As pointed aout above, you may have set the clearance --> 0 in the Building Block and not in the Simulation.

> And, I know there is a mechanism of scaling the permeability between intracellular and interstial space in mucosa to avoid drug accumulation in enterocytes, does the figure mean an accumulation in my simulation (I use the specific intestinal permeability and organ permeability calculated automatically )?
No, this is not indicative of an accumulation... as pointed out above, this is just the first entry-point of the drug into tissue where it still has a high concentration before distributing into the body.

Looking at your file and trying a fit, I didn't see a problem.
I used the Zhang model and fitted the following:
![image](https://user-images.githubusercontent.com/25477643/68874488-9090ec80-0701-11ea-81be-760fe1129263.png)

Varying both, calculation methods for partitioning and permeabilities, the curves could be fitted very well using the Zhang model (the one with only few processes)... I didn't check on the feasability of the end results for the parameters:
![image](https://user-images.githubusercontent.com/25477643/68874638-d6e64b80-0701-11ea-9a7e-ce5f7ee0d402.png)

Of course you had a lot of processes in the Shan model and you will need to inform them to some extent from literature. Just fitting is not the ideal way to go in PBPK.

Maybe this helps.
Stephan

**Comment by wangwei1619** [comment]
Dear @StephanSchaller ,

I think I come across some bug. 
![image](https://user-images.githubusercontent.com/54141158/68909005-e314ec00-0787-11ea-9b86-cb921cf6a8a0.png)
![image](https://user-images.githubusercontent.com/54141158/68909017-edcf8100-0787-11ea-8cc6-1c685b8185bc.png)
Thanks for your help, I will folllow your guide .

**Comment by wangwei1619** [comment]
Hi, @StephanSchaller 

I feel I am a troublemaker.
I thought I came across a bug, so I tried to unload and reload the clearance and transporter processes to solve it, but failed.
Then I am trying to re-build this mode from the beginning. However, I can not load the transporters processes any more, like this:
![image](https://user-images.githubusercontent.com/54141158/68912208-6c312080-0792-11ea-8ec7-6aff72b60196.png)
I only define one individual and one compound, and associate the vemurafenib to the transporters, but I transporters are not showed in simulation.
Is there anyway to solve this?

**Comment by msevestre** [comment]
Do you have the transporters in your individual?

**Comment by wangwei1619** [comment]
Hi, @msevestre 
Yes, I firstly load transporters in individual, then I assocoate them to drug

**Comment by msevestre** [comment]
It does not look like it from the screenshot. Can you please go to the expression tab of your individual and make a screenshot?

**Comment by wangwei1619** [comment]
Hi, @msevestre 

Yes, I find I have made a mistake by adding transporters to enzymes when I check the individual building block. And from this new work I can get the result what @StephanSchaller showed. 

Thanks for your help

**Comment by prvmalik** [comment]
Consider checking out this recent publication, which features a discussion of PBPK modeling of vemurafenib doi: 10.1002/cpt.1672

**Comment by leeking-55** [comment]
> Hi, all
> 
> I am doing a vemurafenib (Log P 5.1, pka 7.1, MW 500, fu <0.01)simualtion, but I can't reach the Cmax like the observed data.
> ![image](https://user-images.githubusercontent.com/54141158/68741261-1e000e00-0628-11ea-896b-a3821016efd9.png)
> 
> The hepatic clearance rate is according to publication value, and the fu is fitted to be 2.70E-4 to get consistent with blood plasma ratio of 0.72. The distribution model is Poulin & Theil. It's an oral formulation, however, choosing dissolved formulation can only make littele difference
> I have condiser transporters like ABCG2, ABCB1, OATP1B3 and also the EHC. After parameters identification, the parameters for transporters have been set to make the distribution in brain be of small fraction, which is agreement with publication, and biliary clearance get very small so that EHC might get insignificant.
> 
> Is there any else factor to better the fitting? Moreover, published data says vemurafenib is mainly excreted unchanged by biliary pathway, especially within first 48 h, and I think it suggest the EHC for vemurafenib is important. Can EHC influence the Cmax?
> 
> Any comment is appreciated.

hi,wangwei
I have the same problem，have you solved this problem?
Can I add your wechat?
best wish,
leeking

**Comment by wangwei1619** [comment]
Hi, Ieeking,

Yes, I have finished this model. You can contact me via my email wangwei1619@yeah.net, and I give you ma wechat there.

Best regards,
Wang Wei
