### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by damkeeper** [Open-Systems-Pharmacology/Forum#425]
my ps-sim cannot run very well.the metabolizing enzymes datebase are not available.what should i do?

**Comment by StephanSchaller** [comment]
Hi @damkeeper, please check out the documentation here: https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-data#adding-protein-quantities-by-querying-the-internal-database

And follow the instructions at the very bottom here: https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-options

Best,
Stephan

**Comment by StephanSchaller** [comment]
And of course first download the database here: https://github.com/Open-Systems-Pharmacology/Gene-Expression-Databases/releases/download/v2.0.0/GENEDB_human.expressionDb

**Comment by damkeeper** [comment]
with your help,i have solved my problem.thank you a lot.

best,
damkeeper

**Comment by msevestre** [comment]
Thanks @StephanSchaller
