### ISSUE TITLE
Modeling of non-linear pharmacokinetics 

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/Forum#426]
Hi, everyone.
In this quetiapine model, a good fitting was obtained for 25 mg single-dose PK. But prediction underestimated concentrations under multi-dose scenario. I have tried multiple caculation methods for permerbility and distribution, and no one appears to solve this matter. Quetiapine is extensively metabolized, and I used metabolic parameters from a previous study. CLint values of 1.34, 0.106 and 0.24 μL/min/pmol for CYP3A4, CYP2C9 and CYP2D6, respectively.
![image](https://user-images.githubusercontent.com/45459593/69149632-d8ed4780-0b11-11ea-8b1c-c9c364e12ce2.png)
Should I use Michaelis-Menten kinetics to mimic metabolism instead of a first-order CLint ?
Thank you !

Best,
Liang Z

**Comment by StephanSchaller** [comment]
Hi Liang,

how are the two observed data connected (same study and maybe even same individual (or population mean?)).
What is the formulation? Tablet? Any solubility issues?

Do you have in vitro characterization of the CYP metabolism of quetiapine (Km or EC50 values)?

A first guess could be to use Michaelis Menten kinetics, but apparently there was no saturation observed under therapeutic conditions: https://www.ncbi.nlm.nih.gov/pubmed/16841513

Maybe the link helps…

Stephan

**Comment by regulus92** [comment]
@StephanSchaller Thanks for your reply. The two observed data come from one study, so I think there is no ethnic variation. The formulation is common tablet set as solution because of its fast dissolution. Though the drug label says that quetiapine PK follows linear kinetics, a first-order elimination by CYPs underestimates concentrations under 300 mg b.i.d.

**Comment by wilbertdew** [comment]
Hi Liang,

Can you zoom in on the time between 190 and 200 hours to make sure it is not a graphical or timestep issue?

**Comment by regulus92** [comment]
@wilbertdew @StephanSchaller I think it's not. But satisfactory fitting was observed after adjusting metabolism by using Michaelis-Menten kinetics. Thank you for your help.
![image](https://user-images.githubusercontent.com/45459593/69530203-9c579b00-0fac-11ea-87c7-b793198d427c.png)

**Comment by StephanSchaller** [comment]
@regulus92 

Happy to help! Stephan
