### ISSUE TITLE
Parameter Identification (Rate constant for endosomal uptake (global); hydrodynamic radius)

### ISSUE THREAD

**Issue by ClaireGrube** [Open-Systems-Pharmacology/Forum#430]
Hey there,

I am currently on a project using the large molecule model setting in my simulations. However the default settings do not describe my data very well.
cmax is generally overestimated, while clearance is underestimated for almost every patient sample. That s why I used the parameter identification to fit the curves via "Rate constant for endosomal uptake (global)" individually to the patients. However, I have concerns regarding the physiological plausibility. Is it plausible to use a user defined variability in a generic population? I'd highly value your opinion in this matter.

Moreover, cmax is influenced by the hydrodynamic radius. I have the estimate of the hydrodynamic radius that is described in Niederalt et al, 2017, while in the same time I have an experimentally determined value as well. Do you think changes made in this parameter are justifiable?

Would it make sense to use parameter identification for both of these two values simultaneously? I was thinking about using weighting to stress the importance of the hydrodynamic radius on the distributional phase (and thus cmax) on the one hand side and the importance of the "Rate constant for endosomal uptake (global)" for clearance on the other side.

Thank you for your input on that issue, looking forward to fruitful discussions.
Kind regards!
CG

**Comment by Christoph27** [comment]
Dear Claire,
more background information would be helpful (which type of large molecule, which species etc.).
If it is an IgG antibody, I would stick to the 5.34 nm used during model development. 
The Kd(FcRn) is a parameter to consider regarding clearance. Note, that experimental values are highly depending on assay conditions. For the development of the protein model in PK-Sim, Kd(FcRn) values were used which stem from BIAcore assays in which the antibody was immobilized on the chip surface. With these values, the FcRn concentration in the endosomal space was fitted. So it is problematic to use affinities to FcRn measured using a different assay. I have made good experience with a Kd(FcRn)=0.85 µM for humanized IgG1 antibodies in humans (this is also used in the paper you mentioned).  

If you overestimate Cmax and underestimate clearance, target-mediated drug disposition could be something to consider.

Best regards,
Christoph

**Comment by ClaireGrube** [comment]
Dear Christoph,

thank you very much so far. Since we are investigating a non-antibody, we are assuming no TMDD. I have attached some files to illustrate the differences observed between standard starting parameters of the endosomal uptake rate constant and the altered version. They all show the prediction of a population to (some of the) observed concentrations on a log-scale of the y-axis and the time on the x-axis with solely this constant changed.

Do you think this constant is subject to inter-individual variability, thus justifying to implement a user defined variability on that parameter in a population?

Kind regards,
Claire
![kup-fitted](https://user-images.githubusercontent.com/58309239/69865173-cce74f80-12a0-11ea-9b09-3bb186e0f544.JPG)
![kup-fitted20h](https://user-images.githubusercontent.com/58309239/69865174-cce74f80-12a0-11ea-847b-18b2200b10e4.JPG)
![PK-Sim-Standard3](https://user-images.githubusercontent.com/58309239/69865175-cce74f80-12a0-11ea-86d2-0026229ffa8c.JPG)
![PK-Sim-Standard4](https://user-images.githubusercontent.com/58309239/69865176-cce74f80-12a0-11ea-9609-8c930a941589.JPG)

**Comment by Christoph27** [comment]
Dear Claire,
then the clearance is rather overestimated (late concentrations underestimated) with the standard parameterization, right? Interesting. Do have a very large compound [r>>r(antibody)]?
I would agree that it is reasonable to add a user defined variability on the endosomal uptake rate. Either directly or via adding variability to the endosomal volume  [easiest via the parameter "Fraction endosomal (global)"].  (Changing the endosomal volume also results in a changed total endosomal uptake since the later is defined volume specific.)  

Best regards,
Christoph

**Comment by ClaireGrube** [comment]
Dear Christoph,

you are right with your guess, this is a large compound, indeed. ;) I will test the sensitivity of endosomal volume on the model as you suggested and then compare both. 

I ll keep you updated if things improved. Thanks so far!

Regards,
CG

**Comment by StephanSchaller** [comment]
Hi Claire, what is the calculated "radius (solute)" for your compound? is it a molecule or a nanobody?
To me, it looks like distribution, rather than clearance ist might be an issue.
Does the compound actually bind to FcRn?

Did you try reducing the (calculated) radius to check its effect on the PK?

**Comment by ClaireGrube** [comment]
Dear Stephan,
thanks for your input. I did try to reduce the radius, it definately is improving cmax fit based on VPC reaching its optimum fit at about 20% reduction. It s the reason why I was asking in my initial inquiry whether it was plausible to do so. (since the estimate is based upon a variety of experimentally validated proteins and I m new to the field).
Regards,
CG

**Comment by StephanSchaller** [comment]
While there are more parts to the puzzle, here, I believe if 20% works for the radius, this should be acceptable. While the radius (solute) of the molecule is one part, the other is the endothelial structure of the tissue. The endothelial cell structural heterogeneity is classified in continuous endothelium, fenestrated endothelium and discontinuous endothelium.
As an abstraction, PBPK models use the so-called "two-pore formalism". 
While this mechanism, and "pore" sizes (or radii) are just one of the parameters, has been informed by experiments to some extent, and uncertainty always remains, (individual) variability may also occur.

But as @Christoph27 said, more background information would be needed to be more helpful.

Best,
Stephan

**Comment by Yuri05** [comment]
@ClaireGrube Closing. Please reopen if there are still any unanswered questions.

**Comment by StephanSchaller** [comment]
@ClaireGrube , the community would appreciate if you could share how the issue was solved in the end?
Thanks,
Stephan
