### ISSUE TITLE
How important is permeability on flux rate of drug from plasma to interstitial space (Jvi,org) for biologics PBPK?

### ISSUE THREAD

**Issue by SL-CHOI** [Open-Systems-Pharmacology/Forum#431]
Hello all,

It is a question about equation 2 in paper "Christoph et al. 2018 A generic whole body physiologically based pharmacokinetic model for therapeutic proteins in PK-Sim".

![image](https://user-images.githubusercontent.com/58403330/70254611-a8e6ab00-1785-11ea-9d8c-f39d9a222b18.png)

Equation 2 in the paper explicitly indicates product of permeability and surface area (PS,org) is a crucial factor to the flux rate of drug from plasma to insterstitial space (Jvi,org). 

On the other hands, Peclet numbers in equation 2, that defines ratio of convective and diffusive transport (Pe,org= J,org * (1-Sigma,org)/ PS,org), would cancel out PS,org in equation 2. As a result, Jvi,org is independent of PS,org.

![image](https://user-images.githubusercontent.com/58403330/70254707-d16ea500-1785-11ea-9414-e6d6a899ef7e.png)

This makes me wonder the reason of having permeability (PS,org) in equation 2 from the paper.

**Comment by StephanSchaller** [comment]
But you still have the Peclet number in the exponent within the denominator in equation 2.

**Comment by SL-CHOI** [comment]
Yes, but Peclet number (Pe) is a ratio of extravasation-diffusive transport, which has a different physiological meaning as compared to PS,org for diffusive transport. 

When PS,org is cancelled out, how to explain the denominator term EXP(Pe)-1?

**Comment by StephanSchaller** [comment]
> , how to explain the denominator term EXP(Pe)-1?

Not sure I understand what you mean by this.

Have you read up on the references from which these equations were derived:
 
Ref. [[46](https://www.ncbi.nlm.nih.gov/pubmed/8295933)] should be helpful, e.g. Equation (5), some more on Peclet around Equation 17 and 33.

@Christoph27 can you comment?

**Comment by SL-CHOI** [comment]
@StephanSchaller Thank you Stephan for pointing out that. We may find something out from Ref. 46.

**Comment by StephanSchaller** [comment]
@SL-CHOI, happy to help.
Please do let us know if you find sth. out.

**Comment by StephanSchaller** [comment]
@SL-CHOI , did you have further insights, here?

**Comment by SL-CHOI** [comment]
According to Rippe 2014 paper eqn(5),  the contribution of PS,org to the overall clearance (CL) is dependent on Peclet number (Pe), as the term EXP(Pe)-1 controls the proportion of diffusion to the overall CL
They used simulation and demonstrated that when Pe>3, PS is no longer an important factor, and vice-versa.

**Comment by StephanSchaller** [comment]
@SL-CHOI , okay, thank you.
