### ISSUE TITLE
AAG ontogeny

### ISSUE THREAD

**Issue by PKSimUser** [Open-Systems-Pharmacology/Forum#432]
Does anyone know which ontogeny function for AAG is implemented within PK-Sim version 8.0? Is it the same as that listed in the PK-Sim® Ontogeny Database Version 7.3:
Mayer et al., A novel approach to estimate ontogenies for PBPK applications – From literature
data to simulations.
https://www.page-meeting.org/default.asp?abstract=8583

 I cannot find the PK-Sim ontogeny database published for version 8?

**Comment by msevestre** [comment]
This is the same as listed for 7.3. nothing has changed as far as I know
Is it referenced somewhere in the documentation?

**Comment by Incei** [comment]
> Is it the same as that listed in the PK-Sim® Ontogeny Database Version 7.3:

Yes, there are uptil now no updates implemented on AAG ontogeny. Since there are no other ontogeny updates after 7.3, the versioning of the documentation has not been changed and is still the latest one.

**Comment by PKSimUser** [comment]
Ok thank you

**Comment by Yuri05** [comment]
Closing. @PKSimUser Please reopen if you have any further questions.
