### ISSUE TITLE
Propofol and (Nor-)Adrenaline PBPK Model

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#433]
Anyone know of publication on PBPK models for Propofol or (Nor-)Adrenalin or has ideas for publications that could help build these models?

Thanks,
Stephan

**Comment by regulus92** [comment]
Hi, Stephen. I found two PBPK reports for propofol.
1. Michelet R, Van Bocxlaer J, Allegaert K, Vermeulen A. The use of PBPK modeling across the pediatric age range using propofol as a case. J Pharmacokinet Phar. 2018;45(6):765-85.
2. Gill KL, Gertz M, Houston JB, Galetin A. Application of a physiologically based pharmacokinetic model to assess propofol hepatic and renal glucuronidation in isolation: utility of in vitro and in vivo data. Drug Metab Dispos. 2013;41(4):744-53.

Regards,
Liang

**Comment by Incei** [comment]
@StephanSchaller I have build a PBPK model for Propofol parent drug only. I will publish it on the OSP repository as soon as I have finalized the report. Perhaps you can use this as starting point for including your metabolites.

https://github.com/Incei/Propofol-Model

**Comment by StephanSchaller** [comment]
Thanks @regulus92 and @Incei 

@Incei ..don't know how I could have missed tis repository. This should be perfect, we don't necessarily require metabolites. It is for an point-of-care ICU application.

**Comment by Incei** [comment]
@StephanSchaller , all is good :)

**Comment by RobinM92** [comment]
Hi Stephen,

As you know I constructed the PBPK model in the first reference of 
Liang, it's in Simcyp.
If you need any more information about the model or input parameters, 
feel free to ask me :)

Kind regards,

Robin

Am 13.12.2019 um 04:22 schrieb Liang Zheng:

**Comment by StephanSchaller** [comment]
Hi Robin, that's much apprechiated. Will certainly get back to you once we run into questions.

Thank you, Stephan
