### ISSUE TITLE
how to generate a Plasma concentration of a population

### ISSUE THREAD

**Issue by anafunguetto** [Open-Systems-Pharmacology/Forum#434]
Hey everyone! 

Could anyone tell me how to generate plasma data for each of the individuals in the population? When I transport the result to Excel, it gives me only the arithmetic average of the PC data ... But I need this data to make a POPPK, so I need each individual's data.

tks!!

**Comment by tobiasK2001** [comment]
Hi, 
I guess you want to export you simulation results. Use some of these options accessable via right click on Simulation

![image](https://user-images.githubusercontent.com/25585248/70927906-2a64f580-2030-11ea-989d-92c3d0fc2f0f.png)


Hope this helps.

Best Tobias
