### ISSUE TITLE
How to consider precipitation process in PK-Sim?

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#435]
Hi, all
I am curious about how to consider precipitation process in PK-Sim. **Formulation** type as **Weibull** and **table** allow dissolution profile showing increasing trend, so how to handle dissolution profile like this ( citted from DOI: 10.1208/s12249-013-0018-2):
![image](https://user-images.githubusercontent.com/54141158/71072488-96269a00-21b9-11ea-83c7-f0ba41a5fba0.png)
It is a weakly basic drug so that it easily precipitate in intestine. I have not found a parameter related to precipitation process like mean precipitation time yet. Is there any way to simulate situation like this?

**Comment by Yuri05** [comment]
You could try reproducing of the corresponding InVitro experiment using particles dissolution.
For this: create a simulation in PK-Sim with a Particles Dissolution Formulation and export it to MoBi.
(Start with a monodisperse formulation).

In MoBi (in the simulation):
1) set `Organism|Lumen|OralApplicationsEnabled` to 0. This will deactivate all movements of drug/liquid/etc. from Stomach into Duodenum
2) Set `Organism|Lumen|Stomach|Liquid` to the volume used in the inVitro experiment
3) Set `Organism|Lumen|Stomach|pH` to the pH used in the inVitro experiment
![grafik](https://user-images.githubusercontent.com/25061876/71108543-9c217880-21c3-11ea-840e-56845eefa49a.png)
Now you can play around with some parameters of the particles dissolution formulation and molecule properties and compare fraction dissolved with your inVitro experiment.
Most of those parameters can be changed directly in MoBi.
(`Treat precipitated drug as` and `Enable supersaturation` can be set either to 0 or to 1)
![grafik](https://user-images.githubusercontent.com/25061876/71111671-3c7a9b80-21ca-11ea-84ad-ed3fb0034873.png)
However if you would like to change number of particle bins or any formulation parameters affecting the radius distribution between particle bins: this must be done in PK-Sim and then reexport the simulation. 
![grafik](https://user-images.githubusercontent.com/25061876/71109247-18688b80-21c5-11ea-9c74-9667917ac1aa.png)

@AndreDlm @KatrinCoboeken Any further comments on this?

**Comment by wangwei1619** [comment]
Dear @Yuri05 ,

Thanks for your comment. Do you mean I can first find porper properties of drug to simulate the in vitro dissolution profile in gastric condition, then use these parameters to do simulation in normal condition?

And how does PK-Sim condsider the precipitation process? Is it a reverse process of dissolution and using Noyes-Whitney equation too?
If so, is there any way to handle situation like this (cited from DOI: 10.1016/j.ejpb.2016.05.017)?
![image](https://user-images.githubusercontent.com/54141158/71138735-5f976080-2247-11ea-9a4d-8452b94711e1.png)
These are dissolution profiles for solid dispersion of celecoxib in 500 mL FaSSIF, and the dashed line is equilibrium solubility of crystalline celecoxib in FaSSIF. The precipitation does not happen as soon as concentration achieve the equilibrium solubility and not lead to a concentration around the equilibrium solubility in the end. Moreover, it shows that drug begin to precipitate when concentration reach the peak (I am not assure if it is named as dynamic solubility), thus there must be 2 kind of solubility value in dissolution function, but Noyes-Whitney equation only has one solubility.

I think the first issue may could be addressed by easily calculating the final equilibrium solubility of solid disperion. What about the second issue? Do I have to make change to dissolution function?

Best regards,
Wang Wei

**Comment by Yuri05** [comment]
>Do you mean I can first find porper properties of drug to simulate the in vitro dissolution profile in gastric condition, then use these parameters to do simulation in normal condition?

Yes

>And how does PK-Sim condsider the precipitation process? Is it a reverse process of dissolution and using Noyes-Whitney equation too?

Yes. For details s. e.g. 
* https://www.sciencedirect.com/science/article/abs/pii/S0939641110001517 
* https://onlinelibrary.wiley.com/doi/abs/10.1111/j.2042-7158.2012.01534.x 

<img src="https://ars.els-cdn.com/content/image/1-s2.0-S0939641110001517-fx1.jpg">

>If so, is there any way to handle situation like this...?

Well, not sure if it's possible to reproduce such a dissolution profile 1:1 with the Noyes-Whitney. Using polydisperse formulation in combination with supersaturation you can achieve immediate dissolution of the part of the drug followed by slow precipitation to equilibrium (s. example attached). However it is still not exactly your case
[P1_Precipitation.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3983600/P1_Precipitation.zip)

**Comment by wangwei1619** [comment]
That's quite helpful, I'll try latter.
Thank you very much.
