### ISSUE TITLE
How to compare population PBPK models in one graph?Can I realize it in PK-SIM?

### ISSUE THREAD

**Issue by RachelQin95** [Open-Systems-Pharmacology/Forum#436]
Hi everyone,
I have a little problem :I want to compare simulations of two population PBPK models in one plot just like the plot I've uploaded,but I can't find the correct operation in PK-SIM，could you please tell me how I can draw this plot?
 Thank you for your kindly help.
![捕获](https://user-images.githubusercontent.com/59172339/71363237-7b965b80-25d3-11ea-9507-8ff6a78a27b5.JPG)

**Comment by Yuri05** [comment]
https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#comparison-chart-for-individual-or-population-simulations-in-one-plot

**Comment by RachelQin95** [comment]
Thank you for your reply,
I've read the manual,but there are some detailes I can't understand:I've selected two simulations as the plot show,but the result always only one simulation,could you please tell me what went wrong?
![image](https://user-images.githubusercontent.com/59172339/71387930-196c4380-2631-11ea-8ad8-0fbab7645515.png)
![image](https://user-images.githubusercontent.com/59172339/71387991-67814700-2631-11ea-9bd9-0510830ff845.png)
 Thanks again for your kindly help and happy Christmas Eve~

**Comment by Yuri05** [comment]
Select `Simulation Name` for grouping
![grafik](https://user-images.githubusercontent.com/25061876/71412706-2f88fc80-264f-11ea-8a08-669598c5f0ab.png)
Add splitting by colour for your simulation name
![grafik](https://user-images.githubusercontent.com/25061876/71413246-927b9300-2651-11ea-9082-35e5d2a9329e.png)
That's it :)
![grafik](https://user-images.githubusercontent.com/25061876/71413272-af17cb00-2651-11ea-8a3d-44dd46be59eb.png)
S. also example attached 
[PopComparison.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3998254/PopComparison.zip)

Merry Christmas to you as well :)

**Comment by RachelQin95** [comment]
I got it!Thank you！

**Comment by jzq90** [comment]
That's helpful. Thanks
