### ISSUE TITLE
genotype spicificity in pksim

### ISSUE THREAD

**Issue by AyeshaTanveer** [Open-Systems-Pharmacology/Forum#437]
How to add genotype specificity of a drug using pk sim? I am working on a drug which is CYP2C9*1/1 and CYP2C9*1/3 genotype  specific. kindly guide me in this matter.

**Comment by regulus92** [comment]
For the sake of simplicity, you may consider genotype as a molecular-specific parameter, that is, to adjust metabolic parameters such as kcat for different genotypes/phenotypes.

**Comment by AyeshaTanveer** [comment]
Alright Thank you soo much
