### ISSUE TITLE
Importing observed data

### ISSUE THREAD

**Issue by nmens** [Open-Systems-Pharmacology/Forum#44]
Dear all

First attempt with PK Sim. Observed data button on Imported/Exported tab is blocked (grey color). It is only possible to import Fraction Data. Being in mind that Fraction Data is for dissolution data, should I also use it for PK concentration data? Why Observed data button is blocked?

Rgds
NS

**Comment by Yuri05** [comment]
Do you have any compounds in your project?
If not: please create/load a compound first. After that you will be able to load concentration observed data for any of your project compounds
![clipboard01](https://user-images.githubusercontent.com/25061876/28071505-6bcf9aa8-6650-11e7-863c-93414575deab.jpg)

**Comment by nmens** [comment]
Many thanks.
This was the problem. Importing data before creating a compound.
A rookie question

**Comment by msevestre** [comment]
@nmens no problem. That's why the forum was created
