### ISSUE TITLE
Error with the MoBi Toolbox for R

### ISSUE THREAD

**Issue by Ricardo-DO** [Open-Systems-Pharmacology/Forum#440]
Hello everyone
I hope you are doing well.
I have been having an issue with the MoBi toolbox for R.
I was working with the version developed by Stephan Schaller and using some code that he handed us in the PAGE Meeting 2018. I was using R for sensitivity analysis.
Now I updated to MoBi 8 and the MoBi toolbox for R that comes with the installation.
I am using the exactly same R code (changing the name of the package and the name of my simulation) but I got this warning:

Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: Result with path_id Sim|Organism|VenousBlood|Plasma|ABC|Concentration in container does not exist!

The funny thing is that the code that I use, worked once but then never again.
I would really appreciate if you could give me hand checking what's wrong with the code.
Please find attached the xml file, the MoBi file and the R code.

Many thanks for your help!
[git.txt](https://github.com/Open-Systems-Pharmacology/Forum/files/4026115/git.txt)
[Sim.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/4026116/Sim.zip)

**Comment by StephanSchaller** [comment]
That's indeed strange.

Re-running the workshop exercise still works with 8.0.

I have tested your code and it seems to throw errors only for some of the nodes (sometimes on sometimes 2).

Running the simulation explicitly sometimes throws this error: 
```
Error in updateSimulationInputs(DCI_Info) : 
  Component handle 31370816 is invalid!
```

We will have to look into it.

**Comment by StephanSchaller** [comment]
@Yuri05 @msevestre , this might be an error when SimModel is written?

**Comment by Ricardo-DO** [comment]
Hello! 
Stephan, thanks for your time to reply.
I have checked again and if I export the simulation from PKSim, the R code works well for my analisis.
However, if I export the simulation from MoBi is when I have the problem.
And as you suggested, probably it would be a problem when the SimModel in written from MoBi.

**Comment by Yuri05** [comment]
Closing. @Ricardo-DO FYI: R-Toolbox was completely reimplemented with the latest OSP release, providing a lot of new features.
Take a look :) https://docs.open-systems-pharmacology.org/working-with-r/r-introduction
