### ISSUE TITLE
problem on multi-dose simulution

### ISSUE THREAD

**Issue by xixi-1995** [Open-Systems-Pharmacology/Forum#441]
hi, everyone
I met one problem when I did multi-dose simulation, 
![image](https://user-images.githubusercontent.com/54713645/71878935-d9947880-3167-11ea-97ed-ba7a25994f49.png)
I have tried to simulate lower multi-dose ,it goes well, when I tried to simulate higher multi-dose, it shows error like the picture described, I'm wondering how to solve this problem and how to understand the error I have met?
I really need your help

**Comment by Yuri05** [comment]
The error means that the underlying ODE system could not be numerically solved.
You can try to increase the number of internal solver steps in the solver settings (make sure that `Advanced `parameter mode is selected). However the predefined value of 100000 is already pretty high; increasing it will with high probability result in the same error after longer computation time
![grafik](https://user-images.githubusercontent.com/25061876/71886716-f7001d00-313c-11ea-9ba3-d8dec1edc740.png)

The problem occurs between the `last output time point before 1560 min` and `1560min`. E.g. if you simulate with 4 points/h in this time interval, the problem begins somewhere in the time interval [1545..1560] min. Try to find a time bound within this time interval where the numerical problem begins.

E.g. do something like in the screen below. You will get a new location of the problematic output time (e.g. _1550.1234_ min). After that set a simulation time to the `last output time point before before the new problematic time` (e.g. for my example it would be _1550.1200_ min), simulate and try to investigate the simulation results to get a hint what might go wrong.
![grafik](https://user-images.githubusercontent.com/25061876/71888471-88bd5980-3140-11ea-8add-564bf33c238f.png)

**Comment by xixi-1995** [comment]
thanks for your patiently reply , I have tried to adjust resolution as you mentioned above, it seems that I need try something more as the end-time is up to 168h. it is noted that I have tried to do a multi-dose  simulation with dosing interval is12h,it seems go well, while dosing interval=24h seems to have errors, I'm still confused.

**Comment by xixi-1995** [comment]
@Yuri05 thanks for your patiently reply , I have tried to adjust resolution as you mentioned above, it seems that I need try something more as the end-time is up to 168h. it is noted that I have tried to do a multi-dose simulation with dosing interval is12h,it seems go well, while dosing interval=24h seems to have errors, I'm still confused.

**Comment by Yuri05** [comment]
Can you upload your project?

**Comment by xixi-1995** [comment]
hi@Yuri05 ,thanks for your help. Here is my PK-Sim file, the simulation of po-60mg-multi-144h-bid goes well.while po-60mg-multi-144h-qd seems to have something wrong.
[Uploading Duloxetine.zip…]()

**Comment by Yuri05** [comment]
@xixi-1995 you didn't upload the project

**Comment by xixi-1995** [comment]
oh sorry,
[Duloxetine.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/4034364/Duloxetine.zip)

**Comment by Yuri05** [comment]
ok, that's a numerical problem with Weibull formulations with lag time > 0.
As a workaround: approximate your Weibull dissolution function with a table. The easiest way to do this:
1. Right click on the formulation **graph** and select "Export to Excel"
![grafik](https://user-images.githubusercontent.com/25061876/71977242-96dea900-3218-11ea-90ee-d830addec14f.png)
2. Create new table formulation and import it from the exported Weibull formulation file
![grafik](https://user-images.githubusercontent.com/25061876/71977369-e329e900-3218-11ea-8436-17e1638a2a2a.png)
3. Configure your simulation and replace your Weibull formulation with the new table formulation
[Duloxetine_Table.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/4035210/Duloxetine_Table.zip)

@AndreDlm FYI

**Comment by xixi-1995** [comment]
@Yuri05 That's quite helpful!! Thank you very much!
I'm curious about why and will it be suit for situation similar, I will try more later~
