### ISSUE TITLE
Are UGT enzymes all 1 uM/L?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#443]
I found that the reference concentration in the database for UGT enzymes are all 1 μM/L by default. Is this the real situation or jut a lack of data?

**Comment by tobiasK2001** [comment]
Dear jzq90,

that are just  lack of data as measured absolute protein abundances coming available only recently. You can insert a reference concentration of your own choice from a resonable source.

E.g. from here for UGts
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6222000/

best, Tobias

**Comment by jzq90** [comment]
Dear Tobias,

Thanks very much for the kind answering. It' very helpful.

Also, OSP is a great platform and software. Much appreciated for devotion to it.

Best,
Aaron
