### ISSUE TITLE
Could PK-Sim simulate renal reabsorption?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#444]
I know it is possible to adjust GFR fraction to compensate for the reabsorption or active secretion process.
But is there a method to calculate or predict the reabsorption process from physiochemical properties, especially for the passive reabsorption, when experimental data is unavailable.

**Comment by StephanSchaller** [comment]
> is there a method to calculate or predict the reabsorption process from physiochemical properties

No, sorry to say this is currently not an option within PK-Sim.

The couple of free tools we know of to calculate (Q)SAR (also some renal reabsorption transporters included) are: 

pkCSM:
 
http://biosig.unimelb.edu.au/pkcsm/prediction
 
and admetSAR
 
http://lmmd.ecust.edu.cn/admetsar2/
 
Hope this helps,
Stephan

**Comment by jzq90** [comment]
Hi Stephan,

The tools you share seems very interesting. I will look into it. Thanks very much for sharing.

Best,
Aaron
