### ISSUE TITLE
How to correlate experimental permeability to specific intestinal permeability properly and where to find transporter data in rats?

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#447]
Hi, all
I am doing the PBPK model on andrographolide and encounter some problems related to permeability and transporters. The experimental permeablity is cited from doi.org/10.1002/jps.22693.
![image](https://user-images.githubusercontent.com/54141158/72587082-ea46aa80-392e-11ea-987e-a89fec74c2ca.png)
![image](https://user-images.githubusercontent.com/54141158/72587140-2843ce80-392f-11ea-8efe-cd340be1f8fb.png)
![image](https://user-images.githubusercontent.com/54141158/72587411-229ab880-3930-11ea-80e6-72a7d5c602e6.png)
Figures are apparent permeability through Caco-2 cell,  effective permeability in four gut segments with and without inhibitor for transporter P-gp (verapamil) and Bcrp (dipyridamole). Frome figures, It seems the concentration of transporters are distinct in each segemnt of gut and permeability calculated from Caco-2 cell can not stand for its true permeability because it is influenced by transporters expressed on cells.

So I think I have two choices to handle with it.

1.  Bbypass the simulation of transporters influence. To make it, I can not use specific intestinal permeability calculated by PK-Sim directly because it ignores the influence of transporters. I can model different effective permeation in different parts of gut according to literature.  I think I may achieve it by adjusting specific intestinal permeability and absorption surface area ratio, but I don't know the calculation method. Is this right (Pspecific = Peff * (1/absorption surface area ratio))? 

2. Model the influence of transporters. To make it, I need to find the expression data of transporters in rat. Since PK-Sim doesn't have a database for rat, is there any databse to refer? And how to calculate the kinetics for transporters to make the effective permeability consistent with literature?

Any comment is appreciated. Thanks a lot.

**Comment by tobiasK2001** [comment]
Dear WangWei,

I would go for option1 one with some modification. I would try changing "Effective surface area enhancement factor" from the default values. That  will mimick active influx or efflux by an unspecific transport process  according to Schlender et al. 2018. (DOI 10.1007/s40262-018-0661-6)
You will find the factor in PK-sim here:
![image](https://user-images.githubusercontent.com/25585248/72592914-f406e880-3903-11ea-878b-961191ee5fc1.png)
Regarding the specific intestinal permeability you can try the PK-sim calculated or the Caco measured A-B or B-A. It is probably hard the say which permeability best represents the "passive" permeability. Probabbly it is something betwen the CaCo a-B and B-A.

Hope this might help you. Good luck!

Tobias

**Comment by wangwei1619** [comment]
Dear @tobiasK2001,

Thanks for your help, it's really helpful. I think the parameters "Effective surface area enhancement factor" is what I mentioned as "absorption surface area ratio". However, I am still not very sure if the calculation method I posted is right in terms of correlating our modified permeation to experimental effective permeability since no calculation method is introduced in the paper you cited.

And I also very want to know if there is a database giving the transporters expression of rats because we have added some P-gp inhibitor to our new formulation so that permeation would change. Is there any data source suggested? And how to calculate the kinetics for transporters to make the effective permeability consistent with literature?

Thanks for your help .

Best regards,
Wang Wei

**Comment by tobiasK2001** [comment]
Dear Wang Wei,

I am not sure if the calculation method you posted can be applied. In PK-sim the specific intestinal permeability (P_int_Invitro) i.e. the surface area-normalized transcellular permeability of the innermost layer of the intestinal wall, is calculated from the drugs´ lipophilicity and effective molecular weight. In the Simulation the Intestinal permeability (transcellular) is used. The transformation is done via this formula: 
![image](https://user-images.githubusercontent.com/25585248/72810911-d963a500-3c5e-11ea-86a1-b6a07aee0b35.png)
were m and b are correlation factors to translate the specific intestinal permeability to an intestinal permeability P int required for the prediction of oral drug absorption. The fit of this factors is described here: http://linkinghub.elsevier.com/retrieve/pii/S0022354915318244
Together with the effective absorption area in each gut segments of the individual a mass transport via the intestinal membrane is calculated in the simulation. The effective surface area is calculated for teh lower ileum like here (screen shot from mobi):
![image](https://user-images.githubusercontent.com/25585248/72811682-6b1fe200-3c60-11ea-8dc1-a8a27c12328d.png)
were Ageom is the geometrical calculated surface area of the gut segment.

Regarding the rat database: sorry there is no for PK-sim. You might use the human one and adjust expression levels, if you have literature for this or fit it to your data.

Hope this might help you.

Best, Tobias

**Comment by wangwei1619** [comment]
Dear Tobias,

Thanks for your zealous help.

Best regards,
Wang Wei

**Comment by tobiasK2001** [comment]
You are welcome ;-)
