### ISSUE TITLE
UGT1A1 ontogeny

### ISSUE THREAD

**Issue by garynor** [Open-Systems-Pharmacology/Forum#448]
Hi, 

I have a question for the forum regarding UGT1A1 ontogeny in PK-SIM. 

In the following table, data showing the ontogeny of UGT1A1 in PK-SIM, I assume that the 3rd column is fraction of adult activity which in the following plot.  Can you please explain what 2nd column stands for?

Thanks
ML

Post menstrual age [year(s)] | Ontogeny for UGT1A1 | Ontogeny for UGT1A1_1
-- | -- | --
0.698271871 | 2.552011728 | 0.000979058
0.769230783 | 2.38158989 | 0.007233677
0.858116925 | 2.010226488 | 0.064657465
0.890073895 | 1.816496134 | 0.130265653
0.919260323 | 1.637136698 | 0.224505559
1.029093981 | 1.228398442 | 0.755379558
1.075121403 | 1.176906228 | 0.884206295
1.128819823 | 1.152582049 | 0.954406977
1.226630092 | 1.140699267 | 0.991511762
1.361833453 | 1.138464808 | 0.999002397

**Comment by Yuri05** [comment]
2nd column is GeoSD of the ontogeny factor.

**Comment by Yuri05** [comment]
I guess you created the table above via exporting of the corresponding ontogeny factor plot to Excel?
Column names are pretty misleading indeed 😕

**Comment by Yuri05** [comment]
P.S. You can find detailed documentaion of ontogenies used in PK-Sim in [PK-Sim Ontogeny Database documentation](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/blob/master/PK-Sim%20Ontogeny%20Database%20Version%207.3.pdf)

**Comment by garynor** [comment]
Thanks for your quick response and help.

**Comment by garynor** [comment]
After I looked at the UGT1A1 section, I found that there were some references that were excluded from the literature data.  Can you please explain what criteria were used to exclude the reference data?

**Comment by msevestre** [comment]
We should make sure the export is using adequate column names

**Comment by Incei** [comment]
> After I looked at the UGT1A1 section, I found that there were some references that were excluded from the literature data.  Can you please explain what criteria were used to exclude the reference data?

Looking at these sources that were not included, for
(DOI): 10.1124/dmd.110.037192 : figure 1A : x-axis scale is cut between 2.0 - 5 years, making it difficult to scan that values properly. One could have thought of using the data below 2 years. This figure indicated 90% of adult activity is reached 3.8 months of postnatal age (1.07y postmenstrual age)
(DOI): 10.1136/gut.50.2.259: Figure 2 is a histogram including a wide age-range per 'bar', indicating no differences in mRNA levels from 6 months and older (1.5y postmenstrual age). 

It could be that at the time both references were used as validation check to the fit results (adult levels reach < 6months of postnatal-age = <1.5y postmenstrual age), which matches well with the ontogeny table.

**Comment by garynor** [comment]
Thank you for your explanation.
