### ISSUE TITLE
Modelling hydrolysis in blood in PK sim in a feeding study

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#449]
Dear All, 

I have an ester which hydrolyses in blood into a hydroxyl. I would like to model this in a multiple feeding study. I am not sure how to implement this in PKSim. 

Any comments would be welcomed!

Best
Pri

**Comment by PavelBal** [comment]
My first suggestion would be:
1) Define an enzyme in the individual and only express it in blood plasma (relative expression in blood plasma = 1, 0 otherwise).
2) Define a reaction of the ester to hydroxyl catalyzed by the enzyme.

**Comment by PriKalra** [comment]
Thanks pavel. And for the feeding study I model the administration protocol as oral dose?

**Comment by StephanSchaller** [comment]
> Define an enzyme in the individual and only express it in blood plasma (relative expression in blood plasma = 1, 0 otherwise).

We have had this case in a project recently. Make sure you know what drives/triggers the transformation (pH dependent, temperature dependent, and in which compartments)
If it is a spontaneous reaction, you still have to go via the approach Pavel suggests, but likely need to set the expression in ALL compartments in PK-Sim.

> Thanks pavel. And for the feeding study I model the administration protocol as oral dose?

Yes, if it is a feeding study, you can/should model it as oral dose (with meal if necessary).

**Comment by PriKalra** [comment]
Hi Stephan, 

Thank you for the additional information. If the hydrolysis is dependent on the pH or temperature, do I have to model it in a particular way? 

Best, 
Pri

**Comment by StephanSchaller** [comment]
It depends how sensitive the hydrolysis is towards temperature or pH.
There are slight variations in pH throughout the body (mybe pH 7-7.5) and body temperature may also change under certain circumstances (36-41 °C). So if these changes don't affect the hydrolysis by much, you don't have to worry.
If they do, you'll have to find how, and derive a hydrolysis function that takes these changes into account appropriately.

**Comment by PriKalra** [comment]
Thank you! 

This was very helpful

**Comment by StephanSchaller** [comment]
...and of course, as always, you would have to define the new hydrolysis function in MoBi ;-)

**Comment by PriKalra** [comment]
Hi, 

Thanks. Mobi is the best!

 I have one more question. If the Enzyme is also expressed in the small intestine, which part is the correct part for expression information? The GIT non mucosal tissue or Intestinal mucosa or GIT lumen? I am not completely clear what are the exact differences?

**Comment by tobiasK2001** [comment]
Dear Pri,
that depends on your enzyme or how you want to have your enzyme. As a rule of thumb I would go along these lines E.g. if you think your enzyme acts like other metabolizing enzymes like CYPs than you might chose intestinal mucosa as it will have the most impact there. Mucosa has a comparable small volume and a relative to its volume high blood flow rate. Thus an expressed enzyme there will have more impact on substances present in blood or plasma than if they are present only in the GIT non mucosal tissue. If you think your enzyme might be present in intestinal fluid or parts of it like intestinal bacteria. You might choose lumen. 
Hope this might help you.
Best, Tobias

**Comment by PriKalra** [comment]
Thanks Tobias!
