### ISSUE TITLE
Relative bioavailability factor

### ISSUE THREAD

**Issue by nmens** [Open-Systems-Pharmacology/Forum#45]
Dear all
Is it possible to add a bioavailability factor relative to formulation? Or I need to simple input the corrected dose (Dose*Frel).

Thks in advance

**Comment by Yuri05** [comment]
Can you describe your goal in more detail?
What do you want to achieve with this kind of dosis scaling?

**Comment by msevestre** [comment]
@nmens I am assuming that this is not relevant to you anymore since we did not get any feedback. Feel free to reopen with more details. Thanks
