### ISSUE TITLE
problem in creating an individual

### ISSUE THREAD

**Issue by thPrabhath** [Open-Systems-Pharmacology/Forum#450]
could not create an individual with the given constraints:
species: human
population: preterm
gender: male

age: 110 days
gestational age: 29 weeks
weight: 1.03 kg
height: 30.6 cm
bmi: 11.4kg/m2

could someone please help me with this.

**Comment by Yuri05** [comment]
PK-Sim ["Create Individual"-algorithm](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Create-Individual-Algorithm) will only create virtual individuals with reasonable characteristics, i.e. that are in agreement with the database. If implausible combinations of weight, height and body mass index are given as constraints, PK-Sim® will not be able to create an individual.

You could create a preterm for your combination of `{Age, GA}` and some `{Weight, Height}` combination  which is close to yours but still in the reasonable range (acceptable by PK-Sim). E.g.
![grafik](https://user-images.githubusercontent.com/25061876/72978719-40a46500-3dd7-11ea-82a8-278d3b393dfd.png)

**Comment by thPrabhath** [comment]
I thank you for the suggestion. have proceeded as suggested and obtained a decent prediction.
