### ISSUE TITLE
Enterohepatic circulation in Rat

### ISSUE THREAD

**Issue by Ricardo-DO** [Open-Systems-Pharmacology/Forum#451]
Hello everyone

Is there a way to trigger enterohepatic circulation at certain time in a Rat model?
I know they lack gallbladder but the bile secretion is triggered by food intake.
I have tried to add a meal event with no gallbladder emptying but it didn't work.

Thanks!
Ricardo

**Comment by PriKalra** [comment]
Hi, 

I recently faced a similar problem in one of my projects, maybe this post #410  would help you?

Best
Pri

**Comment by Ricardo-DO** [comment]
Hi Pri

Thank you for bringing that topic here.
Did you use the giant mice approach?
I think I will start with that one as my compound is an acid and I don't think that could go under enterogastric recirculation.

Thanks!
Ricardo
