### ISSUE TITLE
Running simulations for a population with very heterogenous dosing

### ISSUE THREAD

**Issue by jgg1822** [Open-Systems-Pharmacology/Forum#452]
Hello,

I have a data set with 500+ subjects that I would like to use to evaluate my PBPK model. However, each subject has a different dosing regimen. Is there any way to incorporate highly varied dosing without needing to create a new building block and new simulation for each of the 500+ subjects? I know batch mode can be useful for trying different values for a parameter, but is this the way to go if I need to run simulations with varying dose amounts and times?

Thank you!

**Comment by StephanSchaller** [comment]
Hi Jgg, did you solve this?

You have the info on the dosing regimens in some format, excel? You can generate a dummy regimen in PK-Sim and then set the dosing with a loop in R and run your analysis there.

Let me know if you have additional questions.
Stephan

**Comment by jgg1822** [comment]
Hi Stephan,

Thanks for the response! I think the R files in the link below are what I need to use your strategy, correct?

https://github.com/Open-Systems-Pharmacology/OSPSuite-R

Thanks,
Jackie

**Comment by StephanSchaller** [comment]
Hi Jackie,

this is not released, yet. Best you use this: https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/31191104/artifacts

Best,
Stephan

**Comment by jgg1822** [comment]
Thanks! I looked through the Introduction (attached), and I see how to change the dose. Do you know if it’s possible to change multiple dosing? We have many data sets with individuals we need to simulate with 40+ doses, all with different doses (e.g. the dosing is different between subjects but also each of the individual doses in the set is different rather than something like 1 mg q24h for 40 days or something). Just wondering if you know how feasible it would be to use R to code this before I start really digging in and trying it. Thanks!

**Comment by StephanSchaller** [comment]
Yes, this can be done using scripting in R.
You just need the dosing info in a well structured database (excel file or csv or whatever).

You set up 40+ dummy doses with zero dose in PK-Sim and then set their actual timing and dose in R for each individual.
