### ISSUE TITLE
Building an intranasal model in MoBi 

### ISSUE THREAD

**Issue by Mahmood1212** [Open-Systems-Pharmacology/Forum#454]
Hello Everyone,

I have been trying to build a simulation for an intranasal administration of an oral drug (no IV formulation) on MoBi to investigate the concentration in the brain, lungs, and venous blood. Can you help me with the specific steps to build the spatial structure for the simulation for the intranasal compartment?

Appreciate it!
Mahmood
[oral sim amilo.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/3837710/oral.sim.amilo.zip)

**Comment by AndreDlm** [comment]
Dear Mahmood,

this tutorial [here](https://ascpt.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fpsp4.12300&file=psp412300-sup-0001-suppinfo01.pdf) explains how to add a new compartment to an existing model structure for small molecules. Although the specific use case of that tutorial is different, it might be of help to guide you through the technical steps.

Good luck!
André
