### ISSUE TITLE
How to administer a feeding study for 2 hours in multiple dosing form

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#455]
Dear All, 

I have a multiple dosing administration as feeding (Oral) and it needs to be simulated as 50 mg over a period of 2 hours bi daily with an administration gap of 12 hours. 

For this I have chosen advanced protocol, however I am not able to have the dosing spread for 2 hours. 

![image](https://user-images.githubusercontent.com/13007976/73938139-f2b75300-48e6-11ea-9327-64192203c90d.png)

How do I proceed?

Best, 
Pri

**Comment by StephanSchaller** [comment]
HI Priyata,

you have to expand your view:
![image](https://user-images.githubusercontent.com/25477643/73945485-a7a43c80-48f4-11ea-875a-4872e51e20c1.png)

**Comment by PriKalra** [comment]
Hi Stephan, 

Thank you! So I do not keep the administration type as oral in such a case?

**Comment by msevestre** [comment]
@PriKalra What is an oral absorption with a dosing spread ? Can you explain

**Comment by PriKalra** [comment]
We have rat oral feeding study where they are fed for 2 hours and then given a 12 hour break to repeat the same pattern of feeding. I was wondering that when I administer this as intravenous infusion, then it wouldnt consider the absorption process in the simulation or would it? 

Sorry, I am a newbie at complex administration! Please correct my thoughts here.

**Comment by prvmalik** [comment]
To do this in Mobi:

1. Create an IV infusion over 2 hours as stated above
2. Export the Simulation to Mobi
3. Add a tag to the Lumen > Stomach that says 'Stomach'
![Prikalra2](https://user-images.githubusercontent.com/29066045/73951086-094fb100-48cb-11ea-878d-d8a9849671b0.JPG)

4. Change the drop location of the drug to the lumen > stomach, rather than the venous plasma but adjusting the tags in the application event.
![Prikalra3](https://user-images.githubusercontent.com/29066045/73951113-110f5580-48cb-11ea-8a55-df302699c094.JPG)

**Comment by StephanSchaller** [comment]
> Thank you! So I do not keep the administration type as oral in such a case?

Sorry, forgot about that. You can then change to "User Defined" with location "Lumen/Stomach":
![image](https://user-images.githubusercontent.com/25477643/73951751-56994600-48fe-11ea-8b86-301f7277ece4.png)

and define a formulation as zero-order with 120 min:

![image](https://user-images.githubusercontent.com/25477643/73951481-d96dd100-48fd-11ea-9dee-760d694fc526.png)

Or as Paul suggested ;-)

**Comment by prvmalik** [comment]
@StephanSchaller The limitation to this approach is that everything gets dumped into the stomach at time = 0 and then starts moving along the GI tract. With the zero order dissolution, it will end up dissolving in the luminal segments of the small intestine. With respect to the rat study, this approximates the effect of a rat eating everything at time = 0 and then it taking 2 hours to 'digest.'

On the other hand, the Mobi approach is limited in that you have to assume that the food is dissolved automatically as there is no implementation of a formulation (although experts like Stephan may be able to accomplish this without getting a headache).

**Comment by prvmalik** [comment]
Alternatively you could bin the oral administration. Create 12 administrations of the oral dose divided in 12 portions that occur every 10 minutes.

**Comment by PriKalra** [comment]
Thank you very much for these comments. Helps me keep the approach limitations in mind and hence have the assumptions depending on the use-case!
 Much appreciate it!

**Comment by Yuri05** [comment]
>Alternatively you could bin the oral administration. Create 12 administrations of the oral dose divided in 12 portions that occur every 10 minutes.

Would go this way as well. Here you can also incorporate a dissolution profile and e.g. correctly calculate fraction absorbed etc. (in case of "Infusion into the stomach" further modifications in MoBi would be required to get the correct fraction absorbed etc.)

**Comment by PriKalra** [comment]
OK! to make sure I understand it correctly:
![image](https://user-images.githubusercontent.com/13007976/73954406-120fa980-4902-11ea-9cb4-d3e5fb682c5b.png)

Something like this?

**Comment by Yuri05** [comment]
>Something like this?

Yes, just with Dose=`50/12 mg` and same for Amount of water
