### ISSUE TITLE
Nonspecific binding

### ISSUE THREAD

**Issue by shbae1211** [Open-Systems-Pharmacology/Forum#456]
Hello, again..
I cannot find where to enter a nonspecific binding parameter (fu,mic,,,etc) for CLint and/or Ki.
Is this value automatically calculated by physicochem (Log P) and reflected model?

**Comment by tobiasK2001** [comment]
Hi,
this value is calculated automatically here if you add a total liver CL based on microsome T1/2.

![image](https://user-images.githubusercontent.com/25585248/74225449-01bd4d00-4cbb-11ea-81a1-6421b2b2ea3e.png)
Please note, if you calculate Clint from hepatocytes, there is only a default value given. Ideally you have a measured fu in assay or you might think about using the calculated value from the microsomal assay or some literature value if available.

Hope this might help.

Best, Tobias
