### ISSUE TITLE
Gastric Emptying Time in Population

### ISSUE THREAD

**Issue by HTQ05** [Open-Systems-Pharmacology/Forum#461]
Is there any option of changing the gastric emptying time in a simulation designed for population? 
For example: I am working on a Drug Interaction model, when two models are coupled for interaction in a single simulation, then according to the literature the gastric emptying time increases. So, when I do the same procedure in an **INDIVIDUAL SIMULATION FOR INTERACTION**, the option appears in Physiology, while it is not apperaing in POPULATION SIMULATION.

**Comment by StephanSchaller** [comment]
Make sure you have the view "Hierarchy" selected:
![image](https://user-images.githubusercontent.com/25477643/74604414-0bc9bc00-50be-11ea-8ec7-a7a8fcc0f89a.png)

Also in "User defined Variability", you can select the GET:
![image](https://user-images.githubusercontent.com/25477643/74604429-39af0080-50be-11ea-9606-b9bb0bda54e1.png)

Hope this helps

**Comment by HTQ05** [comment]
Ok. I am talking about this one 
![GET](https://user-images.githubusercontent.com/60983521/74604988-501c8280-50e5-11ea-922c-8104bae66d0b.jpeg)

Aren't these different; Gastric empty Time and GET of non-disintegrated moeity?

**Comment by StephanSchaller** [comment]
Yes, as mentioned above, it is a bit further down - you need to scroll:
![image](https://user-images.githubusercontent.com/25477643/74606107-f52b6100-50cd-11ea-8fc5-701e08cfe954.png)

**Comment by StephanSchaller** [comment]
and make sure you change the view in the parameter tab to "Hierarchy"!!!

**Comment by HTQ05** [comment]
ok. got it. Thank you so much.

**Comment by Yuri05** [comment]
@HTQ05 FYI I have edited your screenshot here and in the related issue (original screenshot showed the compound name and it seemed to me that it was not by intention)

**Comment by HTQ05** [comment]
> 
> 
> @HTQ05 FYI I have edited your screenshot here and in the related issue (original screenshot showed the compound name and it seemed to me that it was not by intention)

Thank you. Yeah it was not intentional.

**Comment by Yuri05** [comment]
@HTQ05 Regarding your initial problem.
In a Population GET (Gastric Emptying Time) is distributed following the predefined probability distribution. Now if you would like to change this predefined distribution, there are several possibilities.

### Alternative 1
**Change the mean GET value in an Individual and create a new population based on this individual.** Then the GET change will be _propagated_ to the population (predefined probability distribution will be **rescaled**)

E.g. if I create a Population for the mean ICRP individual (`GET=15 min`), GET in the population looks like this:
![grafik](https://user-images.githubusercontent.com/25061876/74608687-9a9cff80-50e3-11ea-8731-3433f1ec59cb.png)
Now if i change the GET in this individual to `GET=45 min` and create a population, GET distribution is rescaled accordingly:
![grafik](https://user-images.githubusercontent.com/25061876/74608725-df289b00-50e3-11ea-8aa2-bd933bc04bc2.png)

### Alternative 2
If the rescaling above is not what you want (e.g. if you need completely different kind of distribution or want to set `GET=const` for all individuals in the population, you could do the following:
1. Export population to CSV
2. Open it e.g. with MS-Excel (or any other suitable editor)
3. Look for the column `"Organism|Lumen|Stomach|Gastric emptying time [min]"`
4. Adjust GET values according to your needs and save the CSV
5. Import new Population from this changed CSV

**Comment by HTQ05** [comment]
ok. I am working on a Drug-Drug Interaction Model Development.
In One Drug Simulation GET is normal at base level. But when I couple it with the second drug to see the interaction, at that point GET should be increased from base level.
So, what I have concluded from your suggestions is that I should design a seperate drug model for incoproration in Interaction Simulation with changed GET. Am I right?

**Comment by StephanSchaller** [comment]
What you need to do depends on what you want to achieve:

Di you simply want to manually change the GET or do you want this to happen dynamically based on the drug concentration within the DDI scenario?

**Comment by HTQ05** [comment]
> 
> What you need to do depends on what you want to achieve:
> 
> Di you simply want to manually change the GET or do you want this to happen dynamically based on the drug concentration within the DDI scenario?

I want to change it manually in order to check the resultant effect.

**Comment by Yuri05** [comment]
> when two models are coupled for interaction in a single simulation, then according to the literature the gastric emptying time increases.

@HTQ05 Can you provide the corresponding reference(s)? Trying to understand your use case...

>So, what I have concluded from your suggestions is that I should design a seperate drug model for incoproration in Interaction Simulation with changed GET. Am I right?

No. What I proposed was to create a different **population** with increased GET and use it in the simulation(s) where you investigate your DDI mechanism. 
* Alternative 1 was meant for the case where you still need variability in your GET values. 
* If you want the same GET value in all individuals of your population, you could use alternative 2.

However both proposals will allow to change GET in a _population_ but not in a _population simulation_.

**Comment by HTQ05** [comment]
> Can you provide the corresponding reference(s)? Trying to understand your use case...

**The default value of 15 min for ∼63% gastric emptying
to occur was used for the simulations following
oral administration of nifedipine without grapefruit
juice. As administration of grapefruit juice leads
to an approximately 30 min delay in gastric emptying
time, the gastric emptying time for the simulations
following simultaneous oral administration
of nifedipine and grapefruit juice was increased to
45 min.
[GFJ and Nifedipine PBPK.pdf](https://github.com/Open-Systems-Pharmacology/Forum/files/4210518/GFJ.and.Nifedipine.PBPK.pdf)
**

**Comment by Yuri05** [comment]
> As administration of grapefruit juice leads
to an approximately 30 min delay in gastric emptying
time, the gastric emptying time for the simulations
following simultaneous oral administration
of nifedipine and grapefruit juice was increased to
45 min.

Ok, in this case I would realize it via adding of 100ml grapefruit juice (realized as a meal event) at administration times. Then GET is increased to ca. 45min (slowly decreasing back to the original value)
![grafik](https://user-images.githubusercontent.com/25061876/74612920-317cb280-510a-11ea-8ef6-3315d141a6ed.png)
![grafik](https://user-images.githubusercontent.com/25061876/74612932-52dd9e80-510a-11ea-8fd2-f1b8d188e253.png)
![grafik](https://user-images.githubusercontent.com/25061876/74612948-6c7ee600-510a-11ea-8bd7-a72ae83a9cae.png)

**Comment by HTQ05** [comment]
@Yuri05 Okay. Thanku so much..

**Comment by MCR15** [comment]
> > As administration of grapefruit juice leads
> > to an approximately 30 min delay in gastric emptying
> > time, the gastric emptying time for the simulations
> > following simultaneous oral administration
> > of nifedipine and grapefruit juice was increased to
> > 45 min.
> 
> Ok, in this case I would realize it via adding of 100ml grapefruit juice (realized as a meal event) at administration times. Then GET is increased to ca. 45min (slowly decreasing back to the original value) ![grafik](https://user-images.githubusercontent.com/25061876/74613019-f038d280-510a-11ea-8e7c-1494e89dd1d2.png)![grafik](https://user-images.githubusercontent.com/25061876/74612932-52dd9e80-510a-11ea-8fd2-f1b8d188e253.png) ![grafik](https://user-images.githubusercontent.com/25061876/74612948-6c7ee600-510a-11ea-8bd7-a72ae83a9cae.png)

I need to track the GET variation over time in the simulation, something similar to the image in the preceding comment. How can I obtain this? I have attempted, but I obtained a graph where the effect of food administration on GET is not reflected; it only indicates the predefined value (15 minutes). However, the simulated plasma concentrations are capturing the effect of food.
