### ISSUE TITLE
Problems on skin permeation model in MoBi

### ISSUE THREAD

**Issue by carrenof** [Open-Systems-Pharmacology/Forum#466]
Hello everyone, 

I have been trying to build a simulation for transdermal application of fentanyl patch using the launched skin permeation model in MoBi. Based on the User’s Guide, I was able to create simulations for testosterone and connecting the model to a whole-body model generated in PK-Sim. 

My next step was then to apply the skin model to a whole body fentanyl PBPK model to investigate venous blood concentrations of fentanyl after the patch application. 

Unfortunately, I am not being able to get it right! 

First problem, since my fentanyl whole-body PBPK model takes into account fentanyl metabolism by CYP3A4, after merging whole_body_simulation and skin_simulation my "Molecules Building Block" shows not only fentanyl but also CYP3A4 and its metabolite. 

![image](https://user-images.githubusercontent.com/51857007/74870716-2f903a80-5328-11ea-8f07-d4ac51fb31b9.png)

Because of that, every time I try to create a new simulation, CYP3A4 molecule appears in the “Molecule Start Values” for the Path Element “Dermal_application_Area” and I have to manually unchecked all the box “Is present” in order to make the simulation work (Figure bellow). 

![image](https://user-images.githubusercontent.com/51857007/74870884-7e3dd480-5328-11ea-931f-7e5995b9b3f3.png)

How could I solve this problem? Is this a problem during the process of merging the two simulations? 

Another point I would like to address, after being able to simulate the patch administration, it is clear that I am not capturing the observed venous profile correctly. (Observed data from: https://accp1.onlinelibrary.wiley.com/doi/epdf/10.1177/0091270006286901).

![image](https://user-images.githubusercontent.com/51857007/74870971-aa595580-5328-11ea-8061-3afc60e4b865.png)

I was thinking about optimize the bloodstream clearance amount (Qabs) and the maximum rate of dermis to bloodstream clearance amount (Jmax). 

However, I was not able to find those two parameters in my simulation tree. Are they only available for in vitro simulations? 

Finally, how can I simulate a multiple dosing regimen using this model? For example, the transdermal systems being replaced every 72 hours. 

Could you please, give me your thoughts, answers, or input?

Thank you so much, 

Fernando

**Comment by PriKalra** [comment]
Hi Fernando, 

I am not an expert on this problem, however I have implemented a skin permeation model in MoBi once. These are my thoughts to things:

Everytime you create a new simulation, you can get rid of unchecking the box by the following protocol:

In MoBi, You have the `parameter start value `and the `Molecule start value` component in the Building blocks. Please uncheck the Molecule and parameter value there. This would ensure that the building block for your simulation always stays the same. 

For the Qabs and Jmax, how have you implemented them in the model? Usually, I implement them as global parameters so that I can easily find the path. 

The multiple dosing part, I am not the best one to answer this, you might find a way in #305 ?

Hope I was of help!
Pri

**Comment by abdullahhamadeh** [comment]
Hi Fernando

I have just uploaded an Events building block [here](https://github.com/Open-Systems-Pharmacology/Skin-permeation-model/commit/aa39b8636be20d94769ac4d6c8e0ff41899ddbde) that you can use for multiple dosing. 

Best,

**Comment by carrenof** [comment]
Hi @PriKalra and @abdullahhamadeh 

Thanks for your help! I was able to get rid of  unchecking the box following the protocol and also figured out how to obtain the Qabs and Jmax parameters. 

Also, I was able to simulate  multiple dosing using the Events building block shared by @abdullahhamadeh . 

However, as we can see in the drug concentration-time profile bellows it seems that there is no drug accumulation in between doses. Am I doing something wrong?  

Also, I don't understand why I'm having this flat profile between 20 and 50 h after dose.  I tried to optimize the diffusion process of stratum corneum, epidermis and dermis but did not work. Do you have any comments about that? 

![image](https://user-images.githubusercontent.com/51857007/75480361-22e69480-596f-11ea-9054-1abbe3159b42.png)

Thank you, 

Fernando

**Comment by PriKalra** [comment]
Hi @carrenof 

Glad that it worked out! 

From the looks of it the clearance from the blood is fast enough to not allow for accumulation. There are couple of ways of moving forward from my perspective. I would tweak some parameters and see their consequence on the model:

1. I will try to plot the deposit in corneum, dermis . I would also try to plot the parameter of clearance into the blood from the skin and see what that rate looks like. 
2. I would try to tweak the parameter Jmax and the cyp enzyme parameters to to see its affect on the blood levels of the simulation. The simplest way I go forward is by not allowing any metabolism to happen such that I can completely understand the dynamics between blood and skin. and later I add more complexity.  
3. Just a question on your note of optimizing the diffusion parameter for the three layers, did you do it together or one at a time? What is the consequence of a strong fold change in this parameter? does it lead to for example sustained release when the parameter is fold lower?
4. What about the partition coefficient of the vehicle and water?

If you are open to sharing your model, please do so and I will try to look into it too to help! :)
Hope this might help in someways!

Best, 
Pri

**Comment by carrenof** [comment]
Hi @PriKalra 

Thank you so much for your help! I was able to optimize the parameters and finally the simulation is working now. 

![image](https://user-images.githubusercontent.com/51857007/76316168-7f6f7b00-62b0-11ea-8ea0-480b11d033d8.png)


Best, 

Fernando
