### ISSUE TITLE
Export generated variability from PopPK models

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#467]
Dear all, 

I am looking for a way to export the introduced variability by myself in the PopPK model. In my case, I have introduced variability on the weight and on the permeability. 

I would just need these two parameters to be exported to excel for the population. How do I go about that?

thanks and best, 
Pri

**Comment by msevestre** [comment]
What about Right click on your population and export to csv? This would export all variabilities defined in your model

>I have introduced variability on the weight

What do you mean with this? The weight is calculated as sum of all organ weights. If you create a user defined variability on weight, this might not do what you expect.

**Comment by PriKalra** [comment]
Created a population as described in #403 for weight variability

But, I found the Permeability values in the csv now. I think there was a writing problem in the file. 

Thanks
