### ISSUE TITLE
add arithmetic mean to box plot

### ISSUE THREAD

**Issue by TTLL88** [Open-Systems-Pharmacology/Forum#468]
Morning. Wondering if it is possible to show arithmetic mean in the box plot?Thanks.

**Comment by msevestre** [comment]
No the box plot are not configurable.
see https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#running-and-analyzing-a-population-simulation

They show 2.5, 25th 50th 75th and 97.5th percentiles

**Comment by msevestre** [comment]
If you think this would be a good addition to the software, you could briefly explain your use case and why you would need to use an arithmetic mean instead of median ? Thanks :)

**Comment by TTLL88** [comment]
Nothing specific actually. Just exploring the flexibility of plotting in the software. Thank you.

**Comment by msevestre** [comment]
@TTLL88 You can always export the simulated values for a population and create whatever plot you need using R or Matlab
