### ISSUE TITLE
removal simulated outlier

### ISSUE THREAD

**Issue by TTLL88** [Open-Systems-Pharmacology/Forum#469]
Morning,everyone. Quick question. Is it possible to remove the outliers generated in the simulation? Thanks a lot.

**Comment by msevestre** [comment]
see the documentation
https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#running-and-analyzing-a-population-simulation

More particularly, 
![image](https://user-images.githubusercontent.com/1041237/74953367-9583cd00-53cf-11ea-85c0-2c21318a89c5.png)

**Comment by TTLL88** [comment]
Thank you. Actually I meant removal of outliers from the simulation.  I guess it can't be done?

**Comment by msevestre** [comment]
It can be done in a few steps
1. You would have to find which individual corresponds to your outlier (going over the box with the mouse will show you the corresponding individuals)
2. Then you would go in your population, and export it to csv. 
3. Open the csv, remove the individuals with id found in Step 1. 
4. Then import the csv back as  a new population and use this modified population in your simulation

**Comment by TTLL88** [comment]
Thank you :)
