### ISSUE TITLE
Which data/studies used for maturation profiles of enzymes?

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#47]
Dear all,

i was wondering if someone could give me and the community a list of the the datasources and studies that were used for the development of the maturation profiles of enzymes available in PK-Sim?

I am especially interested in the maturation of the available UGTs ;)

thanks in advance!
Daniel

**Comment by Incei** [comment]
Hi Daniel,

We have just published the [PK-Sim® Ontogeny Database Version 7.1](https://github.com/Open-Systems-Pharmacology/Forum/issues/49) where you can find back where our enzyme and plasma protein ontogenies in PK-Sim are derived from. 

Cheers!
Ibrahim

**Comment by DanielMoj** [comment]
Hi Ibrahim,

great news! Thank you guys very much!!

Daniel
