### ISSUE TITLE
Concomitant administration of two drugs.

### ISSUE THREAD

**Issue by AParisotto** [Open-Systems-Pharmacology/Forum#471]
Hello people
for the development of the simulation it is necessary to use a database of the pharmacokinetics of a drug (Concentration x time), for example.
I have already validated drug 1 and drug 2, compared to AUC, Tmax, Cmax and Half-life, with data from the literature.
how do I build the protocol for administering the two drugs together? the concentration of 150mg of drug 1 and 600mg of drug 2 orally? Is the result reliable, considering the previous validation already done for each drug?

**Comment by jzq90** [comment]
Just choose the two drugs in the simulation modules. I think it is reliable only when there are no potential DDI between the two drugs. Maybe you can check whether the metabolism route, enzyme or transporters involved are overlapped.

**Comment by StephanSchaller** [comment]
As @jzq90 previously mentioned: you have to select them both when you create a simulation (here a screenshot):
![image](https://user-images.githubusercontent.com/25477643/76099169-04b21180-5fcb-11ea-8d08-f5cd5660b1e6.png)

Should be valid if there are no interactions, as @jzq90 already correctly explained.
