### ISSUE TITLE
deferential model settings

### ISSUE THREAD

**Issue by AParisotto** [Open-Systems-Pharmacology/Forum#472]
how to administer 2 drugs, 1 of which is a standard model for small molecules and the other is a model for proteins and large molecules

**Comment by prvmalik** [comment]
Hi, this is not possible right now.

**Comment by StephanSchaller** [comment]
While it is not possible to select this when you create your simulation, you can use the protein model to simulate small molecules. After creation of the simulation with the protein model, you have to re-set a number of parameters for the small molecule, mainly the endothelial permeability back to ~100 cm/s
