### ISSUE TITLE
The solubility for dissolved formulation

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#474]
I have a compound with poor solubility but dissolved in 5% DMSO which used in the in vivo animal PK study. However, when I build the model for this drug in animals, I found the solubility has a huge impact on bioavailability. 
In the simulation, I input the formulation as ‘dissolved’ in the software, but apparently it participated in the GIT in the simulation but not in the real world. I think the difference is the DMSO used in the real world.
How could I fix this in the model?

**Comment by prvmalik** [comment]
Hi

Enabling 'supersaturation' in the advanced features should fix this.

Paul
