### ISSUE TITLE
Sensitivity Analysis

### ISSUE THREAD

**Issue by thPrabhath** [Open-Systems-Pharmacology/Forum#475]
Hi,
Can someone guide me through the sensitivity analysis and parameter identification in PK-Sim. The criteria to be considered and parameters to be choosen the method of doing sensitivity analysis and parameter identification.

**Comment by StephanSchaller** [comment]
Sure, 

Sensitivity Analysis: https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis

Parameter Identification: https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification

If you have any questions after going through the documentation, please let us know.

Best,
Stephan

**Comment by AnisPBPK** [comment]
> Sure,
> 
> Sensitivity Analysis: https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis
> 
> Parameter Identification: https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification
> 
> If you have any questions after going through the documentation, please let us know.
> 
> Best,
> Stephan

Hello Stephan, can you please let me know how can i interpret the result of sensitivity analysis? 
for exemple if we take the influence of  t1/2(microsomal assay) on total body clearance we have sensitivity analysis = 0.66   (with variation range = 1.5 ans number of steps = 3).

Thank you very much in advance!
