### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by thPrabhath** [Open-Systems-Pharmacology/Forum#478]
Is there a way in PK-Sim to resample the and evaluate the parameters by bootstraping. If any please guide me through the process.

**Comment by msevestre** [comment]
Nothing like that in PKSim. You can do it in Matlab or R. I would suggest you give our new r toolbox a try. It's still in beta but it should be fairly easy to implement this type of scenarios

**Comment by thPrabhath** [comment]
Thank you for the info. Could you please guide me through that process by which it can be performed in R.

**Comment by pchelle** [comment]
Using the new R toolbox, you can obtain a data.frame with the PK parameters by individual in a few steps by following the example tests/dev/script-pk-analyses.R
Then, you can directly perform the bootstrap analysis using the random sampling with replacement of the R function sample(x, length, replace=TRUE). 
The process is to create a loop with bootstrap runs on which you use the function sample(), then get the corresponding parameters from the data.frame to which you can aggregate any statistic function.

**Comment by jzq90** [comment]
Are there some packages in R for PK-sim?

**Comment by PavelBal** [comment]
> Are there some packages in R for PK-sim?
 
https://github.com/Open-Systems-Pharmacology/OSPSuite-R
