### ISSUE TITLE
How to simulate renal impair

### ISSUE THREAD

**Issue by leeking-55** [Open-Systems-Pharmacology/Forum#479]
hello, erveryone:
     I have a question when I uesd pk-sim to simulate renal impair. healthy people's GFR was 120ml/min, and in "ADME" section in "compounds" section, add renal clearances process, the process type, I chose kidney plasma clearance, and value of plasma clearance was inputed by healthy people's plasma clearance which comes from literature. so when I sumulate renal impair, the GFR was 45ml/min, the value of plasma clearance how to change.
I really need help, thanks 
best wishes.
                 leeking.

**Comment by prvmalik** [comment]
This parameterization is what you will need.

https://www.page-meeting.org/pdf_assets/1160-Schmulenson_PAGE2018.pdf

Change all physiological/anatomical parameters first. Once finalized, then adjust specific GFR (mL/min/100g kidney) to achieve the desired GFR (in your case, 45 mL/min).

It is fine to make a mean individual with these parameters, but I advise that you do not make CKD populations without a thorough understanding of the physiology and the popgen algorithms in PK-Sim.

**Comment by leeking-55** [comment]
thank you very much for your help.


best wishes.
sincerly,
leeking.












At 2020-04-13 02:16:20, "Paul Malik" <notifications@github.com> wrote:

This parameterization is what you will need.

https://www.page-meeting.org/pdf_assets/1160-Schmulenson_PAGE2018.pdf

Change all physiological/anatomical parameters first. Once finalized, then adjust specific GFR (mL/min/100g kidney) to achieve the desired GFR (in your case, 45 mL/min).

It is fine to make a mean individual with these parameters, but I advise that you do not make CKD populations without a thorough understanding of the physiology and the popgen algorithms in PK-Sim.
