### ISSUE TITLE
License renewal

### ISSUE THREAD

**Issue by hualiwu2017** [Open-Systems-Pharmacology/Forum#48]
The license for PK-Sim on my computer has expired. Could you please give me a direction on how to obtain a new license?

**Comment by msevestre** [comment]
@hualiwu2017 The Systems Biology Suite (now called Open Systems Pharmacology Suite) is now open source and can be used under the  [GPLv2 License](https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/LICENSE)

You can download the latest version using the following link
http://setup.open-systems-pharmacology.org

Cheers,
Michael
