### ISSUE TITLE
Different Permeability Calculation Methods in special populations

### ISSUE THREAD

**Issue by LkKov** [Open-Systems-Pharmacology/Forum#481]
Hello everybody,

we have a general question: Has anybody every experienced that a different permeability calculation method has better fit for plasma-concentration predictions in special populations compared to the one used in the "base-model"? And would there be a (physiological) rational for changing the calculation method between populations you could think of?

Thank you very much in advance!

**Comment by jzq90** [comment]
I think there is only one permeability calculation method in PK-Sim.
Could you share what different permeability calculation method do you use?

**Comment by Yuri05** [comment]
>I think there is only one permeability calculation method in PK-Sim.

Currently there are 3 permeability calculation methods in PK-Sim;
s. https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-compounds-definition-and-work-flow#distribution

**Comment by jzq90** [comment]
> 
> 
> > I think there is only one permeability calculation method in PK-Sim.
> 
> Currently there are 3 permeability calculation methods in PK-Sim;
> s. https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-compounds-definition-and-work-flow#distribution

Thanks. I missed this.

**Comment by AnisPBPK** [comment]
> > I think there is only one permeability calculation method in PK-Sim.
> 
> Currently there are 3 permeability calculation methods in PK-Sim;
> s. https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-compounds-definition-and-work-flow#distribution

Hello, can you tell us what is the difference between this 3 methods ? 

thank you very much in advance!

**Comment by Yuri05** [comment]
Please follow the documentation link above and you will find the description of the different methods 
![grafik](https://user-images.githubusercontent.com/25061876/81320986-4d04b300-9092-11ea-9bd8-e60920fdcfd0.png)

**Comment by AnisPBPK** [comment]
> Please follow the documentation link above and you will find the description of the different methods
> ![grafik](https://user-images.githubusercontent.com/25061876/81320986-4d04b300-9092-11ea-9bd8-e60920fdcfd0.png)

Thank you very much! it's clear now
