### ISSUE TITLE
How to adjust the solubility of one oral drug according to cyclodextrin concentration

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#482]
Hi, all

The cyclodxtrin (CD) is an often used solubilization method and can enhance drug solubility depending on CD concentration. As the CD transfers along GI tract, the concentration of CD in GI segments are different from each other and varing with time, and result in change of drug solubility in GI tract. So, is there anyway to consider this impact on solubility in MoBi?

I have made a simulation where drug and CD are taken orally together. The drug solubitlity in duodenum is defined by a formula:
![image](https://user-images.githubusercontent.com/54141158/76943157-dbce3c80-6939-11ea-83a4-271b5c423d8c.png)
And this fomula is also can be seen in spatial structure:
![image](https://user-images.githubusercontent.com/54141158/76943269-05876380-693a-11ea-978e-ea579f3c4bbd.png)
I think this formula does the same thing to both drug and CD and is what expected for CD solubility. So, how to adjust the solubility of drug according to CD concentration? The formulas in simulation block seems not could be changed.

Thanks for comment.

**Comment by jzq90** [comment]
How about using the concentration of CD in the GIT to modify the solubility of the drug?

Also, I think the influence of CD on the absorption is much more complicated. For one thing, it increases the dissolution rate rather than increases the solubility. For another, the drug entrapped in CD is not free, which can not penetrate the intestine membrane.

**Comment by wangwei1619** [comment]
That is really ture. Anyway, I think it requires the modeifacation to default built-in equation to consider the impact of CD

**Comment by PavelBal** [comment]
Hi,

an interesting setting.

First of all, you cannot change the equation in the simulation itself, you have to do it in the Spatial Structure Building Block (BB) and then update your simulation.

As you can see, in the Spatial Structure BB, the parameter `Solubility` is located under the entry `MoleculeProperties`. This means that this parameter will be created for each molecule in the simulation, using the same formula. So, if you change the formula, it will be changed for each orally administered molecule.

You could create a parameter in the molecule that turns the effect of CD on or off, and further parameters you need to describe the effect. E.g., assuming a Michaelis-Menten-like effect, you would define _per molecule_ the parameters:
- CD_effect_active (values 0 or 1)
- CD_effect_Km
- CD_effect_Vmax

Then in the formula you could use something like:

`(CD_effect_active = 0 ? 1 : Vmax * C_cd / (C_cd / Km)) * Solubility * Solubility_pKa_REFpH_Factor / Solubility_pKa_pH_Factor + SolubilityTable`

To generically access the parameter value of the molecule for which the formula is calculated, use the key-word `MOLECULE` in the path-definition of the aliases (variables) of the equation, while `C_cd` should always be the concentration of CD:

![image](https://user-images.githubusercontent.com/25903040/77519442-cbf5b180-6e7f-11ea-95da-65350bcd926d.png)


So, for CD itself, you would set the value of `CD_effect_active` to zero, for the affected molecule to one.

Let me know if it works!

**Comment by PavelBal** [comment]
The dimensions of Km and C_cd should be `Concentration (molar)`, and not `Concentration (mass)`, as in the screenshot.

**Comment by wangwei1619** [comment]
Wow!! Genius!! @PavelBal ,
Thanks for your suggestion, I will try it later. So, is what you mean first to creat a parameter in Molecule BB to switch the effect of CD on or off, then modify the solubility equation in Spatial Strucure BB ?

**Comment by PavelBal** [comment]
Just experience ;)

Yes, exactly - create the parameters describing the effect of CD in the Molecule BB, and then adjust the formula in the spatial structure BB.

**Comment by msevestre** [comment]
>Wow!! Genius!! @PavelBal ,

agreed.

**Comment by wangwei1619** [comment]
Oh, I meet a few bit problems when I try this method. I want to use this equation to calculate solubility: 
![image](https://user-images.githubusercontent.com/54141158/77882826-685ef000-7294-11ea-8d59-7bc4582b34d4.png)
The parameters used to CD molecule are with dimension of **concentration (mass)** as default, but parameters for drug molecule are with dimension of **concentration (molar)** thus the calculated solubility should be with molar dimension. Would this make a mistake for program since the solubility is in mass dimension by default?

**Comment by wangwei1619** [comment]
And the second question is if I have a parameter defined in Molecule BB in  dimension of **concentration (mass)** , can I refer to it as dimension of  **concentration (molar)** in formulas elsewhere?

**Comment by wangwei1619** [comment]
Opps! When I configure the simulation using modified BB, I get this note:
![image](https://user-images.githubusercontent.com/54141158/77894334-b6c9ba00-72a7-11ea-8b71-5d24241af954.png)
![image](https://user-images.githubusercontent.com/54141158/77894349-bb8e6e00-72a7-11ea-99ea-894640fcf97c.png)
This would happen after I add new alias into formula "PARAM_IntestinalSolubility" and ignores whether the original equation is changed or not. Does MoBi scans parameters prior to loading the equation and conclude I am circularly refering parameters? 

Can I avoid this? And is this problem related to the **Parameter type** and **Group** I chose when I created parameters in Molecule BB?

**Comment by PavelBal** [comment]
Sorry, forgot about this issue.

Parameter type and Grop have no implications at all. The problem here is that the new formula tries to calculate solubility based on the concentration of CD - but the concentration of CD depends on its solubility - this is called "circular reference". I have to think about how to overcome this problem. Unfortunately, I do not have a quick solution.

**Comment by wangwei1619** [comment]
Thanks for your concern, I will be waiting. Good luck!

**Comment by wangwei1619** [comment]
I have heard that PK-Sim version 9 is released and extend the R-Toolbox, including "creating user defined PK parameters not available in PK-Sim/MoBi out of the box". Is it possible to creat parameters or process above in new version?

**Comment by PavelBal** [comment]
"creating user defined PK parameters not available in PK-Sim/MoBi out of the box" means creating of PK-parameters like AUC etc, see here: https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#pk-analysis-viewhttps://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#pk-analysis-view

New parameters in the model cannot be created from R. Unfortunately, I did not have to further look into this problem.
