### ISSUE TITLE
How to get the full absolute path in Mobi?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#486]
After exporting the PK-sim model into Mobi, a lot of parameters' path was shown in the way of  ". . |"
How could I get the full absolute path instead of abbreviation?

**Comment by prvmalik** [comment]
A tedious way:
Manually navigate to the path through the parent building block

I too am interested in the easy answer to this question.

Paul

**Comment by StephanSchaller** [comment]
There is no easy way in MoBi ;-)

One way would be to re-reference it in a formula with the option "absolute path" selected.
![image](https://user-images.githubusercontent.com/25477643/80893294-5af0b780-8cd1-11ea-8c6b-5ded9e8f46c9.png)

**Comment by jzq90** [comment]
@StephanSchaller Thanks. But the problem is that sometimes it only displays the last item in the path and there are a lot of items having the same name in different paths. 
For example, in your picture, there is a `blood flow rate` item in each tissue. How do you know `..|..|Blood flow rate` is from the bone? 
Another example like below, where to find `Height` from `..|..|..|Height` ？

![图片](https://user-images.githubusercontent.com/58142266/80899137-f2d8ba80-8d3e-11ea-8800-a07920e5b96b.png)

**Comment by StephanSchaller** [comment]
Well, your chosen local reference point is: "Organism|Lumen|Caecum|Distal radius", the "..|" means you are going one level up from there... so from "Distal radius" to "Caecum" to "Lumen" and then select "Height", so it  is "Organism|Height"...

**Comment by msevestre** [comment]
@jzq90 In general, you should look at formula in the context of a simulation. There,  all path are absolute. Relative paths are used to ensure that we can create me formula and reuse it over and over again, thus avoiding formula duplication.

>Another example like below, where to find Height from ..|..|..|Height

This is a good example of relative path gone wrong. Access to global parameters such as Height, Age etc.. should be absolute. For example, the path could read "Organism|Height" and it would not make the formula LESS reusable. 

All:
I feel that it would be a good feature to have a way to copy a path to clipboard from any entity in a simulation. (for example for a parameter, a container etc..) 
If yes, can someone create a feature request in MoBi and we can implement it if there is enough interest

**Comment by jzq90** [comment]
Thanks, all. It helps.

**Comment by teutonicod** [comment]
> This is a good example of relative path gone wrong. Access to global parameters such as Height, Age etc.. should be absolute. For example, the path could read "Organism|Height" and it would not make the formula LESS reusable.

I absolutely agree @msevestre . I think it would make more sense to have some paths referenced in this way. Would this be part of the feature request from @StephanSchaller ? Or we would need a new feature request?

**Comment by msevestre** [comment]
there is one feature request for PKSim
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1475
