### ISSUE TITLE
Is it possible to export Mobi project to PK-Sim?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#487]

**Comment by tobiasK2001** [comment]
Yes, just right click on the simulation and chose "save simulation to MoBi pkml Format..."
Than load the pkml file in PK-sim via:
![image](https://user-images.githubusercontent.com/25585248/77291078-d415eb80-6cdd-11ea-89fd-d631f9b0d514.png)

Hope this might help you.

Best, Tobias

**Comment by jzq90** [comment]
> 
> 
> Yes, just right click on the simulation and chose "save simulation to MoBi pkml Format..."
> Than load the pkml file in PK-sim via:
> ![image](https://user-images.githubusercontent.com/25585248/77291078-d415eb80-6cdd-11ea-89fd-d631f9b0d514.png)
> 
> Hope this might help you.
> 
> Best, Tobias

Thanks. It is helpful.
