### ISSUE TITLE
are all the tablets dissovled in the stomach?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#488]
![图片](https://user-images.githubusercontent.com/58142266/77305973-e9b50080-6d31-11ea-935d-122ab1119fb5.png)
I found the default release rate fraction in the stomach is 1.0, while in all the other GIT is 0.

Does this set means all the tablets are dissolved in the stomach totally? Not in the intestine at all?

**Comment by Yuri05** [comment]
> Does this set means all the tablets are dissolved in the stomach totally?

No, those are **initial** values. All release rates are time dependent functions.

Note: "_Release rate fraction XXX_" parameters are only used only for tablet formulations **different from "_Particle dissolution_"** with **deactivated "_Use as suspension_"** option.

**Comment by jzq90** [comment]
> 
> 
> > Does this set means all the tablets are dissolved in the stomach totally?
> 
> No, those are **initial** values. All release rate fractions are time dependent functions.
> 
> Note: "_Release rate fraction XXX_" parameters are only used only for tablet formulations **different from "_Particle dissolution_"** with **deactivated "_Use as suspension_"** option.

Thanks, it's helpful.

I'm working on a project for gastric residential tablets. Is it possible to make the tablet stay only in the stomach in the simulation?

**Comment by Yuri05** [comment]
>I'm working on a project for gastric residential tablets. Is it possible to make the tablet stay only in the stomach in the simulation?

Not sure why you would need this, but technically this is possible. What formulation type do you use?

**Comment by jzq90** [comment]
> 
> 
> > I'm working on a project for gastric residential tablets. Is it possible to make the tablet stay only in the stomach in the simulation?
> 
> Not sure why you would need this, but technically this is possible. What formulation type do you use?

The Weibull function was used in the simulation.

As for my purpose:
The formulation shows different dissolution profiles in vitro and is sensitive to pH. Then we design the formulation as gastric residential tablets. In the real world, the tablets will only stay in the stomach at acidic pH.
In the simulation, as you described above, the tablet will enter the intestine with time. This may change the pH and liquid volume and this will make the discrepancy between real-world and simulation.

**Comment by Yuri05** [comment]
In case your formulation is defined as suspension: deactivate "Parameter is state variable" option for all "Suspension fraction XXX" parameters. This will turn them into const (fraction stomach=1; fraction elsewhere = 0); thus the tablet will dissolve in stomach only
![grafik](https://user-images.githubusercontent.com/25061876/77410895-ed8d6500-6dbb-11ea-9015-09f352efb617.png)

**Comment by jzq90** [comment]
> 
> 
> In case your formulation is defined as suspension: deactivate "Parameter is state variable" option for all "Suspension fraction XXX" parameters. This will turn them into const (fraction stomach=1; fraction elsewhere = 0); thus the tablet will dissolve in stomach only

Thanks for your kind help again. Now I get how to use the option "parameter is state variable". Much appreciated.
However, I'm a little confused about why change the "suspension fraction XXX" but not "release rate fraction XXX". Also, should I change the "tablet_Location XXX" parameters in this situation?

**Comment by Yuri05** [comment]
For each tablet formulation different from "Particle dissolution", PK-Sim allows the option `Use as suspension` to be selected. **If selected**, the formulation will disintegrate in the stomach and the disintegrated particles will migrate along the gastrointestinal tract compartments. The drug release from the individual particles will then depend on the dissolution process selected (Weibull / Table / etc.). **If this option is not selected**, the tablet will be treated as non-disintegrating tablet with **discrete** transition in the different intestinal compartments. 

If you look at the definition of the tablet release rate fraction in a GI segment, you will see that **_exactly one of the model parameters_** - either the _suspension fraction_ or the _tablet location_ - of the given GI segment is used to calculate the corresponding release rate fraction. The other parameter is unused (it will switch to the opposite if the value of "Use as suspension" will be changed). 

Thus **depending on you selection of "Use as suspension"** either all suspension fraction or all tablet location parameters must be modified.
![grafik](https://user-images.githubusercontent.com/25061876/77415558-f170b580-6dc2-11ea-9221-18547a5fc418.png)
