### ISSUE TITLE
Concentration in Stomach

### ISSUE THREAD

**Issue by JoseDavidGomez** [Open-Systems-Pharmacology/Forum#489]
Dear Comunity,

I cannot find in the manual how are the concentration in stomach calculated after oral administration.

Does it consider the whole lumen volumen (1.57l) or is there a way to know the fluid volume that is considered?

Thank you!

JD

**Comment by PavelBal** [comment]
All lumen compartments have the parameter `Liquid'. Most of the processes taking place in lumen (such as absorption etc.) calculate the _dissolved_ concentration of the drug as `Amoung/Liquid`.

**Comment by JoseDavidGomez** [comment]
By rough calculations from the simulation stomach_concentration/dose in a solution, i get a liquid volume of around 1.9L. Does it make any sense? I thought fluid volume in the stomach was less than 500 mL.

**Comment by PavelBal** [comment]
The liquid volume in stomach is by default around 400 ml, additional to that the volume you administer with the application (around 250 ml).

In PK-Sim, there is no output for the concentration of drug in lumen liquid (I think it should be there), so there is no direct way to plot it in PK-Sim. In MoBi, you will find this parameter under `Organism|Lumen|LumenSegment|DrugName|Effective concentration in lumen`, the formula for which is

`EnableSupersaturarion ? M/Liquid : min(Solubility/MW ; M/Liquid)`

`M` is the amount of the molecule, `Liquid `the volume of the liquid in the lumen segment, and `MW `is the molecular weight of the compound.

**Comment by Yuri05** [comment]
>In PK-Sim, there is no output for the concentration of drug in lumen liquid (I think it should be there), so there is no direct way to plot it in PK-Sim. 

What is plotted in PK-Sim is `M/Liquid`; the **effective** (solubility limited) luminal concentration is indeed available only in MoBi

**Comment by Yuri05** [comment]
>In PK-Sim, there is no output for the concentration of drug in lumen liquid (I think it should be there), so there is no direct way to plot it in PK-Sim

I must correct: luminal concentration plotted in PK-Sim is exactly the effective concentration given by the formula above
(`EnableSupersaturarion ? M/Liquid : min(Solubility/MW ; M/Liquid)`)

**Comment by jzq90** [comment]
> 
> 
> The liquid volume in the stomach is by default around 400 ml, additional to that the volume you administer with the application (around 250 ml).

Why the default liquid in my model is only 50 mL? Isn't this is too small?
![图片](https://user-images.githubusercontent.com/58142266/77617925-4b62ae00-6f70-11ea-9ab5-3d0c5bdae4ce.png)

**Comment by Yuri05** [comment]
>Why the default liquid in my model is only 50 mL? Isn't this is too small?

This is not too small. Default liquid volume in adults **in fasted state** is around **45** ml.
S. e.g. https://www.ncbi.nlm.nih.gov/pubmed/18602774

**Comment by Yuri05** [comment]
@JoseDavidGomez Closing. Please reopen if there are still any unanswered questions.
