### ISSUE TITLE
How to change formulation in Mobi

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#490]
I got a Mobi project imported from in PK-Sim. It used a tablet formulation. I've adjusted the model for several places in Mobi, but now I want to change the formulation from "tablet" to "dissolved". Is it possible to change it directly in Mobi but not in PK-Sim? 
It seems the project transfered from PK-Sim to Mobi then transfered from Mobi back to PK-Sim. The structure is different.

**Comment by Yuri05** [comment]
> Is it possible to change it directly in Mobi but not in PK-Sim?

1. Create a new dummy project in PK-Sim. **Name you compound the same as in MoBi** (parameters do not matter; only the name)
2. Create new **oral administration protocol with required parameters** and new **dissolved formulation**.
3. Create new simulation using compound, administration protocol and (dissolved) formulation from above (individual does not matter; use any)
4. Export simulation to MoBi.
5. In MoBi: open Events building block and export your administration protocol as pkml
![grafik](https://user-images.githubusercontent.com/25061876/77409671-f11fec80-6db9-11ea-9926-d9c362240ebf.png)
6. Now go to your MoBi project, open Events building block, go to Applications and select "Load **Event Group**"
![grafik](https://user-images.githubusercontent.com/25061876/77409863-45c36780-6dba-11ea-8161-2c2066c2793c.png)
7. Select previously imported administration protocol. In the prompt which comes after that select only the top level container (MyApplication in this example)
![grafik](https://user-images.githubusercontent.com/25061876/77409995-84f1b880-6dba-11ea-9d5e-0ee63f17ce85.png)
8. Delete your previous (tablet) administration
![grafik](https://user-images.githubusercontent.com/25061876/77410103-b23e6680-6dba-11ea-8dea-7fee25a91450.png)

**Comment by jzq90** [comment]
Thanks very much for your kind help.
