### ISSUE TITLE
Blood/plasma concentration ratio has no impact on PK in PK-Sim standard model

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#492]
Dear all,

When using in a model the PK-Sim standard distribution model, I tried to modify the parameter "Blood/plasma concentration ratio", and simulating both the output "peripheral venous blood/whole blood" and "PVB/plasma". By changing the "Blood/plasma concentration ratio" there is no difference in the PK profiles generated, which I find very odd. Do you have any explanation? I could replicate this behavior also in the example model file for paracetamol provided with PK-Sim, so this is not limited to my model. (To replicate, I just changed the distribution model from R&R to PK-Sim standard in the example). Just as comparison, with the R&R distribution model the PK in plasma and blood was modified by changing the blood/plasma parameters for this model, so what I observed seems to be specific for the PK-Sim distribution model.

Does anyone has any explanation? And even more important, is this behavior correct?

Thanks in advance for your clarifications!

Best,

Donato

**Comment by Yuri05** [comment]
Well, the explanation is: not "Blood/plasma concentration ratio" (**B2P**) itself is used in the "PK-Sim standard" distribution model, but its formula.

This is how it looks like in PK-Sim standard model:

```
Parameter: S1|C1|Blood/Plasma concentration ratio
	Formula: (f_water_rbc + f_lipids_rbc * 10^LogP + f_proteins_rbc * KProt) * fu * HCT - HCT + 1
		fu: S1|C1|Fraction unbound (plasma)(0.11)
		LogP: S1|C1|Lipophilicity(3 [Log Units])
		KProt: S1|C1|Partition coefficient (water/protein)(22.2331460674157)
		HCT: S1|Organism|Hematocrit(0.47)
		f_lipids_rbc: S1|Organism|Vf (lipid, blood cells)(0.005)
		f_proteins_rbc: S1|Organism|Vf (protein,blood cells)(0.325)
		f_water_rbc: S1|Organism|Vf (water,blood cells)(0.625)

Parameter: S1|C1|Partition coefficient (blood cells/plasma)
	Formula: (f_water_rbc + f_lipids_rbc * 10^LogMA + f_proteins_rbc * KProt)*fu
		fu: S1|C1|Fraction unbound (plasma)(0.11)
		LogMA: S1|C1|Lipophilicity(3 [Log Units])
		KProt: S1|C1|Partition coefficient (water/protein)(22.2331460674157)
		f_lipids_rbc: S1|Organism|Vf (lipid, blood cells)(0.005)
		f_proteins_rbc: S1|Organism|Vf (protein,blood cells)(0.325)
		f_water_rbc: S1|Organism|Vf (water,blood cells)(0.625)
```

As you can easily see, in fact it is `Partition coefficient (blood cells/plasma) = (HCT - 1 + B2P) / HCT`
But due to the fact that B2P is not used **directly**, changing it does not have any effect.

Comparing it with e.g. Rogers and Rowland model:
```
Parameter: S2|C1|Blood/Plasma concentration ratio
	Formula: (f_water_rbc + f_lipids_rbc * 10^LogP + f_proteins_rbc * KProt) * fu * HCT - HCT + 1
		fu: S2|C1|Fraction unbound (plasma)(0.11)
		LogP: S2|C1|Lipophilicity(3 [Log Units])
		KProt: S2|C1|Partition coefficient (water/protein)(22.2331460674157)
		HCT: S2|Organism|Hematocrit(0.47)
		f_lipids_rbc: S2|Organism|Vf (lipid, blood cells)(0.005)
		f_proteins_rbc: S2|Organism|Vf (protein,blood cells)(0.325)
		f_water_rbc: S2|Organism|Vf (water,blood cells)(0.625)

Parameter: S2|C1|Partition coefficient (blood cells/plasma unbound)
	Formula: (HCT - 1 + B2P) / fu / HCT
		B2P: S2|C1|Blood/Plasma concentration ratio(1.19438493679775)
		fu: S2|C1|Fraction unbound (plasma)(0.11)
		HCT: S2|Organism|Hematocrit(0.47)

Parameter: S2|C1|Partition coefficient (blood cells/plasma)
	Formula: K_pu_bc*fu
		fu: S2|C1|Fraction unbound (plasma)(0.11)
		K_pu_bc: S2|C1|Partition coefficient (blood cells/plasma unbound)(12.8507724719101)
```
As you can easily see from the last 2 equations
`Partition coefficient (blood cells/plasma) = (HCT - 1 + B2P) / HCT`

Which is exactly the same as in the PK-Sim standard model. Just with the difference that B2P i used **directly**.

I guess this is due to historical reasons. "PK-Sim standard" was the first distribution model used in PK-Sim, R&R was added later. 
"PK-Sim standrad" did not rely on B2P, which was introduced with R&R. "PK-Sim standard" was left AS IS.
As far as I remember, in PK-Sim 4 B2P was hidden in case "PK-Sim standard" distribution was selected - to avoid thid kind of confusion.

Don't remember why "PK-Sim standard" was kept AS IS - should be doable to rewrite the equations in the same way as in R&R.

**Comment by teutonicod** [comment]
Hi @Yuri05 ,

Thanks a lot for the explanation. I would say that if possible, it would be better to use directly the value provided, instead of the formula, in the PK-Sim dist model. Since it would avoid misunderstanding on one side, and most importantly, if someone has measured values for B/P partition (this is my case :-)) it would be possible to integrate this information in the distribution model, as it is already possible in the other distribution model.

**Comment by Yuri05** [comment]
Created an issue for this: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1455

**Comment by teutonicod** [comment]
Thanks a lot @Yuri05 !
Is there a way to change the blood to plasma ratio in a simulation so that is would be used instead of the formula? in PK-Sim (ideally) or in MoBi?

**Comment by Yuri05** [comment]
>Is there a way to change the blood to plasma ratio in a simulation so that is would be used instead of the formula?

You mean right now? 
 * If you need to do it in PK-Sim, you could just calculate of `(HCT - 1 + B2P) / HCT` and set it as the new value for `Partition coefficient (blood cells/plasma)` (of course as soon as HCT or B2P changes it must be redone...). Better solution not possible.
* In MoBi: In the Spatial Structure Building block, change the formula of `Partition coefficient (blood cells/plasma)`
![grafik](https://user-images.githubusercontent.com/25061876/77556268-91f4d180-6eb8-11ea-9569-aaa8f9b06920.png)
1. Change the formula type to "Explicit ormula"
2. Create new formula and set it to `(HCT - 1 + B2P) / HCT` (s. above)

**Comment by teutonicod** [comment]
OK, thanks a lot!

**Comment by Erik-Sjogren** [comment]
Sorry for being late into this discussion.
Is there a plan for doing this more convenient? 
Lets say have an option for that if one manually input B:P ratio (at given HCT) in Compound BB, the "Partition coefficient (blood cells/plasma)" is automatically calculated and used for all simulations?

**Comment by PavelBal** [comment]
Let's reopen, @Erik-Sjogren has a valid point.
