### ISSUE TITLE
What's the meaning and function of “Tablet time delay factor“？

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#494]
![图片](https://user-images.githubusercontent.com/58142266/77509660-1723ba80-6ea8-11ea-8e48-ea4d6b3ed14f.png)

**Comment by PavelBal** [comment]
The rate of transfer between lumen compartment A (e.g., duodenum) and lumen compartment B (e.g. UpperJejunum) for **liquids** is calculated as the amount of the compound (liquid form) in comparment A times `Intestinal transit rate (absolute)` of the compartment A.

For solids, like the tablet, the rate is further multiplied by the parameter `Tablet time delay factor`. However, I do not know where this value comes from.

**Comment by jzq90** [comment]
> For solids, like the tablet, the rate is further multiplied by the parameter `Tablet time delay factor`. However, I do not know where this value comes from.

This is interesting. I've read from some literature that bigger the tablet, slower the transit. So does this mean that I can change `Tablet time delay factor` to simulate this situation?

Also, if I set this value to 0, it will become a stomach retention formulation, which will only stay in the stomach?

**Comment by Yuri05** [comment]
>This is interesting. I've read from some literature that bigger the tablet, slower the transit. So does this mean that I can change Tablet time delay factor to simulate this situation?

Yes.

>Also, if I set this value to 0, it will become a stomach retention formulation, which will only stay in the stomach?

Indeed. This is easier than modifications of suspension fractions/tablet locations (as proposed in https://github.com/Open-Systems-Pharmacology/Forum/issues/488) - and can be done directly in PK-Sim

**Comment by tobiasK2001** [comment]
HI, sorry to jump in, but hm, really? Is it possible to change the tablet delay factor in PK-sim to 0? I tried and it through an error saying that it must be greater than 0. If I use super-small values (with use as suspension activated) instead of 0 I only see a small effect. If I use bigger values <10000 than fraction absorbed decreases and concentration in stomach and later gut segments like duodenum decrease as well. Not sure if this mirrors the behavior of a tablet stuck in stomach...

**Comment by Yuri05** [comment]
Well, if you set it to 0 (or to a very small value if PK-Sim does not allow zero), you will see that the solid fraction in stomach is const =1 and all other solid fractions are zero. Which means the tablet remains in stomach and dissolution occurs only there
![grafik](https://user-images.githubusercontent.com/25061876/77562173-f4050500-6ebf-11ea-883d-f34e83101015.png)

If you set it to very high value, you will see that solid fractions in stomach and all small intestine segments is zero (stomach goes from its initial value 1 immediately to zero), solid fractions in large intestine are not zero (in fact, "Tablet delay factor" is applied only to the small intestine but not to the large intestine). Which means that the dissolution starts in large intestine.
![grafik](https://user-images.githubusercontent.com/25061876/77562839-d2f0e400-6ec0-11ea-911d-36025cddba39.png)
Depending on the relevant properties (solubility, intestinal permeability etc.) I could imagine that the total fraction absorbed in both cases is not very different...
