### ISSUE TITLE
Is it possible to build a model from IV and PO C-T curve? 

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#495]
Is it possible to build a model just from the IV and PO C-T curve without knowing the physiochemical properties of the drug, such as LogP, solubility and permeability?

**Comment by regulus92** [comment]
Usually a pharmacokinetic model based on CA or NCA. With enough preclinical/clinical PK data, we may consider population pharmacokinetic modeling, i.e. top-down approach. My opinion.

**Comment by StephanSchaller** [comment]
@jzq90, sure, you can use the data to fit LogP, solubility and permeability in  a parameter identification.
If you have fraction unbound as a value, this should likely work. If you also need to fit fu, you might get multiple solutions but will be able to match the data nonetheles.

If the resulting values for LogP, solubility and permeability are then correct, can't be determined.

**Comment by jzq90** [comment]
> @jzq90, sure, you can use the data to fit LogP, solubility and permeability in a parameter identification.
> If you have fraction unbound as a value, this should likely work. If you also need to fit fu, you might get multiple solutions but will be able to match the data nonetheles.
Thanks. This is a good idea. 
But I find the it couldn't get a good fit in parameter identification. I think the initial values of LogP, solubility and permeability have a huge impact on the identification.

**Comment by jzq90** [comment]
> 
> 
> Usually a pharmacokinetic model based on CA or NCA. With enough preclinical/clinical PK data, we may consider population pharmacokinetic modeling, i.e. top-down approach. My opinion.

Thanks, of course that works. But I'm working on the First-in-human simulation from a fitted preclinical model.

**Comment by StephanSchaller** [comment]
> But I find the it couldn't get a good fit in parameter identification. I think the initial values of LogP, solubility and permeability have a huge impact on the identification.

True, maybe you can get an initial value from calculated values using QSPR? If you have the molecule structure in SMILES format, you can use these tools:

pkCSM:
 
http://biosig.unimelb.edu.au/pkcsm/prediction
 
and admetSAR
 
http://lmmd.ecust.edu.cn/admetsar2/


(or you first try aome manual fitting)

Good Luck!

**Comment by jzq90** [comment]
Thanks.
