### ISSUE TITLE
Is there absorption in the stomach?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#496]
>In PK-Sim, there is no output for the concentration of drug in lumen liquid (I think it should be there), so there is no direct way to plot it in PK-Sim

I must correct: **luminal concentration plotted in PK-Sim is exactly the effective concentration given by the formula above**
(`EnableSupersaturarion ? M/Liquid : min(Solubility/MW ; M/Liquid)`)

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/Forum/issues/489#issuecomment-603908012_

I found there is no "fraction absorbed" option in the stomach. Does this mean there is no absorption in the simulation?

**Comment by jzq90** [comment]
![图片](https://user-images.githubusercontent.com/58142266/77620581-a34fe380-6f75-11ea-8a92-b981a5e908c1.png)

**Comment by Yuri05** [comment]
>I found there is no "fraction absorbed" option in the stomach. Does this mean there is no absorption in the simulation?

Yes, this is correct.

**Comment by jzq90** [comment]
> 
> 
> > I found there is no "fraction absorbed" option in the stomach. Does this mean there is no absorption in the simulation?
> 
> Yes, this is correct.

But why not include the absorption process in the stomach?
I know most of the drug is absorbed in the intestine because of the large mucosa area. But I think some specific drug is absorbed in the stomach to the extent which could not be ignored.
