### ISSUE TITLE
PKsim with R/Rstudio

### ISSUE THREAD

**Issue by gsharma14** [Open-Systems-Pharmacology/Forum#498]
Hello there!
I have worked with PKsim on Matlab and GUI but I want it to work on R/R studio but after having gone through all the scripts in the suite I did not find much on how to do that. Can someone help me out with that. I downloaded the Mobi toolbox in R but I couldn't do so with PKsim. I am new to R so I would appreciate all the help.

Thank you!

**Comment by msevestre** [comment]
The Mobi toolbox in R will be deprecated in the next few weeks.
I'd strongly suggest you check the OSPSuite-R package out which will be its official replacement
https://github.com/Open-Systems-Pharmacology/OSPSuite-R

If you are new to R, I'd suggest doing some beginner R course first, for example 
https://www.coursera.org/learn/r-programming

**Comment by msevestre** [comment]
Also see here for a discussion on how to get started
https://github.com/Open-Systems-Pharmacology/Forum/issues/477
