### ISSUE TITLE
PBPK-PD model when dose is not known

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#501]
Hi!

I am fairly new to PBPK and I have never used PKSIM-MOBI software. Before I embark on the project, I just wanted to know whether its possible to build a PBPK-PD model for a drug whose DOSE is not known?
In my data, subjects are smoking cigarettes. While we know the dose in cigarettes, while smoking, lot of it is dissipated into the air or undergoes pyrolysis or is lost by other means, so we don't know the exact dose that is reaching the bloodstream. We have plasma concentrations in 105 subjects and related PD parameters such as heart rate and blood pressure.

Your response will be much appreciated, and help me save time.

Regards,
Sumeet Singla

**Comment by StephanSchaller** [comment]
Dear Sumeet,

thank you for your question.

Indeed, you can build a PBPK-PD model for a drug whose DOSE is not known.

1. ideally, you do have a reference scenario (i.e., dataset), where the dose was known on which you develop (and another to qualify) your PBPK/PD model
2. you then set up your scenario for which the DOSE is not known with the same model and let the parameter identification estimate the dose.

If you are very confident in your drug properties and in-vitro characterizations (and the IVIVE), you can also go without step 1...

Best,
Stephan

**Comment by tobiasK2001** [comment]
Dear Sumeet,

in case you have already an established PBPK model for your compound of interest you can deduce from your blood concentrations an "fraction absorbed after smoking". I.e. if you are investigation nicotine you might use the model described here:
https://www.ncbi.nlm.nih.gov/pubmed/32166575
Or maybe you can assume for your compound of interest a similar pulmonary absorption kinetics like there.

Hope this might help you.

Best, Tobias

**Comment by humblewarrior** [comment]
Great responses!! Thank you so much to both of you!
