### ISSUE TITLE
Geometric mean, standard deviation

### ISSUE THREAD

**Issue by ckcho0625** [Open-Systems-Pharmacology/Forum#502]
i am doing calculation of sum concentration of two compound.

i used geometric form for statistics, and i derived geometric mean and standard deviation.

but, when i searched in google, i am confused because i did not found method that calculate 5% to 95% percentile based on geometric mean and deviation. 

So, i wonder what method is used to calculate 5% to 95% percentile in pk-sim. 

Then, i will apply this method to calculate sum of our each concentration.

Or, is this possible to calculate automatically sum of concentration of two compound, and express geometric mean and 90% confidence interval in pk-sim? 

Thank you for your appreciation.

**Comment by jzq90** [comment]
I think PK-Sim gets the population first, then gets the simulation for each individual in the population. So it gets the complete data of the population. With this, you can get arithmetic mean, geometric mean, 5%, 95% percentile or whatever statistics you want.
