### ISSUE TITLE
What parameters should I change to have this individual / population with kidney disease?

### ISSUE THREAD

**Issue by AParisotto** [Open-Systems-Pharmacology/Forum#504]
Hello people
For an individual / population with kidney disease, should I change the Glomerular Filtration Rate (GFR)? do I keep the standard unit of measurement for the PK-sim it self? is mL / min / 100g?
Are there any other parameters that i must change to have an individual / population with the characteristics of this disease?
Thanks

**Comment by prvmalik** [comment]
This parameterization is what you will need.

https://www.page-meeting.org/pdf_assets/1160-Schmulenson_PAGE2018.pdf
