### ISSUE TITLE
ISEF optimization

### ISSUE THREAD

**Issue by ckcho0625** [Open-Systems-Pharmacology/Forum#509]
Hello, i have a question about IVIVE.

When i developed and confirmed PBPK model, metabolic fraction of CYP isoform is too much low than my expectation. I inputted Vmax and Km data in process type of 'in vitro metabolic rate in the presence of recombinant CYPs/enzymes - michaelis menten' 

Results of intensive searching, i think that the cause is difference between rhCYP system and HLM system. So, i want to adjust ISEF factor for overcoming my problem. But, I didn't found methods to modify this factors. How can i adjust this factor? Where can i find this parameter? also i wonder default value of this parameter.

Thank you for your appreciation.

**Comment by prvmalik** [comment]
Hi,

There are no reliable methods for IVIVE of Vmax for metabolism. However, the in vitro Km value does have some utility. The best way forward is to use the in vitro Km in your michaelis-menten approximation, then use the parameter identification tool to optimize the Vmax parameter.

Paul

**Comment by StephanSchaller** [comment]
Yes, and elaborating further on @prvmalik s great explanation, an ISEF factor is nothing more than a multiplication of your Vmax, so fitting Vmax (or "applying a factor that works") is the way to go.
