### ISSUE TITLE
PK Sim classes

### ISSUE THREAD

**Issue by Annum-Z** [Open-Systems-Pharmacology/Forum#51]
Dear Sir,
Could you please guide me as to where I can find a map of all the classes, how they are arranged and how they call each other, or which class is the parent class and which is  the child class, and which class comes under which class.
Thanks!

**Comment by msevestre** [comment]
Hi @Annum-Z,
There is no document like that available at the moment. 
Making sure that this kind of document stays up to date is extremely time consuming. 

I'd me more than happy to give you guidance if you have specific questions or if you explain, what you are trying to achieve. 

Cheers,

**Comment by Annum-Z** [comment]
Hi, 
Thankyou for your reply. I would actually like to know which files are involved in setting up the model in PKsim, or which files are responsible for creating the model ? 

Thanks !

**Comment by msevestre** [comment]
Hi @Annum-Z ,

Assuming that all building blocks have been created (Individual or Population, Compound, Protocol), let's start the journey from the top shall we? 

- It all begins at the `CreateSimulationPresenter` which is responsible to start the creation workflow. Ultimately, this presenter will call the method [`CreateModelFor(simulation)`](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/bc72510accafb005f13d2681c08aa699ca894a91/src/PKSim.Presentation/Presenters/Simulations/CreateSimulationPresenter.cs#L59) from the `SimulationModelCreator` object.

- From [there](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/bc72510accafb005f13d2681c08aa699ca894a91/src/PKSim.Core/Services/SimulationModelCreator.cs#L44), the code is really doing two things: 
 
  1. Convert `PK-Sim Building Blocks` into `Core Building Blocks` (the one used in `MoBi`). There is not a one to one mapping between those building blocks so this needs to be done in `PK-Sim`. That mapping is done in the [`BuildConfigurationTask.CreateFor(simulation)`](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/bc72510accafb005f13d2681c08aa699ca894a91/src/PKSim.Core/Services/SimulationModelCreator.cs#L49) call. 
  1. Once the `BuildConfiguration` has been created, the core object `ModelConstructor` is called. This object is located in the `OSPSuite.Core` component and is used by `PK-Sim` and `MoBi` to create models. Look at the call [`_modelConstructor.CreateModelFrom(buildConfiguration, simulation.Name);`](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/bc72510accafb005f13d2681c08aa699ca894a91/src/PKSim.Core/Services/SimulationModelCreator.cs#L53)

- That means that all the logic to create a `PK-Sim` or `MoBi` model is really implemented into the [`ModelConstructor`](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/f75c2b2f6a639a8a8f27e4937358ad7819e87ba0/src/OSPSuite.Core/Domain/Services/ModelConstructor.cs#L71) class. I would strongly suggest to look at all the integration tests available in core to see how this is being used. Especially, the [`ModelConstructorIntegrationTests`](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/783d8c42ee11e3bfdc7c9d7401a9519f35e35485/tests/OSPSuite.Core.Tests/Core/ModelConstructorIntegrationTests.cs#L16) that creates a small yet full features model. Each assumption on the model creation process is validated using one test in the test cased `When_running_the_case_study`.

Does it answer your question? 
Cheers,

**Comment by msevestre** [comment]
Let me know if you need more help there.
