### ISSUE TITLE
Kp scalar value

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#513]
Hi! I have couple of questions.

1) Where can I find Kp scalar (ratio of drug concentration in tissue and plasma) to optimize Kp values for various organs?
2) Where is the place to enter Vss value in the software?
3) What is the difference between "venous blood" and "peripheral venous blood"? I am trying to predict plasma concentration. Which one should I go for?

Regards,
Sumeet

**Comment by jzq90** [comment]
I think there isn't a way to adjust Kp and Vss directly in a PBPK model. These parameters are dependent on the properties of molecules and physiological parameters. 
The same reason you can only adjust organ permeability and solubility but can't adjust bioavailability directly. But I think you can use the real data to fit LogP, solubility and permeability in a parameter identification like below:
https://github.com/Open-Systems-Pharmacology/Forum/issues/495

**Comment by jzq90** [comment]
From the instruction of software:
![图片](https://user-images.githubusercontent.com/58142266/80557020-167ec680-8a08-11ea-9a2a-5efb15d08607.png)

**Comment by msevestre** [comment]
This is the correct answer. Thanks @jzq90

**Comment by humblewarrior** [comment]
So, what I am trying to understand is how this software is different in terms of its functionality, specifically in terms of entering Kp values for different organs. I am trying to replicate results from previous study, and I have Kp values of all the organs from that study. I just don't see where I can enter those Kp values, to get similar tissue-concentration time profiles. I see that we can enter partition coefficient in parameters ->Distribution -> Partition Coefficient, and there are two types of partition coefficient: 1) Interstitial:plasma and 2) Intracellular Plasma.

**Comment by humblewarrior** [comment]
@jzq90 There is actually place to enter Vss in the software. When you define the population and run the simulation, in the box it asks you to enter PK-parameters. I was asking for place to "Enter" Vss and you mistook it as "Adjusting Vss". No worries! I am getting to know this software more as I am exploring and will keep posting my questions here. Please bear with me!

**Comment by StephanSchaller** [comment]
> is different in terms of its functionality

What do you mean here? Different to what, and what study are you trying to replicate?

There is also the calculated value for Kp blood/plasma in parameters ->Distribution -> Partition Coefficient given:
![image](https://user-images.githubusercontent.com/25477643/81987282-99736400-9639-11ea-9349-45de7c61f500.png)

as @jzq90 correctly stated, the Kp is csalculated from your lipophilicity and such. So in a way you have to adjust the input values (also the partitioning calculation method has an influence) to get the measured Kp.

**Comment by humblewarrior** [comment]
@StephanSchaller 

So, the work that I am trying to replicate is in the process of getting published. In that study, the authors used Simcyp software. They have Kp value of 0.266 (which was adjusted) and then they reported Kp values of the drug in each organ. I am trying to get that. I am trying to get Kp values of the drug in each organ. How should I get Kp value of drug in each organ? Or maybe there is a way to adjust the Kp value of the drug in each organ so that my simulated, lets say brain tissue concentration is similar to the previous study?? I don't know. That is what I want so that I can compare my results with the results of that study. 

I am sorry. I am still naive when it comes to PBPK and this software. I am trying to figure it out as much.

**Comment by StephanSchaller** [comment]
Well, be aware that SimCyp and PK.Sim differ in some of the details of how the PBPK model is built.

In any case, find out what partition coefficient calculation method they used (likely "Method 1" which should correspond to Rodgers and Rowland). So select Rodgers and Rowland in PK-Sim when you create your Simulation.
You can also "by force" change the B:P partitioning in PK-Sim by changing the partition coefficient i showed above. This parameter is the same for all organs, as "blood/plasma" is organ-independent.

You can change tissue partitioning with the other Kp vlaues 1) Interstitial:plasma and 2) Intracellular:plasma.

But again, this is "forcing" partitioning by hand, and not recommended. Better find out what might be different for your compound that the predicted values don't work (tissue / cellular binding partner?).

**Comment by humblewarrior** [comment]
Method was by Poulin and Theil and corrected by Berezhkovskiy. I can see those methods in the software. I think you answered my question for now. Thank you so much! I really appreciate it. Stay safe!

**Comment by leeking-55** [comment]
> Method was by Poulin and Theil and corrected by Berezhkovskiy. I can see those methods in the software. I think you answered my question for now. Thank you so much! I really appreciate it. Stay safe!

Excuse me, did you  solve your problem? If it is not recommended to modify the tissue partitioning with the other Kp vlaues 1) Interstitial:plasma and 2) Intracellular:plasma, then it is better to modify what parameters to get the KP value reported in the literature, and look forward to your reply.
have a good day
leeking.
