### ISSUE TITLE
Parameter Identification 

### ISSUE THREAD

**Issue by Wenjing1018** [Open-Systems-Pharmacology/Forum#515]
Hello，
In the Simulation Explorer mark the two simulations"Oral 500mg"and"oral 850mg",Select both intestinal permeability parameters and click the upper Add button,In the tab Configuration keep the default settings,In the Ribbon Bar Run & Analyze click Show Visual Feedback and then Run to start the optimization. but the Show Visual Feedback interface only show a simulated result, the selection part is grey, but the case is black, it can be selected, I want to know where my problem are?  
<img width="631" alt="f9c9c74c055398f4a8b583de632527e" src="https://user-images.githubusercontent.com/63133525/80776323-b49f9780-8b94-11ea-9e20-80b9ec72b397.png">
<img width="380" alt="b92ecd8bd63c2d39c4ba30062a57aae" src="https://user-images.githubusercontent.com/63133525/80776329-bb2e0f00-8b94-11ea-87ef-7d0131a2a115.png">

**Comment by msevestre** [comment]
How many outputs do you have that are mapped to observed data ? 
This is the first step of the PI definition. I believe that only outputs mapped to observed data will be shown here

**Comment by Wenjing1018** [comment]
> How many outputs do you have that are mapped to observed data ?
> This is the first step of the PI definition. I believe that only outputs mapped to observed data will be shown here
 are you talking about this part? Any questions?
![image](https://user-images.githubusercontent.com/63133525/80777842-1a8e1e00-8b99-11ea-9339-9c3f7d075b29.png)

**Comment by msevestre** [comment]
Your screen shot only shows one output (first column) unless the path are different but this is not visible. Therefore only one output to select from the PI output selection.

I am not sure I understand your problem. What do you expect to happen?

**Comment by Wenjing1018** [comment]
> Your screen shot only shows one output (first column) unless the path are different but this is not visible. Therefore only one output to select from the PI output selection.
> 
> I am not sure I understand your problem. What do you expect to happen?

 I'm sorry I don’t understand what’s your meaning. 
There are three different doses(three simulations) in my first column, and there are several data for each dose, but only one dose（one simulation） is shown in the show visual feedback, and the other two are not shown.

**Comment by msevestre** [comment]
@Wenjing1018 

The combo box is only available WHILE the PI is running
After the RUN, the information is discarded

**Comment by Wenjing1018** [comment]
@msevestre 
PI is running started by clicking on RUN? How to run the PI?
Thank you very much!

**Comment by PavelBal** [comment]
In this case, the PI is solved faster than you can click "Show visual feedback", so you only see the "VIsual Feedback" window after the run is finished :)

**Comment by Wenjing1018** [comment]
@PavelBal 
In this case, how do I operate to show three simulations in the "VIsual Feedback"window?

**Comment by StephanSchaller** [comment]
You can't. You can only display one simulation output at a time.

**Comment by Wenjing1018** [comment]
@StephanSchaller
I tried to operate yesterday and understood the sentence——the PI is solved faster than you can click "Show visual feedback", so you only see the "VIsual Feedback" window after the run is finished.As you said,I can only display one simulation output at a time.
Thank you very much!
