### ISSUE TITLE
What is plasma albumin concentration in animals and human?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#516]
I wonder if it is possible to extrapolate fu (free fraction) value from one species to another species based on the albumin concentration.
But I couldn't find the absolute value of albumin concentration in PK-Sim. Could anyone tell me if I can get the plasma albumin concentration in the software or some references?

**Comment by StephanSchaller** [comment]
> I wonder if it is possible to extrapolate fu (free fraction) value from one species to another species based on the albumin concentration.

**Comment by jzq90** [comment]
> 
> 
> > I wonder if it is possible to extrapolate fu (free fraction) value from one species to another species based on the albumin concentration.
> 
> I don't believe you can as not only the amount but also the albumen itself and associated binding affinities will be different.

So the fu of each species in the model for each species？This is frustrating.
The study of linear plasma protein binding would be much harder without a model support.

**Comment by StephanSchaller** [comment]
Yes
![image](https://user-images.githubusercontent.com/25477643/80910288-8bb30a00-8d2e-11ea-8531-33754e6f330c.png)

Biology is frustrating at times...

**Comment by jzq90** [comment]
Thanks anyway.
