### ISSUE TITLE
How to add a reversible reaction in PKsim?

### ISSUE THREAD

**Issue by shapoo1** [Open-Systems-Pharmacology/Forum#517]
I want to add a reversible reaction of drug metabolites in PKsim. e.g.  Drug to its metabolite and then metabolite to its parent drug? How can I do this in Pksim?

**Comment by prvmalik** [comment]
You will enter two compounds: 'DRUG' and 'METABOLITE'

You will enter two enzymes in your individual: 'K1' and 'K2'

For the forward reaction, enter it on the 'DRUG' ADME tab under the enzyme K1. Specify that 'METABOLITE' is the metabolite.

For the reverse reaction, enter it on the 'METABOLITE' ADME tab under the enzyme K2. Specify that 'DRUG' is the metabolite.

This assumes that you know the rates of the forward and reverse reactions.

**Comment by shapoo1** [comment]
Hi @prvmalik 
Thanks for your help
I want to add a reversible reaction by the ADH enzyme. In this case, I have only one enzyme and one compound. Do I need to add its metabolite separately as a compound?
Thanks in advance

**Comment by prvmalik** [comment]
Yes, you will add the metabolite as a separate compound. 

To avoid complications, I recommend adding another ADH enzyme (called something different) in your individual for the reverse reaction. In the ADME tab for the metabolite, add this new ADH as a metabolizing enzyme for the reverse reaction. Ensure that your parent drug is selected as the 'metabolite' for this reaction.

**Comment by shapoo1** [comment]
Dear @prvmalik 
Thanks a lot for your help

**Comment by prvmalik** [comment]
Be aware that with this setup, the metabolite will be able to distribute around the body once created in the liver.

**Comment by shapoo1** [comment]
@prvmalik 
Thanks again
I will try it out, in case I have any question will get back to you.

Regards,
