### ISSUE TITLE
New to Pk Sim: Tutorials are out of date

### ISSUE THREAD

**Issue by Felixhad** [Open-Systems-Pharmacology/Forum#518]
I want to set up a simulation. In previous tutorials there isn't a tab for observers. I don't understand what this is or how to set it up and I cannot set up a simulation without it. I would appreciate the help.

**Comment by PavelBal** [comment]
This is true, the documentation is outdated.

You don't need to set up any observers, just click on "OK" when you are in the tab "Observers".

**Comment by tobiasK2001** [comment]
Hi Felix,
 if you would like to know what observers actually are, please check this out:
https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/model-building-components#observers
This was writting for MoBi, but as Pavel explained it now also applies for PK-Sim.

Best, Tobias

**Comment by msevestre** [comment]
@all:
The documentation is also open-source. If you find part of the documentation outdated, please do not hesitate to submit a change request.

The process is described [here](https://docs.open-systems-pharmacology.org/how-to-contribute). This is an amazing way for any of our users to participate in the open-source initiative.
