### ISSUE TITLE
Support custom workflows in MoBi with MoBi Extensions / Plugins

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Forum#52]
I would like to discuss here  the idea of **Extensions / Plugins** for **MoBi** that would support any custom workflows.

## Power and Flexibility
MoBi is very flexible. You can edit and change any model created with PK-Sim or create your own model from scratch. A lot of powerful features, such as parameter identification, sensitivity analysis, export to Matlab etc.. are already backed-in and available out of the box.

Now some specific tasks can be very repetitive or hard to accomplish and thus error prone.

## Support for custom Workflows
* A first example is adding a new organ such as a tumor. This is absolutely doable by hand and the steps to perform are well known and described [here](https://github.com/Open-Systems-Pharmacology/MoBi/issues/1).  It feels that this functionality could be encapsulated and performed somewhat automatically by MoBi. Does this workflow belongs in MoBi out of the box? I can't say for sure. Having the possibility however to support this workflow in MoBi by simply installing a MoBi plugin would be a tremendous gain.

* Another example would be adding a custom PD Model or custom specific observers that your organization is always using etc... This can be done at the moment by exporting some pkml files and importing them again. What if this function was available right from the ribbon bar via a simple button click?

## How would this work?
* In a nutshell, MoBi would provide an interface that software developers could use to implement a plugin.
* The resulting component would be installed separately
* A plugin would have access to all building blocks and simulations defined in the project as well as to all analyses performed in the project, such as parameter identifications and sensitivity analyses.
* A plugin could add, modify any building block or simulations using the `Command` implementation. The usage of `commands` is crucial so that any change performed to the model will be logged in the history for review
* A plugin would be started from a custom ribbon menu in the navigation bar and provide a custom icon and title to be easily identifiable 

## What do you think?
There are a lot more examples that could benefit from such a workflow. I'd like some feedback from the community to see if such an *plugin concept* would be beneficial. Can you describe some of the workflows/processes that you would like MoBi to support via the implementation of custom plugins?

**Comment by PavelBal** [comment]
The idea sounds really great and I fully support it. Another examlpe of a workflow which could be implemented via a plugin is adding PBPK models to existing model. At the moment, the user has to merge different building block and play close attention to the molecule start values block. An automation of such a process would make re-using of existing model much easier.

**Comment by StephanSchaller** [comment]
Great Idea!!

If you say Plugins: this could be a great opportinity for SMEs as abusiness case, provoding very useful features but allowing for a licensing model.
I think this could really trigger an avalance for interest in software development but also Base-Database improvements for OSPS!

For extensions of your list:

- An Application Plugin (or as a base feature) to make building your application as easy as in PKSim

- A Population Plugin: this could be especially interesting for disease models (QSP models): A provider/developer can generate sophisticated in-silico populations from clinical datasets and provide the in MoBi through a plugin for population simulation!
Of course this requires the popSim feature from PKSim in MoBi.

- NONMEM Plugin: as an extension to the last point: automatically generate a population simulation (generating application protocol, the population and loding the observed data from ONE SINGLE SHEET)!

- ...

**Comment by tobiasK2001** [comment]
Great Idea, How about a R Extensions / Plugins? Maybe there is already R-toolbox? But is it available for the 64 bit Version?
Also an Extensions / Plugins for Inhalation would be great. Obviously ther has been some work done in the past (http://journals.lww.com/ccmjournal/Abstract/2013/12001/926___RISK_ASSESSMENT_FOR_AMIKACIN_INHALE_IN_ICU.882.aspx). Maybe you can extract the generall concept and worklow for that.
