### ISSUE TITLE
Sensitivity analysis

### ISSUE THREAD

**Issue by AnisPBPK** [Open-Systems-Pharmacology/Forum#520]
Hi,

Can someone guide me through the sensitivity analysis in PK-Sim. I want to know how to interpret the results on sensitivity analysis?
if we take the influence of t/2(microsomal essay) on totale body clearance/F  for exemple:  we have sensitivity analysis=   -0.66   with a variation range= 1.5 and number of steps =3

Thank you !

**Comment by Yuri05** [comment]
s. https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis#mathematical-background

**Comment by AnisPBPK** [comment]
> s. https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis#mathematical-background

Hello Yuri, 
thank you for answer, I alredy read this, they give  As an example, a sensitivity of -1.0 implies that a 10% increase of the parameters leads to a 10% decrease of the PK parameter value, and a sensitivity of +0.5 implies that a 10% increase of the parameters leads to a 5% increase of the PK parameter value.  

I want to know if this 10% increase of the parameters change for exemple to 150% if we put 1.5 as variation range ? 

thank you again !

**Comment by msevestre** [comment]
@AnisPBPK 

>I want to know if this 10% increase of the parameters change for exemple to 150% if we put 1.5 as variation range ?

This is correct
Check this section here

The relative variations Δk are defined by multiplication of the value in the simulation with variation factors. These variation factors are defined by setting two configuration parameters "Number of Steps” [ = n ] and “Variation Range” [ = a ] in the following way :


For each value of k = 1 ... n, two factors are used:  ![image](https://user-images.githubusercontent.com/1041237/81354363-64936a00-9099-11ea-9a5a-34b10b483bcf.png)

For the default setting n = 2 and a = 0.1, we get 4 variation factors: 1/1.1, 1/1.05, 1.05, 1.1 .

So if you want to have 150% increase (e.g. a parameter with value 2 would be set to 5!) you'll have to  set the a to 1.5 indeed

**Comment by AnisPBPK** [comment]
@msevestre 
> So if you want to have 150% increase (e.g. a parameter with value 2 would be set to 5!) you'll have to set the a to 1.5 indeed


thank you very much it was so helpful! 
last question just to confirm that I understood correctly: for example, with an a= 1.5 so a sensitivity of -0.66 implies that a 150% increase of the parameters leads to a 66% decrease of the PK parameter value ? (or 6.6% decrease of the PK parameter value)
