### ISSUE TITLE
Lymph Flow in the Mucosa

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/Forum#522]
Can anyone explain why the plasma flow entering the mucosa is:
(Q_Duodenum*(1-HCT)**-L_Duodenum**)*Cp_SInt

And not:
Q_Duodenum*(1-HCT)*Cp_SInt

The parameter MassTransferIntestinetoMucosaPlasmaRate can be found in the intestine_pls_mucosa_pls neighborhoods.

The flow leaving the mucosa makes sense:
(Q_Duodenum*(1-HCT)-L_Duodenum)*Cp_Duodenum

Thanks in advance for the clarification

Paul

**Comment by PavelBal** [comment]
This is actually like this for all plasma flows from organ to venous blood:

`MassTransferOrgPl2BloodPool` : `(Q*(1-HCT)-Q_lymph)*C_pls`

`Q` refers to blood **inflow** from arterial blood into the organ. In large molecules model, it is assumend that a fraction of blood plasma is transported via lymph, so the flow of plasma out of the organ is lower by the lymph flow rate.

**Comment by prvmalik** [comment]
That's right for venous blood Pavel. But I am talking about Plasma flow into the Organ (and then subsequently entering the mucosa).

In this case the equivalent equation would be MassTransferBloodPool2OrgPl:
Q_org*(1-HCT)*Cp_Arterial

**Comment by Christoph27** [comment]
I think Paul is right. Normally, the plasma flow rate into the organ is  Q_org*(1-HCT), then the flow splits into the outflow of plasma (rate Q_org*(1-HCT) - Q_lymph) and lymph flow (rate Q_lymph) going back to venous blood via the interstitial space.. 
There seems to be a bug for the mucosa organs.

**Comment by PavelBal** [comment]
Ah ok. Well, the same here - the input into the mucosa is the blood flow rate of small intestine non-mucosa (therefore, the flow rate with which arterial blood enters non-mucosal SI) minus the lymph flow of non-mucosal SI.

**Comment by prvmalik** [comment]
The reference to lymph flow is specifically to the second neighbor (the mucosa) and not the first neighbor (non-mucosal small intestine).

![lymph](https://user-images.githubusercontent.com/29066045/81417428-2e95ca80-9119-11ea-8a32-c21caa8ab82f.JPG)

**Comment by PavelBal** [comment]
> The reference to lymph flow is specifically to the second neighbor (the mucosa) and not the first neighbor (non-mucosal small intestine).

Right... Weird.

**Comment by Christoph27** [comment]
As said above, it is a bug. I made a bug report (#1478).
Good catch, Paul!

**Comment by Yuri05** [comment]
Closing in favor of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1478
