### ISSUE TITLE
help: why i can't show building block explorer in mobi?

### ISSUE THREAD

**Issue by GUTATA** [Open-Systems-Pharmacology/Forum#524]
I open the .pkml file using the File menu,it should show the building block explorer in left like photo 2.However ,my project can't show building block explorer ,like photo 1,it's  empty!what't should i do to solve this [problem?
[图片]

[图片]

**Comment by msevestre** [comment]
We cannot see your screenshots. Can you add them again?

**Comment by GUTATA** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael Sevestre"<notifications@github.com&gt;; 
发送时间: 2020年5月9日(星期六) 晚上10:24
收件人: "Open-Systems-Pharmacology/Forum"<Forum@noreply.github.com&gt;; 
抄送: "饭小诗"<913004516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Open-Systems-Pharmacology/Forum] help: why i can&#39;t show building block explorer in mobi? (#524)





 
We cannot see your screenshots. Can you add them again?

**Comment by GUTATA** [comment]
> 我们看不到您的截图。您可以再添加一次吗？
![e473fd84dade322c10fb3ce32aba952](https://user-images.githubusercontent.com/58537338/81476436-7ebd7b80-9244-11ea-886b-a03f2bd4a1ab.png)

 
![5415d0ac1d99f26b3cf8591b70f18cf](https://user-images.githubusercontent.com/58537338/81476408-5fbee980-9244-11ea-9206-8df6bb73d9f3.png)

**Comment by jzq90** [comment]
@GUTATA 
![图片](https://user-images.githubusercontent.com/58142266/81491387-b407af00-92c0-11ea-9c16-f3c7a1a58b1d.png)
单击图中标红的箭头

**Comment by GUTATA** [comment]
我整个building blocks都没有，所以更没有您所指的红色图标了......
你看我第一张截屏，我导入pksim的simulation以后，除了上面的栏目，下面全是一片空白。尝试过点上面栏目的view 中的 building block ，可是还是上面都没有。完全一片空白




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aaron Jiang"<notifications@github.com&gt;; 
发送时间: 2020年5月10日(星期天) 中午1:19
收件人: "Open-Systems-Pharmacology/Forum"<Forum@noreply.github.com&gt;; 
抄送: "饭小诗"<913004516@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Open-Systems-Pharmacology/Forum] help: why i can&#39;t show building block explorer in mobi? (#524)





 
@GUTATA
 
 单击图中标红的箭头

**Comment by jzq90** [comment]
> 
> 我整个building blocks都没有，所以更没有您所指的红色图标了...... 你看我第一张截屏，我导入pksim的simulation以后，除了上面的栏目，下面全是一片空白。尝试过点上面栏目的view 中的 building block ，可是还是上面都没有。完全一片空白

新建一个空白project也没有building block吗？

**Comment by GUTATA** [comment]
没有.....我试过直接在mobi中新建，PKsim导入，都是空白。如果您经常使用MOBI，我可以加您微信或是QQ吗？交流起来可以方便一些



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aaron Jiang"<notifications@github.com&gt;; 
发送时间: 2020年5月10日(星期天) 中午1:57
收件人: "Open-Systems-Pharmacology/Forum"<Forum@noreply.github.com&gt;; 
抄送: "饭小诗"<913004516@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Open-Systems-Pharmacology/Forum] help: why i can&#39;t show building block explorer in mobi? (#524)





  
我整个building blocks都没有，所以更没有您所指的红色图标了...... 你看我第一张截屏，我导入pksim的simulation以后，除了上面的栏目，下面全是一片空白。尝试过点上面栏目的view 中的 building block ，可是还是上面都没有。完全一片空白
  
新建一个空白project也没有building block吗？

**Comment by jzq90** [comment]
> 
> 没有.....我试过直接在mobi中新建，PKsim导入，都是空白。如果您经常使用MOBI，我可以加您微信或是QQ吗？交流起来可以方便一些
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Aaron Jiang"<notifications@github.com&gt;; 发送时间: 2020年5月10日(星期天) 中午1:57 收件人: "Open-Systems-Pharmacology/Forum"<Forum@noreply.github.com&gt;; 抄送: "饭小诗"<913004516@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [Open-Systems-Pharmacology/Forum] help: why i can&#39;t show building block explorer in mobi? (#524) 我整个building blocks都没有，所以更没有您所指的红色图标了...... 你看我第一张截屏，我导入pksim的simulation以后，除了上面的栏目，下面全是一片空白。尝试过点上面栏目的view 中的 building block ，可是还是上面都没有。完全一片空白 新建一个空白project也没有building block吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我也是新手，可以多多交流，微信：jzq9080949

**Comment by StephanSchaller** [comment]
OSP going international ;-)

**Comment by msevestre** [comment]
@GUTATA @jzq90  please be mindful that a goal of the forum is also to make sure that other users will be able to find answers to their questions by reading previous posts . Therefore, if possible, can you please stick to English as a language when answering or asking questions? Thanks for your understanding

**Comment by GUTATA** [comment]
@StephanSchaller  Lol  the importance of bilingualism

**Comment by GUTATA** [comment]
importance of bilingualism



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "esqlabs GmbH"<notifications@github.com&gt;; 
发送时间: 2020年5月10日(星期天) 晚上8:00
收件人: "Open-Systems-Pharmacology/Forum"<Forum@noreply.github.com&gt;; 
抄送: "饭小诗"<913004516@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Open-Systems-Pharmacology/Forum] help: why i can&#39;t show building block explorer in mobi? (#524)





 
OSP going international ;-)
