### ISSUE TITLE
tissue concentration

### ISSUE THREAD

**Issue by leeking-55** [Open-Systems-Pharmacology/Forum#525]
hello，everyone
I have some difficulties, i need your kindly help.
1.how to define blood flow limited and permeation limited partitioning in pK-SIM.
2.now I have experimental data on the distribution of rat tissues. Which module in the software should I use to optimize the model according to rat tissue data?
I really need your kindly help,
sincerelly,
leeking

**Comment by prvmalik** [comment]
1. PK-Sim/OSP models represent distribution mechanistically. Cellular permeability is calculated based on one of three algorithms that you can choose in the ADME tab of the Compound Building Block. Molecules with low cellular permeability will be permeability rate limited in their distribution, and molecules with high cellular permeability will be blood flow limited, generally speaking. Important determinants of cellular permeability are lipophilicity (logP), molecular weight, fraction unbound in plasma and acid-base status. 

![Compound Building Block](https://user-images.githubusercontent.com/29066045/81620902-fb726600-93ba-11ea-9abf-3dbbbcf54659.JPG)
![Building Block 2](https://user-images.githubusercontent.com/29066045/81620906-fdd4c000-93ba-11ea-8056-c15cfc50fb20.JPG)

2. When your simulation has been constructed, you will have an opportunity to 'Define Settings and Run.' Here, you can select relevant observable states in the model. You are likely interested in the concentration of the drug in the whole organ or perhaps only in the cellular space, depending on how your experimental data is measured. Below you will find an example of the observers for the intracellular concentrations in the kidney, as well as the concentrations in that whole organ/tissue.

![Picture3](https://user-images.githubusercontent.com/29066045/81621045-6a4fbf00-93bb-11ea-8227-7e7af62e4fc7.JPG)

These observers can be used to optimize chosen parameters in the 'Parameter Identification Tool.'

**Comment by leeking-55** [comment]
dear Paul:
I really appreciate your kindly and patiently comments, that's really helpful. But I have other questions, 
1.Is it possible to set different organs for blood flow limited or permeation limited partitioning，such as the brain is  permeation limited partitioning, and the live is  blood flow limited. what;s more, you said the molecules with low cellular permeability will be permeability rate limited in their distribution, and molecules with high cellular permeability will be blood flow limited, is there a boundary value.
2.Can the following option represent tissue-plasma partition coefficient


have a good day.
sincerelly'
leeking.







At 2020-05-12 07:14:27, "Paul Malik" <notifications@github.com> wrote:

PK-Sim/OSP models represent distribution mechanistically. Cellular permeability is calculated based on one of three algorithms that you can choose in the ADME tab of the Compound Building Block. Molecules with low cellular permeability will be permeability rate limited in their distribution, and molecules with high cellular permeability will be blood flow limited, generally speaking. Important determinants of cellular permeability are lipophilicity (logP), molecular weight, fraction unbound in plasma and acid-base status.




When your simulation has been constructed, you will have an opportunity to 'Define Settings and Run.' Here, you can select relevant observable states in the model. You are likely interested in the concentration of the drug in the whole organ or perhaps only in the cellular space, depending on how your experimental data is measured. Below you will find an example of the observers for the intracellular concentrations in the kidney, as well as the concentrations in that whole organ/tissue.

These observers can be used to optimize chosen parameters in the 'Parameter Identification Tool.'

**Comment by jzq90** [comment]
> is there a boundary value

Sorry to cut in.
I think the boundary would be different for different tissue because of the different blood flow rates and surface areas. Also, I think the boundary is just a vague saying for classification. In most situations, the partition depends on both permeability and blood flow rate. 
In PBPK, the model will calculate the partition process based on permeability and blood flow rate with pre-defined equations, then present the final results no matter it is perfusion-limit or permeability-limit or both-limit.
If the brain belongs to permeation limited partitioning, there has to be a mechanism under this phenomenon, such as the low surface area in BBB, low paracellular permeation, efflux transporter.
Find this mechanism, input to the model, you can simulate the permeation behavior in the brain.
