### ISSUE TITLE
How to add a time dependency to B/P partition coefficient

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#526]
Dear all,

In a model for a small molecule I would like to make the blood/plasma partition coefficient change with time. I found the parameter in MoBi (Spatial structure --> MoleculeProperties) and I tried to make the parameter as a state variable. (I will refer to the B/P partition coefficient as K)
If I set up the time dependency as a fixed number (e.g. dK/dt=2) everything works file but if I try to do something more complex, I don't manage to make it work.

1) How can I set up the state variable equal to a parameter? So an equation like dK/dt=a, in which I could estimate the variable “a”? I created a parameter in the MoleculeProperties but MoBi does not allow me to reference it in the formula (I have no idea why…).
2) If I try to reference the B2P coefficient in the equation of the state variable (to get something like dK/dt=a*K) MoBi gives an error message mentioning that the reference to the parameter cannot be found

Many thanks for your help! Below you have a screenshot of the way I tried to set up the parameter
(FYI, there are only test in order to implement a better equation, so do not worry if these parameterizations do not make sense).

Donato

![image](https://user-images.githubusercontent.com/11489621/81818100-e0743300-952d-11ea-9052-d679e820da0d.png)

**Comment by Yuri05** [comment]
Parameters defined in global or local molecule properties must be referenced with the keyword MOLECULE. This should solve the problem in 2. The problem in 1 I didn't fully understand, but maybe it has the same reason(?)
![grafik](https://user-images.githubusercontent.com/25061876/81826790-6bf2c180-9538-11ea-85c0-2eaabb3aea0e.png)

**Comment by teutonicod** [comment]
Thanks @Yuri05 , indeed this solved the second issue. By the way, it is a little weird that a reference directly created by MoBi with a drag-and-drop is then not correct... shouldn't this reference with the MOLECULE naming done directly?

About my issue 1) I created a parameter called "test" (you have it in the screenshot below)
![image](https://user-images.githubusercontent.com/11489621/81839090-5fc23080-9547-11ea-994f-c7dc4d5de80f.png)

If I try to drag this parameter in the formula, MoBi does not allow me to do it, even if I have it available on the right of the formula

![image](https://user-images.githubusercontent.com/11489621/81839258-98620a00-9547-11ea-8e25-d1d23ba0f0e2.png)

Donato

**Comment by StephanSchaller** [comment]
> ... shouldn't this reference with the MOLECULE naming done directly?

Well, technically, moby could ask you if you want the one (specific) or the other (generic), but doesn't know by itself, because depending on the use case, both can be correct. 
It wouldn't be that trivial to implement. But you may add it as a feature request.

Not sure why the drag&drop doesn't work here. If you create an entry in the list to the left with the "+" and define "test" manually, does it work if you create the simulation?

**Comment by Yuri05** [comment]
>If I try to drag this parameter in the formula, MoBi does not allow me to do it, even if I have it available on the right of the formula

Could reproduce it. Seems that MoBi does not allow to drag&drop an organism parameter into the formula (or RHS formula) of a global molecule parameter. I don't see a reason for that and would consider it as a bug.

**Comment by teutonicod** [comment]
Hi @Yuri05, thanks a lot, indeed it looks like a bug! I managed to drag the parameter B2P, so it seems that parameters already created can be added. Do you have any idea for a workaround waiting for the bug to be solved? Shall I make a bug report?

@StephanSchaller 

> Well, technically, moby could ask you if you want the one (specific) or the other (generic), but doesn't know by itself, because depending on the use case, both can be correct.

Not sure what you mean (but you know, MoBi has still many unsolved mystery for me! ). Can these two ways of referencing be correct? from a (naive) user point of view, if I would like to reference a parameter, I would expect anyway that the reference automatically created should be correct. 
(If you compare it to PK-Sim, it would be like if you drag the observations in the simulation and then when running the simulation PK-Sim would complains that the reference to the observation is not correct).

**Comment by Yuri05** [comment]
>Do you have any idea for a workaround waiting for the bug to be solved? 

Add ANY reference and edit it manually (path, alias)

>Shall I make a bug report?

sure.
