### ISSUE TITLE
Tissue concentration when a binding partner is present

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#527]
Dear all,

I recently realized something in PK-Sim which can be misleading for a new user (and for older ones as well!). When we add a binding partner expressed in an organ, and then we simulate the concentration in this tissue (with the observer **Whole organ**), PK-Sim will only show the concentration of the free drug, and not the concentration of the drug bound to the binding partner. This is somehow logical, since the two entities are different (free and bound molecule) but in most cases, when we have tissue concentrations, we have the total amount of drug. 
If I got it right, I think that we should clearly show this in PK-Sim, since this can be easily solved with an observer (this is how I did it). So I think that we should systematically add this observer so that somehow it appear clear that the total concentration does not reflect the drug bound to something.

I found this in the case of binding partners, but if you have other examples, please share!
What do you think?

Best,

Donato

**Comment by StephanSchaller** [comment]
I agree, but it may not be that easy to create this as a generic observer, as the binding partners may have different names... @Yuri05 ideas?

**Comment by StephanSchaller** [comment]
Maybe if substrings are allowed for tags... but this may cause other problems. 

@teutonicod maybe you can create a feature request for this in the PK-Sim repo?

**Comment by yishuanwu** [comment]
I did fall into this trap... It took me months before I realize what is going on in a moment of serendipity

**Comment by PavelBal** [comment]
Well I think it should be possible to implement it in PK-Sim, as PK-Sim knows what are the complexes at the stage of model creation.

**Comment by teutonicod** [comment]
Thanks to everybody for your feedback!

@msevestre @Yuri05, it seems that I was not the only one falling into this trap. Do you think that it would be possible to implement an observer to account for tissue concentration also including the target binding? If needed, we can discuss about this!

Thanks,

Donato

**Comment by Yuri05** [comment]
>Do you think that it would be possible to implement an observer to account for tissue concentration also including the target binding?

@teutonicod If you think it would be helpful - please create a feature request in PK-Sim ;)
