### ISSUE TITLE
Isn't there a bladder compartment in the default PK-Sim

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#529]
I can't found a bladder compartment in the animal or human model created by PK-Sim.

**Comment by prvmalik** [comment]
There is no bladder compartment, but there is a urine compartment.

**Comment by jzq90** [comment]
> 
> 
> There is no bladder compartment, but there is a urine compartment.

Thanks, I notice that. But the urine concentration cannot represent the concentration in bladder interstitial or intracellular in many cases.

**Comment by StephanSchaller** [comment]
Yes, urine only represents bladder lumen.

**Comment by Christoph27** [comment]
The "Urine" compartment in PK-Sim should be viewed as compartment collecting the amount of drug excreted by the kidney. It has a static, artificial  volume of 1 L and can thus not be used to e.g. simulate urine concentrations. Thus the "Urine" compartment does not represent the bladder lumen in a physiological sense as other compartments do represent things in PK-Sim but only in the sense that drug wich is excreted by the kidney flows to the the bladder lumen.

**Comment by StephanSchaller** [comment]
Yes, I should have put "represents" in exclamation marks ;-)

Outupts that make sense for urine are "Amount" and "Fraction excreted to urine".

**Comment by jzq90** [comment]
Yes, Yes. @StephanSchaller @Christoph27 
But I'm not interested in the concentration in urine. I'm interested in the concentration in the bladder interstitial and intracellular in a case of bladder cancer.
I wonder if I can make a request for adding a bladder compartment in PK-Sim including organ weight, volume, blood flow rate etc.

**Comment by Yuri05** [comment]
>I wonder if I can make a request for ...

@jzq90 You can always make a request :) If and when it will be implemented depends on the ratio of effort and community interest.
