### ISSUE TITLE
Simulating multiple metabolites generated from 1 compound in PK Sim

### ISSUE THREAD

**Issue by tchiu1001** [Open-Systems-Pharmacology/Forum#53]
Hi, 

I am interested in simulating a compound(A) that undergoes hepatic metabolism into 2 distinct metabolites (B&C) at different rates of formation using PK Sim. In PK Sim, it only allows me to pick one form of metabolite after I input the metabolizing enzyme for the parent compound. Also, the metabolism of parent compound in the input is an overall rate. I want to break it down to two different rates for the 2 metabolites. For example, 2/3 of metabolism goes to B and 1/3 goes to C. 

Is there a way to pick more than 1 metabolite from parent compound in PK Sim? Or is this something that requires more complex input using MoBi. 

I would also like to define how the metabolites are being eliminated to get a simulated PK profiles of parents and metabolites together. 

Any help is greatly appreciated.

Thanks

**Comment by msevestre** [comment]
Hi @tchiu1001 ,

This is a standard workflow that is supported out of the box by `PK-Sim`. 

This can be achieved using for example `Intrinsic Clearance` processes as opposed to a `Total Hepatic Clearance` process. 
![image](https://user-images.githubusercontent.com/1041237/28746041-9e262692-7452-11e7-8def-a6d9e66da5d3.png)

In your case, you will have to identify which enzyme is responsible for the resp. metabolization process. These enzymes will also need to be available in the individual you are using in your simulation. After that, you won't have any problem defining the connection between the parent compound and the two metabolites. 
![image](https://user-images.githubusercontent.com/1041237/28746071-35beb294-7453-11e7-9ce7-16118236fec5.png)

Don't forget to check the reaction diagram in the simulation to make sure that the created reaction network matches your expectations.

![image](https://user-images.githubusercontent.com/1041237/28746077-50866af4-7453-11e7-817e-e939eaad8a7b.png)

Cheers,

**Comment by tchiu1001** [comment]
Thanks Michael, for the very detailed explanation. 

The 2 metabolite formation works when they are being produced by two different CYP enzymes. In my situation, they are both being formed by the same CYP (for example, CYP3A4). In this case, how do I tell PK-sim to produce both metabolites B and C from one CYP3A4 reaction and also defining different rate of formation for the two metabolites. 

Thanks

**Comment by msevestre** [comment]
Hi @tchiu1001,

Interesting. This workflow is not supported by the PK-Sim out of the box. Right now,  only one metabolite can be created  by a metabolization process. That being said, and depending on what you are trying to achieve, you could do the following:

1. Create two enzymes CYP3A4-1 and CYP3A4-2 and define your processes as two independent processes. This will work great if your processes are only first order process and / or the actual enzyme concentration is not a limiting factor of the underlying process .

2. Alternatively you could do as in 1., Export to MoBi and modify the reaction building block to have the second reaction use the same enzyme as the first one.

What are you trying to model? Are you worried about inter-species extrapolation etc.?

**Comment by tchiu1001** [comment]
Ok I will give it a try. Thanks

By the way, are there courses which we can sign up to learn more about how to operate PK-sim and Mobi at an advance level?

**Comment by msevestre** [comment]
@tchiu1001 
Did you manage to get it working?

I am working for [Design2Code Inc](www.design2code.ca). We offer personalized (individual/group) training in PK-Sim and MoBi. Contact us via the website if you are interested.

**Comment by msevestre** [comment]
@tchiu1001 Let us know if you need more help here. Cheers
