### ISSUE TITLE
MoBi does not allow committing changes in organ protein expression

### ISSUE THREAD

**Issue by yishuanwu** [Open-Systems-Pharmacology/Forum#532]
Hi, 

I have a simulation in MoBi for which I'd like to optimize the relative tissue expression (M_0) of the protein binding partner of a TMDD model. I am able to modify the parameter in the simulation and the simulation ran. However, when I attempt to commit the changes in MoBi by updating the below screenshot item, my simulation gives me an error (second screenshot) about parsing the 'M_0':

![image](https://user-images.githubusercontent.com/13445680/82403746-91e2ff00-9a2d-11ea-8f4c-122817047ef9.png)

![image](https://user-images.githubusercontent.com/13445680/82404077-54cb3c80-9a2e-11ea-81d2-7fc0bf5c889a.png)

Where else should I modify the relative expression of the protein to avoid the error message?

Thanks again!
Shirley

**Comment by PavelBal** [comment]
You should not optimize the "M_0" parameter but "Relative expression (normalized)" of the molecule in the respective compartment.

**Comment by Yuri05** [comment]
What is "M_0"-parameter?

**Comment by PavelBal** [comment]
@Yuri05 

![image](https://user-images.githubusercontent.com/25903040/82436048-7d3a5180-9a95-11ea-951c-9cb4582d51b8.png)

**Comment by Yuri05** [comment]
Well, in a "standard" model it's possible to optimize start amounts of proteins and commit the optimized values back into building blocks, so here the problem seems to be **project-related**.
[DummyModel_OptimizeStartAmount.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/4656279/DummyModel_OptimizeStartAmount.zip)

![grafik](https://user-images.githubusercontent.com/25061876/82437583-f044c780-9a97-11ea-82e0-229237f2f29d.png)

**Comment by yishuanwu** [comment]
Thank you for both of your help. 

I did not realize that I can conduct parameter identification for the start amount in MoBi and was doing the optimization manually before. 
When I do it by parameter identification, transferring to the simulation, and then commit the changes, I did not run into the error -- so maybe I was modifying the parameter at the wrong location? I went under Parameter > Organism > Individual Organ > Interstitial, and modify the M_0 from there.

**Comment by Yuri05** [comment]
>Is a new release being planned?

Yes. For now you can use the [portable version of MoBi9](https://ci.appveyor.com/api/buildjobs/2ktan3rh0auhiqqm/artifacts/mobi-portable-setup.zip) (not released yet) to open the file.

**Comment by yishuanwu** [comment]
I am sorry to be a bother. It's telling me "Unable to load DLL 'OSPSuite.Func.ParserNative.dll": The specified module could not be found. (Exception from HRESULT: 0X8007007E)"

Pavel did say that I should not optimize the M_0 but should normalize the relative expression-- I finally found that parameter. It's under the parameter tab next to the initial value tab. Changing the relative expression changes the start amount, while changing the initial value M_0 does not change the start amount in the parameter tab, even though they both affect the current simulation. Therefore my issue is fixed. Thanks!

Shirley
