### ISSUE TITLE
Lipophilicity in PKsim

### ISSUE THREAD

**Issue by AnisPBPK** [Open-Systems-Pharmacology/Forum#534]
Hi,

Can someone let me know if the lipophilicity of the compound and lipophilicity (exprement) in the microsomes used to calculate specific clearance in Pk-sim should be the same value ? 
because i want to optimaze my lipophilicty and i don't know if i should also change the lipophilicity (exprement).

thank you in advance

**Comment by prvmalik** [comment]
The short answer is yes - the two values should be the same - for scientific consistency and reporting. 

But there are no technical consequences to having a different value locally within the experiment.

**Comment by AnisPBPK** [comment]
> The short answer is yes - the two values should be the same - for scientific consistency and reporting.
> 
> But there are no technical consequences to having a different value locally within the experiment.

Thank you for your reply prvmalik
