### ISSUE TITLE
Metabolism and bile clearance

### ISSUE THREAD

**Issue by leeking-55** [Open-Systems-Pharmacology/Forum#535]
hi, everyone.I encountered some problems and need your help.The drug is metabolized by CYP3A4 by more than 80%, and the unchanged drug excretionis via the urine and bile is  about 2.5%. In the software, I define metabolism. How to define bile excretion? Whether based on unchanged drug  via bile to defined.
![image](https://user-images.githubusercontent.com/61484279/82998599-85b4fe00-a03a-11ea-926a-2f99147e4615.png)
![image](https://user-images.githubusercontent.com/61484279/82998692-9cf3eb80-a03a-11ea-8337-b6ad013a7534.png)
I really need help.
best wishes,
leeking.

**Comment by jzq90** [comment]
Maybe you can use the amount in bile (2.5% of the dose)/AUCplasma to get bile clearance

**Comment by leeking-55** [comment]
Thanks for your answers, but I am still a little confused. Do you mean that I only need to focus on unchange drug? The excretion via bile marked with [14C ] is about 60%, don't I need to focus on this?
best wishes,
leeking










At 2020-05-27 16:58:09, "Aaron Jiang" <notifications@github.com> wrote:

Maybe you can use the amount in bile (2.5% of the dose)/AUCplasma to get bile clearance

**Comment by StephanSchaller** [comment]
If you change the value above which you marked with a yellow questionmark, to sth else than zero you have biliary clearance of the compound the process was defined for.

If you want to account also for the metabolite, you first have to define a metabolite as compound and link it as metabolite to the enzymatic metabolism of the parent and then define biliary clearance for the metabolite as well.

You can then use the simulation output "fraction excreted to bile" to check how much of the dose from parent and metabolite ended up in bile...

**Comment by leeking-55** [comment]
thanks for your kindly help
have a good day,
leeking.













At 2020-05-28 04:10:23, "esqlabs GmbH" <notifications@github.com> wrote:

If you change the value above which you marked with a yellow questionmark, to sth else than zero you have biliary clearance of the compound the process was defined for.

If you want to account also for the metabolite, you first have to define a metabolite as compound and link it as metabolite to the enzymatic metabolism of the parent and then define biliary clearance for the metabolite as well.

You can then use the simulation output "fraction excreted to bile" to check how much of the dose from parent and metabolite ended up in bile...
