### ISSUE TITLE
Virtual Population BE

### ISSUE THREAD

**Issue by divyenshah** [Open-Systems-Pharmacology/Forum#540]
Greetings All!
I am new to PK-Sim and MoBi. I was able to complete part up to simulation and then parameter identification. 
Could someone please guide me how to perform population PK and then a virtual BE?

Regards,
Divyen Shah

**Comment by StephanSchaller** [comment]
There is an upcoming webinar, where you will also learn about population simulations and other basics:
https://www.eventbrite.com/e/webinar-page-2020-pbpk-qsp-with-pk-sim-mobi-osp-suite-registration-93720625915

(but it does not include BE, explicitly).

Best,
Stephan

**Comment by jzq90** [comment]
1. Create a population
2. Simulate the PK profile
3. Calculate BE with predicted data by traditional method

**Comment by divyenshah** [comment]
Thank you everyone.
