### ISSUE TITLE
How to fill in the parameter values for gastrointestinal permeability

### ISSUE THREAD

**Issue by Wenjing1018** [Open-Systems-Pharmacology/Forum#541]
![image](https://user-images.githubusercontent.com/63133525/83937622-f9a49280-a800-11ea-8139-cfbf9998e804.png)
 I want to know which part of the PK-Sim these two parameters should be filled in？

**Comment by HenrikCordes** [comment]
Hi @Wenjing1018 ,

I think the it would be appropriate to do this in a simulation:
![image](https://user-images.githubusercontent.com/4817133/83938815-ea5d1f00-a7d7-11ea-8cf7-343eb39306cf.png)

Set the left drop down menue to "advanced" and you can modify the organ specific permeability. Note that you have access to the permeability into both directions  Int->cell & cell->int, as well as the permeability on the apical side (mucosa) and the endothel.

In PK-Sim the passive permeability is dependent on the compund properties such as LogP and pka. This means if the membrane composition and compartment pH does not change (which is assumed for all organs) the permeability should be the same in all organs. 
The appearent permeability however includes passive and active transport processes and thus,  different permeabilities might be a hint for transporter activities. 

It might be helpfull if you state also the background regarding your question. 
Why do you want to change these parameters? Are these experimental values? Does this come from another model?

Kind regards,
Henrik

**Comment by Wenjing1018** [comment]
Hi，@HenrikCordes,thank you for your reply!
 But I also have some problems.As you said，I have access to the permeability into both directions Int->cell & cell->int, as well as the permeability on the apical side (mucosa) and the endothel.But in this case, should I choose to change which of these three options for basolateral small intestinal permeability?
Kind regards,
Wenjing Pan

**Comment by HenrikCordes** [comment]
Dear @Wenjing1018,

again, it is difficult to tell...

Without a minimum of background information about your project and why you want to change the default parameter it is not possible to give a reasonable recommendation beyond the technicalities as was done in my previous post.

Why do you want to change this parameter? What is the problem exacly? 
What hypothesis are you following here and on which information is this based? 
Where do your posted values come from, what was done to derive them? Why do you think it would be a good idea to use them?

Kind regards,
Henrik

**Comment by Wenjing1018** [comment]
Dear @HenrikCordes,
The reason I changed it was because the parameter value of a new article was changed, So I want to understand the parameter value.Thank you for your reply!
Kind regards,
Wenjing Pan

**Comment by jzq90** [comment]
How did you get these two parameter values? From literature? Or by a special assay？

**Comment by Wenjing1018** [comment]
Dear @jzq90
these two parameter values come from  a special assay,but the values are optimized by PK-Sim,so I just want to know  Where to change the corresponding value?
Kind regards,
Wenjing

**Comment by jzq90** [comment]
You don't tell us the meaning of Basolat. small. int. perm or what's the special assay? How could somebody know where to put it without knowing what it is.
I know it is the abbreviation of basolateral small intestinal permeability. But this is just a name.

**Comment by Wenjing1018** [comment]
Dear jzq90, 
This picture shows the meaning of these two parameter values,and the assay‘s name is "A Comprehensive Whole‑Body Physiologically Based Pharmacokinetic 
Drug–Drug–Gene Interaction Model of Metformin and Cimetidine 
in Healthy Adults and Renally Impaired Individuals". The relevant information is shown in the supplementary file.
![image](https://user-images.githubusercontent.com/63133525/84138766-6af27880-aa81-11ea-82e8-23855b24f752.png)

**Comment by NinaHanke** [comment]
Dear Wenjing1018, 
https://github.com/Open-Systems-Pharmacology/Metformin-Model
I hope this answers your questions. 
Kind regards, 
Nina
