### ISSUE TITLE
PK-Sim Default Kdeg parameters for mechanism based inhibition

### ISSUE THREAD

**Issue by georgeuf** [Open-Systems-Pharmacology/Forum#546]
Hi there

Could you let me know how to check the default value in PK-Sim regarding the  Kdeg parameter for mechanism-based inhibition?I could not find it anywhere. Thanks so much.

**Comment by georgeuf** [comment]
Ok. Thanks.

**Comment by msevestre** [comment]
@sfrechen Is there such a parameter in PK-Sim?

**Comment by georgeuf** [comment]
Michael Sevestre <notifications@github.com> 于2020年6月30日周二 上午10:08写道：

**Comment by StephanSchaller** [comment]
There is a kdeg for the enzyme turnover which is calculated based on the enzyme (in red):
![image](https://user-images.githubusercontent.com/25477643/86145255-01e9a800-baf7-11ea-83e8-c7caf9097c79.png)

The kdeg you are referring to is likely the "kinact" (in green) in the above slide?

You can edit this one when selecting your interaction:
![image](https://user-images.githubusercontent.com/25477643/86145402-2e052900-baf7-11ea-8ad1-4826a8c7a043.png)

The "kdeg" from enzyme turnover can be changed indirectly by changing the half-live values in the expression tab:
![image](https://user-images.githubusercontent.com/25477643/86145561-5ab94080-baf7-11ea-899d-6b96e9699d7e.png)

**Comment by georgeuf** [comment]
The Kdeg i referred to is not "kinact", but rather the enzyme turnover you
mentioned in your #2 point. Thanks for the clarification.  In this case,
Kdeg=0.693/(T1/2). Since T1/2 can be modified, so is Kdeg.
Thank you. Regards

esqlabs GmbH <notifications@github.com> 于2020年6月30日周二 上午11:30写道：
