### ISSUE TITLE
Not able to customize Gastric Emptying Time in Population

### ISSUE THREAD

**Issue by arketkar** [Open-Systems-Pharmacology/Forum#547]
I am looking to customize the mean and standard deviation for the Gastric Emptying Time in a Population.
I am not able to see any option to modify the Gastric Emptying Time while and after creating a population. After initiating a 'Simulation' I am able to see the Small and Large Intestinal Transit Times under the Hierarchy view, however Gastric Emptying Time is not seen.

Snapshots enclosed for your reference.
![Small Intestine_Hierarchy view](https://user-images.githubusercontent.com/32693494/84490907-6b795200-acc1-11ea-91be-2c3ed66d1ecc.JPG)
![Population_User Defined Variability](https://user-images.githubusercontent.com/32693494/84490919-6caa7f00-acc1-11ea-98aa-aa59b2731162.JPG)
![Stomach_Hierarchy view](https://user-images.githubusercontent.com/32693494/84490922-6d431580-acc1-11ea-8b50-38c67173915f.JPG)

Your help will be appreciated.

Thanks.
Anant

**Comment by arketkar** [comment]
Hi Michael,

Thanks for your reply. Sure I’ll do that in future. I am new to github.

Have you transferred my question there? I am not able to track it. Do I need to post it again in the Forum?

Appreciate if you could please guide me on how to post a question in the Forum.

By the way, this is a great platform and hats-off to the entire team for your endless efforts and contributions to this branch of science!!!

Thanks and regards.
Anant

**Comment by AndreDlm** [comment]
Dear @arketkar ,

the gastric emptying time be found under the distribution tab of a population: 
![Annotation 2020-06-16 092635](https://user-images.githubusercontent.com/26541603/84744403-7ed33880-afb3-11ea-9d45-247f16d30066.png)

If you want to have a user-defined distribution for that parameter, you could export your population to csv (via the context menu of the population). In the csv-file you will find a column listing the gastric emptying time for each individual of you population:
![Annotation 2020-06-16 093215](https://user-images.githubusercontent.com/26541603/84745031-4849ed80-afb4-11ea-920f-7900009fc42d.png)

Replace this column with the values you want to have (you could simply create a user-defined distribution using your desired mean and standard deviation in e.g. R using `rnorm(n,mean,sd)`) and import the new population as follows: 
![Annotation 2020-06-16 093427](https://user-images.githubusercontent.com/26541603/84745242-9828b480-afb4-11ea-8243-36d3ca826b63.png)

Good luck!
André

**Comment by arketkar** [comment]
Thank you so much Andre.
