### ISSUE TITLE
fraction dissolved invivo and fraction dissolved invitro - IVIVC

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#55]
Hi

I am trying to build a PB-IVIVC model using PK-sim, and was successful with it.
Now I am trying to compare with IVIVC model developed using WinNonlin. I was thinking of using fraction dissolved in-vivo and fraction dissolved in-vitro as one of the comparisons between PB-IVIVC and IVIVC. 
Is there a way for me to extract this information from PK-sim?
please advise.

**Comment by KatrinCoboeken** [comment]
Within the lumen there exist an observer "fraction dissolved" which can be selected vi "Define selections and run". This is the simulated in-vivo fraction dissolved. The fraction dissolved depends strongly on the formulation you selected for your simulation.

**Comment by moulirc** [comment]
Hi Katrin,

I really appreciate your help and thanks.
Regards

Mouli
