### ISSUE TITLE
Exporting to Mobi and PK-Sim Formulation Questions

### ISSUE THREAD

**Issue by Ijustwantohide** [Open-Systems-Pharmacology/Forum#550]
I'm relatively to new to PKSim and Mobi so these may be pretty basic questions...

1) On the available PK-Sim models, how come some are available to send to Mobi while others aren't? What factors does it depend on?

2) On PK-Sim demonstrations, what formulation can be best used for oral tablet and capsule dosage forms? I noticed "dissolved" is commonly used but I'm also a little confused on if that should only be used in solution and not solid dosage forms.  If we want to account for bioavailability of a tablet, would it be recommended to use weibull function instead?

**Comment by regulus92** [comment]
1. Simulations in PK-Sim should be available to send to Mobi. Can you describe your question more specifically?
2. Please refer to https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-formulations.
I think Weibull function could give a satisfactory fitting to release features of most preparations.

**Comment by msevestre** [comment]
@Ijustwantohide I second @regulus92 I am not quite sure what you mean. 
Please reopen if you need more help

**Comment by PavelBal** [comment]
The only scenario when a simulation cannot be exported to MoBi is when the model has been re-imported from MoBi. So:

1) Model developed in PK-Sim
2) Model sent from PK-Sim to MoBi (e.g. for incorporation of new PD effects)
3) Model sent from MoBi to PK-Sim e.g. for Population Simulation.
