### ISSUE TITLE
warning message for absorption 

### ISSUE THREAD

**Issue by AnisPBPK** [Open-Systems-Pharmacology/Forum#553]
[](url)
![Capture 2](https://user-images.githubusercontent.com/64975824/85048319-746f9500-b193-11ea-9287-ab2f2fcdcf8e.PNG)
Hellon ervry one, i have this warning message on PKsim (it say : absorption seems to be incomplete or absorption precess is not finiched and that we should compared these PK parameters with IV simulation)  can someone tell me it's due to what ? and how to remove it ? 
Thak you !

**Comment by prvmalik** [comment]
For non-compartmental analysis, volume of distribution (Vd) can only be calculated on an IV profile or in cases where bioavailability (F) is equal to 1.

For oral administration, what is calculated is Vd/F. If F is less than 1 (i.e. absorption process incomplete), the warnings remind you that the estimates for Vd may be inflated.

**Comment by AnisPBPK** [comment]
Thank you very match @prvmalik !
so it juste a reminder for the value of these parameters that not influence the model or the validation of model ?

> For non-compartmental analysis, volume of distribution (Vd) can only be calculated on an IV profile or in cases where bioavailability (F) is equal to 1.
> 
> For oral administration, what is calculated is Vd/F. If F is less than 1 (i.e. absorption process incomplete), the warnings remind you that the estimates for Vd may be inflated.

**Comment by prvmalik** [comment]
Yes the values in the 'PK-Analyses' are calculated from the simulated PK profile after it has finished running. The values have no impact on or relevance to the model itself.

**Comment by AnisPBPK** [comment]
> Yes the values in the 'PK-Analyses' are calculated from the simulated PK profile after it has finished running. The values have no impact on or relevance to the model itself.

ok, thak you very match it was so helpful !
