### ISSUE TITLE
A strange PK profile of an oral formulation

### ISSUE THREAD

**Issue by wangwei1619** [Open-Systems-Pharmacology/Forum#554]
Hi, all

Recently I have recived a PK result of a single administraiton of an oral formulation with, like this:
![image](https://user-images.githubusercontent.com/54141158/85105357-f798f580-b23c-11ea-997d-ff6ea1dc9cca.png)
The absorption peak which should exist in first several hours seems disappeared  in this figure. However, the first data point was measured at 0.5 h, which may result in absorption peak not recorded.
I think the figure is strange because drug is meatabolized quickly according to the profile before 15 h, but curve after 20 h seems to say it is not. Besides, how is the second peak formed, by enterohepatic circulation? Is it normal for a peak caused by enterohepatic circulation to be so high?
And is there any else potential reason to explain this phenomenon?

Thanks for comments.

**Comment by tobiasK2001** [comment]
Yes, indeed this looks strange and leaves more questions than answers. From the time course it looks like we have strong colonic absorption here.  I guess we are in human? EHC peaks tend to occur after the first meal after dose e.g. 3-4 hours after last dose. Tablets are immediate release or controlled release? Compound is BCS 2 or 4?

**Comment by wangwei1619** [comment]
Oh, I should say this is data from beagle dogs. The chemical is lycopene, but it is formulated with PEG so that solubility is exceeding 800 ug/mL and it dissolves fast, but I don't know the exact permeability because I didn't receive such data. Is there any example of formulation behaving like this?

**Comment by RobinM92** [comment]
If it is lycopene, are both the trans and cis form measured or only one 
of the two? As the cis-isoform accumulates into micelles in vivo.

Kind regards,

Robin

Dr. ir. Robin Michelet
Senior scientist

Freie Universitaet Berlin
Institute of Pharmacy
Dept. of Clinical Pharmacy & Biochemistry
Kelchstr. 31
12169 Berlin
Germany
Phone:  + 49 30 838 50659
Fax:      + 49 30 838 4 50656
Email: robin.michelet@fu-berlin.de
www.clinical-pharmacy.eu
REGISTER NOW!  9th International Microdialysis Symposium; early bird: -15 May 2020

**Comment by wangwei1619** [comment]
Hi, Robin

In fact, I don't know which type this lycopene is of. We have suspened this modeling work since we don't have enough supporting data. But, I still think this is a interesting example that I can keep in mind.

Thanks for your help.

Best regards,
Wamg Wei

**Comment by Yuri05** [comment]
@wangwei1619 Closing. Please reopen if there are still any unanswered questions.
