### ISSUE TITLE
Data of few individuals missing in PK-Analysis after DDI population simulation (PK-Sim 8)

### ISSUE THREAD

**Issue by arketkar** [Open-Systems-Pharmacology/Forum#557]
Hi GitHub members,

I have set-up a Midazolam + Rifampicin DDI model in PK-Sim version 8, and a simulation set-up with a population of 'N = 25'.

In one of the simulation scenarios, I am getting 'NaN' as an output of as may as 18 out of 25 individuals in a .csv file exported by clicking on 'PK-Analysis to csv' button.

I am enclosing a zip file of .pksim5 project file for that project along with the .xlsx files of .csv PK-Analysis files. It has following simulations with dosing summary and outcomes. Same human population was used in all the following simulations.

**Simulation-1. 'Kharasch'04_MDZ+RIF_i.v._PopPK'**
_Dosing:_ Midazolam 1 mg i.v. on Day 1 and Day 7, and Rifampicin 600 mg p.o. from Day 2 to Day 7
_PK-Analysis csv file:_ No issues. Data generated for all Individuals.

**Simulation-2. 'Kharasch'04_MDZ+RIF_p.o._PopPK'**
_Dosing:_ Midazolam 3 mg p.o. on Day 1 and Day 8, and Rifampicin 600 mg p.o. from Day 2 to Day 7
_PK-Analysis csv file:_ Issues in observed data. Data not generated for 18 out of 25 individuals for 'AUC_inf_t1' and 5 out of 25 individuals for 'AUC_inf_tLast'. Mean values appearing after clicking the button 'Show PK-Analysis' for Midazolam are not matching with that of the csv files. 

**Simulation-3. Kharasch'04_MDZ+RIF_p.o._PopPK_without RIF'**
_Dosing:_ Midazolam 3 mg p.o. on Day 1 and Day 8, and No Rifampicin dose
_PK-Analysis csv file:_ No issues. Data generated for all Individuals.

**Questions-**
**a.** Why the data for so many individuals is missing (NaN) in case of Simulation-2, where Midazolam and Rifampicin are dosed? Even the data for Cmax is also missing to my surprise.

**b.** The same simulation when run without Rifampicin dosing (Simulation-3), shows output for all the individuals. Same is the case when Midaolam is dosed by i.v. route along with Rifampicin p.o. (Simulation-1), where data for all individuals is generated. Why the data for even for the first dose of Midazolam without any pre-dose of Rifampicin is not generated in Simulation-2? 

**c.** Why the mean value of a parameter appearing in Simulation-2 is different than the mean of values in a .csv file?

Appreciate if someone can help me understand the reasons behind such observations. I am facing such problem with some other simulations as well. This is just one example I am sharing as a case.

Thanks and regards.
Anant

[Kharasch'04_MDZ+RIF_i.v._PopPK-PK-Analyses.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/4825086/Kharasch.04_MDZ%2BRIF_i.v._PopPK-PK-Analyses.xlsx)
[Kharasch'04_MDZ+RIF_p.o._PopPK-PK-Analyses.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/4825088/Kharasch.04_MDZ%2BRIF_p.o._PopPK-PK-Analyses.xlsx)
[Kharasch'04_MDZ+RIF_p.o._PopPK_without RIF-PK-Analyses.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/4825090/Kharasch.04_MDZ%2BRIF_p.o._PopPK_without.RIF-PK-Analyses.xlsx)

[Midazolam DDI_PK-Sim8_Github upload.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/4825096/Midazolam.DDI_PK-Sim8_Github.upload.zip)

**Comment by tobiasK2001** [comment]
Dear Anant,

That is an interesting finding. Thanks for bringing that up. It is an problem that is easy to overlook. Unfortunatly PK-sim does not display directly in the results, if some individuals in the Population simulation did not lead to results. However that seems to be the case here. I am not sure if I can explain to you what happened in detail but nevertheless I can give you a Workaround.

If you look at your simulation results on log scale you will see that the Midazolam concentrations are very low after the first dose:
![image](https://user-images.githubusercontent.com/25585248/85583940-fd2c7c00-b63e-11ea-9084-6a1257c5ea48.png)
and the mena and the grey shade are looks a bit strange there.
My naive thinking is that the solver tolerance is to high here, to get results and PK-sim throws NaN for the PK-analysis.
The simple workaround is to lower the absolute and relative tolerance in the simulation setting to e.g. this value:
![image](https://user-images.githubusercontent.com/25585248/85584482-79bf5a80-b63f-11ea-90cc-5178614a4c58.png)
I did several tries iteratively lowering it to get it right (see file attached)
[Midazolam DDI_PK-Sim8_Github upload_tk.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/4826420/Midazolam.DDI_PK-Sim8_Github.upload_tk.zip)

. With that numbers No NaN will appear in the PK-analysis and the graph does not look spooky anymore
![image](https://user-images.githubusercontent.com/25585248/85584895-d884d400-b63f-11ea-8a07-705d868e4888.png)

This non-converging of simulations seems to happen more often after po dosing and not for IV. I am not sure why?
Also it would be good to know to which value the tolerances should be lowered to overcome situations like these, without having to try so often.
Maybe  Juri or Michael S can help here?
I think it would be nice to get a direct alert from PK-sim that some individuals did not get a result in Population simulation

**Comment by arketkar** [comment]
Dear Tobias,

Thank you so much for spending time on that and digging out the cause. Sincerely appreciate that. I tried that through the file you had attached, it worked perfectly.

However it took a lot of time to complete the simulation due to change in the tolerance limits. In this case plasma concentrations are dropping down due to large difference between two doses. It would be better for me to run the simulations separately for control dosing (Midazolam without perpetrator) and with perpetrator (dosing Midazolam only after Rifampicin), and then separately collect and compare data for the control and treatment simulations and calculating AUCR on populations.

As pointed out by you it would be nice to get such alerts as the mean data does not indicate anything about the individual response.

Thanks once again.

Regards.
Anant
