### ISSUE TITLE
Antibody competitive binding to FcRn 

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#558]
Dear all,

I would need to model two antibodies competing for FcRn binding. From my understanding, in the basic protein model, there is the IgG competition to FcRn which could be used for this scope, but this IgG model is a simplified model, so difficult to parameterize to mach a full PBPK.

As alternative, do you think that it would be feasible to model two antibodies in PK-Sim independently and then merge them in MoBi to account for the competition to FcRn binding?
Do you see any other way to model this type of interaction?

Thanks for your feedback!

Donato

**Comment by Christoph27** [comment]
Hi Donato,

no need to go to MoBi for this. You can define two different antibodies in PK-Sim and use both in a simulation. They will both compete for binding with the same FcRn (together with IgG_endo). I.e. changing the Kd_FcRn of antibody 1 will change the clearance also of antibody 2 already in PK-Sim (if the dose is high enough). 

Best, Christoph

**Comment by teutonicod** [comment]
Hi @Christoph27 ,

thanks a lot for your reply!

Best,

Donato

**Comment by StephanSchaller** [comment]
Yes, I can confirm what @Christoph27 wrote. We have evaluated this for external high-dose IgG therapy.
