### ISSUE TITLE
adding a new compound - naproxen

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#56]
HI,

Is there a repository of molecules/compounds where I can download them to build a model? 
If I need to build how I can go about added them? I remember seeing a script to add a molecule and was not sure how to use it. Also in the same note, someone made a comment that if the data is extracted from drug bank it has to be validated? if so how please let me know the validation process.

Thanks in advance.
mouli

**Comment by TheiBa** [comment]
Repo, examples, and "coordination structure" are being worked on. In another issue a direct read-in, e.g. from DrugBank was discussed. Alternatively and straightforward: just add a compound building block in PK-Sim and fill-in as described in the manual. With phys-chem only, you can not directly expect the perfect description of in vivo PK data. Using PK data to refine/estimate parameters such as lipophilicity or clearance is common. Validation is a much discussed topic, you may want to check recent guidelines from EMA/FDA ... I think keeping in mind the intended use is important when thinking about appropriate qualification.

**Comment by moulirc** [comment]
Hi TheiBa,

Thanks for your comments on this issue.

regards
Mouli
