### ISSUE TITLE
partition coefficients (PC)

### ISSUE THREAD

**Issue by jmgallo** [Open-Systems-Pharmacology/Forum#561]
Hi,
The documentation on the website related to PC calculation is fine; however when running PK-Sim it's a bit tedious to extract the values. Under Compound > ADME > Distribution Calculation there is no list of the parameter values. It seems you have to do a simulation to extract those; is that correct? A number of modelers write their own code and use PK-Sim or Gastro-Plus to provide initial parameter values. It would be advantageous to be able to extract PCs for the different estimation methods prior to running a simulation. 
Following a simulation the PCs are reported as Interstitial:Plasma and Intracellular:Plasma. Further, for a 3-subcompartment tissue you want the PC as unbound fraction in the interstitial fluid/intracellular compartment, which could be obtained by dividing the 2 PC provided by PK-Sim. 
Are there options to get this info without running simulations?
Thanks, jmg

**Comment by jmgallo** [comment]
OK, thanks. Is there a simple means to change the PC estimation method without starting over? I find it very clunky.....thanks

**Comment by msevestre** [comment]
@jmgallo You can configure your simulation (right-click on your simulation, configure) or click on the configure button and select another PC calculation method and click ok. 

you should be back to where you were in just about 3 mouse clicks with the added benefit of a brand new set of parameters.

**Comment by msevestre** [comment]
I should add that the reason why those values are not defined in the compound directly is due to the usage of a building block concept. Some parameters are defined in the individual per organ (volume fraction lipid etc.. ). Therefore the actual PC formula can only be evaluated once both individual and compound are mixed together within a simulation

Hope that helps

**Comment by jmgallo** [comment]
Thanks! Will try….

**Comment by Yuri05** [comment]
@jmgallo Closing. Please reopen if there are still any unanswered questions.
