### ISSUE TITLE
Capillary endothelium as a barrier for highly bound compounds

### ISSUE THREAD

**Issue by CSchraepel** [Open-Systems-Pharmacology/Forum#562]
Dear OSP-community, 

in a Pk-Sim/MoBi booklet, we read that for compounds, which are "highly bound" to plasma proteins (diclofenac was given as an example) the exchange between plasma and interstitial space is not instantaneous, i.e. the capillary endothelium constitutes a true barrier for this drug. This could be taken into account in Pk-Sim by carrying out either of the following instructions:

- One could use the distribution model for proteins and large molecules instead of the standard model for small molecules
- or the values under permeability/endothelial could be set to 0.1 cm/min for all organs, except of brain and liver. For Liver periportal and pericentral one should set the permeability to 10 cm/min.
 
Could somebody maybe explain the background of these approaches? Do you know, where the numbers 0.1 cm/min and 10 cm/min come from? 
Do you think, this adaption is generally recommended/mandatory for all compounds, which are highly bound to plasma proteins (what would be a cut-off value) or just for certain scenarios?
 
Thank you very much in advance! 

Best regards, 
Christina

**Comment by StephanSchaller** [comment]
Dear Christina,

thanks for your question.
Can you share in which booklet you found this info?

Both instructions are a "rough" approximation of the truth.

The truth is, you would need to explicitly model Albumin as a compound itself, then move both (your compound and albumin) to MoBi, there define the binding between them and simulate the resulting distribution.

What happens for compounds highly bound to albumin is the following: as they mostly circulate bound to albumin, they will distribute as albumin does (with the small free fraction still distributing as a "standard" small molecule). Albumin, however, only very slowly transits the endothelial barrier (via pores and transcytosis as e.g. elaborated for PK-Sim [here](https://pubmed.ncbi.nlm.nih.gov/29234936/)).

So above instructions are an approximation of this to make your life easier (i.e. not needing to switch to MoBi).
The 0.1 cm/min and 10 cm/min are numbers, that reflect, that the liver has larger pores and thus also there Albumin (and thus your bound drug) can transit more easily.
If 0.1 cm/min and 10 cm/min are the right numbers for your drug, you will have to evaluate by simulation. Other values (with the same approximate ratio between liver and other organs, though) might work better for your compound.

Hope this helped,
Stephan

**Comment by CSchraepel** [comment]
Dear Stephan, 

thank you very much for your quick and comprehensive feedback! We will look into the suggested approaches! 

Best regards, 
Christina
