### ISSUE TITLE
Calculation surface areas not comprehensible

### ISSUE THREAD

**Issue by davbus** [Open-Systems-Pharmacology/Forum#563]
Hi,

To calculate flows from the interstitial to intracellular space (and vice versa) the permeability-surface area product is employed. The documentation for the prediction of the surface area (interstitial/intracellular) in MoBi states for e.g. fat tissue: 

SA [cm2] = (V_fat * 1000 / 14.2)^0.75 * 5 * 1E2. 

V_fat is the intersitial volume in fat tissue according to the reference, but the exponent 0.75 would not yield cm2 as a unit. Would you ellaborate on the provided equation and if possible point at where to find further information on the calculation of cellular surface areas in PK-Sim? I am aware that the information must be available somewhere in MoBi but could not find it yet.

Thank you very much in advance!
Best wishes,
David

**Comment by StephanSchaller** [comment]
Hi @davbus , this formula is set up not in an ideal way (hardcoded values) and thus may need some explanation. It is a fitted/informed allometric function and its constants can be interpreted the following way:

- the 14.2 are a fitted reference value for fat volume (in "theoretical dimension" volume, e.g. cm^3 and the dimension with "v_fat" cancel out)
- the 5*1e2 are the fitted reference value for fat surface area (in "theoretical dimension" surface, e.g., cm^2)

So in the end the formula adds up to the surface dimension, but the way it is set up technically (using the dimensionless constants), it  does not. So it is a technicality.

(This answer might need confirmation by @Yuri05 ;-))

**Comment by davbus** [comment]
Hi @StephanSchaller, 
Many thanks for your reply! That makes perfect sense to me. I guess these values were determined as presented in the supplementary of this publication: [10.1002/psp4.12205](url). Are you aware if this is published for all organs represented in PK-Sim for further reading on the topic or is this Bayer internal work that was never shared (I mean beyond PK-Sim of course)? 
Best wishes,
David

**Comment by StephanSchaller** [comment]
Actually, I don't know any publication from the top of my head. @Yuri05 might be able to help.

**Comment by JanSchlender** [comment]
A recent publication on the large molecule model framework explains the concept as well (although not touching on the small molecule parametrization). Maybe this provides some clarity. Otherwise @Christoph27 might help here
https://link.springer.com/article/10.1007/s10928-017-9559-4

**Comment by Christoph27** [comment]
Sorry for my late answer (was on holidays). I also don't have any better reference than the supplemental material in 10.1002/psp4.12205 you mentioned. Since your question is on the interstitial/intracellular surface area, you won't find anything on that in the paper Jan mentioned. There only the plasma/interstitial surface area is given which is estimated by a completely different rationale (the proteins are not assumed to diffuse into cells).
