### ISSUE TITLE
Is there a pdf manual for PKSim?

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#567]
![80557020-167ec680-8a08-11ea-9a2a-5efb15d08607](https://user-images.githubusercontent.com/44484877/87238616-6e538980-c3ca-11ea-9474-5be074af04fa.png)

Hi!
Couple of months ago, a user posted this image, supposedly taken from PKSim documentation. I can't seem to find the original documentation. Is there a manual in the form of pdf somewhere available?
I am aware of this: https://docs.open-systems-pharmacology.org/
But, what I am looking for is documentation from where this above picture was taken.

**Comment by Yuri05** [comment]
The screenshot above is taken from https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#running-a-simulation-in-an-individual 

pdf documentation can be found in the "Open Systems Pharmacology Suite X.Y" group of the Start menu.
![grafik](https://user-images.githubusercontent.com/25061876/87246902-9685cb80-c450-11ea-8d26-725a6bbd1255.png)

pdf documentation might be slightly outdated compared to the online version (docs.open-systems-pharmacology.org)
