### ISSUE TITLE
adding a tranist compartment 

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#57]
I am trying to simulate Dysphagia where the transit time between mouth to stomach vary between 5 min to 10 min (after an oral dose). could you please let me know how I can get this done?

**Comment by PavelBal** [comment]
As far as I know, PK-Sim model do not have a distinct representation of a mouth compartment. Oral applications are directly "placed" into stomach.

Perhapts you could simulate the transition times by varying the application start time?

**Comment by moulirc** [comment]
Hi Pavel,

Thanks for the suggestion, may I know if there is an example I can look into. 

thanks in advance
kind regards

**Comment by Aedginto** [comment]
in addition, it may be worth thinking about the importance of this time delay to oral absorption. The time delay is unlikely to be a rate limiting step in absorption unless it is a small, lipophilic, highly soluble compound (BCS 1). In this case, entry to the duodenum is the rate limiting step in absorption and as a result, time to enter the stomach would be important. For drugs that have lower permeability or solubility, this time delay would make no difference to uptake rate. You could asses the importance of the time delay by simply increasing gastric emptying time by 5-10 minutes and seeing what it does to your curve. This a crude method but would provide a lot of insight. 
All the best!
Andrea
