### ISSUE TITLE
All building blocks and simulations gone

### ISSUE THREAD

**Issue by NinaHanke** [Open-Systems-Pharmacology/Forum#571]
Good morning, 

When I opened my PK-Sim file this morning all my Simulations and building blocks dissapeared and I received this: 
![grafik](https://user-images.githubusercontent.com/36850897/87905689-78782680-ca61-11ea-9601-582df7e175d7.png)

In the history I cannot rollback anywhere with the following error: 
![grafik](https://user-images.githubusercontent.com/36850897/87905770-a2314d80-ca61-11ea-9a85-898e3fede63f.png)

Please can somebody advise me on how to retrieve my work? 

Kind regards, 
Nina

**Comment by StephanSchaller** [comment]
@NinaHanke, did you change Versions since the last time you saved the project?

**Comment by NinaHanke** [comment]
Sorry, did not say that. 

I started in 8.0 and I am still in 8.0. 
I also tried the "repair" function of PK-Sim, but without success.

**Comment by NinaHanke** [comment]
I was able to open it on the server and to delete the Simulation that caused the problem. 

Many thanks for your help!
