### ISSUE TITLE
Km Units

### ISSUE THREAD

**Issue by Wenjing1018** [Open-Systems-Pharmacology/Forum#572]
Transporter Proteins in the compound, the parameter Km unit is  mol/l、nmol/l, drop-down box back to the M、nM and other related units, I want to know what is  nM unit represents? The Km offered mM units from many literatures, but Km seem to be units of concentration, does it mean that mol/l is equivalent to M?? If this is the case, does the software provide a repeat?
![image](https://user-images.githubusercontent.com/63133525/88284911-ce2e2680-cd20-11ea-840d-9ec7c2216782.png)

**Comment by PavelBal** [comment]
`M` stands for "Molar", which is equivalent to "mol per liter". So while the word "mol" represents an amount and is abbreviated by `mol`, the word "molar" represents the concentration and is abbreviated by `M`.

So yes, `mM = mmol/l` and is just an alternative way to represent the concentration.

**Comment by Wenjing1018** [comment]
@PavelBal，
thank you for your replying!
 I would also like to know that the two units are selected separately in the model, and the simulation results are the same?

**Comment by msevestre** [comment]
Yes it's all the same. Those units are equivalent. It's just a convenience for the user that's all

**Comment by Wenjing1018** [comment]
@msevestre,
 Thank you  for your reply, I understand it very well .
