### ISSUE TITLE
 save simulation chart with the observed data

### ISSUE THREAD

**Issue by AyaSaleh90** [Open-Systems-Pharmacology/Forum#573]
Hello,
I want to know how can I save a plot generated from a simulation with the observed data included??
Because whenever I try to export the plot, it only gives me the simulation only with no observed data

Thanks,
Aya

**Comment by msevestre** [comment]
@AyaSaleh90 How do you export your plot?

**Comment by AyaSaleh90** [comment]
> @AyaSaleh90 How do you export your plot?

when I run the model and get the time profile analysis,, I tried the export function from PK-sim, either results to excel/to csv/ to PDF --> all of those gave me the simulation only.
while I copy the plot to clipboard it gives me the simulated with the observed data, but with the resolution is not good

**Comment by msevestre** [comment]
What about using the export feature option?

![image](https://user-images.githubusercontent.com/1041237/88319924-d8353280-ccea-11ea-8c46-ffe549fcf368.png)

**Comment by AyaSaleh90** [comment]
Okey,, so you mean by defining the Width & Height,, then copying it to the clipboard will give better resolution, right??

**Comment by msevestre** [comment]
yes. You can create the plot as you wish to have for your export scenario

Otherwise exporting to excel. You get the row data (on different sheet) but then you can create your own plot 

![image](https://user-images.githubusercontent.com/1041237/88324943-6e208b80-ccf2-11ea-916d-96505d7830de.png)

**Comment by AyaSaleh90** [comment]
Thank you so much 👍
