### ISSUE TITLE
 How to open the gene database?

### ISSUE THREAD

**Issue by Wenjing1018** [Open-Systems-Pharmacology/Forum#575]
the gene database can be directly installed in the PK-Sim  Previously, but now after downloading the file ,it can not be opened, failed to install in the PK-Sim,  is it necessary to give what operation to open this gene database?
![image](https://user-images.githubusercontent.com/63133525/88548725-08b1ff00-d052-11ea-82f7-0504087f77a5.png)

**Comment by msevestre** [comment]
@Wenjing1018 Nothing has changed in the way the expression DB is to be used. The format of the file has changed about 2 years ago. 

see https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-options#template-database-path

**Comment by msevestre** [comment]
Or please explain what you mean with `Failed to install in PK-Sim`

**Comment by Wenjing1018** [comment]
@msevestre ，
This problem has been solved.
sincerely!
