### ISSUE TITLE
Using in vivo absorption profile as formulation input

### ISSUE THREAD

**Issue by RobinM92** [Open-Systems-Pharmacology/Forum#58]
Good day everyone,

We are currently validating a PBPK model built in PKSim using different historical clinical trials.
For most of these clinical trials, specific (oral) formulations are used without specifying any in vivo or in vitro characteristics. Using the same fast dissolution weibull function for all is not an option, as the data consists of a range of slow and fast releasing formulations.
Luckily, IV data is also available so we were able to extract in vivo absorption profiles using deconvolution. 
However, I can't seem to find a way to use these in vivo profiles (fraction absorbed over time) as an input for our PBPK model, in order to circumvent the lack of knowledge about our formulation characteristics.

Is there any way to characterize the formulation in PKSim using in vivo absorption profiles instead of in vitro dissolution data? 

Kind regards,
Robin Michelet
Ghent University

**Comment by TheiBa** [comment]
Dear Robin,

 

You can define an administration protocol in PK-Sim with administration type "user defined" and target  "(peripheral) venous blood, plasma" and supply the deconvoluted data as table input, to circumvent looking at effects of dissolution, absorption and first pass. Alternatively, you can e.g. include a Weibull dissolution function and fit it to your PO data to characterize your formulations, keeping absorption and first pass mechanistic. I guess, the choice also depends on what you would like to do at the end. Would be interesting to see what works for you – keep us posted ;-) 

 

Best,

Thomas

**Comment by msevestre** [comment]
@RobinM92 Was the information provided sufficient? Where you able to move further in your evaluation?

**Comment by RobinM92** [comment]
Hello everyone,
We tried both approaches and the fitting of the weibull function seemed to give the best results, whereas inputting the deconvoluted data as table input did not result in satisfactorily results. As our compound is actively transported, I guess this is because the lack of mechanistic description of the absorption in the latter approach? I've included representative plots below. 
Thank you very much for your help!

Kind regards,
Robin 

![image](https://user-images.githubusercontent.com/30694339/29371258-34b57622-82a8-11e7-8088-7444696153d7.png)

**Comment by TheiBa** [comment]
Hm, if you have cross-over data and your model describes IV well, table input 
of deconvoluted data into plasma should also match well. Can you post IV?

**Comment by RobinM92** [comment]
Here is the IV data used for the deconvolution

![image](https://user-images.githubusercontent.com/30694339/29373710-567a5514-82af-11e7-8def-4d2693dde715.png)

**Comment by msevestre** [comment]
@RobinM92 Did you try to model IV as well? Is the process well described by PK-Sim in that case?

**Comment by RobinM92** [comment]
Good morning,

As the drug we are developing the PBPK model for is never administered as an IV bolus (only IV infusion), we took from the literature a PopPK model describing IV data of this compound, and simulated an IV bolus in NONMEM to obtain the bolus profile as input data for the deconvolution analysis. As you suggested, we compared this to the PKSim simulation of a bolus administration, and the prediction was not very good: 

 
![-lu4ainfwaoh8doqm3ljfuqcu6epcxeqfs4jgru9szl5srvco3_of8nmumj3qjz9lzpmeic0u3-vupdfppbljg1mf1dokczuqtmooyf5hcr376yvekc-j2jxdn2l_jpyojfr7rtyfwc4oqp3unhmsgdzkojh0oskspigr2uj1u67d3sybpq1jzsxofvsqw-h5zkrksyhnklbw6cud](https://user-images.githubusercontent.com/30694339/29557705-3b1cb7b0-872a-11e7-9e2c-f72c7e6355b8.png)

As our PBPK model described other IV infusion data for the study compound very well, probably, the reason could be that the NONMEM model we used was not developed for the same population we were simulating in PKSim. Indeed, in the reference model manuscript, it is indicated that the model was developed with data from intensive care unit patients: polytrauma, postoperative complication or other medical reasons, and also the patients were mechanically ventilated.

As our drug binds to albumin, and trauma patients usually present a decrease in plasma albumin, we tried to simulate this population to get a better match between the NONMEM and PKSim simulation. As albumin levels cannot be modified in PKSim (#6 from the PKSim forum: "Possibility to scale Albumin levels in the 'individual' building block") we increased the plasma protein scale factor in the population and a better fit was obtained. It would, however, be more physiological to be able to change the protein content of the blood rather than use this scalar, is there any way to do this?

And to verify our understanding of this scalar: when the plasma protein scale factor is increased, the fu increases too, correct?

Thank you very much,
Robin

![Uploading yBy95V_FxamyWu-hbI_oJtl_DyPGxQtgGtbUfTqBaTVpc4_6e3mMJkUgWwcVgaoGGgY5SGoZoCHNKFvBBVZVjY2F_GsXWybDk5IG7hjaNE-kJI1tCylks6Kf3wDrfx9h982j0zyydtgtK6hnFovcTX26YDj-rpB0pkXOoREzbteRqnz-4xYWpTBNX-Bb4qpm3sN7e6n4n2L7AnUQI.png…]()

**Comment by msevestre** [comment]
Hi @RobinM92 ,

>And to verify our understanding of this scalar: when the plasma protein scale factor is increased, the fu increases too, correct?

Yes this is correct. 

Exporting the simulation to MoBi (or finding the `Fraction unbound (plasma)` parameter in PK-Sim and hovering over it) reveals the following equation:

```
Fraction unbound (plasma) = 1 / (1 + (BindingPartner = Albumin ? AlbuminOntgenyFactor : (BindingPartner = Agp ? AgpOntogenyFactor : 1) ) * (1 - fu_ref) / fu_ref) * PlasmaProteinScaleFactor
```

As you can see, the first term calculating the actual fu in the simulation is multipled by the `PlasmaProteinScaleFactor` term.

Cheers
