### ISSUE TITLE
how to extend the simulation curve?

### ISSUE THREAD

**Issue by Wenjing1018** [Open-Systems-Pharmacology/Forum#582]
I want to extend the simulation curve to 144 h, but now it's only 36 h, how to extend the simulation curve?
![image](https://user-images.githubusercontent.com/63133525/89542159-e0848600-d831-11ea-8019-7746009927a6.png)

**Comment by StephanSchaller** [comment]
![image](https://user-images.githubusercontent.com/25477643/89550672-35aca180-d80a-11ea-90db-a20a98636f72.png)

**Comment by StephanSchaller** [comment]
Change the max. "End Time" to 144h

**Comment by Wenjing1018** [comment]
@StephanSchaller，
I got it ,thanks!
yours sincerely!
