### ISSUE TITLE
How to include 'user defined variability' in population PK modeling for 'kcat', which is 'obtained by PI'?

### ISSUE THREAD

**Issue by arketkar** [Open-Systems-Pharmacology/Forum#584]
Hi!

In one of the models, I incorporated 'in-vitro Vmax' and 'Km' values generated using a recombinant CYP. Then I optimized the 'kcat' value by Parameter Identification (PI) to fit to the observed data. While running a simulation for a population I wanted to incorporate some variability (as SD) for the 'kcat' value. However under the 'user define variability' I am seeing only the 'in-vitro Vmax' and 'Km' parameters, and not the 'kcat' obtained by PI. In such a case 'in-vitro Vmax' has no effect, as that has been taken over by 'kcat'.
Can someone suggest me the way to incorporate variability for 'kcat' in such a case?
Thanks in advance.
Anant

**Comment by NinaHanke** [comment]
Dear Anant, 

You could add variability on the reference concentration of your CYP (in your population under "user defined variability"). 
We use "log normal" distribution with a GeoSD from literature. 
BUT if you selected "Ontogeny/variability like CYP..." in the individual that you built your population from, 

![grafik](https://user-images.githubusercontent.com/36850897/89614107-089cd500-d884-11ea-9312-889747b455e5.png)

it should already have variability in your population. 
You can check that in your population under "Distribution->Ontogeny factor". 

![grafik](https://user-images.githubusercontent.com/36850897/89614292-692c1200-d884-11ea-8ebd-ecaf233ff41a.png)


Yours, Nina

**Comment by arketkar** [comment]
Dear Nina,

Thank you so much for those inputs. 

I have selected "Ontogeny/variability like CYP..." in the individual. So the variability as highlighted by you would work in my case.

Thanks once again.

Regards.
Anant
