### ISSUE TITLE
Getting drug amount for a compartment

### ISSUE THREAD

**Issue by DonkeySaddle** [Open-Systems-Pharmacology/Forum#586]
I am working with the Alprazolam project, found in the model library, and am wondering how do I get the total amount of drug(as opposed to the concentration) in a compartment (e.g., the total amount of Alprazolam in the brain, or even the brain plasma or brain tissue)?

**Comment by StephanSchaller** [comment]
Standard output in PK-Sim in Concentration... if you need to calculate the Amount, you could multiply it by the compartment volume (could be easily done with the OSP R package.

Another way would be to export the simulation to MoBi. There you can directly plot/output the amount in compartments.
Or you create an Observer for that in MoBi and load it into PK-Sim to plot amounts there.
