### ISSUE TITLE
using GENEDBhuman

### ISSUE THREAD

**Issue by rkdevarakonda** [Open-Systems-Pharmacology/Forum#59]
How to integrate the GENEDBhuman with PKSim. Unable to open it/use it to add an enzyme system using this DB for simulations...

**Comment by msevestre** [comment]
Check this post out
https://github.com/Open-Systems-Pharmacology/Forum/issues/8

Let me know if you  need more help

**Comment by rkdevarakonda** [comment]
Thank you so much, it works!
