### ISSUE TITLE
How to import a large dataset?

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#591]
![image](https://user-images.githubusercontent.com/44484877/90203135-e1776380-ddad-11ea-91ff-9db6b548be42.png)

Hi, in the above pic by data is longitudinal data of 100 subjects. Some time points are repeating in different subjects, and its giving me this error shown in the pic. Any idea how to get around it?

**Comment by NinaHanke** [comment]
Hi there, 
should work, these are the right tags...
At the moment PK-Sim thinks you have 110 individuals ("Import 110"). 
Did you check that no individual has the 9 min time point twice? 

If that doesn't help try squared brackets for the units in your dataset: --> Time [min] and --> Concentration [ng/ml] 
and also try to put your IDs in the third column, not the first. 
Hope that helps, Nina

**Comment by humblewarrior** [comment]
Thanks a lot! That worked!
