### ISSUE TITLE
Question regarding removing subjects in simulation and chart settings

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#595]
![image](https://user-images.githubusercontent.com/44484877/91331731-267d9b80-e799-11ea-862f-0bc6e00adc17.png)
Hi!

In the above image, I know that in chart settings. for "color", you can drag down the color to give constant color coding to different subjects. This functionality is very useful if I have 100 subjects in observed data and I want to denote subjects by same color in a graph. However, I am wondering if there is similar functionality available for "style" and "symbol" column? I don't want to change individual subjects style or symbol one by one. Any help will be much appreciated.

![image](https://user-images.githubusercontent.com/44484877/91332203-d3581880-e799-11ea-9b01-32f77beb7475.png)
My next question is: If I want to remove multiple subjects with observed data in simulation building block, how do I do that? I have 100 subjects and I don't want to remove them one by one. I saw tutorial for chart settings and it was very helpful, so thank you for that, but I am still struggling a bit.

**Comment by humblewarrior** [comment]
@msevestre I am extremely sorry for the inconvenience. I usually ask in the forum, but somehow didn't see it this time where I am posting it. I will be more mindful in the future. Thanks for letting me know!

**Comment by msevestre** [comment]
@humblewarrior 
> However, I am wondering if there is similar functionality available for "style" and "symbol" column? I don't want to change individual subjects style or symbol one by one. Any help will be much appreciated.

No unfortunately nothing like this. 

> If I want to remove multiple subjects with observed data in simulation building block, how do I do that?

Can you explain what you mean here? you want to remove the observed data from the simulation? Then select the observed data and right click to remove them? Or please clarify what you are trying to do

**Comment by humblewarrior** [comment]
@msevestre 
To clarify on the second part, I know that we can remove and observed subject by right click. But, I have 100 observed subjects. Is there a way I can remove all of them at once instead of removing 100 subjects one by one?

**Comment by msevestre** [comment]
@humblewarrior Select all of them and click remove 
![image](https://user-images.githubusercontent.com/1041237/93347565-3a01ac80-f803-11ea-806b-2b6064ef3d27.png)

**Comment by humblewarrior** [comment]
Michael,

I think I should be more clear. I know you can select multiple subjects,
but the issue is I have to select 100 subjects, each one of them
separately. Is there a way to select all of them at once? Just like in
excel where you drag your cursor over multiple rows or columns and delete
them. That "drag" function is not there.

Regards,
Sumeet

**Comment by msevestre** [comment]
>Is there a way to select all of them at once?
not at the moment

If you think this could be a good feature, please create an issue in the PK-Sim repo and explain what problem it would solve and how you would suggest the user experience to be realized (e.g. describes the steps that the user would have to accomplish)
