### ISSUE TITLE
OSP workshop @ ISSX 2017, Cologne, Germany, June 25

### ISSUE THREAD

**Issue by TheiBa** [Open-Systems-Pharmacology/Forum#6]
http://issxeuro2017.org/satellite/

**Comment by Dieter08** [comment]
Hi TheiBa

I missed the workshop. Is there another workshop planned for beginners?

Regards
Dieter @TheiBa

**Comment by TheiBa** [comment]
Hi Dieter,

Certainly there are additional workshops. Next one planned is in October, hope 
that fits, please see
 <https://github.com/Open-Systems-Pharmacology/Forum/issues/7> 
https://github.com/Open-Systems-Pharmacology/Forum/issues/7

Best,
Thomas 
<https://github.com/notifications/beacon/AYQo2UZkVIXr372lsVUfKeh_uQehG5Bbks5sSKV0gaJpZM4NWpbt.gif>

**Comment by TheiBa** [comment]
Dear Dieter,

additional workshops will again be announced and tagged correspondingly in the 
forum, when fixed. Planning ongoing, but with 2 European workshops at ISSX and 
PAGE just delivered in the last 2 months, fixing next ones may take a while 
though. Maybe consider Florida.

Best,

Thomas
