### ISSUE TITLE
How to set up Parent-Metabolite Model

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#605]
Hi!

Is there any tutorial on how to set up parent-metabolote model in PK-Sim. I am getting parent compound tissue concentrations in various organs but I am not sure how to get metabolite concentrations in those same organs even though I have included metabolite information in the building block.

Thank you!

Regards,
Sumeet

**Comment by msevestre** [comment]
@humblewarrior 
> I have included metabolite information in the building block.

What do you mean by this?

When you want to get metabolite concentrations, the metabolite needs to be a full-blown compound that you will add in the simulation. The linking between the Compound and its metabolite is done at the simulation level

Also please check the documentation.
https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#how-to-set-up-a-parent-metabolite-simulation
