### ISSUE TITLE
Where to find the equation of degree of charge in subcompartments and Partition coefficients

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#609]
Dears, 

I would like to see the formula which defines:

1) The degree of charge on the compound in the case of being acid/base or neutral in different subcompartments (which should look like Handerson hasselback equation) 

2) How the formula of the charged/neutral compound calculation feeds into the partition coefficient (would have logP in it )

3) formula which does the calculation of the membrne permeabilities  (would somewhere use the above two formulas to derive this)

Where can I find this?

Best, 
Pri

**Comment by StephanSchaller** [comment]
Hi @PriKalra ,

There is no explicit output for the ratio of ionized/neutral fractions per compartment. But the partition coefficient implicitly contains that info (e.g. https://www.sciencedirect.com/science/article/abs/pii/S0022354916320342). 
If you use the R&R partition method, you will have to look at the intracellular:plasma PC to see details:
![image](https://user-images.githubusercontent.com/25477643/93666423-65dc9680-fa7e-11ea-9317-2f3b0b704a56.png)

other PCs are derived from this one (you get more details when exporting to MoBi and browsing through the Neighborhood Organ_int_Organ_cell).

Likewise (go to MoBi Neighborhood Organ_int_Organ_cell) for permeabilities (will need to select "Charge-dependent Schmitt" for permeability calculation)

Best,
Stephan

**Comment by PriKalra** [comment]
Thank you very much!  :D 

Best, 
Pri
