### ISSUE TITLE
Intestinal transit model

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/Forum#61]
Sorry in advance if this is a very basic question. I'm trying to discern the underlying model equations of transit between the lumen and the mucosa, and the absorption from the mucosa to the portal vein used in PK Sim. I have read both Thelen papers (Thelen et al. 2011, J. Pharm Sci; Thelen et al. 2012, J. Pharm. Sci) and the third part by Willmann (Willmann, Thelen, and Lippert 2012, J. Pharm and Pharmacol), but it remains unclear to me what specific equations regulate these processes. 

As I understand it, using a tablet for example, after ingestion the dissolution of the drug happens according to particle size groups and Noyes-Whitney. Then, from Thelen (2011), "the drug is transported along the lumen of the intestine according to the transit function and can enter the mucosa of the corresponding segment either by the transcellular route directly into the enterocytes or by paracellular diffusion into the intersitial space of the mucosa...The fully dissolved drug once absorbed into the mucosal space can then diffuse from one sub-compartment to another, can be metabolized in the intracellular space, and finally reaches the vascular space of the mucosa to enter the portal vein blood." 

Is this transit function referring to the Gaussian distribution model? I presume not because, as I understand it, the compartmental model replaced this one to alleviate technical complications. I have experience with other PBPK intestinal absorption models (e.g. Fenneteau, Poulin, and Nekka 2010, J. Pharm Sci; Peters 2008, Clin Pharmacokinet; Agoram, Woltosz, Bolger 2011, Adv. Drug Deliv. Rev.; Gertz, Houston, and Galetin 2011, Drug Met Disp; Yu and Amidon 1999, Int J Pharm etc.) so I have some handle on these processes are modelled therein, does PK Sim's compartment model compare with them (modulo the inclusion of internal compartments in each organ, like the RBCs etc., of course)?

I've tried to understand the model structure by exporting PK Sim models to .txt and also by using MoBi to export to Matlab .m files but I haven't yet figured it out. I'm particular interested in the general form of these processes (i.e. given an SI compartment i, the transfer and absorption in that compartment), so if someone could point me in the direction of the model equations, I would be very appreciative!

**Comment by Yuri05** [comment]
>As I understand it, using a tablet for example, after ingestion the dissolution of the drug happens according to particle size groups and Noyes-Whitney.

It's true if the formulation chosen was _Particle Dissolution_.
For other formulation types a corresponding dissolution function is used (Weibull, _Lint80_, ...)

>Is this transit function referring to the Gaussian distribution model? I presume not because, as I understand it, the compartmental model replaced this one

Correct

>I've tried to understand the model structure by exporting PK Sim models to .txt and also by using MoBi to export to Matlab .m files but I haven't yet figured it out. I'm particular interested in the general form of these processes (i.e. given an SI compartment i, the transfer and absorption in that compartment), so if someone could point me in the direction of the model equations, I would be very appreciative!

You can find the formulas of the drug transfer along the lumen and (passive) drug absorption from the lumen into mucosa in the Passive Transports building block in MoBi. Both applies to the **liquid** drug (=dissolved part of a tablet)

`LumenDrugTransport_xxx` describes the drug transfer along the lumen.
E.g. `LumenDrugTransport_duo` describes drug transfer `Lumen/Stomach` :arrow_right:  `Lumen/Duodenum`

<img width="583" alt="001" src="https://user-images.githubusercontent.com/25061876/29870898-013090ec-8d8a-11e7-8cc1-f28de4d4f7c8.png">

Under _Kinetic_ you can see the corresponding process rate:
<img width="565" alt="002" src="https://user-images.githubusercontent.com/25061876/29870950-427eb060-8d8a-11e7-8dde-6f40fbf4a87a.png">

`DrugAbsorption_trans` and `DrugAbsorption_para` processes describe (passive) transcellular and paracellular absorption from Lumen into Intestinal Mucosa. In the current model paracellular absorption is always zero per default.
<img width="569" alt="003" src="https://user-images.githubusercontent.com/25061876/29871102-e2565020-8d8a-11e7-8a94-80ecc1b4fec2.png">

If you look at the kinetic of `DrugAbsorption_trans` you will see that it points to the `NEIGHBORHOOD|MOLECULE|Drug absorption rate (lumen to mucosa)` parameter.
<img width="653" alt="004" src="https://user-images.githubusercontent.com/25061876/29871211-3d657e00-8d8b-11e7-9b20-4261b9b81d17.png">

Here, the NEIGHBORHOOD keyword refers to the neighborhood between source and target compartment of the transport, and you will find the final equation in the corresponding neighborhoods of the spatial structure building block, e.g _Neighborhood between Lumen/Duodenum and Mucosa/Duodenum/Intracellular_(please refer to the user manual for more details about using keywords in formulas):

<img width="792" alt="005" src="https://user-images.githubusercontent.com/25061876/29871969-fa6a90ec-8d8d-11e7-9509-f7d56451f3aa.png">

If some active transport processes are available in your model, you can find process description e.g. in the Molecules building block:
<img width="601" alt="007" src="https://user-images.githubusercontent.com/25061876/29874452-15d5ad0e-8d97-11e7-969a-cdfb0089e75a.png">

Movement of the tablet along the lumen and release rate of the tablet is described in the Events building block. Release rate depends on the formulation type.

E.g. for the formulation type `Particle Dissolution`: you have transports `ParticlesDrugReleaseXXX`
Each transport describes the dissolution process of particles in one lumen segment and is defined as 
`Release rate fraction XXX * Release rate of the tablet`
<img width="680" alt="008" src="https://user-images.githubusercontent.com/25061876/29874946-a04fd120-8d98-11e7-9654-b94aab257ce6.png">
`Release rate of the tablet` depends on the formulation type. E.g. for particles dissolution it's described by the Noyes-Whitney equation.
<img width="805" alt="009" src="https://user-images.githubusercontent.com/25061876/29876676-c345c888-8d9d-11e7-83b6-17c86751427b.png">
`Release rate fraction XXX` is the result of the movement of the tablet/particles along the lumen (Stomach :arrow_right: Duodenum :arrow_right: ...) and reflects the fraction of tablet/particles in the corresponding lumen segment.
<img width="835" alt="010" src="https://user-images.githubusercontent.com/25061876/29876973-90de5dd2-8d9e-11e7-9397-cdb455383dc8.png">

s. example project attached 
[Example_OralApplication_MonoParticles.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1263899/Example_OralApplication_MonoParticles.zip)

**Comment by mlcraig** [comment]
Thanks so much for this detailed response @Yuri05 I've taken the time to dig through the equations/processes you've highlighted and to do some more searching through the literature. I'm wondering whether you could comment on the generalities of the absorption model I've highlighted below?

-Pint is calculated using the membrane affinity and the molecular weight (as outlined in Thelen 2011).
-The rate of drug absorption from the lumen to the mucosa can be summarised as (I haven't included each term here for simplicity) Pint*Aeff(TranscellularPermeabilityLumenCellular-TranscellularPermeabilityCellLumen) 
-From mucosa to PV plasma: (1-f_mucosa)*Q*(1-HCT)*C
-From mucosa to PV RBCs: (1-f_mucosa)*Q*HCT*C_RBCs
-Passive diffusion between the mucosa RBCs, the interstitial space, and the intracellular space is dependent upon some combination of 1) surface areas between RBCs/plasma/interstitial/intracellular, 2) endothelial permeability and/or permeability between RBCs/plasma/interstitial/intracellular, 3) mucosal drug concentrations, 4) the unbound fraction, 5) tissue partition coefficients
-The differential equations for each of the mucosal spaces are sums/differences of metabolism, mass transfer from the lumen, passive diffusion to neighbouring spaces, and mass transfer to the portal vein

Do the items highlighted above sum up the major characteristics of the intestinal absorption model? Thanks again.

**Comment by msevestre** [comment]
@mlcraig Please reopen if you still have questions. Thanks
