### ISSUE TITLE
Simulation tab closes after re-configuring the simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Forum#613]
If a simulation is opened and then re-configured, the opened tab disappears. This did not happen before.

**Comment by msevestre** [comment]
@PavelBal PK-Sim or MoBi?

Can't reproduce in PKSim with v9. Please describe and move to the appropriate repo

**Comment by PavelBal** [comment]
PK-Sim, sorry, didn't pay attention... cannot move it, however.

OK I just realized it re-appears to the right of the opened tabs. So if e.g. you have 10 simulations open, and configure the simulation that is the first from the left, it will be closed and re-appear as the first from the right.

**Comment by msevestre** [comment]
ok this was always like that. Please reopen if you have an issue with this
