### ISSUE TITLE
Total Amount in Organism

### ISSUE THREAD

**Issue by DonkeySaddle** [Open-Systems-Pharmacology/Forum#625]
I am cutting my teeth with the [Alprazolam](https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/tree/master/Alprazolam) model in the OSP-PBPK-Model-Library. I've exported one of the simulations (An oral dose of 0.5mg) to Mobi and I am trying to create my own observers. 

Unfortunately, I am struggling to create the most basic Observer I can think of - the amount of drug in the entire organism: 
![Screen Shot 2020-10-12 at 11 02 59 PM](https://user-images.githubusercontent.com/25123758/95885663-87623280-0d4b-11eb-93e0-ea94ed04a233.png)
![Screen Shot 2020-10-12 at 11 03 06 PM](https://user-images.githubusercontent.com/25123758/95885678-8cbf7d00-0d4b-11eb-93ec-e3d8987b8b4f.png)

When I plot the results of this observer ("Total amount of dose-Alprazolam") against the existing observer "Applications|PO_0.5mg-Xanax_IR-Applications_1" (which seems to give the amount of unabsorbed drug?) the starting values for the two plots are totally different:

![Screen Shot 2020-10-12 at 11 04 04 PM](https://user-images.githubusercontent.com/25123758/95886593-c93fa880-0d4c-11eb-9648-b2a917c76182.png)

The mass of the initial dose (0.5mg) is 1.62 umol, which is the starting value of the "PO_0.5mg-Xanax_IR-Applications_1" observer, but the starting value for my observer is 3.24 umol.  I'm not sure how the starting value can be anything other than 1.62 umol (or maybe a smaller value?). What's wrong with the formula I defined? It seems like I am counting everything twice...

**Comment by tinydrummerkid** [comment]
Related, I am interested in calculating the total amount excreted/metabolized. Can this be done?

**Comment by Yuri05** [comment]
You observer is almost correct :)
The problem is: there are some molecule-related **parameters** in the simulation which are tagged with the name of "their" molecule - and they must be excluded from the "Total Amount"-Observer. 
You can see it if you e.g. export created simulation as text (_Create Simulation Report..._) and search for your observer - it will look like below
```
Observer: Total_Amount
	Path: S2|Organism|Alprazolam|Total_Amount
	Formula: M_1 + M_2 + M_3 + M_4 + M_5 + M_6 + M_7 + M_8 + M_9 + M_10 + M_11 + M_12 + M_13 + M_14 + M_15 + M_16 + M_17 + M_18 + M_19 + M_20 + M_21 + M_22 + M_23 + M_24 + M_25 + M_26 + M_27 + M_28 + M_29 + M_30 + M_31 + M_32 + M_33 + M_34 + M_35 + M_36 + M_37 + M_38 + M_39 + M_40 + M_41 + M_42 + M_43 + M_44 + M_45 + M_46 + M_47 + M_48 + M_49 + M_50 + M_51 + M_52 + M_53 + M_54 + M_55 + M_56 + M_57 + M_58 + M_59 + M_60 + M_61 + M_62 + M_63 + M_64 + M_65 + M_66 + M_67 + M_68 + M_69 + M_70 + M_71 + M_72 + M_73 + M_74 + M_75 + M_76 + M_77 + M_78 + M_79 + M_80 + M_81 + M_82 + M_83 + M_84 + M_85 + M_86 + M_87 + M_88 + M_89 + M_90 + M_91 + M_92 + M_93 + M_94 + M_95 + M_96 + M_97 + M_98 + M_99 + M_100 + M_101 + M_102 + M_103 + M_104 + M_105 + M_106 + M_107 + M_108 + M_109 + M_110 + M_111 + M_112 + M_113 + M_114 + M_115 + M_116 + M_117 + M_118 + M_119 + M_120 + M_121 + M_122 + M_123 + M_124 + M_125 + M_126 + M_127 + M_128 + M_129 + M_130 + M_131 + M_132 + M_133 + M_134 + M_135 + M_136 + M_137 + M_138 + M_139 + M_140 + M_141 + M_142 + M_143 + M_144 + M_145 + M_146 + M_147 + M_148 + M_149
		M_1: S2|Organism|VenousBlood|Plasma|Alprazolam(0 [µmol])
		M_2: S2|Organism|VenousBlood|BloodCells|Alprazolam(0 [µmol])
		M_3: S2|Organism|ArterialBlood|Plasma|Alprazolam(0 [µmol])
		...
		M_129: S2|Organism|Spleen|Intracellular|Alprazolam(0 [µmol])
		M_130: S2|Organism|Saliva|Saliva|Alprazolam(0 [µmol])
		M_131: S2|Organism|Saliva|SalivaGland|Alprazolam(0 [µmol])
		M_132: S2|Neighborhoods|Lumen_uje_UpperJejunum_pls|Alprazolam|DrugAbsorption_para|ProcessRate(0 [µmol/min])
		M_133: S2|Neighborhoods|Lumen_uje_UpperJejunum_cell|Alprazolam|DrugAbsorption_trans|ProcessRate(0 [µmol/min])
		...
		M_146: S2|Neighborhoods|Lumen_coldesc_ColonDescendens_cell|Alprazolam|DrugAbsorption_trans|ProcessRate(0 [µmol/min])
		M_147: S2|Neighborhoods|Lumen_colsigm_ColonSigmoid_cell|Alprazolam|DrugAbsorption_trans|ProcessRate(0 [µmol/min])
		M_148: S2|Applications|PO_0.5mg|Xanax_IR|Application_1|Alprazolam(1.61935452528622 [µmol])
		M_149: S2|Applications|PO_0.5mg|Xanax_IR|Application_1|ProtocolSchemaItem|DrugMass(1.61935452528622 [µmol])

```

* `Applications|PO_0.5mg|Xanax_IR|Application_1|ProtocolSchemaItem|DrugMass` is the **initial drug mass** of applied molecule. That's why the start value of your observer is 2*InitialDose. 
* Another wrongly added parameters are the so called "Process rates" of oral absorption processes (all the entries `Neighborhoods|...|ProcessRate`)

In order to remove unnesessary parameters from the resulting formula you should add some excluding conditions, e.g.
* Exclude everything below `ProtocolSchemaItem `container(s)
* Exclude everything below `Neighborhoods `container
![grafik](https://user-images.githubusercontent.com/25061876/95969781-711daa80-0e0f-11eb-9bb8-5e21185e0152.png)

Then you will get:
```
Observer: Total_Amount
	Path: S5|Organism|Alprazolam|Total_Amount
	Formula: M_1 + M_2 + M_3 + M_4 + M_5 + M_6 + M_7 + M_8 + M_9 + M_10 + M_11 + M_12 + M_13 + M_14 + M_15 + M_16 + M_17 + M_18 + M_19 + M_20 + M_21 + M_22 + M_23 + M_24 + M_25 + M_26 + M_27 + M_28 + M_29 + M_30 + M_31 + M_32 + M_33 + M_34 + M_35 + M_36 + M_37 + M_38 + M_39 + M_40 + M_41 + M_42 + M_43 + M_44 + M_45 + M_46 + M_47 + M_48 + M_49 + M_50 + M_51 + M_52 + M_53 + M_54 + M_55 + M_56 + M_57 + M_58 + M_59 + M_60 + M_61 + M_62 + M_63 + M_64 + M_65 + M_66 + M_67 + M_68 + M_69 + M_70 + M_71 + M_72 + M_73 + M_74 + M_75 + M_76 + M_77 + M_78 + M_79 + M_80 + M_81 + M_82 + M_83 + M_84 + M_85 + M_86 + M_87 + M_88 + M_89 + M_90 + M_91 + M_92 + M_93 + M_94 + M_95 + M_96 + M_97 + M_98 + M_99 + M_100 + M_101 + M_102 + M_103 + M_104 + M_105 + M_106 + M_107 + M_108 + M_109 + M_110 + M_111 + M_112 + M_113 + M_114 + M_115 + M_116 + M_117 + M_118 + M_119 + M_120 + M_121 + M_122 + M_123 + M_124 + M_125 + M_126 + M_127 + M_128 + M_129 + M_130 + M_131 + M_132
		M_1: S5|Organism|VenousBlood|Plasma|Alprazolam(0 [µmol])
        ...
		M_131: S5|Organism|Saliva|SalivaGland|Alprazolam(0 [µmol])
		M_132: S5|Applications|PO_0.5mg|Xanax_IR|Application_1|Alprazolam(1.61935452528622 [µmol])
```

**Comment by Yuri05** [comment]
@sfrechen @AndreDlm FYI

**Comment by DonkeySaddle** [comment]
@Yuri05 this is great - thanks so much. That clears it up!

**Comment by DonkeySaddle** [comment]
For anyone coming across this issue who is simply looking to calculate the total amount of drug, or some other molecule, in the organism, as opposed to the sum of the total amount of drug in the organism and the applications container (the green line in the plot above), I believe this correct:
![Properties](https://user-images.githubusercontent.com/25123758/96672406-34cbdc00-1332-11eb-98a2-39a9ed60ba75.png)
![Formula](https://user-images.githubusercontent.com/25123758/96672410-372e3600-1332-11eb-9634-0e2436702e4b.png)

**Comment by Yuri05** [comment]
@DonkeySaddle Yes, this is correct.
