### ISSUE TITLE
Interstitial:plasma partition coefficients are the same for all organs, but intracellular:plasma are different. Why?

### ISSUE THREAD

**Issue by eburg007** [Open-Systems-Pharmacology/Forum#630]
Basically the title. In my simulation, my interstitial:plasma partition coefficients are all = 0.96, while the intracellular:plasma range from 0.51 (bone) to 0.83 (lung and muscle).

I'm also a bit confused about why there is an intracellular:plasma partition coefficient in the first place, since this skips over the interstitial space? (unless intracellular refers to RBCs in this case?)

Thanks!

**Comment by StephanSchaller** [comment]
If you go through the literature in partitioning coefficients, you might find tissue:plasma partitioning. In PBPK, tissue is separated into intracellular and interstitial, which requires the partitioning coefficients between plasma, interstitial and intracellular.

The intracellular:plasma PC is kind of an artefact of this compartmental structure and is there as a "surrogate" for the tissue:plasma PC... for the interstitial:plasma PC, it is assumed that the composition of the interstitial space is similar between organs and thus you get the same value for all organs here...

For more details (and a more precise/technical explanation), please refer to the literature provided in the [documentation](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-compounds-definition-and-work-flow#adme-properties)

Best,
Stephan

**Comment by eburg007** [comment]
Thank you!!
