### ISSUE TITLE
Renal and Hepatic Specific CL.

### ISSUE THREAD

**Issue by Vichelfer** [Open-Systems-Pharmacology/Forum#632]
I am working with a molecule that is excreted by renal CL and other pathways, including hepatic CL. The renal CL is about 65% of the total CL. I don't have information about the enzymes responsible for the metabolism of this molecule, so I inputted the CL as follows:

For the Renal CL, I used "Renal CL -> Kidney Plasma CL" (and used the value of Renal CL from literature, divided by 70 kg).
For the rest of the CL, I inputted as "Total Hepatic CL -> Liver Plasma CL" (using total CL from literature minus renal CL divided by 70 kg).

Then I simulated the fraction excreted to urine for calculation of the renal CL. But I ended up having 80% renal CL. 
I don't know what I am doing wrong.

And also, if I run the Parameter Identification it gets better fitting the data, but it still ended up having about 80% of renal CL.

I was wondering if maybe it has to do with the way that the specific CL is calculated for the renal and hepatic CL? Because I was expecting that the proportion of renal CL and hepatic CL remains the same during the simulation like the one that I inputted as initial values.

**Comment by StephanSchaller** [comment]
Hi @Vichelfer ,

effective clearance will also depend on the tissue (or intracellular) concentrations and partitioning of your compound.
Maybe you can compare intracellular unbound concentrations in the two tissues and if liver concentrations are lower than in kidney, this might contribute to this unexpected shift in the fractions excreted/metabolized

Fitting will not explicitly change this.
You might create "observed data" of fraction excrted/metabolized and include it in your parameter identification (and re-fit the specific clearance rates).

**Comment by Vichelfer** [comment]
Thank you very much for clarifying that for me, @StephanSchaller!
It really helped! I'll try that!
