### ISSUE TITLE
How can I find the course to learn about the PK-sim software

### ISSUE THREAD

**Issue by Zhaowenyu-gaga** [Open-Systems-Pharmacology/Forum#634]
I am a novice for the knowledge about the PBPK model and found this software in this platform.

And my project is about an organic compound's metabolism in human body. We just want to observe the change of this compound in different organ under various time level. Could I use this software to get that? And how can I learn this software? I have downloaded this software but I did not find how to add my parameters

Thank you very much for your help. I am in such perplexed.

**Comment by StephanSchaller** [comment]
Please refer to the tutorials e.g. here:

http://www.open-systems-pharmacology.org/#tutorials

**Comment by Zhaowenyu-gaga** [comment]
Thank you very much for your answer, it really helped me.

By the way, could you please guide me whether this software can simulate the quantity of one chemical compound's residue in certain organs for animals after a few days' exposure, such as in the chicken (I did not find "chicken" option in the "individuals" part).

Thank you for your help in advance.

**Comment by StephanSchaller** [comment]
There are a number of different animals you can select from although chicken is currently not one of them.

A Chicken PBPK model is currently in development and will be released likely in apring/early summer 2021.

**Comment by Yuri05** [comment]
>A Chicken PBPK model is currently in development and will be released likely in apring/early summer 2021.

cool :)
<img width="150" src="https://user-images.githubusercontent.com/25061876/98053108-22749680-1e38-11eb-8989-7dc546d1080b.png">
