### ISSUE TITLE
Is chart editor not available in PK-Sim while conducting population simulations?

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#641]
![PK-Sim](https://user-images.githubusercontent.com/44484877/99202258-7490b280-277c-11eb-90d0-2d08585be638.jpg)
![Mobi](https://user-images.githubusercontent.com/44484877/99202261-765a7600-277c-11eb-83ed-6f9699644c93.jpg)

Hi!

I really appreciate that PK-Sim has really nice chart editor when I create an individual simulation (in top image) which allows us to modify axes, units, and pick time scale. But, I noticed that when I create population simulation (bottom pic), I don't have that same functionality of chart editor to edit my graphs right there. Am I missing something?

**Comment by msevestre** [comment]
@humblewarrior Both pictures are taken from PK-Sim. One is an individual simulation the other one is for a population simulation
Please explain what you mean

**Comment by humblewarrior** [comment]
@msevestre I will definitely keep in mind to post future discussions in the forum. I am extremely sorry, once again.

So, in an individual simulation (in top image), you see chart editor on right-hand side of the pic, which allows you modify your graph in variety of ways e.g. pick legend position, change color coding, change labels, change axis scales, pick a time scale etc etc.
However, when I do population simulation (in the bottom pic), you can see that chart options now don't have that functionality to allow me to modify my graph in a variety of ways.

**Comment by Ricardo-DO** [comment]
Hi

Probably the options of the population simulations are not as flexible as for the individual data but you can set the characteristics at the beginning of the simulation.

![pop1](https://user-images.githubusercontent.com/59565610/100469175-ae8f7c00-30cd-11eb-866e-bdc1fdca459c.png)

In the output tab you can change the colour of the lines, the scale, units and which statistics to plot.

I hope that helps.

Regards,
Ricardo
