### ISSUE TITLE
New Empty Model Repository Request

### ISSUE THREAD

**Issue by Bcicali** [Open-Systems-Pharmacology/Forum#642]
Drug: Levonorgestrel

Short Description: Whole-body PBPK model of levonorgestrel with and without ethinyl estradiol as CYP3A4 DDI victim drug

Topics: PBPK, Hormonal Contraceptives, DDI

Thank you!

**Comment by msevestre** [comment]
@Bcicali Received. Thanks

**Comment by msevestre** [comment]
done 
https://github.com/Open-Systems-Pharmacology/Levonorgestrel/
