### ISSUE TITLE
How to Apply GFR Formula?

### ISSUE THREAD

**Issue by Wenjing1018** [Open-Systems-Pharmacology/Forum#645]
Dear to all,
The GFR value in PK-Sim  is actually calculated according to the following formula. I wonder if the applicable age of this GFR is 30-100 years old? Do the FPMA、Vmax、TA50、Hill cofficient in the formula need to be changed at different age stages? Or between 30 and 100 years old, the FPMA is 26.6 ml/min/100g,Vmax is 0.9 ml/min/100g,TA50 was 59 years for
females and 54 years for males. The Hill coefficient was parameterized at 1.5, these values are fixed?
Sincerely!
![image](https://user-images.githubusercontent.com/63133525/100107203-5fb2ce00-2ea4-11eb-87d3-c2c4fcc6d4be.png)

**Comment by StephanSchaller** [comment]
@JanSchlender

**Comment by Wenjing1018** [comment]
@StephanSchaller,
I'm sorry I didn' t understand what's your meaning,Can you explain the details?
I would appreciate it !

**Comment by StephanSchaller** [comment]
> I'm sorry I didn' t understand what's your meaning,Can you explain the details?

I was only tagging another OSP community member (Jan Schlender) to prompt him to answer to this question as he is quite the expert on renal clearance in PK-Sim ;-)

**Comment by prvmalik** [comment]
I am attaching the full equation for specific GFR in PK-Sim. Specific GFR (mL/min/100g kidney) is then multiplied out by the individual's kidney volume to get the individual GFR.

The hill function for aging does not apply when age is less than 30. There is a piecewise limiter. 

In virtual populations, there is inter-individual variability on individual kidney volume, GFRmat, TM50 (maturation), and the Hill coefficient for maturation (H). These values can be viewed for each individual by exporting a virtual population to .csv format.

The Hill coefficient for aging is fixed at 1.5. The aging half-times (TA50) are fixed at 54 and 59 years for males and females, respectively. The maximal decreasing factor is fixed at 0.9 mL/min/100g kidney. The volume of the standard kidney (Vstd) is 440 mL. These values are the same for all individuals in the population. 

![GFRslide](https://user-images.githubusercontent.com/29066045/100376507-a2c48c80-2fdd-11eb-9bec-59074ae1b732.JPG)

**Comment by Wenjing1018** [comment]
@prvmalik 
Your detailed explanation is very useful to me, I also want to know the GFR how to be standardized by the individual BSA?for example, eGFR 90 ml/min/1.73m2, converted to GFR 90*1.73=155.7 ml/min,am I right?
Sincerely!

**Comment by prvmalik** [comment]
No. The GFR in mL/min in PKSim would be divided by the individual's BSA (Mosteller formula usually), and then multiplied by 1.73m2.

**Comment by Wenjing1018** [comment]
@prvmalik 
I think I understand very well. Thank you for your detailed answers！
Yours，
Sincerely！
