### ISSUE TITLE
Change binding processes expression in MoBi

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#654]
Dear all,

I would like your help to know if there is any trick to facilitate the implementation of changes in MoBi.
My problem is that I made a model in MoBi with a binding expressed in different organs including plasma and RBC. I also included some TMDD components in the model.
I now would like to change the expression of the binding partner, but I would like to import the new expression from PK-Sim without losing the reactions for TMDD which I have already included in the model.
I tried to import the simulation and just use the ''_Parameter start values_'' and the ''_Molecule start values_'' BB but by doing so it looks like I lose the TMDD component of the model (not sure why since the TMDD should be in the reaction BB...).
Do you have any recommendation on how to solve this problem?

Thanks in advance!

Best,

Donato

**Comment by msevestre** [comment]
@teutonicod 
Can you explain what you mean with 
> but by doing so it looks like I lose the TMDD component of the model (not sure why since the TMDD should be in the reaction BB...).

**Comment by teutonicod** [comment]
@msevestre 
What I ment was that when implementing the TMDD in the model (with turnover of the binding partner and degradation of the complex) I get in the simulation the typical profile of the TMDD. When on the other side I replace the parameter start value BB and the molecule start values BB coming from PK-Sim, I lose this behavior, also for parameterization similar to what I had before. I am not saying that MoBi does something wrong, I just meant that I thought MoBi took the information on the reactions from the reaction BB.
But if you want the main point of my question is: if I want to change the expression of a binding (also in tissues like plasma and RBC), is there an easy way to do it? Is it better to change manually the parameter in MoBi or to import it from PK-Sim? In this last case, how do you connect to a model already in place (with reactions, molecules,....) ?

**Comment by StephanSchaller** [comment]
Hi @teutonicod ,

normally this should work if you only added the TMDD reactions in MoBi when it worked (and you e.g. did not expand the spatial structure with a new organ or if you did not renamed one of the compounds).
Another way would be to save your reactions BB including the TMDD and reload it into your freshly exported PK-Sim simulation in MoBi.

Best,
Stephan

**Comment by teutonicod** [comment]
@StephanSchaller ,

Thanks a lot, it works now. Probably in some of the test before I renamed accidentally the process.
Best,

Donato
