### ISSUE TITLE
Getting the derivatives w.r.t. to time for a compartment

### ISSUE THREAD

**Issue by DonkeySaddle** [Open-Systems-Pharmacology/Forum#655]
New to PK-Sim/MoBi, was wondering if using MoBi I could get the derivative w.r.t time for the amount of drug/molecule in a compartment? 

If so, how do I do this?

**Comment by StephanSchaller** [comment]
Hi @DonkeySaddle , do you mean as the RHS of the differential equation (i.e. the formula) or just as a numeric value?

In any case, neither can be directly obtained in MoBi.

Technically, the first should be available on a ODE export to Matlab ODE (available in "Dev Mode" I believe (@Yuri05 , please comment), ant the latter could be obtained (as an approximation) by calculating the differential from simulation outputs in, e.g.,  R (or Matlab).

Best,
Stephan

**Comment by Yuri05** [comment]
Not much to add  - it's exactly as @StephanSchaller explained. S. https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Using-Matlab-Toolbox-with-PK-Sim-MoBi-Version-9.0-or-later#preparation for the instructions how to start PK-Sim/MoBi in "Developer mode"

@DonkeySaddle What for would you need such a derivative?

**Comment by DonkeySaddle** [comment]
Hey @StephanSchaller, this is exactly what I am after! Thanks so much. 

@Yuri05, Thank you! I am actually really interested in the RHS, for some reason I thought I would have better luck getting the derivative values. Am new to PK/PD modeling, and hoping to get a better understanding of what the models look like. 

Thanks again you two!

DS

**Comment by DonkeySaddle** [comment]
So I think I am close... I got the MoBi Matlab Toolbox and generated a XML file (with the MoBi shortcut) to be read into the Toolbox script **generateMatlabCodeForXML**. However, when I run the MatLab script and select the XML file I get this error:

![Screen Shot 2020-12-14 at 11 29 09 PM](https://user-images.githubusercontent.com/25123758/102171962-cb65d680-3e65-11eb-8007-036a59c86254.png)

I am sure this is all pretty obscure and dated, but figured it was worth a shot...

Thanks,
DS

**Comment by Yuri05** [comment]
Seems you did not add the path to the OSP Matlab toolbox to the Matlab search path. It must be added **incl. subfolders**.

**Comment by DonkeySaddle** [comment]
@Yuri05, thanks. Will see if I can't figure it out...nothing comes easy to me.

**Comment by DonkeySaddle** [comment]
I was ultimately able to get what I was after (the RHS of each compartment) by right clicking on the simulation I was interested in in MoBi and choosing "Export Simulation to Matlab Differential Equations"

![Export to Matlab](https://user-images.githubusercontent.com/25123758/103163174-81b3af00-47c8-11eb-8bd7-7f6c3cc4f0fd.png)

This created a number of Matlab scripts, one, in particular, titled "ODEMain" that had something like 367 RHS equations for the drug and its metabolites of the many PK-Sim/MoBi compartments (e.g. venous blood plasma). 

![RHS](https://user-images.githubusercontent.com/25123758/103163293-647fe000-47ca-11eb-898a-3fedd90ae5ab.png)

Another Matlab script, titled "ODEInitialValues" contained, not surprisingly, the initial value for each of the differential equations and, more importantly, comments with which compartment each RHS corresponded to. 

![Initial Values](https://user-images.githubusercontent.com/25123758/103163317-a446c780-47ca-11eb-9d54-df50309560b8.png)
