### ISSUE TITLE
Can physiological data for cat be added to PK-Sim?

### ISSUE THREAD

**Issue by Dieter08** [Open-Systems-Pharmacology/Forum#66]
For simulation of pets often used by animal health development departments the physiology of cat would be useful. Is any cat physiology data available?

**Comment by Yuri05** [comment]
Only proprietary cat physiology data is available, which cannot be published as part of open source software.

**Comment by msevestre** [comment]
@Dieter08 This would be a great contribution to the community by the way. :)

**Comment by msevestre** [comment]
I have created the following feature request https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/293

This is where community input could shine
