### ISSUE TITLE
Template Database help

### ISSUE THREAD

**Issue by nsutlian** [Open-Systems-Pharmacology/Forum#661]
I new to PK-Sim and still learning; I am currently working on the tutorial "PK Drug-Drug-Interaction: Simulating the DDI of rifampicin and midazolam"; I am unable to open any of the EX_DDI_RIF files since my version of PK-Sim is new and not compatible with those files. However, I am able to load from templates for the rifampicin and completed that portion. My issue is that when I try to load administration protocols, under predefined templates I only have a 25mg warfarin sodium protocol and rifampicin 600mg protocol and I do not have anything else listed. Same with observed data, I only have the Baneyx 2013 rifampin and Peloquin rifampin. Did I download incorrectly and I am missing these templates?

**Comment by msevestre** [comment]
@nsutlian 
Can you clarify
> I am unable to open any of the EX_DDI_RIF files since my version of PK-Sim is new 

PK-Sim is backward compatible and can open project starting with  version 6.0 which was released like 5 years ago+

Is it possible that the tutorials that you are using is asking you to use a specific template database ?
