### ISSUE TITLE
How to monitor total urinary process rates

### ISSUE THREAD

**Issue by Mitmischer** [Open-Systems-Pharmacology/Forum#666]
Hello,

I set up urinary clearance via tubular secretion in PK-Sim and exported the model to Mobi.
I have ~20 metabolites in the system and for ~each 10, I need to monitor the total secretion rate. Plotting would be nice to have, but availability in the R Toolbox would be fine.

In the passive transports tab, I found the Renal Clearances for each metabolite. I checked the "Create ... parameter on each" for each of them and I verified that those are plausible. They are located in the neighborhood between kidney plasma und urine:

![grafik](https://user-images.githubusercontent.com/774380/104340148-b0d05d00-54f8-11eb-9952-988b7a180d03.png)

Finally, I defined two custom parameters that add the process rate parameters. One of them looks like this:
![grafik](https://user-images.githubusercontent.com/774380/104340537-14f32100-54f9-11eb-9997-8b0e09f3a23b.png)

 However, this does not work. If I plot UrinaryRate_Deconj, it will be a constant 10 (which leads me to the conclustion that each `n_i` is just 1 and not updated. That confuses me as the rates themselves are plausible and _not_ 1 during the whole simulation. Am I doing something the wrong way or is that a bug?

**Comment by StephanSchaller** [comment]
The approach should be correct.

On first glance, you are missing an "n" in the formula:

![image](https://user-images.githubusercontent.com/25477643/104348347-ec235980-5501-11eb-8d32-ebfbefc374be.png)

likely the clearance rates are quite small (<< 1) and thus you don't see the change on top of the static "10" that is currently added in the formula.

Hope that helps,
Stephan

**Comment by Mitmischer** [comment]
Well, that's embarassing - you're right! Thanks a lot :)

**Comment by StephanSchaller** [comment]
No worries, it happens to the best ;-)
