### ISSUE TITLE
Zero order receptor recycling reaction

### ISSUE THREAD

**Issue by hsiebinga** [Open-Systems-Pharmacology/Forum#669]
Dear community,

I’ve been working on several PBPK protein models regarding a radionuclide used in clinical practice. Currently, I’m trying to optimize my tumor model (including 3 different tumor compartments). In short: the drug binds to a receptor on cell membranes (interstitial), after which the complex get internalized into the intracellular compartment. Then, unbinding of the complex takes place and the receptor is recycled back onto the membrane (or back to the interstitial space in MoBi).

I managed to include this receptor recycling reaction via a first order reaction in the Passive Transport building block (source: intracellular, target: interstitial and dN/dt = k_recycling * receptor_amount_intracellularly). However, I assume a 0 order reaction is more plausible, since this recycling of the receptor is not dependent on the receptor concentration. I tried changing the equation to: dN/dt = k_recycling, where k is amount/time or concentration/time. But this doesn’t seem to be correct, because I get an error running the simulation. After allowing negative values (just to check what was going on), I observed that this 0 order recycling reaction continues to take place, even if there is no amount of the receptor left intracellularly. Resulting in negative receptor intracellular amounts and way too high interstitial amounts.

Thus, my question is: how can I add a zero order receptor recycling reaction, which will no longer take place after the intracellular amount of the receptor is 0? Is it for example possible to include some sort of if statement in MoBi: if receptor amount > 0, then dN/dt = k?

Thanks for your help!

Hinke

**Comment by PavelBal** [comment]
Dear Hinke,

yes you can define the rate equation as

`n_receptor > 0 ? k : 0`

This is a conditional expression of the form `condition ? value if TRUE : value if FALSE`.

However, I can imagine that such rate equation could result in numerical problems. Instead, I would you something like

`k * n_receptor / (Km + n_receptor)`

with a very low `Km`.

**Comment by hsiebinga** [comment]
Dear Pavel,

Thanks so much for your quick and useful reply. I tried to run your first suggestion and indeed I get an error solving ODE. Is there a way to change the solver settings in some way to fix this?

If not, I will try to implement the latter suggestion. Still I have an additional question regarding the Km you suggest to use, just also to check if I understood you correctly. Is Km an amount value (like 0.0001 nmol), so that the equation is devided by a very low value at low concentrations, resulting in a very small rate (almost neglectable)?

Thanks again for you help, really appreciated!

Hinke

**Comment by PavelBal** [comment]
You can reduce the value of `AbsTol` (e.g. to 1e-13 or even 1e-15) located under Simulation Settigns -> Solver Settings:

![image](https://user-images.githubusercontent.com/25903040/104709661-7eed0f80-571f-11eb-8b9e-17e01c69f939.png)


For the second part - yes, exactly, the rate will decline when the amount of the receptor converges towards zero.

**Comment by hsiebinga** [comment]
Adjustments of the solver settings didn't seem to work, but your second suggestions works perfectly!

Thanks again!
