### ISSUE TITLE
Kinetics of a DDI (Alprazolam and Itraconazole)

### ISSUE THREAD

**Issue by DonkeySaddle** [Open-Systems-Pharmacology/Forum#673]
I am trying to create a simulation with a DDI. I have chosen Alprazolam and Itraconazole. I believe Itraconazole will inhibit CYP3A4 and effectively increase the amount of Alprazolam (and perhaps vice-versa?). 

Anyways, is there a way I can identify how the kinetics of the ADME processes have changed given the interaction(s). For example, I would love to see if the RHS's (and their parameters) of any of the compartments have changed (looking at the code I exported to MATLAB form MOBI it doesn't look like they have, though there a lot of equations...perhaps I missed something). E.g., shouldn't there be some RHS, or variable definition, that uses both Drugs. I have been able to discern that an interaction is occurring, just by comparing the results I got from a simulation with Alprazolam and no Itraconazole, but I want to better understand what is happening and where it's happening (presumably the CYP3A4 in the liver is less available because it is being tied up by Itraconozale).  

Thanks,

DS

**Comment by DonkeySaddle** [comment]
For anyone who runs into this, I believe the parameters in the RHS's do in fact contain all the relevant information. For example, in this case the Km_app parameters (the Michaelis constant?) for the Alprazolam metabolites are different. Specifically, the "Km interaction factor" parameter (one of the two parameters that defines the Km_app parameter) goes from being 1 (the case where there is no interaction) to dynamic (it is defined using various RHS's for Itraconazole and its metabolites). 

Hope that makes sense and, even more, that it's correct...

DS

**Comment by StephanSchaller** [comment]
Yes, the differences are visible in detail in MoBi (export from PK-Sim) within the Reactions Building Block.

A DDI mechanism might change the reaction network and affect formulas for certain parameters (e.g. how Km_app is calculated including Ki values as mentioned by DS above).

Best,
Stephan
