### ISSUE TITLE
Run PBPK model from Excel data with various input parameters

### ISSUE THREAD

**Issue by MTHuisman** [Open-Systems-Pharmacology/Forum#674]
Dear All,

I'm somewhat of an on/off user of PK-Sim (as I'm driven by demand). I'm almost done with a PBPK model for 1 compound with optimized parameters (based on in vivo rat data). I'm still working on the PD-aspect (in MoBi). 

As a next step, I'd like to be able to load the parameters from an Excel file, from e.g. 10 new compounds (e.g. LogP, Papp, MW, RLM, potency) and get PK/target occupancy as an output. I've done such a thing in the past, but can't find back how I did it... So, basically, I'd like to re-run the same PBPK model with a different set of input values and predict PK and target occupancy for a batch of compounds (ideally from Excel input, or a CSV-file). 

If someone could point me in the right direction, I'd be very appreciative. :-)

Having asked that, I'd like to express my gratitude that this software is available (and is becoming ever better). 
Kind regards,
Maarten

**Comment by StephanSchaller** [comment]
Dear Maarten,

good to see you are still using the Software.
If I understand correctly, you are looking for an option to import different sets of parameters to MoBi.

1. You can directly load a set to an existing Simulation:
![image](https://user-images.githubusercontent.com/25477643/105984851-00875a80-609b-11eb-9634-3ad5b9df3c62.png)

2. You can import Parameter Start Values (PSVs) into your PSV Building Blocks (and then update/create your simulations from it):
![image](https://user-images.githubusercontent.com/25477643/105985023-375d7080-609b-11eb-978b-2f6cba1b08b1.png)

Best,
Stephan

**Comment by MTHuisman** [comment]
Dear Stephan,
Thank you for your prompt reply and clear explanation. I do think that this will make it work. I'll give it a try and 'close the comment', if it works 👍 
Kind regards,
Maarten

**Comment by MTHuisman** [comment]
![image](https://user-images.githubusercontent.com/38977503/106004075-20c31380-60b3-11eb-8fc4-22510fd86f60.png)


Hi Stephan,
Thanks again, that did put me in the right direction, but I still need to tackle a few steps. What is the format I should choose (like to top panel, or the bottom panel). Ideally, I'm able to include e.g. 5 molecules at the same time, each with their properties (logP, MW, Papp etc). 

Alternatively, now that've been trying this today (all day really...) I recall that during the course you (or Pavel), mentioned the model can be exported to R-studio and then you can run parallel simulations with varying input/starting parameters. Could that be a better approach?

Thanking you in advance,
Maarten

**Comment by StephanSchaller** [comment]
The top panel would be the format to choose.
You will have to do the import separately for each of the 5 settings (i.e., compound properties). Likewise I would recommend to "clone" the PSV or Simulation (depending on if you do the import on the PSV or Simulation level) and then create a simulation for each scenario.

> Alternatively, now that've been trying this today (all day really...) I recall that during the course you (or Pavel), mentioned the model can be exported to R-studio and then you can run parallel simulations with varying input/starting parameters. Could that be a better approach?

Yes, this would definitely be the ideal (and more convenient) approach. You then just have to run the scenarios and load the respective parameters in a loop or in parallel. This is especially useful if you want to re-use this kind of set-up.

Best,
Stephan

**Comment by MTHuisman** [comment]
Thank you so much! Please see your PM in LinkedIn.
