### ISSUE TITLE
Is The Maximum Number Of MOBI Observations 5001? 

### ISSUE THREAD

**Issue by DonkeySaddle** [Open-Systems-Pharmacology/Forum#677]
Is there a maximum number of observations that a simulation will generate? Regardless of the resolution I set and the time I run my simulations for, the maximum number of observations I can get is 5001. Is there a way to change this?

To be clear, If in "Output Intervals" I set the "Resolution" to 60pts/h, the "Start Time" to 0, and the "End Time" to 100, when I export the simulation to Excel there will only be 5001 rows in my sheet (NOT 6001) and the observations(concentrations or amounts) do not occur at 1 minute intervals.

**Comment by msevestre** [comment]
Hi @DonkeySaddle ,

Yes there is a maximum number of generated points **per** interval.
[max is 500](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Constants.cs#L14)

Our experience is that there is absolutely no need to have such a high density of points for the whole simulation time. It just bloats (in general) the memory and project size for nothing and can reduce significantly charting performance.

If you need to have a very high density of points in a specific time range of your simulation (for instance right after an application), you can add a simulation interval. 

If you really need to have 1pts per hour for 100 hours like in your example, then create multiple intervals. Each interval can have up to 5000 points so you could create one from 1 to 50h and one from 50 to 100 and you should be good to go. However, see above for performance issues

**Comment by DonkeySaddle** [comment]
@msevestre Thank You!
