### ISSUE TITLE
Absorption model for PKSIM - what is it called?

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#68]
Is there a name for absorption model used in PKSIM?
Similar to Simcyp - ADAM 

kind regards
mouli

**Comment by msevestre** [comment]
Model published here

[Evolution of a detailed physiological model to simulate the gastrointestinal transit and absorption process in humans, part 1: oral solutions.](https://www.ncbi.nlm.nih.gov/pubmed/21993815)

If there is a name for it, it should be in there :)
