### ISSUE TITLE
simulation in MoBi: concentrations and amounts do not match

### ISSUE THREAD

**Issue by Mitmischer** [Open-Systems-Pharmacology/Forum#686]
Hello,

in my particular simulation, I have the following values for my compound TCA and for the caecum (all in MoBi default units)
Organism|Lumen|Caecum|TCA: 0.9027149 µmol
Organism|Lumen|Caecum|TCA|Concentration in lumen: 12701.01 µmol/l.
Organism|Lumen|Caecum|Volume: 0.000487745349439205 l.

If multiply the volume and the concentration, I get 6.1942777 µmol which differs a lot from 
Organism|Lumen|Caecum|TCA. What's wrong here?

I can provide the model if that helps.

**Comment by StephanSchaller** [comment]
The relevant Volume from which concentrations in Lumen are calculated is "Liquid Volume":

![image](https://user-images.githubusercontent.com/25477643/109438669-42eddf80-7a2b-11eb-99a0-8221431c0462.png)

**Comment by Mitmischer** [comment]
That explains it, thank you :)
