### ISSUE TITLE
Can we use the Matlab Toolbox with PK-Sim V9?

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/Forum#690]
Dear all,

I think my question is already in the title :-)
I am using PK-Sim version 9 and I would like to know if you can export the simulation and read it with the old Matlab toolbox from version 8. I have seen that in v9 there isn't anymore the option to export the equations in Matlab or the export as xml file. Is the pkml the only way to export models now? Can this file format be used in Matlab?

Thanks a lot in advance for your help!

Donato

**Comment by StephanSchaller** [comment]
You have to run it in Developer Mode ;-)

**Comment by teutonicod** [comment]
How can I do that? Will it allow me to export the simulation in a compatible format? like xml?

**Comment by Yuri05** [comment]
>You have to run it in Developer Mode

Exactly. S. [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Using-Matlab-Toolbox-with-PK-Sim-MoBi-Version-9.0-or-later) for details.

>Is the pkml the only way to export models now? Can this file format be used in Matlab?

No, `pkml `cannot be used in Matlab. 

From the [OSP Suite 9 Release Notes](https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/v9.1):
![grafik](https://user-images.githubusercontent.com/25061876/110107799-a9685a00-7dab-11eb-916b-85cf37c2e887.png)

**Comment by teutonicod** [comment]
Great! Thanks a lot @Yuri05 and @StephanSchaller !
