### ISSUE TITLE
Sharing our newly developed models

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/Forum#691]
Hello, we want to share our newly developed quetiapine and aripiprazole PBPK models. Would you please creat empty model repositories? @Yuri05

**Comment by Yuri05** [comment]
@regulus92 done
https://github.com/Open-Systems-Pharmacology/Quetiapine-Model
https://github.com/Open-Systems-Pharmacology/Aripiprazole-Model
