### ISSUE TITLE
Where to find the reference of ontogeny factor for albumin or AGG?

### ISSUE THREAD

**Issue by Celin7391** [Open-Systems-Pharmacology/Forum#698]
So I want to set a range for ontogeny factor (albumin), but I could not find any reference to get the range. Is it good to set 0.1-100?

**Comment by Celin7391** [comment]
Hi everyone! Our team is focused on the reason why PK-SIM predicted acidic highly bound drugs poorly, especially in the distribution phase. So we want to investigate the albumin-related factors such as plasma protein scale factor, ontogeny factor (albumin). However, we could not find any reference to investigate the ontogeny factor. e.g. How to set the boundary for ontogeny factor in parameter identification?

**Comment by Incei** [comment]
Hi Celin7391,

There is documentation on the ontogeny of human serum albumin located under this repository : https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation , called  [PK-Sim® Ontogeny Database documentation. ](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/blob/master/PK-Sim%20Ontogeny%20Database%20Version%207.3.pdf )

The ontogeny is described on page 45-46 of the document. On page 47 you can find the ontogeny and info for AGP.

This ontogeny factor is automatically set in pk-sim, based on the age you are simulating. Hope that helps.

**Comment by Celin7391** [comment]
Thank you Incei!
Cannot express how much gratitude I have.... I have been stuck in here for a whole week. Thank you soooo much!!!!!
