### ISSUE TITLE
Prediction line

### ISSUE THREAD

**Issue by melagha** [Open-Systems-Pharmacology/Forum#699]
Hello all,
I am working on  a model for DDI where the observation collected up to 72 hours. When running the simulation, the prediction line covers only 24 hours. Anyone knows how to change the graph setting to allow visualizing the prediction line to cover desired time?

Best regards

**Comment by msevestre** [comment]
@melagha Change the simulation time of your simulation
see https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#running-a-simulation-in-an-individual

**Comment by melagha** [comment]
Great. Really appreciate your help and time.
