### ISSUE TITLE
parameter identification error 

### ISSUE THREAD

**Issue by nmidde** [Open-Systems-Pharmacology/Forum#70]
Hello,
When I tried to use parameter identification I am running into 'Faulted' status. I am not sure whether I am doing something wrong or it is something else. Please see the attached image. Thanks for your help.
![image](https://user-images.githubusercontent.com/29755212/29928449-0c535600-8e37-11e7-8214-94e8610079c2.png)

Best,
Narasimha

**Comment by msevestre** [comment]
@nmidde 
According to the error, it seems that you are trying to simulate some negative time.
Would it be possible for you to attach your project so that we can take a look? 
Cheers,

**Comment by nmidde** [comment]
Thank you msevestre. Yes, you are right I have a negative predose time value in my observed data. Once I removed that I was able to run the optimization. Thank you so much for your response. Have a great day! Best, 
Narasimha

**Comment by PavelBal** [comment]
Is there an issue entry for this somewhere? I think this behavior should be changed (ignoring negative values in the PI).

**Comment by Yuri05** [comment]
>I think this behavior should be changed (ignoring negative values in the PI).

Agree. Please create an issue

**Comment by msevestre** [comment]
Do you mean PK-sim should ignore data point with negative time?

**Comment by PavelBal** [comment]
> Do you mean PK-sim should ignore data point with negative time?

Yes

**Comment by TheiBa** [comment]
Ignore or take as t=0? Often negative times are taken as pre-dose information (confirm that nothing is left after a wash-out phase, or “normal” value for endogenous substances, or …). This may require case-specific considerations, especially if there is more than one pre-dose value. We may not want to cover for all options in PK-Sim, but indeed ignore. In case, we should provide a warning in PK-Sim though (like negative time values ignored) … which is better than throwing an error.

**Comment by PavelBal** [comment]
> Ignore or take as t=0? 

Ignore, for the reasons you mentioned.
