### ISSUE TITLE
Issues: Obese population, GOF plot and Renal impairment population

### ISSUE THREAD

**Issue by vbalbas** [Open-Systems-Pharmacology/Forum#71]
Dear all, 

I am simulating PK data using PBPK model. I want to obtain the PK profile different individuals and compare the output using data coming from a clinical trial. I have a few questions that maybe you could help me with: 

1. I have an Obese patient in my clinical trial data set. PKSim creates properly an individual with its specific characteristics (gender, age, height and weight). But when I create 200 ID population (either from healthy subject or the previously generated ID) with the same specific ID characteristics, PKSim crashes with the following warning: 

![image](https://user-images.githubusercontent.com/16211975/29981650-c9b43b48-8f4e-11e7-9dc5-61ce8e622753.png)

How may I create a 200 ID population with the obese patient characteristics? 

2. Is there a way in which I can plot model predicted concentration vs my data **(GOF Plot)** for all the simulated ID I have?

3.  Is there a **rapid alternative** in which I can **simulate different IDs** from the same data set? (by uploading a data set with NONMEM format, for example). Or should I create an administration protocol, a specific population and a simulation per each ID?

4. Is there a possibility of **simulating different degree of Renal impairment**? (not only by updating GFR per ID).

Thank you in advance
Kind regards
Violeta
``

**Comment by msevestre** [comment]
Hi @vbalbas,

Regarding 1: This is a bug. 
Could you please send a screenshot of the settings that you used to created your obese Individual as well as the settings you used to create the population

2/ Cannot you use observed data import for that? You can display these data in individual and population simulation concentration plots

3/ Can you explain what you mean with IDs from the same data set? Are you asking if there is a way to create a bunch of unrelated individuals and administration protocols automatically?

Thanks,
Michael

**Comment by JanSchlender** [comment]
Hi Violeta,

4. Currently, there is no build-in template provided for different stages of renal impairment. Solely adapting GFR will by far not meet the complexity of this disease. Not only renal parameters need to be adjusted but also the crosstalk of the hepato-renal axis should be considered. 

Best,
Jan

**Comment by vbalbas** [comment]
Hi @msevestre, 

1. The settings I used to create both, my obese individual and the obese population are: 

      ![image](https://user-images.githubusercontent.com/16211975/30016381-2b7454aa-9155-11e7-9865-7147cf0642bb.png)

2. Yes, I can add observed data to plot of simulated concentration vs time. I´m referring to plot concentration vs concentration, which I know I can obtain after estimating a parameter. But in my case, I just would like to obtain this plot, collecting all my individual data (observed) and their simulated mean concentration (predicted) for model evaluation:

      ![image](https://user-images.githubusercontent.com/16211975/30016414-556a2f32-9155-11e7-94c2-abc809f2bb2b.png)

3. Yes, that is what I meant. 

Hi @JanSchlender, 
 
4. I understand that only by altering GFR, renal impairment is not captured. For that reason I was asking if there would be a renal impairment build-in template provided in PKSim. As there is not, would you, by any chance, any publication where renal impairment is simulated using PKSim? 

Thank you @msevestre and @JanSchlender, 

Best, 
Violeta

**Comment by msevestre** [comment]
@vbalbas 

1. What about the population settings? What ranges did you use? Could you post a screenshot as well?

2. I see. No those plots are not available at the moment outside of  the  parameter identification. Would you please add a feature request for PK-Sim explaining your use case?

3. No this is also not available at the moment. This was in the pipeline at some points but the momentum was lost before of a lack of interest at the time. I would appreciate if you could also add a feature request for that.

Cheers,

**Comment by vbalbas** [comment]
Hi @msevestre,

1. For the population are exactly the same values for the specific ID, so there are not ranges (I wanted to simulate 200 ID with similar characteristics than for my specific ID). 

      ![image](https://user-images.githubusercontent.com/16211975/30030057-ea5835fe-918b-11e7-9a09-f1942850e61a.png)
 
2 -3. I will add a feature for each one. 

Thank you very much for your early reply. 

Best,
Violeta

**Comment by msevestre** [comment]
@vbalbas 
I see thanks. PK-Sim should definitely not crash (I will create a bug report for that).
Would you mind explaining your use case ?e.g. Why do you need to create 200 (almost) identical individuals? Unless you have some user defined variability in your population, the only variability you will get out of this population is in SA and Q and some few other parameters).

**Comment by vbalbas** [comment]
@msevestre
Just to see how good is the model prediction for 200 ID (almost identical), comparing the prediction with my data for the specific ID, but taking into account the variability for those mentioned parameters.  

As an example:

**Simulation of 200 ID with the sameage,  weight, and height:**    
      ![image](https://user-images.githubusercontent.com/16211975/30032457-590bd0c8-9196-11e7-8f1d-3d263bd6d6f9.png)

**Comment by StephanSchaller** [comment]
@vbalbas, great thread!

1. Take into consideration, that even though you can create a "heavy" population in PKSim, they may not reflect the pathophysiology of obese patients (blood flow, fat/muscle distribution). But it's a start. An Obese population should be another feature request.

2. & 3. Great feature requests. Especially 3. has great potential aspecially if we want to use PKSim for analysis of Phase III Datasets.

4. I believe there are a number of publications that have covered renal impaired:
- https://www.ncbi.nlm.nih.gov/pubmed/18840029 (mostly hepatic but also covers renal)
- https://www.ncbi.nlm.nih.gov/pubmed/24912798
- https://www.ncbi.nlm.nih.gov/pubmed/28738449 and maybe 
- https://www.ncbi.nlm.nih.gov/pubmed/24214317

**Comment by vbalbas** [comment]
Hi @StephanSchaller, 

Thank you very much for your comments and for the suggested publications. They are very interesting indeed. 

Best,
Violeta

**Comment by msrinivasan1** [comment]
Dear @vbalbas 

I found this paper that might help for model building in obesity

https://link.springer.com/article/10.2165%2F11594420-000000000-00000

**Comment by vbalbas** [comment]
Thank you @msrinivasan1!

**Comment by msrinivasan1** [comment]
Dear @msevestre ,

I have published PK data from only ONE obese individual in a case report. I would like to build a model on PKSim to understand how to dose the drug in that population. What should my general strategy be to build this model?

**Comment by msevestre** [comment]
@msrinivasan1 Please try to create one entry for each question you have. This will help other users in the community to find answer to similar questions.
In the meantime, check the [best practices](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5080648/pdf/PSP4-5-516.pdf) to get started with PK-Sim

**Comment by msrinivasan1** [comment]
Dear @msevestre ,

1. I created a virtual patient population 100 patients weighting between 90- 165 kgs in weight. 
2. I put in all the drug related information, administration information and simulated the conc-time profile 
3. However, I'm getting a Cmax of the drug at 0.02 umol/L. It is really small as compared to the data in the literature.

Any idea what I am missing here?

**Comment by msevestre** [comment]
Please create a new entry explaining your issue as requested. Thanks for your efforts
