### ISSUE TITLE
Batch import of administration protocols

### ISSUE THREAD

**Issue by NinaHanke** [Open-Systems-Pharmacology/Forum#722]
Dear developers, dear masters of the R-toolbox, 

We would like to batch-import individual administration protocols from a NONMEM dataset or excel file. 
As in oncology projects patients often get personalized administration (doses, intervals, dosing times), an R-tool or PK-Sim function to import all these administration protocols in one go (like for batch import of observed data) would safe us so much time and would also ensure reproducibility. 

Do you have or work on something like this? 
XXX, Nina

**Comment by Yuri05** [comment]
@AndreDlm @sfrechen You have done smthg like that, right?

**Comment by NinaHanke** [comment]
Dear André and Juri, 

Many thanks for your ultra rapid replies! 
We saw the post on the snapshot and json file (#305), but I did not understand how to generate 50 different multiple-dose administration protocols with that. 

How do I decide if I use the R toolbox or the snapshot method? Are there differences? 
Thx again, LG, Nina

**Comment by AndreDlm** [comment]
Well, with `jsonlite` in R you could read in a pre-existing admin snapshot, overwrite all relevant values (dose, admin times - which would be taken from the Excel sheet), export the modified snapshot as `json` file no. 1 and repeat the process _n_ times until you have your 50 admin protocols. 
The decision on whether to use the R toolbox or not probably depends on your familiarity with the toolbox/R and whether you want to have the simulation results in PK-Sim or not?

**Comment by NinaHanke** [comment]
Ok, that was very helpful! 
We will go with the json files and snapshots then, to get Simulations in PK-Sim. 
Thanks again 👍 👍 👍

**Comment by NinaHanke** [comment]
Dear André and Juri, 
It worked beautifully (Ghazal and I combined our R and PK-Sim expertises) and I am in love with snapshots now :)
Thanks again!!!
Nina

**Comment by AndreDlm** [comment]
Good to hear this! I guess the issue can then be closed? Otherwise please re-open

**Comment by GhazalMontaseri** [comment]
Dear André and Juri, 
many thanks for your great supports and valuable helps. We could successfully define our individualized dose administration protocols. 
Kind regards, Ghazal
