### ISSUE TITLE
Hepatic flood flow

### ISSUE THREAD

**Issue by flyhighyj** [Open-Systems-Pharmacology/Forum#725]
Hi all,

I have a question regarding hepatic blood flow in adults. 
I created a virtual adult population n=1000. The mean specific liver blood flow is 0.205 L/min/Kg organ and the liver volume is 1.95 L. Assuming the density of 1 Kg/L, the liver blood flow is calculated to be 400 mL/min. 
Hepatic blood flow in adults is lower than the literature value of 1640 mL/min. 
Will you please help me to calculate hepatic blood flow correctly from a virtual population?
Thank you.

**Comment by StephanSchaller** [comment]
Dear @flyhighyj ,

the listed liver blood flow is only arterial flow. you have to add portal vein blood flow to get total blood flow.
Total blood flow should then align very well with literature values.

Hope this helps,
Stephan

**Comment by flyhighyj** [comment]
> Dear @flyhighyj ,
> 
> the listed liver blood flow is only arterial flow. you have to add portal vein blood flow to get total blood flow.
> Total blood flow should then align very well with literature values.
> 
> Hope this helps,
> Stephan
