### ISSUE TITLE
Relationship between PKSIM.Core.Model and OSPSUITE.SimModel

### ISSUE THREAD

**Issue by Annum-Z** [Open-Systems-Pharmacology/Forum#73]
Dear Sir,

I have a question regarding the compilation of the PKSim software. If I am correct, The calculation engine for the Simulation is found in the OSPSuite.SimModel (which are a couple of c++ files like DESolver.cpp or SimulationTask.cpp). However, after the compilation, I see c# files from the PKSim.Core.Model, and my original thought was that there exists a relationship between the PKSIM.Core.Model and OSPSUITE.SimModel. However, there seems to be no declaration from the OSPSUITE.SimModel in the  PKSIM.Core.Model. So, I was wondering how is the Simulation being generated without any reference to the calculation engine which is OSPSUITE.SimModel ? Or would I be missing some crucial detail here ?

Thank you !

**Comment by Yuri05** [comment]
>If I am correct, The calculation engine for the Simulation is found in the OSPSuite.SimModel

Correct.

>So, I was wondering how is the Simulation being generated without any reference to the calculation engine which is c 

`OSPSUITE.SimModel` is referenced and used in the `OSPSuite.Core` (s. e.g. [SimModelManager.cs](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Services/SimModelManager.cs)). `OSPSuite.Core` is the central component of the OSP Suite which encapsulates functionalities common for both PK-Sim and MoBi (Model Building, Model evaluation, Parameter Identification, Sensitivity Analysis and so on)
