### ISSUE TITLE
Parameter identification using Nelder-Mead - "MoBi toolbox for Matlab" VS "MoBi"

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#75]
Dear Community,

At the moment i am trying to re-identify parameters within MoBi that I initially (more than 1.5 years ago) identified using the MoBi toolbox for Matlab. 
In my past work (toolbox for Matlab) I used Nelder-Mead with a parameter parameter range. Now that I am using the parameter identification from within MoBi i have some issues identifiying the same parameter values as a year ago with the MoBi toolbox for Matlab.

I think that I configured the identification correctly in MoBi (e.g. linear/log scaling) - I used the same simulations and the same observed data.

Now my question is if I can reproduce the old parameter values from within MoBi? 
Do you have any experience on that? 
Is the Nelder algorithm in MoBi exactly the same as the one used in the MoBi toolbox for Matlab?

I'd very much appreciate your experience on that issue :)

Best 
Daniel

**Comment by PavelBal** [comment]
In my experience, the curret Nelder-Mead (and also the LM) in MoBi behaves completely different from that in the old ToolBox. In MoBi, it ignores the boundary values of the parameters, which is, according to documentation, the correct behavior (unconstrained algo). However, the Nelder-Mead in the old ToolBox very rarely quit the defined range - actually so rare that I thought it was a bug.

Unfortunately, I could not find a way to obtain identical identification results in MoBi and Matlab/R.

**Comment by DanielMoj** [comment]
Hi PavelBal,

thank you very much for your response! 
It is reassuring to know that you can confirm my finding!

Did other users have different experiences?

**Comment by msevestre** [comment]
@DanielMoj I had various results trying to compare old and new optimization. In some instances, results were almost identical. In other, the optimal values were widely different. 

Now I have a few questions for you: 
* Why do you absolutely want to reproduce the old values? 
* How do old and new error compare?
* What happens if you start the optimizer in MoBi with your older *BEST* results. Is the outcome different? Or is MoBi still finding the same solution has before?

**Comment by DanielMoj** [comment]
@msevestre thank you very much for sharing your experience!

Now to the questions :)

1. I want to reproduce them to be sure that my results (conclusions and so on) of the previously developed models are also valid if I had used the open source version.
2. I have to check the errors!
3. Most but not all newly identified values are within a ~15% range from the mobi toolbox PI vlaues, But it seems to be highly dependent on the starting values!

**Comment by TheiBa** [comment]
Hi Daniel,

some thoughts from my side. 1. of course makes perfect sense. 3. may be something to think about in the context of sensitivity and identifiability. Is model performance according to your expectation with different parameter sets, i.e. are you satisfied? If so, what do different sets tell you? 15% is close by on the one hand, but on the other hand, for a sensitive parameter this can already make some difference in results, which in that case is probably compensated by other parameter changes. Are these correlations a problem for what you want to do with the model? For example, if you want to predict something, how dependent are the predictions on the chosen values? Or may it make sense to fix some correlated parameters, e.g. based on prior knowledge? For other thoughts a description of your model may help – complexities, number of parameters you try to identify based on what kind of data … 

Cheers,
Thomas

**Comment by DanielMoj** [comment]
Hi Thomas,

thank you for all the good thoughts and impulses! I guess we have to discuss further internally, especially whether the ~15% deviation is indeed an issue for us. As soon as we have made up our minds and decided how to proceed I can share our trail of thoughts on what we decided and how we came to our decision. May help others :)

Best,
Daniel

**Comment by TheiBa** [comment]
Dear Daniel,



Sounds good. And sharing your thoughts and experience, is always good and 
welcome in a community ;-)



Cheers,
Thomas

**Comment by msevestre** [comment]
Closing. Please let us know if you have any more questions
