### ISSUE TITLE
"MoBi toolbox for Matlab" VS "MoBi" - Parameter identification -> Parameter Scaling?

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#76]
Dear OSP users,

in the "MoBi toolbox for Matlab" it was possible to leave the parameter scaling field blank. In the MoBi parameter identification one is forced to select either "log" or "linear".

My question is what the MoBi toolbox for Matlab assumed in case one left the parameter blank (log or linear)?

Thank you very much in advance!
Daniel

**Comment by Yuri05** [comment]
>in the "MoBi toolbox for Matlab" it was possible to leave the parameter scaling field blank.

it was clearly a bug and the program behavior was ambiguous. 
Most functions interpreted it as linear but in some functions it was interpreted as log
