### ISSUE TITLE
Extend PBPK Model to add tumor

### ISSUE THREAD

**Issue by drfreedman** [Open-Systems-Pharmacology/Forum#77]
I followed the suggested workflow documented in this forum to add a Tumor container by importing a saved representative Organ. 

 The Organ did not import successfully in that although all the neighborhoods were shown and I renamed them appropriately, new Organ did not appear in the list of Spatial Structures.

Please provide a clear explanation of all the steps required to extend a PBPK model by adding an Organ or Tissue.

Regards,

Immanuel Freedman, Ph.D SMIEEE

**Comment by msevestre** [comment]
Hi @drfreedman ,

The new organ will not appear in the list of spatial structure. Instead it will be added into the existing spatial structure from which the **load container from file** was initiated.

Let me know if you have more questions,

Bests,
Michael

**Comment by msevestre** [comment]
@drfreedman Closing. Please reopen if you have more questions
