### ISSUE TITLE
Introduction to PK-Sim

### ISSUE THREAD

**Issue by anujadhas** [Open-Systems-Pharmacology/Forum#78]
Hello Everyone,
I am new for PK-Sim Software. 
I want little help on how to import data sets & its output Prediction.

Any Literature is available for Introduction of PK-Sim & a Step-Wise procedure of simulation as i don't programming background.
# #

**Comment by TheiBa** [comment]
Dear Anujadhas,

No programming required to import data. Just clicking the right buttons and choosing the right settings – and starting with a reasonable structured data-set. Details on HowTo should be in the manual. If questions remain, you can maybe specify them further.  

Best,

Thomas

**Comment by anujadhas** [comment]
Hello,
I don't have any manual. Can you please send me the link of the same.

**Comment by TheiBa** [comment]
For example, hit F1, like in most software solutions … PDF is also on GitHub as well as in your general program menu within OSP and in the installation folder …

**Comment by msevestre** [comment]
@anujadhas PDF can be found [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/blob/master/Open%20Systems%20Pharmacology%20Suite.pdf)

**Comment by anujadhas** [comment]
@TheiBa @msevestre Thank You... It really helped me.
