### ISSUE TITLE
Changing the dose in MoBi

### ISSUE THREAD

**Issue by watt0005** [Open-Systems-Pharmacology/Forum#79]
How do I change the dose in a MoBi simulation? I opened the Molecule Start Values and under Molecule Parameters, changed the Total Drug Mass to a new value. However when I re-ran the simulation the concentration time profile did not change.

**Comment by PavelBal** [comment]
Hello @watt0005,

the concept of administrations in MoBi is completely different from the one in PK-Sim. The administrations are located in the "Events"-BuildingBlock.
To change the dose in the simulation, navigate to "Applications -> *NameOfTheApplication* -> Application_1 -> ProtocolSchemaItem" and chage either the parameter "Dose" or "DosePerBodyWeight" (see screenshot). The *NameOfTheApplication* and "Application_1" will depend on the application you have.

Hope it helps.

![dose](https://user-images.githubusercontent.com/25903040/31266745-91d054f4-aa75-11e7-9c37-2a5cb4a990ab.JPG)

**Comment by watt0005** [comment]
Thanks, that is very helpful. One follow up question - does it matter whether I change the Dose or DosePerBodyWeight? If I change the DosePerBodyWeight then Dose and DrugMass automatically change. If I change the Dose, then DrugMass changes but DosePerBodyWeight does not automatically change. Resulting plots look the same, so I do not think that it matters, but wanted to confirm.

Original
![image](https://user-images.githubusercontent.com/31321213/31279154-fa11199a-aa75-11e7-9507-e8f4f5925820.png)

Changing DosePerBodyWeight
![image](https://user-images.githubusercontent.com/31321213/31279128-dafbb2f4-aa75-11e7-8a42-96b449b812af.png)

Changing Dose
![image](https://user-images.githubusercontent.com/31321213/31279186-1db1eb7c-aa76-11e7-9e20-afa2ef220b22.png)

**Comment by PavelBal** [comment]
By default, DrugMass is calculated from Dose, and Dose is calculated from DosePerBodyWeight. So if you change Dose directly, (i.e., overwrite the formula) DosePerBodyWeight is not used any more.

**Comment by msevestre** [comment]
@watt0005: Pavel is absolutely correct. A small addition:  The parameter used in the model at the end is the **DrugMass** parameter. In your screenshots, the values are the same, hence the plot looking the same.

As a side note: 
You are changing the dose value in the simulation. 
MoBi protocol concepts is not that different from the one use in PK-Sim in my opinion. MoBi also uses the building block concepts. The **Protocol** building block from PK-Sim finds its MoBi representation under the **Event** building block. You could also update the dose parameter in the event building block to ensure that any new simulation created with this event building block is using the latest dose value.
