### ISSUE TITLE
Mac Version of OSPS ;-)

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#80]
Just a thought as a lay person: as there now exists VS for Mac. Shouldn't it be rather easy to also create a Mac Version for OSPS?

**Comment by msevestre** [comment]
Visual Studio for Mac does not support components written for windows (which are all our UI component by DevExpress for example). So unfortunately this is not possible. 

However using for example parallels desktop for mac,  you can have an instance of PK-Sim running on your mac. It works great

We are now looking into the possibility to use .NET core for our core components. While this will not address your problem, we might be able to run a command line interface (running simulations for example) on linux using the same code as on windows.... stay tune
