### ISSUE TITLE
Unable to capture Absorption & elimination phase

### ISSUE THREAD

**Issue by anujadhas** [Open-Systems-Pharmacology/Forum#81]
Hello,
I am dealing with one formulation where I am not able to captureAbsorption & elimination phase.
Can I get some hint which parameters should be modified? 

Here  I am attaching picture of simulation of plasma profile.

![capture](https://user-images.githubusercontent.com/32504809/31492685-caa5c5d6-af69-11e7-8984-f90ba2a80733.PNG)

**Comment by tobiasK2001** [comment]
Dear Anujadhas,

Sorry it is a bit hard for me to answere your question from the info provided.
The reasons for the mismatch ob simulation and data can be manifold. What did you try so far? Were you able to describe the compound in another formulation? If yes which? Did you follow the way pointed out this best practice?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5080648/pdf/PSP4-5-516.pdf
Hope this might help you!

Best, Tobias

**Comment by anujadhas** [comment]
Hello Tobias,

I am dealing with Extended Release formulation (Animal study: Beagle) having,
T1/2: 3 hrs
Lipophilicity: 3.4
Fraction Unbound: 42%
Metabolized by CYP1A2

I can't share all details as it is Confidential.

I am not at all able to capture absorption and elimination. This is my first attempt of M&S, So I don't have any idea which parameters need to be adjusted/modified.

**Comment by msevestre** [comment]
@anujadhas 
I agree with @tobiasK2001 that following the PBPK modeling best practices as described in the aforementioned article would be the way to go, especially if you have no experience with this type of simulation.

Do you have IV data? Then start with this model first to understand distribution and clearance processes. Once you have a good understanding and the IV model describes your data, It's time to look at absorption and PO models.

**Comment by anujadhas** [comment]
@msevestre 
I have oral data.

**Comment by msevestre** [comment]
@anujadhas Closing. Please let us know if you have any more questions
