### ISSUE TITLE
Open-Systems-Pharmacology documentation

### ISSUE THREAD

**Issue by florentbruneau** [Open-Systems-Pharmacology/Forum#82]
Where can I find all OSP suite 7.1 documentation ? (Relase Notes, Manual, System Requirements, ...) ?
Thank-you in advance

**Comment by msevestre** [comment]
Hi @florentbruneau 

- Documentation can be found at http://docs.open-systems-pharmacology.org (which is nothing else that a link to the OSPSuite.Documentation repository)

- Release Notes and latest suite setup at http://setup.open-systems-pharmacology.org

- Systems Requirements [here](https://github.com/Open-Systems-Pharmacology/Suite#system-requirements)

Hope that helps,

**Comment by florentbruneau** [comment]
Hi @msevestre
Thanks for the links.
The manual is for 7.0.0 : there is no update for 7.1.0 ?

**Comment by msevestre** [comment]
>The manual is for 7.0.0 : there is no update for 7.1.0 ?

This is correct. Documentation is a bit behind. The Release Notes are complete and should give you a good overview as to what has changed between 7.0 and 7.1
