### ISSUE TITLE
OSP website online

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Forum#83]
Our new OSP website is now live at http://www.open-systems-pharmacology.org/

While the content of the platform will remain on GitHub, this new site will provide an overview and quick access to the most important areas of the OSP platform such as:

* Forum, documentation and suite setup
* Latest News
* Examples
* Publications
* Tutorials

If you want to stay up-to-date with the latest news and releases, please subscribe to the [Newsletter](http://www.open-systems-pharmacology.org/#newsletter).

Check it out and let us know what you think!

**Comment by StephanSchaller** [comment]
Very nice! Who designed it?
