### ISSUE TITLE
Partition coefficient (blood cells/plasma)

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/Forum#84]
I wanted to double check that I am understanding a calculation correctly. I want to calculate the partition coefficient (blood cells/plasma). From the export of the model to .txt, I have copied the following: 

Parameter: ...|Partition coefficient (blood cells/plasma)
	IsFixed: True
	Value: 7.64996401377214
	Formula: K_pu_bc*fu
		fu: RPV_opt|RPV|Fraction unbound (plasma)(0.003)
		K_pu_bc: RPV_opt|RPV|Partition coefficient (blood cells/plasma unbound)(91.3868518950275) 

Following the formula, I get K_pu_bc*fu= 91.3868518950275* 0.003=0.2741605557 not the above displayed value of 7.64996401377214. Can you please help me understand where the 7.64996401377214 comes from?

**Comment by Yuri05** [comment]
`IsFixed: True` means that the value of the parameter (originally defined by the given formula `K_pu_bc*fu` ) was overwritten by the given one (7.64).
What is used in a simulation is the **Value**. Original formula is kept for the case you would like to reset parameter value

**Comment by mlcraig** [comment]
Hi @Yuri05 thanks for clarifying. That was really silly, I totally forgot about fixed values. Thanks for clearing that up so quickly.
