### ISSUE TITLE
Experience with PBPK modells for aminoglykoside antibiotics?

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#85]
Dear all, I wonder If you had came across of examples of PBPK modells for aminoglykoside antibiotics using PK-sim and /or MoBi? Are ther more than these?
https://www.ncbi.nlm.nih.gov/pubmed/26323410  

or these http://journals.lww.com/ccmjournal/Abstract/2013/12001/926___RISK_ASSESSMENT_FOR_AMIKACIN_INHALE_IN_ICU.882.aspx

Of special interest maybe: could tissue concentrations be predicted succesfully in e.g. kidney, ZNS or else. Did special issues / problems arouse? What data were critical to inform the model?

Please let me know your suggestions.

Best, Tobias

**Comment by msevestre** [comment]
@tobiasK2001 Closing this issue. Please do not hesitate to reopen with some of your findings
