### ISSUE TITLE
Meropenem

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#86]
I am trying to build a PBPK model for meropenem.
70% of the drug is excreted unchanged in urine. I would like to know if I am missing anything?
Thanks in advance.
kind regards
Mouli
[Meropenam.pdf](https://github.com/Open-Systems-Pharmacology/Forum/files/1398762/Meropenam.pdf)

**Comment by PavelBal** [comment]
You have to implement excretion into urine - at least include GFR. If GFR is not sufficient, add active tubular secretion (which could be P-gp mediated).

**Comment by moulirc** [comment]
Thanks for your comments.

**Comment by moulirc** [comment]
I am trying to build a PBPK model for Meropenem. I was following the example (Ciprofloxacin) to develop this model. 
* I do not know how to implement the 70% renal clearance factor into the compound.
Potential transporter - OAT1, OAT3, % drug metabolized 30, 
Metabolism (enzyme - DHP1), metabolites -  two isomers of β-lactam ring-opened metabolites

Blood plasma partition - 0.55, Additional systemic clearance 3.6 l/h, Volume at steady state 0.29.

I have attached the project file - would appreciate if you could guide me on this.

kind regards
mouli






https://1drv.ms/f/s!AhXr_1fEjP6e7Ua7c9o1RB5zaibj
