### ISSUE TITLE
How to add measured pH dependent solubility profiles to PK-Sim?

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#88]
Dear all,

as far as I know PK-sim predicts the pH-dependent solubility from a given solubility at a reference pH and the pKa values of the compounds. However sometimes you have the luxury of measured pH dependent solubilities and these can differ from the PK-sim calculated. Especially if you a salt from a weak base with a counterion. Here on would like to adapt the calculated solubility profile to measured values (like in other PBPK softwares). I could not see how this might be possible with PK-Sim...Did I miss anything? wouldn’t this imporove the prediction from GI absorption?

**Comment by msevestre** [comment]
Hi @tobiasK2001 
Not possible at the moment. 
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/248 for feature request. 
This will likely be implemented in version 7.3

**Comment by Aedginto** [comment]
What I have done is modify the 'solubility gain per charge' and, if necessary the 'Ref pH' to get close to measured values. This usually works quite well. The software uses the solubility value as a function of pH (what the graph shows) so it doesn't matter if the ref pH is different from the actual value. 
A.

**Comment by tobiasK2001** [comment]
Dear Andrea,
thanks for your comment. Yes sometimes toggle around with pH and solubility helps. However in my case it was a bit more complicated. Indeed I have an ampholyte with an monoprotic acid as counterion. As it is a project compound I can't show it here. but I found a similar case (Desvenlafaxine with a diprotic acid as counterion) in public (PMID: 20630176). 
![grafik](https://user-images.githubusercontent.com/25585248/31988258-cd76a7d0-b96e-11e7-8ab3-96f4ef700641.png)

As you see on the attached screenshot PK-sim can predict the solubility for the ampholyte (pKa basic = 9.2 and acid 10.5) alone quite well. However Desvelavlaxine is given as a fumarate salt (pKa acid at 2.8 and 4). Unfortunatly PK-Sim cannot catch the solubility at pH1 to 6.  Adding the outer most acid pKa from the fumarate to the ampholyte can't help here. One would need to have the possibility to give at least 4 pKA values per cpd to describe solubility behaviour. But than I think that adding pKa values form the counterion to the ampholyte to describe solubility it is bastardizing distribution and permeability calculation for the ampholyte. 
So I think the feature added in version 7.3 will be extreme usefull in cases like this. looking forward to that.

Best, Tobias

**Comment by Yuri05** [comment]
Workaroaund as long as Open-Systems-Pharmacology/PK-Sim#248 is not implemented:
based on _measured_ solubility values, calculate intestinal solubility value for each GI segment manually (`Solubility_segment=f(pH_segment)`)and set it in the simulation.
<img width="384" alt="sol" src="https://user-images.githubusercontent.com/25061876/31989616-1d40a50a-b973-11e7-99a6-e2f0bb77f9b5.png">

**Comment by tobiasK2001** [comment]
Ah good point! Great that the OSP is so flexible :-) Best Tobias

**Comment by drfreedman** [comment]
Dear Sir,

Please explain exactly how the Solubility Gain per Unit Charge is applied to the Henderson-Hasselbach equation.  I am trying to explain some dissolution data and looked for the source code, which does not appear to be available.

Regards,
Immanuel

**Comment by msevestre** [comment]
@drfreedman Please create another entry in the forum for your question so that we only have one thread per issue. Thanks
