### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by tmssou** [Open-Systems-Pharmacology/Forum#90]
Hello,
I just formatted my computer so have to install PK-Sim again. However, the installer keeps prompting an error saying that an older version of the software has already been installed and it needs to be removed before installation can occur. The whole computer has just been formatted and I can't find traces of anything on PK-Sim to uninstall. Does anyone know how to solve this?
Thanks
Tom

**Comment by Yuri05** [comment]
Hi Tom,

* which operating system are you using?
* which version of the OSP suite was previously installed ad which version of the OSP suite are you installing now?
* please provide a screenshot of you error message
* please attach installer log file (in case of failed installation the link to the log file is shown in the installer window)

**Comment by tmssou** [comment]
- I'm using Windows 10
- I believe it was OSP version 7.0.0. or 7.1.0. It wasn't that long ago when I installed that last time. 
- Screenshot of error message:
![image](https://user-images.githubusercontent.com/32617414/32373627-760e2648-c09a-11e7-88b1-54c0b8b34a28.png)
- Installer log file:
[Open_Systems_Pharmacology_Suite_7.1.0_20171103132351.log](https://github.com/Open-Systems-Pharmacology/Forum/files/1440995/Open_Systems_Pharmacology_Suite_7.1.0_20171103132351.log)

**Comment by msevestre** [comment]
That sounds a lot to me like

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/72da6400-7a22-4bcc-b8d3-6423086289f0/visual-c-2015-redistributable-setup-failed-0x80070666-x64-x86?forum=vssetup

**Comment by tmssou** [comment]
My Windows Update status is all up-to-date and there is not more update I can install.

**Comment by Yuri05** [comment]
@tmssou Can you please upload a screenshot of all _Microsoft Visual C++ Redistributables_ installed on your system?
You will find installed software under **Control Panel** ==> **Programs and Features**

![clipboard01](https://user-images.githubusercontent.com/25061876/32377872-58efd980-c0a9-11e7-8135-cf7966bfd2af.jpg)

**Comment by tmssou** [comment]
@Yuri05 
Does this help?
![image](https://user-images.githubusercontent.com/32617414/32384256-99b6154a-c0ba-11e7-8e68-7c9c989f7bb0.png)

**Comment by Yuri05** [comment]
Seems to be an error in Microsoft installation routines of different C++ runtimes...

Please proceed as following
1. Manually uninstall _Microsoft Visual C++ **2017** Redistributable(**x86**)_
<img src="https://user-images.githubusercontent.com/25061876/32410591-ba894bd8-c1c4-11e7-9b1e-ca86d460eaea.png">

2. Install OSP Suite 7.1

3. Download [_Microsoft Visual C++ **2017** Redistributable(**x86**)_](https://go.microsoft.com/fwlink/?LinkId=746571) and install it again

Did it help?

**Comment by tmssou** [comment]
Yes, that works! Thanks so much for your help!
