### ISSUE TITLE
OSP solubility calculation

### ISSUE THREAD

**Issue by drfreedman** [Open-Systems-Pharmacology/Forum#93]
Dear Sir,

Please explain exactly how the Solubility Gain per Unit Charge is applied to the (presumably) Henderson-Hasselbach equation. I am trying to explain some dissolution data and looked for the source code, which does not appear to be available.

Regards,
Immanuel

**Comment by msevestre** [comment]
@drfreedman The source code is available (open source platform) and you can see all equations when exporting a model to MoBi . Please do not hesitate to contact us if you have more questions
