### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#95]
I am trying to simulate and getting this error. Also, attached the project file

[_Run1_Paracetamol.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1465624/_Run1_Paracetamol.zip)

![image](https://user-images.githubusercontent.com/27323536/32709882-bebad750-c87f-11e7-9923-7dd4eb37e19b.png)

**Comment by msevestre** [comment]
@moulirc 
Have you tried to reduce the absolute and relative tolerances as suggested in the message?

What parameters of your model did you change that caused this message to appear?

**Comment by moulirc** [comment]
Hi msevestre,

Thanks and got it fixed.
