### ISSUE TITLE
excretion of urine metabolites

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/Forum#97]
Hello, I may have missed this during a training, but perhaps somebody can help me and it is good to know in the wider community. I would like to enter metabolite excretion data for fitting during parameter identification.  I can enter urine as fraction or as concentration, and the output is amount in container or concentration. There is no option to align the fraction entry for metabolites with the amount in container as output ( I believe). What is the best solution for data entry here? Urine concentration at the mean time point of the time interval when urine volume was taken, how do I add the urine volume then? Thank you.

**Comment by JanSchlender** [comment]
Let me get this right, you have data for metabolite concentration in Urine at hand and want to use this to optimize the excretion to Urine of the metabolite?  There is a concentration of metabolite in urine available as observer in PKSim. The only thing which deviates from parent, is the fraction excreted to urine, which is not available for metabolites. Are you looking for this? Then you may create an observer in MoBi and run the parameter identification there. Since it is not clear if you would like to refer the fraction to the administered (parent) dose or to the amount metabolized, which is changing over time.

**Comment by tobiasK2001** [comment]
Hi Jan,
actually I have a similar problem. I would like to see the fraction excreted to urine  and fraction to feces of the metabolite. I would like to refer to the fraction administered of parent. My naive thinking was to duplicate (save as template and reload under a new name) the existing fraction excreted observers in MoBi and exchange in the Properties of the Observer the parent to the metabolite in the "include list". But that does results in a flat line at zero... What did I miss?

**Comment by sfrechen** [comment]
Hi Tobias,
you can easily create these observers in MoBi. Just create a new Molecule Observer. Set a condition, e.g. tagged with "Urine". Create a new formula and set the equation in Monitor like this:
"TotalDrugMass>0 ? M/TotalDrugMass : 0"
where "TotalDrugMass" has to come with the path "<REPLACE with PARENT MOLECULE>|Total drug mass" and "M" has the path "..".
Hope that helps.

**Comment by tobiasK2001** [comment]
Hi Sebastian,

unfortunatly this does not help. Even whenn I create a new observer for e.g. fraction ecrtend to feces I get a flat line at 0. As I inserted bilary cl and renal plasma CL for the metabolite ther should be something there I guess...
Please find a zipped mobi project (mock up Version with some older literature data) and a Parent and Metabolite cpd to illustrate the problem. Can you find what is missing?
[Demo fraction excreted Observer_renamed.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1501444/Demo.fraction.excreted.Observer_renamed.zip)

**Comment by sfrechen** [comment]
Hi Tobias,
you have a wrong path (MOLECULE|Total drug mass).
As I said, you need to replace MOLECULE with the name of your parent drug.
Best
Sebastian

**Comment by tobiasK2001** [comment]
Ok, did it for bothe feces metabolite observers
![molecule replaced by parent](https://user-images.githubusercontent.com/25585248/33211732-1d15dfe0-d120-11e7-879c-e99d253eaaf7.PNG)

but this works for the Urine fraction metabolite observer only (blue dashed line) 
![results for feces and urine metabolite observer](https://user-images.githubusercontent.com/25585248/33211738-285aaade-d120-11e7-93e3-786571799013.PNG)

but not for the Feces
Strange...

**Comment by sfrechen** [comment]
I confirm that it works for both parent and metabolite the way I proposed it.
Maybe you still have a bug? And are you sure that your metabolite ends up in feces?

**Comment by tobiasK2001** [comment]
Yes that' s a good good point! I was a bit busy with some other stuff, but when I thought about it again I found out that I forgot to set EHC continous fraction to 1 (instead of zero). Obviously all my fraction ecreted to bile ended in the gallbladder and not reached feces of course (this old gallbladder trick again...) So now it works :-) and thanks again for the help!

**Comment by tobiasK2001** [comment]
Maybe it is a good idea to introduce a correction factor to account for different molecular weights of parent and metabolite. I don't think Mobi does it automatically. So I would use this formuala:
TotalDrugMass>0 ? M/((MW_met/MW_par)*TotalDrugMass) : 0

with the additional Parameters:
MW_met Alisa for Metabolite|Molecular weight and MW_par Alisa for Parent|Molecular weight.

Correct?

**Comment by tobiasK2001** [comment]
Hmm, is I get now more than 100 % fraction excreted in feces or urine (depenting were I put all xceretion clearance to) this might be not correct. I would like to retract my lat comment and leave the formula as suggested from Sebastioan.

**Comment by sfrechen** [comment]
TotalDrugMass is molar, no need to adjust anything...

**Comment by msevestre** [comment]
Nothing to add here I believe. Closing. Thanks @sfrechen
