### ISSUE TITLE
bolus infusion 

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#99]
Hi,
I am trying to simulate a data from a published paper.
The drug was given as an iv bolus (1 gm drug ) over 10 mins. is there a way it can be mentioned in PK-sim?
thanks 
mouli

**Comment by Yuri05** [comment]
Use the administration type "**Intravenous infusion**" and set `Infusion time = 10 [min]`

**Comment by moulirc** [comment]
thanks.mouli
